### ISSUE TITLE
Only displayName available for DriveItem.createdBy.user when calling delta endpoint

### ISSUE THREAD

**Issue by rgrebski** [microsoftgraph/msgraph-sdk-java#100]
### Expected behavior

When calling Drive delta endpoint from Postman, in JSON I can see that there is email and displayName returned like this:
```
            "createdBy": {
                "user": {
                    "email": "rgrebski@someemail.com",
                    "displayName": "Firstname Lastname"
                }
            }, 
```
I expect driveItem.createdBy.user to have email field

### Actual behavior
driveItem.createdBy.user does NOT read email field from 'createdBy' json object

### Steps to reproduce the behavior
Call Drive delta endpoint: eg:
https://graph.microsoft.com/v1.0/drives/<drive-id>/root/microsoft.graph.delta

**Comment by deepak2016** [comment]
Thanks @rgrebski for reporting the issue. We will get back on this one.

**Comment by deepak2016** [comment]
@rgrebski  can you please let me know steps to reproduce the issue? Kindly provide me details about the request you are making using postman, I'm trying to reproduce the issue.

**Comment by rgrebski** [comment]
Just call
`graphClient.drive().root().delta()`

and see its content in debug for example.

Btw BaseDriveItemDeltaCollectionResponse is missing deltaLink field as well, I had to extend it locally to work with delta endpoint.

**Comment by deepak2016** [comment]
This issue is fixed with PR: https://github.com/microsoftgraph/msgraph-sdk-java/pull/104
Changes are available in dev branch.
