### ISSUE TITLE
Is it possible to specify owner (CreateBy) when registering a file with MS Graph REST API or to change owner (CreateBy) using MS Graph REST API?

### ISSUE THREAD

**Issue by SEOJUNGJIN** [microsoftgraph/msgraph-sdk-java#1004]
### Expected behavior
<br>

> We use the MS Graph REST API below to register a file to the Teams channel.

`Microsoft Graph authentication provider (Client credentials provider)`
<br>

**HTTP request (to upload a new file)**
`PUT /drives/{drive-id}/items/{parent-id}:/{filename}:/content`

**HTTP request (Upload large files with an upload session)**
`POST /drives/{driveId}/items/{itemId}/createUploadSession`

**HTTP request (Send a sharing invitation)**
`POST /drives/{drive-id}/items/{item-id}/invite`

**HTTP request (Update sharing permission)**
`PATCH /drives/{drive-id}/items/{item-id}/permissions/{perm-id}`
<br>

### Actual behavior
> We cannot set owner (CreateBy) when registering a file or modify owner (CreateBy) later.
> The MS Graph REST API v1.0 Doc also states that the File owner (CreateBy) is a ReadOnly property and cannot be modified.
> But we need to change the file's owner (CreateBy) when upload file or later.
> Is there a way currently in MS Graph REST API for Java, or are there plans to add that feature?
<br>

### Steps to reproduce the behavior
> Using MS Graph REST API for Java ( v5.13.0 )
<br>

**Comment by baywet** [comment]
Hi @SEOJUNGJIN 
Thanks for reaching out. This repository is dedicated to questions about the Java SDK itself. For API capabilities (which apply across languages) the best thing you can do is reach out [on the dedicated Microsoft Q&A forum](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-files.html) to get an answer from the team behind the API.
Closing.
