### ISSUE TITLE
Proguard issue with Android Release

### ISSUE THREAD

**Issue by Digipom** [microsoftgraph/msgraph-sdk-java#1014]
(this is a follow up of #258)

This line appears to include too much code and bloats the size of the build:

```
-keep class com.microsoft.** { *; }
```

I used this line instead:

```
-keepnames public class * implements com.microsoft.graph.serializer.IJsonBackedObject
```

Should the artifact include a consumer-rules.pro so that the config can automatically be exported in release builds?

**Comment by baywet** [comment]
Hi @Digipom 
Thanks for reaching out and for sharing that information with the community.
Is this something you'd be willing to submit a pull request for?

**Comment by Digipom** [comment]
Hi @baywet, yes I could. I just proposed https://github.com/microsoftgraph/msgraph-sdk-java/pull/1016. Thanks!
