### ISSUE TITLE
Live Read/Write SharePoint excel file

### ISSUE THREAD

**Issue by LamaBimal** [microsoftgraph/msgraph-sdk-java#1030]
We are migrating our sheet from google to SharePoint. We have automation of report generation in excel files from the java service. Could you please guide us on how to read/write the SharePoint excel files from java?  Does this SDK support updates on the SharePoint excel file?

**Comment by MIchaelMainer** [comment]
What have you tried so far?

Reference:
https://docs.microsoft.com/en-us/graph/api/resources/excel?view=graph-rest-1.0
https://github.com/microsoftgraph/msgraph-training-java
https://github.com/microsoftgraph/java-spring-webhooks-sample

**Comment by ramsessanchez** [comment]
Hi @LamaBimal, apologies for the extended delay. Upon some searching it seems that the excel files in Sharepoint are reachable through a similar method as any file in OneDrive, thus any questions you may have about uploading, downloading, or modifying the excel files in Sharepoint should be easily answered through the OneDrive API endpoint: 
https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0
Using a code block similar to this should be helpful in reaching the files you need: 
```Java
DriveItemCollectionPage children = graphClient.sites("<Site(Page) ID>")
.drives("<Drive ID>")
.root().children()
.buildRequest()
.get();
````
Alternatively you can also use the ListItemCollection endpoint to reach these files: 
```Java
ListItemCollectionPage items = graphClient.sites("Site(Page) ID")
.lists("<Folder ID>")
.items()
.buildRequest()
.get();
``` 
The Site-ID should be in the form of <Domain>, <ID>, <ID>, to find an example try this on graph explorer: 
https://graph.microsoft.com/v1.0/sites/<YourDomain>.sharepoint.com
