### ISSUE TITLE
Kotlin app java.lang.LinkageError

### ISSUE THREAD

**Issue by RyderChen0708** [microsoftgraph/msgraph-sdk-java#1039]
My app use microsoft.identity to login Microsoft account

but at here cause crash.
```
val interactiveBrowserCredential = InteractiveBrowserCredentialBuilder()
            .clientId(CLIENT_ID)
            .redirectUrl("")
            .build()
```
here is crash information

`java.lang.LinkageError: Package versions: jackson-annotations=0.0, jackson-core=0.0, jackson-databind=0.0, jackson-dataformat-xml=0.0, jackson-datatype-jsr310=0.0, azure-core=1.26.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot`

i try to modify dependencies
but not work.

```
    implementation 'com.microsoft.identity.client:msal:3.0.2'
    implementation 'com.microsoft.graph:microsoft-graph:5.19.0'
    implementation 'com.azure:azure-identity:1.4.6'
    implementation 'com.azure:azure-sdk-bom:1.2.0'
    implementation 'com.fasterxml.jackson.module:jackson-module-kotlin:2.10.5'
```

Thanks for help!

**Comment by ramsessanchez** [comment]
Hi @RyderChen0708, I don't believe you need the microsoft.identiy dependency, the graph-sdk uses azure-identity for the credential builders.
These two should be enough to create a sign-on.:
    implementation 'com.microsoft.graph:microsoft-graph:5.8.0'
    implementation 'com.azure:azure-identity:1.4.0'
Let me know if you're able to sign-on using these two and if not I'll be happy to look further into it. 
Thanks for using the SDK!

**Comment by salmantln** [comment]
Hello i have the same issue aswell. And these are my dependenties 
```    implementation 'com.azure:azure-ai-formrecognizer:3.1.10'
    def jackson_version = "2.13.2"
    implementation "com.fasterxml.jackson.core:jackson-core:$jackson_version"
    implementation "com.fasterxml.jackson.core:jackson-annotations:$jackson_version"
    implementation "com.fasterxml.jackson.core:jackson-databind:$jackson_version"
    implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:$jackson_version"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:$jackson_version"
    implementation "com.fasterxml.jackson.module:jackson-module-kotlin:$jackson_version"
    implementation 'com.azure:azure-core:1.28.0'
    implementation 'com.azure:azure-core-serializer-json-jackson:1.2.16'```

**Comment by ramsessanchez** [comment]
> Hello i have the same issue aswell. And these are my dependenties
> 
> ```
>     def jackson_version = "2.13.2"
>     implementation "com.fasterxml.jackson.core:jackson-core:$jackson_version"
>     implementation "com.fasterxml.jackson.core:jackson-annotations:$jackson_version"
>     implementation "com.fasterxml.jackson.core:jackson-databind:$jackson_version"
>     implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:$jackson_version"
>     implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:$jackson_version"
>     implementation "com.fasterxml.jackson.module:jackson-module-kotlin:$jackson_version"
>     implementation 'com.azure:azure-core:1.28.0'
>     implementation 'com.azure:azure-core-serializer-json-jackson:1.2.16'```
> ```

Are you planning on using azureIdentity for authentication? If so, please try specifying the azureIdentity dependency explicitly. Also, if you plan to use the azure-core library  don't believe you need to specify the serializer, this may be the cause of the version mismatch.

**Comment by jaypg** [comment]
@ramsessanchez I'm also getting this identical error. It crashes when creating a credential builder for an auth provider and that looks like it's the azure-identity library? I'm not finding azure-identity on GitHub; is there somewhere I can raise an issue?

**Comment by baywet** [comment]
https://github.com/Azure/azure-sdk-for-java

**Comment by jaypg** [comment]
Thank you @baywet
