### ISSUE TITLE
Graph API - Sharepoint copyItem with parentReference not working

### ISSUE THREAD

**Issue by vivekbdh** [microsoftgraph/msgraph-sdk-java#1049]
Hello everyone,

Ref:
https://docs.microsoft.com/en-us/graph/api/driveitem-copy?view=graph-rest-1.0&tabs=http

This API of copy drive item using graph API version 2.3.2 was working fine and since morning without any code change we are facing an issue. It seems that even if we pass the parent reference, still it's copying into the same directory as the source file.

We are copying files from one folder to another folder with a new path and name using graph API and kotlin

```
microsoftGraphClient.drives(documentStorage.driveId).items([fileToCopy.id](http://filetocopy.id/))
.copy(it.newPath.getFilename(), parentReference)
.buildRequest()
.post()
```

The above code was working till 18th-April-2022 and not working since 19th-April-2022 morning. It is copying files in the same directory as the source file instead of copying them into the new location.

Can someone look into it and revert?

**Comment by vivekbdh** [comment]
Hello @ramsessanchez: can you please let me know when I can get an update on this?

**Comment by ramsessanchez** [comment]
Hi @vivekbdh , unfortunately we are no longer working with Graph version 2.*.* as we are currently on version 5.19.0 so there have been no updates to the graph SDK version that you are using. It is more likely that there may have been a change to the Sharepoint/Drive endpoint, this is something that is not easily reverted as we do not manage the specific API's that the graph SDK calls on. Is it possible for you to update to a newer version of the graph SDK?

**Comment by ravishah104** [comment]
@ramsessanchez 
It's issue from Sharepoint/Drive endpoint as you said but do you think upgrading will resolve the issue if it's from Sharepoint/Drive endpoint?: 

ref:
https://docs.microsoft.com/en-us/answers/questions/817518/graph-api-sharepoint-copyitem-with-parentreference.html

**Comment by ravishah104** [comment]
> @ramsessanchez It's issue from Sharepoint/Drive endpoint as you said but do you think upgrading graph will resolve the issue if it's from Sharepoint/Drive endpoint?:
> 
> ref: https://docs.microsoft.com/en-us/answers/questions/817518/graph-api-sharepoint-copyitem-with-parentreference.html

Just verified with "com.microsoft.graph:microsoft-graph:5.19.0" and it's same buggy behaviour. It is copying file in source directory only instead of target directory. So it's confirmed that it's issue from API of sharepoint/Drive.

Upgrading the version will not help. 

Below workaround is working fine in case anyone else also facing same. Pass parentReference in copy operatio along with path instead of just id of target directory( ref: https://docs.microsoft.com/en-us/answers/questions/817792/recent-changes-to-the-driveitem-copy-method-of-the.html ).

`fun main() {
    val authCodeCredential = AuthorizationCodeCredentialBuilder()
            .clientId("Client_ID")
            .clientSecret("Client_Secret") //required for web apps, do not set for native apps
            .authorizationCode("Authorization_Code")
            .redirectUrl("Redirect_URL")
            .build()

    val tokenCredAuthProvider = TokenCredentialAuthProvider(listOf("Files.ReadWrite", "Files.ReadWrite.All", "offline_access"), authCodeCredential)

    val graphClient: GraphServiceClient<*> = GraphServiceClient
            .builder()
            .authenticationProvider(tokenCredAuthProvider)
            .buildClient()

    //Trigger copy operation with parent reference
    val targetDirectory = ItemReference()
    targetDirectory.id = "XXX"
    targetDirectory.path = "XXX" // If we pass path for target directory item reference then it's working fine but with just id of target directory it will not work until they don't resolve it. 
    
    graphClient.drives("DRIVE_ID").items("Source_File_ID")
            .copy(
                    DriveItemCopyParameterSet
                            .newBuilder()
                            .withName("Target_File_Name")
                            .withParentReference(targetDirectory)
                            .build()
            )
            .buildRequest()
            .post()
}`

**Comment by ramsessanchez** [comment]
Hi @vivekbdh & @ravishah104, 
As noted it must be a change in the sharepoint API, upgrading will not resolve the issue.
The setting the following parameters will lead to a successful copy: 
Set just the targetDirectory.path 
OR
set both targetDirectory.driveId & targetDirectory.id

Unfortunately driveId or id alone are not enough to specify the target location.
