### ISSUE TITLE
release process

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#106]
We don't have release processes sorted. For example recently 0.3 was released. I should be able to do this:

```
git checkout 0.3
./gradlew publishToMavenLocal
```

and end up with a *microsoft-graph-0.3.jar* published to my local `.m2`. This doesn't happen at all because property substitution was broken (see #97) but if it had I would have ended up with *microsoft-graph-0.2-SNAPSHOT.jar* because versions in `gradle.properties` had not been updated.

Can I suggest that to release these steps need to happen (automated or not):

* edit `gradle.properties` and bump up version, set suffix to blank
* commit 
* tag that commit with the **full** version number (if artifact is labelled as 0.4.0 then the tag should be 0.4.0 not 0.4)
* push tag 
* edit `gradle.properties` and bump up release version, set suffix to `-SNAPSHOT`
* commit + push

**Comment by darrelmiller** [comment]
@davidmoten Thanks for the suggested steps.  Getting a one-step release process is a high priority for us.  However, we have been heads down on trying to get bugs fixed to allow us to GA.  I will make sure we discuss this issue in today's triage meeting.

**Comment by davidmoten** [comment]
Thanks @darrelmiller, by the way prerequisite for further work on releasing is PR #97

**Comment by baywet** [comment]
@davidmoten thanks for your feedback and your patience on the matter.
I've authored #435 which I believe addresses this issue.
Closing for now, let me know if I need to reopen
