### ISSUE TITLE
The SDK should not crash if there is a new derived type added to the metadata

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/msgraph-sdk-java#1064]
SDK should not crash if there is a new derived type added in the metadata, otherwise older apps built with the SDK would crash when there is a new type in the API.
SDK should treat abstract types as concrete and create an instance of the base type not only for Entities as well as for complex types.

Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1328

**Comment by baywet** [comment]
I'm not sure about the behaviour of the current sdk. But the way things are designed for the kiota base this scenario should already be accounted for.

**Comment by maisarissi** [comment]
Hi @baywet . Yes, you are right, for Kiota we are good. This issue is to track the investigation and any enhancement needed in the current version.

**Comment by baywet** [comment]
unless a customer is having a critical issue with this, and they can't upgrade the SDK to the latest version for some reason which should workaround this issue, I think we should park it and not even look into it so we have more bandwidth to push through the Kiota migration.

**Comment by maisarissi** [comment]
The request for fix it in the current version came from @darrelmiller and @garethj-msft as the GA of the next version is too far and many derived types for complex types are being added in the APIs.

**Comment by maisarissi** [comment]
In addition to that, this situation came from a customer incident. They were getting an error with the .NET SDK, but as Java is also strongly typed, this affects us as well.

**Comment by baywet** [comment]
Looking at how derived type determination is implemented, this should already the case, so are we only talking about adding a unit test to make sure of this ? https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/30e73e69d5f928c914220d04512598dce0bf4c63/src/main/java/com/microsoft/graph/serializer/DerivedClassIdentifier.java#L39

Or are their other cases I didn't think about?

**Comment by baywet** [comment]
and we're not using abstract classes in java https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/models/DirectoryObject.java

**Comment by maisarissi** [comment]
The issue in .NET was that the API was returning a new odata.type derived type in the metadata, so older versions of .NET SDK were crashing trying to deserialize to something that doesn't exist instead of creating an instance of the base type for Complex Types. We were doing this for Entities though.

**Comment by baywet** [comment]
yeah I think it was crashing because of the fact they were abstract, which is not the case in Java. @andrueastman anything else you had to fix here?

**Comment by andrueastman** [comment]
Nothing else to resolve really @baywet. 
If we do not emit abstract types in the generated code, we can probably just close this one.
