### ISSUE TITLE
GraphServiceException encapsulates a bit too much?

### ISSUE THREAD

**Issue by kgarlikowski** [microsoftgraph/msgraph-sdk-java#107]
Currently there is not way to know i.e. what status code had been thrown by Graph API by inspecting `com.microsoft.graph.http.GraphServiceException`. That could be useful so that when calling GET on some Object we could catch the exception and actually know that 404 Not Found happened.

In the .Net Graph API SDK that seem to be possible, but Java version possibly hides too much of information regarding the error that caused it.

**Comment by darrelmiller** [comment]
That seems like a reasonable request.  I'll have a conversation with the team to see if there are reasons why we didn't expose this information.

**Comment by darrelmiller** [comment]
Workitem 839917

**Comment by kgarlikowski** [comment]
@deepak2016 Yes, totally. It would be great to have i.e. a responseCode exposed directly. It's somehow accessible via message, as you say, but we would need to have custom parsing logic  which could easily fail when changes to message format happen.

```
try {
  serviceClient.users(user).buildRequest().get()
} catch (ex: GraphServiceException) {
  if (ex.responseCode == NOT_FOUND) ...
```
seems just much more convenient and less error prone.

**Comment by deepak2016** [comment]
This issue got fixed as part of pull request: https://github.com/microsoftgraph/msgraph-sdk-java/pull/111
Changes have been checked-in to dev branch and should be available as part of binary in our next release.
