### ISSUE TITLE
Ensure users

### ISSUE THREAD

**Issue by AcidicNut** [microsoftgraph/msgraph-sdk-java#1087]
### Expected behavior

Hi, 
I have a question. Is it possible to ensure users to a SharePoint list with Graph API?  
I have been looking for an answer for quite a while, but all I could find is that we should use SharePoints REST APIv1 like [this](https://stackoverflow.com/questions/56415461/posting-a-new-item-to-a-sharepoint-list-using-the-ms-graph-api-with-a-people-fie).   

In the .Net version's community extension I found [this](https://github.com/microsoftgraph/msgraph-sdk-dotnet-contrib/blob/master/docs/ROADMAP.md#sharepoint-siteusers). Does this work? If so, how could I use it with Java + Maven?

I guess I could just implement it on my own, based on the community extension's code.

### Actual behavior

-

### Steps to reproduce the behavior

-

**Comment by ramsessanchez** [comment]
Hi @AcidicNut, I'm not quite sure that I understand the premise of your question. Are you planning on adding users' information to a List or are you planning to grant access to a list to certain users? If you are referring to the first, then I suggest first creating an excel document using the excel endpoint on graph and then adding that excel file as a list to your collection of lists, also using graph. Let me know if this is helpful at all or if I'm understanding your question incorrectly, thanks!

**Comment by baywet** [comment]
@ramsessanchez this question is a tough one if you don't have SharePoint development experience. Allow an old SharePoint developer to help you here 🙂

Here, we're talking about [this API](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/ee540898(v=office.15)) (or the equivalent CSOM/REST). Back in the days, for a SharePoint list/page to display information about a user,. it was too slow to query the primary store (AD) over LDAP. So SharePoint was syncing the user information to a profile database. But even querying that directly from a content site was too demanding over large environments. This method effectively "makes sure" we have a local copy of the user information in the current content site before we can use it. Back then, you needed to call it before you could assign list items to a user for example.

@AcidicNut Unfortunately it looks like the SharePoint APIs have not been fully modernized. Where system fields like created by return a identity object, which links to the Microsoft Graph user object, the custom fields don't, they still rely on the User information list. Community members have put a [step by step to create list items with people columns](https://dev.to/manuelsidler/create-a-sharepoint-list-item-with-a-people-lookup-field-using-microsoft-graph-sdk-4ad). This assumes two things:
- User is already available in the information list
- Your application already knows the user information list id.

For the former, the user information list is read-only, which means you cannot add a user entry in there programmatically through Microsoft Graph. You're application probably needs to use the CSOM/pnp core for that specific step, and I suggest to [voice this gap](https://aka.ms/graphfeedback) so the SharePoint product team is aware this is a gap in the APIs and addresses it.

For the latter, you can query `https://graph.microsoft.com/v1.0/sites/<site-id>/lists?$select=system,name,id`, iterate through the results, and find the list with the name "users" (unfortunately filter doesn't seem to be supported on that endpoint for this field).

Hopefully this helps.

**Comment by AcidicNut** [comment]
@baywet Thanks a lot!

This is my first time dealing with SharePoint, so that's why I'm clueless. Just to clarify this for me, I have some more questions.

> Community members have put a [step by step to create list items with people columns](https://dev.to/manuelsidler/create-a-sharepoint-list-item-with-a-people-lookup-field-using-microsoft-graph-sdk-4ad). This assumes two things:
User is already available in the information list
Your application already knows the user information list id.

I'm sorry, I didn't give you all the details, but my original task was the following. I have a SharePoint list with column people lookup fields, and I actually used this step by step guide - that you linked - to look up people from the information list.  
It works great for people who are on the user information list, but fails otherwise. This is why I'm looking for a way to add users to this information list.  

1. As far as my understanding goes, ensure user method adds the given logon name to the user information list, if it's not already on the list, and returns the lookup id that I need. Is this correct? I'm asking because you wrote this:
> For the former, the user information list is read-only, which means you cannot add a user entry in there programmatically through Microsoft Graph.  
2. I'm using Azure identity with an Azure app only. What kind of permissions are needed to use [the ensure user method](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/ee540898(v=office.15))? Currently I have Sites.ReadWrite.All and this should be enough, right?
3. Is it possible to use a custom request based on [this](https://docs.microsoft.com/en-us/java/api/com.microsoft.graph.http.customrequest?view=graph-core-java)?  

Thanks in advance!

**Comment by baywet** [comment]
1. Correct
2. Correct, it might be over permissive though, I don't know exactly which permission level is required and further testing would be required. If you're in an app only scenario and using a secret, you might also have to switch to a certificate.
3. Incorrect. The custom request is meant for requests that go to Microsoft Graph. Just use a plain ok http request on a new client, and add the authorization header yourself.

**Comment by AcidicNut** [comment]
Thanks! I'll use a plain ok http request

**Comment by ddyett** [comment]
closing as it seems there's resolution.
