### ISSUE TITLE
Want to send messages to teams channel/chat using the following API Send chatMessage in a channel using delegated permission

### ISSUE THREAD

**Issue by mohitm2608** [microsoftgraph/msgraph-sdk-java#1109]
1. Currently my app is configured in application (client credential) authentication mode.
2. I need to Send chatMessage/channelMessage in a specified channel/chat - Microsoft Graph v1.0 | Microsoft Docs](https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&tabs=http)  using delegated authentication flow.
3. As discussed with microsoft support team member she suggested me to configure the app authentication flow to delegated (Authorization flow).
4. I need for assistance on authentication and authorization using Graph Java SDK 

Graph API: **https://graph.microsoft.com/v1.0/teams/3f943e9d-d8a2-4789-9514-bba70a1c06e0/channels/19:92696312bdbf42218d55c4da44d5285c@thread.tacv2/messages**

Error Message: **401 Unauthorization**

Kindly let me know if you need any more details from my side.

**Comment by ramsessanchez** [comment]
Hi @mohitm2608,
This helpful startup guide should cover all the steps you will need to begin using the graphSDK including authentication. Please let me know if you run into any trouble. Thanks for using the SDK! 
https://docs.microsoft.com/en-us/graph/tutorials/java?tabs=aad

**Comment by mohitm2608** [comment]
Hi @ramsessanchez 
I have tried it out above steps but still getting 401 Unauthorization error...
Need assistance.
Please let me know if you need any more details...

**Comment by mohitm2608** [comment]
Hi @ramsessanchez 

Anyone from team can help me with delegated authentication code...

**Comment by mohitm2608** [comment]
Hi @ramsessanchez 

can anyone from the your team help me with code for delegated authentication flow.
I am completely blocked right now as I am getting 401 unauthorization error.

Please let me know if anything else required from my side.

**Comment by baywet** [comment]
Hi @mohitm2608,
Most of the team is out due to the 4th of July in the US, expect delayed replies. Thanks for your patience.
There is [extended documentation](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Java) on how to implement the different flows available, depending on what kind of application you're building.

**Comment by mohitm2608** [comment]
Hello @ramsessanchez 

I have tried with above document but still facing the same issue
It will be good if someone from your team help us on writing the code for delegated authentication flow.

Thanks

**Comment by ramsessanchez** [comment]
Hi @mohitm2608, please refer to this guide and let me know which scenario best describes what you are trying to do. As far as I can tell there is no 'delegated authentication flow'. However, several authentication flows do support delegated permissions and thus selecting the right scenario and adding the correct permissions should help resolve your issue. Furthermore, there is no 'delegated authentication code', rather, authentication code is a flow which uses delegated permissions as a means to complete requests.
