### ISSUE TITLE
JsonNull values are ignored by DefaultSerializer

### ISSUE THREAD

**Issue by marmor7** [microsoftgraph/msgraph-sdk-java#1110]
### Expected behavior
When using a `GraphServiceClient` in the default configuration, and using `JsonNull.INSTANCE` to delete a property in a resource, the property should become null and the info would be removed from the resource.

### Actual behavior
`GraphServiceClient` uses by default `DefaultSerializer` with `serializeNulls` set to false
so all `JsonNull` values are ignored and never sent to the API.

### Steps to reproduce the behavior

Assume some contact with id `contactId` exists with the `birthday` field set

```
GraphServiceClient client = GraphServiceClient
                        .builder()
                        .buildClient();

JsonObject jsonContact = new JsonObject();
jsonContact.add("birthday", JsonNull.INSTANCE); // delete the existing birthday

// i'm using batch requests
BatchRequestContent batchContent = new BatchRequestContent();
ContactRequest request = client.me().contacts(contactId).buildRequest();
batchContent.addBatchRequestStep(request, PATCH, jsonContact);
BatchResponseContent response = client.batch().buildRequest().post(batchContent);
```

The response contains 200 OK for that request, but the contact still contains the birthday.

#### (which I think should be the default behavior as nulls are used extensively in the API to delete properties)
Build the Graph `client` like this:

```
DefaultSerializer serializer = new DefaultSerializer(new DefaultLogger(), true); // true means serializeNulls
GraphServiceClient client = GraphServiceClient
                        .builder()
                        .serializer(serializer)
                        .buildClient();
```

The workaround works for me, but I think this might bite other developers and it's not straightforward to debug and figure out the reason

**Comment by ramsessanchez** [comment]
Hi @marmor7, thanks for using the SDK and also for brining up this issue. We have in fact received similar issues with regards to Null Serialization. Unfortunately there are downsides to always serializing null as well as never serializing null, as you've noted here. Your solution has been one of the recommend workarounds, however if you prefer not to set the serialized you can also use the additional data manager and pass in the propertyName as well as JSONnull to achieve the same desired result. While we don't have plans to change the behavior in this version of the SDK, our next generation of SDK's do solve this particular issue. Thanks again for using our SDK's and be on the lookout for the preview version of our new SDK's in the near future!

**Comment by marmor7** [comment]
Hey @ramsessanchez thanks for the clarification.

It seems that my workaround doesn't work well, when I try to insert a new contact via:

```
BatchRequestContent batchContent = new BatchRequestContent();
batchContent.addBatchRequestStep(request, POST, contact);
client.batch().buildRequest().post(batchContent);
```

It no longer works when `serializeNulls` is enabled.

Getting error: `expected a string for ODataType value`
where the json that `DefaultSerializer` returns has a few: `"@odata.type": null` properties (which would have been removed if serializeNulls was false)

Can you please explain how can we use AdditionalDataManager to delete info from a resource? I haven't found any documentation about this.

Thanks.

**Comment by nedimjahic** [comment]
I have also encountered this issue and haven't been able to solve it using additional data manager so far.
Any input would be appreciated.

**Comment by marmor7** [comment]
I was able to fix the issue without using `serializeNulls`.

I previous would serialize the contact object to a json object myself, and then would pass that json object to graph-api client.
When that was the case I indeed couldn't find a way to delete properties in resources of graph api, as the internal serialize would always strip my nulls from the object at some point.

Now, instead, I'm passing the contact object itself to the graph-api client, in which case using the additionalDataManager works fine for nulling properties like this:

```
// create a contact object
Contact contact = new Contact();
contact.id = "12345";

// ask the API the delete the birthday field
AdditionalDataManager mngr = contact.additionalDataManager();
mngr.put("birthday", JsonNull.INSTANCE);

// create a batch step
BatchRequestContent batchContent = new BatchRequestContent();
ContactRequest request = client.me().contacts(contact.id).buildRequest();
batchContent.addBatchRequestStep(request, PATCH, contact);

// send the batch
BatchRequest request = client.batch().buildRequest();
BatchResponseContent response = request.post(batchContent);
```

**Comment by nedimjahic** [comment]
In my case I am sending the following PATCH request client.planner().tasks(taskId).details().buildRequest(new HeaderOption(IF_MATCH, this.detailsEtag)).patch(dto);

Where I am trying to delete an item from the task checklist, the structure being taskDetails->checklist.

Setting the item to JsonNull.INSTANCE using the additional data manager of the checklist does not seem to work. Maybe because I am sending the Patch against the details resource and the data from one level deeper is somehow lost? I have also tried the batch way, thinking it might be a workaround, but to no avail.
