### ISSUE TITLE
Slf4J for logging

### ISSUE THREAD

**Issue by wem** [microsoftgraph/msgraph-sdk-java#112]
Please use Slf4J as logging facade. As it's a defacto standard for logging in the most Java ecosystems.

**Comment by hkncdr** [comment]
It is possible to use a class imolementing the graph logger interface to do that, similar to https://git.know-center.tugraz.at/blob/?f=modules/sharepoint-online-crawler/src/main/java/at/knowcenter/crawler/sharepoint_online/utils/Slf4jGraphLogger.java&r=crawler.git&h=develop

**Comment by buckett** [comment]
I have a small class that does this:

```
package example;

import com.microsoft.graph.logger.ILogger;
import com.microsoft.graph.logger.LoggerLevel;
import org.slf4j.Logger;

import java.util.Objects;

/**
 * Small proxy to send logging through to SLF4J.
 * There's no runtime way to configure SLF4J so we store the state internally.
 * The default logging level is ERROR.
 */
public class Slf4jGraphLogger implements ILogger {

    private final Logger log;

    private boolean isDebugEnabled = false;

    public Slf4jGraphLogger(Logger log) {
        Objects.requireNonNull(log, "You must supply a logger to use.");
        this.log = log;
    }

    @Override
    public void setLoggingLevel(LoggerLevel level) {
        isDebugEnabled = LoggerLevel.DEBUG.equals(level);
    }

    @Override
    public LoggerLevel getLoggingLevel() {
        return (isDebugEnabled)?LoggerLevel.DEBUG:LoggerLevel.ERROR;
    }

    @Override
    public void logDebug(String message) {
        if (isDebugEnabled) {
            log.debug(message);
        }
    }

    @Override
    public void logError(String message, Throwable throwable) {
        log.error(message, throwable);
    }
}
```
that you can use with the client with:
```
        graphClient = GraphServiceClient
                .builder()
                .authenticationProvider(authenticationProvider)
                .logger(new Slf4jGraphLogger(LoggerFactory.getLogger("com.microsoft.graph")))
                .buildClient();
```

**Comment by baywet** [comment]
@darrelmiller any opinion on this one?

**Comment by baywet** [comment]
as @buckett mentioned you can implement any logger you want using the ILogger interface and then provide that to the builder to the SDK uses it.
We're not looking at implementing a different logging infrastructure at the moment.
Closing

**Comment by Aelentel** [comment]
to be honest that doesn't work too well, there is too much instance of exception handling being outputted directly to System.out or System.err.

so can we reoppen that and clean the library code that output exception directly on the system stream ?

**Comment by baywet** [comment]
In the [current v3 work](https://github.com/microsoftgraph/msgraph-sdk-java/tree/feature/v3) there are no instances of `System.` and only 1 instance or printStackTrace, but it's in a unit test.
In the [related core v2 work](https://github.com/microsoftgraph/msgraph-sdk-java-core/tree/feature/v2) there are only instances of `System.` in the samples, and `printStackTrace` in the batch handling + some of the interceptors.

I do agree that the logs should all go through the same APIs, not through separate path, so I'll open an issue in core to fix the irregularities and use the logging infrastructure.
But we won't be replacing the logging infrastructure by Slf4J, that's a choice that's up to the consumers (you), to go and implement ILogger with whatever logging framework you prefer.

**Comment by Aelentel** [comment]
thanks for the constructive answer and sorry for the harsh wording.
