### ISSUE TITLE
Support for loggers at the request level

### ISSUE THREAD

**Issue by mike-harris0n** [microsoftgraph/msgraph-sdk-java#1129]
Our app supports multiple tenants/customers with multiple OAuth authenticated services, and therefore are managing OAuth tokens centrally rather than using the Graph API for that.

We use a singleton factory that adds a HttpClient similar to the default, minus the authenticator interceptor:

```
    protected GraphServiceClient<Request> createInstance() {
        return GraphServiceClient
            .builder()
            .httpClient(HttpClients.custom().addInterceptor(new RetryHandler()).addInterceptor(new RedirectHandler()).build())
            .buildClient();
    }
```
Each tenant/customer request is then built and authenticated on its own thread as needed, using the singleton client:
```
    MessageStreamRequest request = client.me().messages(message.id).content().buildRequest();
    if (shouldAuthenticateRequestWithUrl(request.getRequestUrl()) && creds != null) {
        request.addHeader("Authorization", "Bearer " + creds.getAccessToken());
    }
    return request.get();
```

Does this implementation look okay so far?

We would like to be able to have similar separation of concerns regarding the logger. Currently I think you can only specify the logger during client build. It would be good to be able to easily provide a target for log output during the build of a request, so that log output for different tenants can be better separated.

**Comment by ramsessanchez** [comment]
Hi @mike-harris0n, I believe this looks good. Unfortunately, at the moment there isn't logging support at request build time as this would require a breaking change. The good news is that we are currently working on a new generation of Graph SDK's which will include new implementations for currently available features, this does include the logging feature. Thanks for using the SDK and we hope that you will follow closely as we rollout the new SDK's and their features!

**Comment by mike-harris0n** [comment]
Thanks for the feedback. The new Graph SDK sounds great, can't wait!
