### ISSUE TITLE
PR #104 work incomplete

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#113]
This is issue is to ensure that changes requested on an already merged PR #104 are not forgotten.
In particular, no unit test was supplied and an error was logged not thrown which should be justified in comments at least (or amended to rethrow the error).
Can we get the comments made on that PR addressed please @dadheech115.
[AB#6036](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6036)

**Comment by dadheech115** [comment]
Hi @davidmoten ,
We were occupied with some other critical tasks hence the delay.
I have raised a PR #114 to address your comments.
