### ISSUE TITLE
Multiple instances of GraphServiceClient are required in case of multiple auth tokens.

### ISSUE THREAD

**Issue by Aaditya-Rane** [microsoftgraph/msgraph-sdk-java#1130]
### Expected behavior
A single instance of 'GraphServiceClient' should require in case of sending requests using multiple different users' auth tokens.

### Actual behavior
Currently as given in [Create a Microsoft Graph client](https://docs.microsoft.com/en-us/graph/sdks/create-client?tabs=Java). We require to provide authenticationProvider at the time of creating an instance of GraphServiceClient.
Further inspection of code gives us inputs that, internally it creates a new instance of HttpClient and adds this authenticator as an interceptor in it. 

Each new instance of HttpClient creates its own connection pool. When one requires to fire graph APIs using multiple different users' auth tokens, it needs to create the same number of new instances of GraphServiceClient.

This adds additional load on the system as multiple instances of HttpClients are getting created. 

### Question
How should we proceed with actual designing so that, there will be a single instance of HttpClient/GraphClientService for multiple auth tokens?

**Comment by ramsessanchez** [comment]
Hi @Aaditya-Rane, I believe you will have to make several instances of the HttpClient if you are planning to make requests using different auth tokens. We have built our HttpClient/BaseClient on top of OkHttp3 which has tied us to this pattern which requires authentication to be handled in this way. However, I think you may want to make use of [this class](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/dev/src/main/java/com/microsoft/graph/httpcore/HttpClients.java) to create new clients explicitly. Using the createDefault you can pass in the auth provider directly into the client which you can then use to make requests to a URL directly. In this way you can skip over the creation of the GraphServiceClient if you know the URL that you are hoping to make the request to. 
``` Java
        final OkHttpClient client = HttpClients.createDefault(authProvider);
        final Request request = new Request.Builder().url("https://graph.microsoft.com/v1.0/users/").build();
        final Response response = client.newCall(request).execute();
```

**Comment by Aaditya-Rane** [comment]
Hi @ramsessanchez 

As per the suggested way, we are having the following issues ...
1. For every token new instance of okhttp-client is getting created, which internally creates a separate connection pool and does not utilize the existing connection pool which has got created in the previous request. Resulting in the generation of multiple okhttp connection pools. <br><b> Ideally we should use single OkhttpClient instance as mention in </b> [OkHttpClients Should Be Shared](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/#okhttpclients-should-be-shared) 
2. We would like to utilize the GraphServiceClient builder pattern to build requests and its request-response objects for our input/output. 

In short, it will be better if there is some way, using which we would be able to send requests with a single instance of <b>GraphServiceClient</b> with different auth-tokens.

## Suggested Approach

### For 1st Issue (Multiple HTTP clients required for multiple auth-token)
Can you make use of [tags](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-request/-builder/tag/) from okhttp request? As tags are request-specific, we can add an object implementing "IAuthenticationProvider" in it. 

In the case of raw requests using HttpClient, it can be done as,
```java
IAuthenticationProvider lAuthToken = <some_custom_implementation_of_IAuthenticationProvider>

final Request lRequest = new Request.Builder().url("https://graph.microsoft.com/v1.0/users/") 
                                              .tag(IAuthenticationProvider.class, lAuthToken)
                                              .build();
```

With some additional changes in <b>AuthenticationHandler</b> as follows,
```java
public class AuthenticationHandler implements Interceptor {
    ....
    ....

    @Override
    @Nonnull
    public Response intercept(@Nonnull final Chain chain) throws IOException {
        ....
        ....

        try
        {
            CompletableFuture<String> future = null;
            
            //Use AuthProvider from request if exists.
            IAuthenticationProvider lAuthProvider = originalRequest.tag(IAuthenticationProvider.class);
            if(lAuthProvider != null){
                future = lAuthProvider.getAuthorizationTokenAsync(originalRequest.url().url());
            } else {
                future = authProvider.getAuthorizationTokenAsync(originalRequest.url().url());
            }
            ....
            ....
        }
        ....
        ....
    }
}
```
So by doing the above changes one should be able to use multiple tokens without creating multiple instances of okhttp-client.

### For 2nd Issue (Should be able to use GraphServiceClient with this solution)

Whenever we create a request using GraphServiceClient, as mentioned in [Make API calls using the Microsoft Graph SDKs](https://docs.microsoft.com/en-us/graph/sdks/create-requests?tabs=java#read-information-from-microsoft-graph). 

With some changes, we can provide tags as follows,
```java
graphClient.me().buildRequest().tag(IAuthenticationProvider.class, lAuthToken).get()
```
For that changes would be required in <b>IHttpRequest : package com.microsoft.graph.http</b> as follows, 
```java
public interface IHttpRequest {
    public Map<Class, Object> getTags();
}
```
proceed by further changes in BaseCollectionRequest, BaseRequest, IHttpStreamRequest, BaseStreamRequest. 
In addition with logic to convert Map<Class, Object> to OkHttp tags and add it into OkhttpRequest before executing it.

## Require inputs

Is this approach correct? Looking at the current code it seems to me like this should be able to solve our issue.
**Note:** An above approach is a rough approach that I have come up with after analysis of the code. 

**Please provide input on this, and if it is possible to do some changes like this to be able to send requests using a single instance of <b>GraphServiceClient</b> with different auth-tokens.**

**Comment by baywet** [comment]
Hi @Aaditya-Rane 
This is something we're planning to improve on the next major version of the SDK, which uses [kiota](https://microsoft.github.io/kiota) as its core design and generation engine.
Once a preview is out (we're still a few weeks out), you'll be able to re-use a single http client for multiple authentication context, resolving the memory/connection pressure on the client application.
We're not planning to change how the current major version of the SDK works, so we can focus our energies on this upcoming version.
Thank you for your understanding.

**Comment by Aaditya-Rane** [comment]
Hi @baywet 
Yhaa, we will be looking forward to the next major version of the SDK (which uses kiota).
