### ISSUE TITLE
Please do dependency management

### ISSUE THREAD

**Issue by jenspopp** [microsoftgraph/msgraph-sdk-java#1138]
### Expected behavior
I want to use graph sdk in a project with other dependencies (ERP, 3rd party integration, ...). This is nearly impossible due to the amount of dependencies pulled. 

I would expect that only the necessary libs are pulled with a minimal footprint. 

For additional tasks separate repositories or optional dependencies could be used

### Actual behavior
Too many libraries are pulled, sometimes different ones for the same task:
E.g. together with azure identity: GSON and Jackson, okhttp and jetty, kotlin-stdlib jdk7 and jdk8.... 

This will cause unpredictable behavior since many classes with the same name are there that will cause the class loader to decide, which version is used...
Additionally running the maven enforcer plugin you will get tons of unhandled version issues...
And looking at some versions, OWASP vulnerability check will probably give warnings too...

### Steps to reproduce the behavior
Just look at the maven dependency tree

**Comment by hookluk** [comment]
**please find the focus on that, each modern and trendy tool must address dependency mng in the owasp world**

**Comment by albertocavalcante** [comment]
Is this issue being triaged?

**Comment by ramsessanchez** [comment]
Hi everyone. We are currently working to roll out the latest version of our generated SDK's along with an updated version of our Java-Core library. As many of you have noted we do have some dependency overlap between these two libraries. We will work to make sure that we minimize our dependency overlap prior to the official release of our next generation. We appreciate the patience. Thank you all for using our Java Sdk.

**Comment by baywet** [comment]
Hi,
Dependencies have been cleaned up with the [latest major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/).
Please open a new issue if this is still a challenge for you.
Closing.
