### ISSUE TITLE
If you have an access token you can simply  do something as follows

### ISSUE THREAD

**Issue by SudipRai** [microsoftgraph/msgraph-sdk-java#1151]
If you have an access token you can simply  do something as follows 

```
const error = "error throw by the authentication handler";

const client = Client.init({
	defaultVersion: "v1.0",
	debugLogging: true,
	authProvider: (done) => {
		done(error, "ACCESS_TOKEN");
	},
});
```
See, the complete example: 
https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/samples/javascript/clientInitialization/ClientWithOptions.js

I would also check for the scopes that are used to retrieve the access token.

_Originally posted by @nikithauc in https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/779#issuecomment-1118906410_

How can we implement this in JAVA/Vert.x?

**Comment by baywet** [comment]
Hi @SudipRai 
Thanks for reaching out and for using the Java SDK.
This is already possible through the lambda style. Something along the lines of:

```java
final GraphServiceClient graphClient = GraphServiceClient
        .builder()
        .authenticationProvider((url) -> CompletableFuture.completedFuture(tokenValue))
        .buildClient();
```

You can also use an auto implementation or implement the [interface](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/391a7ac496b5cae3a5fadb6ec15bb0c5d22e01d5/src/main/java/com/microsoft/graph/authentication/IAuthenticationProvider.java#L11) fully.

```java
final GraphServiceClient graphClient = GraphServiceClient
        .builder()
        .authenticationProvider(new IAutenticationProvider  {
               CompletableFuture<String> getAuthorizationTokenAsync(@Nonnull final URL requestUrl) { 
                         return CompletableFuture.completedFuture(tokenValue);
               }
         })
        .buildClient();
```

**Comment by SudipRai** [comment]
Hello @baywet 
Thanks for the reply.

I am new to the both Java and Graph SDK.

What is the value of url in the first example? Or is it just the variable?

**Comment by baywet** [comment]
It's the URL parameter for your lamba (method parameter). The SDK will pass in the request URL so your code can "decide" whether to return a token or not. In our default implementations we make sure the host is graph.microsoft.com (or equivalent for national clouds) before returning any token.

**Comment by SudipRai** [comment]
So, after the creation of graphClient I made the api request like this.
DriveItemCollectionPage children = graphClient.me().drive().root().children()
                .buildRequest()
                .get();

and the response came like this "com.microsoft.graph.requests.DriveItemCollectionPage@85****"  
How can I convert this into the json format or any other readable format?

**Comment by baywet** [comment]
By [getting the GsonInstance](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/391a7ac496b5cae3a5fadb6ec15bb0c5d22e01d5/src/main/java/com/microsoft/graph/serializer/GsonFactory.java#L74)  and then calling gson.toJson(children).

**Comment by SudipRai** [comment]
Thanks @baywet for your help. 

I have some questions related.

1. First I have generated the token through the authorization code flow, through which I have retrieved the refresh token. With the use of refresh token I am generating the new access token like this: 

POST https://www.linkedin.com/oauth/v2/accessToken

Content-Type: application/x-www-form-urlencoded
grant_type=refresh_token&refresh_token=AQQOMeCIQMa6-zjU-02w8EJW67wPVk3hjJE5x1lZhU013LihKD8i1DpvaAl2jnuP8F1uXMgkm8nzjPfnaJR_kQNOxsLRLZWnAMzHMm81S0yQlkBYicw&client_id=861hhm46p48to2&client_secret=gPecS7yqHkyyShvR

2. Then with the new access token I am making the client instance like this:
final GraphServiceClient graphClient = GraphServiceClient
        .builder()
        .authenticationProvider((url) -> CompletableFuture.completedFuture(tokenValue))
        .buildClient();
3. Then I am accessing the Microsoft resources with the created graphClient.


So, I am doing this to retrieve the Microsoft resources without the user interaction/automation. My question is, Is this the right approach? If not how can I do it the right way? 
And also the refresh token is expiring after a certain period of time which is breaking the automation. I have to manually create and update the token(required a user interaction).  

Is there anyway to automate the whole process without the user interaction from time to time??

Regards,
Sudip

**Comment by baywet** [comment]
⚠️⚠️⚠️⚠️ You've shared credentials in the previous message I just edited to remove, please revoke them and consider the data that can be accessed with those has been compromised. ⚠️⚠️⚠️⚠️⚠️

One thing I'm confused about, why is your application getting the access token from linkedin?

The only way to access Microsoft Graph data without any user interaction is through App only context/permissions and client credentials. [More information](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Java)
Not all APIs support an app only context which doesn't carry the information of a user.

Refresh tokens on the other end require user interactions to obtain for obvious security reasons, and are simply a way "to reduce the number of time your application requires user interaction to obtain the access token".

I hope this clarifies things a bit.

**Comment by baywet** [comment]
Additionally, if you have more questions about authentication and how to setup your application registration [you should post on the dedicated Microsoft Q&A forum](https://docs.microsoft.com/en-us/answers/questions/topics/single/297612.html)

**Comment by SudipRai** [comment]
Thank you for your concern. those credentials was random picked from some documentation.
So with the use of client credentials, I can access Microsoft data for any period of time (lets say for the duration of 2 years) without any user interaction?

**Comment by baywet** [comment]
Correct, as long as the API supports API only authentication context (you can tell by looking at the top of the documentation page, permissions table). The only interaction that'll be require is the tenant admin consent.

**Comment by SudipRai** [comment]
Okay, Thanks @baywet for helping me out.

**Comment by SudipRai** [comment]
Is there any way to update the data in the excel sheet using Microsoft SDK Java?

Eg. Https request:
PATCH https://graph.microsoft.com/v1.0/me/drive/items/{id}/workbook/worksheets/{sheet-id}/range(address='A1:B2')
Content-type: application/json

{
"values" : [["Hello", "100"],["1/1/2016", null]],
"formulas" : [[null, null], [null, "=B1*2"]],
"numberFormat" : [[null,null], ["m-ddd", null]]
}
