### ISSUE TITLE
Cannot get message by id after moving it to a new folder created by myself

### ISSUE THREAD

**Issue by internationalJoke** [microsoftgraph/msgraph-sdk-java#1171]
Hi everyone!
Firstly, I moved a message to a folder created by myself according to the guidance (_https://docs.microsoft.com/en-us/graph/api/message-move?view=graph-rest-1.0&tabs=http_)
### 
                          String destinationId = "deleteditems";
                          graphClient.me().messages("AAMkADhAAATs28OAAA=")
	                          .move(MessageMoveParameterSet
		                          .newBuilder()
		                          .withDestinationId(destinationId)
		                          .build())
	                          .buildRequest()
	                          .post();**

Then I want to get this message via id according to the guiance( _https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-1.0&tabs=http_ ), I got the error message of "404 not found": 
**com.microsoft.graph.http.GraphServiceException: Error code: ErrorItemNotFound
Error message: The specified object was not found in the store., The process failed to get the correct properties.**
### 
                            Message specifiedMessage = graphClient
                                    .users("xxx@yyy.com")
                                    .messages( "AAMkADM1ND" )
                                    .buildRequest( requestOptions )
                                    .expand("attachments")
                                    .get();**

Are there any problems with the method please? Thanks a lot.

**Comment by baywet** [comment]
Hi @internationalJoke 
Thanks for using the Java SDK and for reaching out.

The messages path under the user is a shortcut to the inbox mail folder (it doesn't list all the messages in the mailbox).
To get a deleted item, you need to query messages from that folder, like so:

```java
Message specifiedMessage = graphClient
                                .users("xxx@yyy.com")
                                .mailFolders("deleteditems")
                                .messages( "AAMkADM1ND" )
                                .buildRequest( requestOptions )
                                .expand("attachments")
                                .get();
```

**Comment by internationalJoke** [comment]
> Hi @internationalJoke Thanks for using the Java SDK and for reaching out.
> 
> The messages path under the user is a shortcut to the inbox mail folder (it doesn't list all the messages in the mailbox). To get a deleted item, you need to query messages from that folder, like so:
> 
> ```java
> Message specifiedMessage = graphClient
>                                 .users("xxx@yyy.com")
>                                 .mailFolders("deleteditems")
>                                 .messages( "AAMkADM1ND" )
>                                 .buildRequest( requestOptions )
>                                 .expand("attachments")
>                                 .get();
> ```

Hi Baywet, Thanks for for your reply!
I had a try with the method like above but still got the same 404 error, my code is :

###         Message specifiedMessage = graphClient
                .users("xxx@yyy.com")
                .mailFolders("newFolderId")
                .messages( "messageId" )
                .buildRequest( requestOptions )
                .expand("attachments")
                .get();

**Comment by baywet** [comment]
I can't help but notice the Id you're sharing here is different from the one you shared earlier, can you double check this is what you meant in the code?

Are you able to get the folder itself?

```java
 var folder = graphClient
            .users("xxx@yyy.com")
            .mailFolders("deleteditems")
            .buildRequest( requestOptions )
            .get();
```

If you you might have to get the folder first (to get its id) and then use the folder id in the message request instead of the name (special characters can make requests fail on the service side).

**Comment by internationalJoke** [comment]
> I can't help but notice the Id you're sharing here is different from the one you shared earlier, can you double check this is what you meant in the code?
> 
> Are you able to get the folder itself?
> 
> ```java
>  var folder = graphClient
>             .users("xxx@yyy.com")
>             .mailFolders("deleteditems")
>             .buildRequest( requestOptions )
>             .get();
> ```
> 
> If you you might have to get the folder first (to get its id) and then use the folder id in the message request instead of the name (special characters can make requests fail on the service side).

Thanks for your nice reply again! I'll double check it as you said.

Best regards!

**Comment by internationalJoke** [comment]
> I can't help but notice the Id you're sharing here is different from the one you shared earlier, can you double check this is what you meant in the code?
> 
> Are you able to get the folder itself?
> 
> ```java
>  var folder = graphClient
>             .users("xxx@yyy.com")
>             .mailFolders("deleteditems")
>             .buildRequest( requestOptions )
>             .get();
> ```
> 
> If you you might have to get the folder first (to get its id) and then use the folder id in the message request instead of the name (special characters can make requests fail on the service side).

Hi Baywet, I just found that message id changed after the message was sent.
I created a message firstly:
### 
Message message =graphClient.users(senderMail)
                .messages()
                .buildRequest( new HeaderOption("Prefer","IdType=\"ImmutableId\"") )
                .post(message);

then I added attachments and sent it out:
### 
        graphClient.users(senderMail)
                .messages(message.id)
                .send()
                .buildRequest( new HeaderOption("Prefer","IdType=\"ImmutableId\"") )
                .post();

when I fetched messages from "SentItems" mailbox,  I found the id of message in Sentitems mailbox was different from the message.id above. Could you please tell me how can to obtain a immutable message id?

Thanks a lot.

**Comment by baywet** [comment]
Thanks for sharing the solution with the rest of the community. Closing.
