### ISSUE TITLE
How to make com.microsoft.graph.logger.DefaultLogger log to a file

### ISSUE THREAD

**Issue by lchen016** [microsoftgraph/msgraph-sdk-java#1177]
Our software, which is integrated with Microsoft Graph Java SDK, uses log4j2 as the logging framework.   When creating the GraphServiceClient instance, we pass in a DefaultLogger instance with a level that can be configured (ERROR or DEBUG).  

### Expected behavior
Microsoft Graph Java SDK DefaultLogger can log into the same log file as specified by our software with the logger level we expected. 

I want to know if it is possible to redirect the loggers from Microsoft Graph Java SDK DefaultLogger to log4j2 framework, and how to, if possible.
### Actual behavior
the Microsoft Graph Java SDK logs are not logged into the log file, rather they are calculated in a buffer array, which caused memory to increase and throw the "Requested array size exceeds VM limit" exception.  

### Steps to reproduce the behavior

 DefaultLogger logger = new DefaultLogger();
 logger.setLoggingLevel(LoggerLevel.DEBUG);
 GraphServiceClient
                    .builder()
                    .httpClient(graphHttpClient)
                    .logger(logger)
                    .buildClient();

**Comment by ddyett** [comment]
@baywet this should be addressed with the observability features in the next version, correct?

**Comment by baywet** [comment]
right, it's available right now in the preview version of the Java SDK (version 6 and up, available on snapshots).
We implemented OpenTelemetry tracing instrumentation. All that's left is for app developers to add processors and exporters to collect what the SDK is exporting.
https://opentelemetry.io/docs/instrumentation/java/manual/

We yet have to write the documentation about that aspect.
