### ISSUE TITLE
Paging does not work in Microsoft Graph API when requesting transitiveMembers of a use

### ISSUE THREAD

**Issue by alexsuter** [microsoftgraph/msgraph-sdk-java#1182]
I'm reading all transitiveMembers of a specifc user:

```
https://graph.microsoft.com/v1.0/users/XYZ/transitiveMemberOf/microsoft.graph.group?$top=1`
```

then I get the `$nextLink` back and when I call the `$nextLink` it won't work (statusCode: 400)

NextLink:

```
https://graph.microsoft.com/v1.0/users/XYZ/transitiveMemberOf/microsoft.graph.group?$top=1&$skiptoken=RFNwdAoAAQAAAAAAAAAAFAAAAB07M0vLFURAsMsUN4-KQOkBAAAAAAAAAAAAAAAAAAAXMS4yLjg0MC4xMTM1NTYuMS40LjIzMzEGAAAAAdTjC2hqzPNDrFEoagMHQUIAAchf4d1PyVVCl-hg90jO4hwBlAAAAAEAAAAA
```

```
{"error":{"code":"Request_UnsupportedQuery","message":"Invalid search request.","innerError":{"date":"2022-09-14T15:16:13","request-id":"e49d9ded-87ce-4219-80c8-b7f41a7eac2c","client-request-id":"e49d9ded-87ce-4219-80c8-b7f41a7eac2c"}}}
```

What can I do?

Sorry for posting it here. But I don't know how to get help...

**Comment by alexsuter** [comment]
any feeeback?

**Comment by baywet** [comment]
Hi @alexsuter,
Thanks for your patience on the matter. This repository and its issues are focused on the SDK itself and service teams are not watching those.
You should instead post on [the dedicated Microsoft Q&A forum](https://learn.microsoft.com/en-us/answers/topics/microsoft-graph-identity.html) to get answers from the service team.
Let us know if you need anything else.

**Comment by alexsuter** [comment]
ok thanks!

https://learn.microsoft.com/en-us/answers/questions/1047136/paging-does-not-work-in-microsoft-graph-api-when-r-1.html
