### ISSUE TITLE
SDK is not returning data for additionalDataManager

### ISSUE THREAD

**Issue by sachinkumar07** [microsoftgraph/msgraph-sdk-java#1196]
### Expected behavior
Secure score API should return the additional objects in additionalDataManager for controlScores.
graphClient.security().secureScores().buildRequest().get().getCurrentPage().get(0).controlScores.get(0).additionalDataManager()

### Actual behavior
graphClient.security().secureScores().buildRequest().get().getCurrentPage().get(0).controlScores.get(0).additionalDataManager()
Above call is always returning empty map for additionalDataManager. If we are calling API directly from Rest then API is returning all the data. API we are calling using Rest -https://graph.microsoft.com/v1.0/security/secureScores

### Steps to reproduce the behavior
Call graph sdk to get the secureScores and then try to get the controlScores's additionalDataManager.
SDK call - graphClient.security().secureScores().buildRequest().get().getCurrentPage().get(0).controlScores.get(0).additionalDataManager()

Graph SDK version - 5.35.0

**Comment by alesniak303** [comment]
I have a similar issue with the memberOf() call related to retrieving groups.  I cannot retrieve data via the additionalDataManager.

**Comment by ramsessanchez** [comment]
Hi @sachinkumar07 , Thank you for your patience. I've spent sometime looking into the issue and it seems there are some flaws in our additionalDataManager serialization. Unfortunately, fixing this issue may lead to unexpected issues in current customers meaning we'd likely require a major version bump. At the moment we are currently focused on releasing our next SDK version which also includes a fully redesigned version of the core library as well. I have gone ahead and tried your request on the preview version of our SDK and it seems to accuratley populate the additional data. I would recommend trying out the preview version if possible, let me know if you have any question migrating or adopting the new preview version. 
Here you can find a quick readme on how to do so: https://github.com/microsoftgraph/msgraph-sdk-java/tree/feature/6.0
And here is the translation of your code: 
``` Java
    public static void getControlScores() throws ExecutionException, InterruptedException {

        List<ControlScore> scores = graphClient.security()
                .secureScores("<ID>").get().thenApply(score -> {
                    List<ControlScore> scores1 = score.getControlScores();
                    return scores1;
                }).exceptionally(err -> {
                    System.out.println("string");
                    return null;
                }).join();

        Map<String, Object> addData = scores.get(0).getAdditionalData();
        System.out.println(addData.size());
    }
```

**Comment by sachinkumar07** [comment]
Thanks @ramsessanchez , Do we have a date for release of version 6.0.0?

**Comment by ramsessanchez** [comment]
At the moment no, we are still in process of implementing some functionality that is present in the current SDK (largeFileUpload for example). However, we will continue to update this preview version as functionality is added. Thanks again for using our SDK.
