### ISSUE TITLE
BaseRequest typing

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#120]
Similar to discussion in #116, `BaseRequest` is not modelled optimally either. The obvious indicator is the very free typing of the send methods:

```java
protected <T1, T2> T1 send(final HttpMethod method,
                               final T2 serializedObject) throws ClientException;

protected <T1, T2> void send(final HttpMethod method,
                                 final ICallback<T1> callback,
                                 final T2 serializedObject) 
```
T1 and T2 should not be there, `BaseRequest` should 

* carry one generic type T (e.g. `BaseRequest<User>`) and the types represented by `responseClass`, T1, T2 should be based on T as per demo in #119.

@darrelmiller Typing-wise the codebase is a mess but I don't think this is that big a job to fix. You sort this out for one use case and code generation propagates it everywhere.

**Comment by darrelmiller** [comment]
I have asked the team to try and find a concrete example where T1,T2 in the method is different than T1,T2 in the class and then we can decide if all of these generic types are actually needed.
