### ISSUE TITLE
Looking for a way to retrieve all drive items by source.externalid == <specific call record id> in one query?

### ISSUE THREAD

**Issue by edridudi** [microsoftgraph/msgraph-sdk-java#1210]
I've been looking for days now through out the entire api docs for a simple way to search specific drive items (Microsoft Teams Recordings) from the Organization's OneDrive by a specific call record id I receive via the subscription notifications (web hook).

Is there a way to do it in one query instead of searching it drive item by drive item in client side?

**Comment by ddyett** [comment]
I'd suggest asking this question here.

https://developer.microsoft.com/en-us/graph/support
