### ISSUE TITLE
OneDrive API responds slow

### ISSUE THREAD

**Issue by sunny-zode** [microsoftgraph/msgraph-sdk-java#1212]
### SDK version using:
```
<dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.4.6</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.graph</groupId>
      <artifactId>microsoft-graph</artifactId>
      <version>5.17.0</version>
    </dependency>
```

We tried with the 5.36.0 version as well. `<version>5.36.0</version>`
### Expected behavior
API should respond faster

### Actual behavior

API responds slowly for some files and takes 1 or 2 minutes. All files are the same in size and content, however, both APIs responds slow.
File Size: 494 KB

### Steps to reproduce the behavior
We are consuming the following two APIs which we are running it in the multiple threads.
So, irrespective of throttling, we observed like sometimes the API responds after 1 or 2 minutes or more.
This doesn't happens for any particular file, but happens with any file.
Note: We are doing testing by keeping the same file with size and content in one drive folder.
Intent: Downloading of all the files quickly.

APIs:
1.  oneDriveService.getGraphServiceClient()
                      .users(itemInfo.getMetadata().get(userId)
                      .drive()
                      .items(itemInfo.getMetadata().get(itemId)
                      .content()
                      .buildRequest()
                      .get())
2.  oneDriveService.getGraphServiceClient()
                                .users(userId)
                                .drive()
                                .items(itemId)
                                .permissions()
                                .buildRequest()
                                .get()

Thanks

**Comment by sunny-zode** [comment]
Hi @ramsessanchez 

Any update on this? We are working on a high-priority project and got blocked due to this issue.

Request you to take a look and suggest.

Thanks

**Comment by VipraSaha** [comment]
Hi @ramsessanchez 

Can you please share analysis on this ticket? We had raised the ticket around 15 days back and yet to receive initial analysis.
We are working on a high-priority task which is blocked due to this issue.
So kindly look into it on priority.

Thanks.

**Comment by ddyett** [comment]
I'd suggest filing an issue here as well as this seems to be an issue outside the SDK we can't help with.

https://developer.microsoft.com/en-us/graph/support
