### ISSUE TITLE
ErrorItemNotFound on several Calendar API and Mail API SDK requests

### ISSUE THREAD

**Issue by GeertZijlmans1** [microsoftgraph/msgraph-sdk-java#1225]
**Context**
Our application has an active subscription on CREATE events occurring in a Room Resource's Inbox with Calendar Processing set to _AutoUpdate_ and accept new requests tentatively.

**Expected Situation**
A correct synchronization can take place using the Event (Message) Ids provided to the application.

**Actual Situation**
The Graph API returns ErrorItemNotFound upon using the Graph SDK to retrieve an Event (Message) based upon an Id provided through a notification.

I've noticed several failure points (they don't happen always and don't happen at the same point in the synchronization) as if there is a process running in Exchange that moves the Event (Message) to a different store resulting in a new Id.

The process:
1. Our application endpoint receives a notification with a message ID;
2. Our application tries to retrieve the Message for the provided message ID;
- In some cases the Message cannot be retrieved because the Graph SDK returns an ErrorItemNotFound
3. Our application determines it is an Event Message and our application tries to retrieve the Event Message and its Event for the provided message ID. Potentially two things might happen here:
- In some cases the Event Message cannot be retrieved because the Graph SDK returns an ErrorItemNotFound
- In some cases the Event Message is returned, but without the Event
4. In case the Event Message and Event could be retrieved successfully, then the application will synchronize the Event details;
5. Read the Event details once more
- In some cases the Event cannot be retrieved because the Graph SDK returns an ErrorItemNotFound
7. Accept/Decline the Event depending on the outcome of the synchronization in the application
- In some cases the Event cannot be accepted/declined because the Graph SDK returns an ErrorItemNotFound
9. Delete the Event Message
- In some cases the Event Message cannot be deleted because the Graph SDK returns an ErrorItemNotFound

Can you please investigate the behavior above?
So intermittently the SDK returns an ErrorItemNotFound for a normal request for an Event (Message) for an Id provided through the notification.

**Details on the usage of the SDK:**
_Retrieving Message_
`graphServiceClient.users(aResourceIdentifier).messages(aMessageId).buildRequest().get()`

Resulting in a request like:
> https://graph.microsoft.com/v1.0/users/_aResourceIdentifier_/messages/_aMessageId_

_Retrieving Event Message_
`graphServiceClient.users(aResourceIdentifier).messages(aEventMessageId).buildRequest().expand("microsoft.graph.eventMessage/event($select=" + aListOfEventProperties + ")").get()`

Resulting in a request like:
> https://graph.microsoft.com/v1.0/users/_aResourceIdentifier_/messages/_aEventMessageId_?%24expand=microsoft.graph.eventMessage%2Fevent%28%24select%3Dend%2Cid%2CisAllDay%2CisCancelled%2CisOrganizer%2ClastModifiedDateTime%2ConlineMeeting%2Corganizer%2Crecurrence%2CresponseStatus%2Csensitivity%2CseriesMasterId%2CshowAs%2Cstart%2Csubject%2Ctype%29

_Deleting Event Message_
'graphServiceClient.users(aResourceIdentifier).messages(aMessageId).buildRequest().delete()'

_Retrieving an Event_
`graphServiceClient.users(aResourceIdentifier).events(aEventId).buildRequest(getRequestHeaderOptions()).select(aListOfEventProperties).get()`

Resulting in a request like:
> https://graph.microsoft.com/v1.0/users/_aResourceIdentifier_/events/_aEventId_?%24select=end%2Cid%2CisAllDay%2CisCancelled%2CisOrganizer%2ClastModifiedDateTime%2ConlineMeeting%2Corganizer%2Crecurrence%2CresponseStatus%2Csensitivity%2CseriesMasterId%2CshowAs%2Cstart%2Csubject%2Ctype

_Accepting an Event_
`graphServiceClient.users(aResourceIdentifier).events(aEventId).accept(EventAcceptParameterSet.newBuilder().withSendResponse(false).build()).buildRequest().post()`

_Declining an Event_
`graphServiceClient.users(aResourceIdentifier).events(aEventId).decline(EventDeclineParameterSet.newBuilder().withSendResponse(false).build()).buildRequest().post()`

**Comment by ramsessanchez** [comment]
@GeertZijlmans1, approximately how much time is elapsing between these calls? Further, which version of the SDK are you using? From the looks of it, you are using the synchronous versions of the get calls and post calls. I would recommend using the asynchronous calls so that these calls can be given ample time to complete. These calls are being made using exchange which is a legacy workload with plenty of traffic thus timing can be an issue.

**Comment by GeertZijlmans1** [comment]
@ramsessanchez 

The synchronization between an Event in Exchange and a Reservation in our system takes approx. 300ms. Are you available for a call such that I can share a bit more details to you?

If asynchronous calls are preferred, why are they not being mentioned as best-practice and used in the examples?

**Comment by ddyett** [comment]
as we have re-written much of the code here in our upcoming version we will not address this issue directly.  We will make sure the docs use async patterns with the upcoming releases.
