### ISSUE TITLE
Authenticate as User Principal using Certificated-based Authentication (CBA)

### ISSUE THREAD

**Issue by sharonchansy** [microsoftgraph/msgraph-sdk-java#1238]
Does Graph API / Graph SDK support the Azure AD certificate-based authentication method? https://learn.microsoft.com/en-us/azure/active-directory/authentication/concept-certificate-based-authentication-technical-deep-dive

I have an a back-end app currently using username + password credentials to call Graph API successfully:
```
      final var usernamePasswordCredential = new CustomUsernamePasswordCredentialBuilder()
          .clientId("clientId")
          .username("username")
          .password("password")
          .tenantId("tenantId").build();

      final var userTokenCredentialAuthProvider = new TokenCredentialAuthProvider(scopes,
          usernamePasswordCredential);

      var httpClient = buildHttpClient(officialAccountConfiguration,
          userTokenCredentialAuthProvider);

      var graphServiceClient = GraphServiceClient.builder()
          .authenticationProvider(userTokenCredentialAuthProvider)
          .httpClient(httpClient).buildClient();
```

However customer requires we stop using passwords or secrets, and instead switch to certificates. I see that MSAL supports certificates for _**service**_ principals:
```
    ClientCertificateCredential credential = new ClientCertificateCredentialBuilder()
        .tenantId("tenantId")
        .clientId("appRegistrationId")
        .pemCertificate("~/cert.pem").build();
```

Is it also available for **_user_** principals?
If not supported on SDK yet, then is it already available via HTTP API?
Appreciate any hints. Thanks a lot.

**Comment by baywet** [comment]
Hi @sharonchansy,
Microsoft Graph supports two types of contexts: 
- application only which only carries the identity of the application
- delegated which carries the identity of a user using an application

Not all endpoint support both contexts, and you can find which endpoint support what context in the permissions section of the documentation of the specific endpoint.

Certificate authentication is supported for app only context, as well as on behalf of context (e.g. you're building an API secured by Azure Active Directory, and that API in turns calls Microsoft Graph).

You can find more detailed information about how to setup the authentication for your application [in the documentation](https://learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Java)

Let us know if you need anything else.

**Comment by sharonchansy** [comment]
Hi @baywet ,
I need to call the Teams send message endpoint: https://learn.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-1.0&tabs=http#permissions
This requires delegated user context.

I see that Azure Active Directory supports certificate authentication: https://learn.microsoft.com/en-us/azure/active-directory/authentication/concept-certificate-based-authentication-technical-deep-dive
Do you mean that this **cannot** be used by a back-end service to authenticate then call Microsoft Graph?

Thanks.

**Comment by baywet** [comment]
Aaah, you're referring to user certificates, not app certificates. We generally discourage from authenticating the user directly using their credentials, You should instead implement any of the delegated flows (auth code, browser redirection, device code...), when the user is asked to sign in with their browsers, they'll get a prompt allowing them to select the sign-in method, which can include a user certificate if the user account is configured for it.
I hope this clarifies the confusion.
