### ISSUE TITLE
create subscription graphClient call throws "401 Unauthorized graph error response"(Even it has valid token with all required permissions).

### ISSUE THREAD

**Issue by pjpraveenjayakumar** [microsoftgraph/msgraph-sdk-java#1251]
One of our Partner was using graphClient.subscriptions().buildRequest().post(subscription) method to create subscriptions. It is expecting some application permissions.We have set those application permissions in [portal.azure.com](https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fportal.azure.com%2F&data=05%7C01%7Ctmdevsup%40microsoft.com%7C67fa6e4b31a64e9d91b508daaa97cfe3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638009866326755508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RYmA4Uc3oNFCLUxUZ%2BPx8c455VAAfFbtIUqO3lIV3%2B4%3D&reserved=0) against the bot.Permissions are listed during the oauth flow and Partner observed that they were getting "401 unauthorized" for the very first time, even though the generated token has all the required permissions to create subscription and the same flow was working fine with the second attempt. partner was using Graph service client to create the subscription. Could you please let us know what changes needs to be done from partner side to overcome this issue.
Graph Client is using the Token generated via client_credentials.

![image](https://user-images.githubusercontent.com/109327327/199561672-a75f706e-b184-46b9-91fe-e3feabc6de55.png)

Error response coming from AAD
Regarding the create subscription failing for the first time, we have logged the response headers and sharing it here. 

request headers : [SdkVersion : graph-java/v4.2.0, SdkVersion : graph-java/v4.2.0]

response headers : [Cache-Control : no-cache, client-request-id : 6a9af6f3-5472-4c61-b7ce-a5292eb63fcd, Content-Type : application/json, Date : Thu, 06 Oct 2022 10:37:36 GMT, request-id : 300397d4-0c20-4b0e-840b-bce96feb3a10, Strict-Transport-Security : max-age=31536000, Transfer-Encoding : chunked, Vary : Accept-Encoding, x-ms-ags-diagnostic : {\"ServerInfo\":{\"DataCenter\":\"Australia East\",\"Slice\":\"E\",\"Ring\":\"5\",\"ScaleUnit\":\"002\",\"RoleInstance\":\"SY2PEPF0000208A\"}}] service error : [com.microsoft.graph.http.GraphError@2a91269a](mailto:com.microsoft.graph.http.GraphError@2a91269a)

response code : 401

response message : Unauthorized graph error response :com.microsoft.graph.http.GraphErrorResponse@b9d82a4 GraphServiceException : com.microsoft.graph.http.GraphServiceException:

Error code: ExtensionError\nError message: Operation: Create;

### Steps to reproduce the behavior

**Comment by ramsessanchez** [comment]
Hi @pjpraveenjayakumar, as you probably know we have moved on from the v4 series of our sdks. Is it possible for you to upgrade to the latest v5.35.0 version? API's are constantly being updated and with these updates so is our generated library. Please let me know if this is possible. Thank you.

**Comment by MarianneAK** [comment]
Hello @pjpraveenjayakumar , were you able to resolve this ? I'm facing the same issue ...
