### ISSUE TITLE
redirectUrl(),clientId().their pamarameter should put what pamarameter?

### ISSUE THREAD

**Issue by Squall-Huang** [microsoftgraph/msgraph-sdk-java#1263]
This is Android app.
It got wrong at this line ->`graphServiceClient.me().buildRequest().get()`
```kotlin
InteractiveBrowserCredentialBuilder()
       .clientId(accountId)
       .redirectUrl("msauth://")
       .build().let { interactiveBrowserCredential ->
           TokenCredentialAuthProvider(
                arrayListOf("user.read"),
                interactiveBrowserCredential
               )
             }.let { tokenCredentialAuthProvider ->
                  GraphServiceClient.builder()
                      .authenticationProvider(tokenCredentialAuthProvider)
                       .buildClient()
                       }.let { graphServiceClient ->
                       graphServiceClient.me().buildRequest().get()
                      }.let { user ->
                      user?.apply {
                      Log.d(TAG, "user: ${aboutMe}")
                      }
                    }
```

> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.hannlync.kepler, PID: 1775
>     com.microsoft.graph.core.ClientException: Error executing the request
>         at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:410)
>         at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:225)
>         at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:202)
>         at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:335)
>         at com.microsoft.graph.requests.UserRequest.get(UserRequest.java:71)
>         at com.hannlync.kepler.fragment.maintenance_fragment.MaintenanceFragment$onCreateView$1$onCreated$1.onSuccess(MaintenanceFragment.kt:105)
>         at com.microsoft.identity.client.PublicClientApplication.postAuthResult(PublicClientApplication.java:2023)
>         at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onTaskCompleted(SingleAccountPublicClientApplication.java:438)
>         at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onTaskCompleted(SingleAccountPublicClientApplication.java:429)
>         at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnTaskCompleted(CommandDispatcher.java:562)
>         at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$1000(CommandDispatcher.java:86)
>         at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:538)
>         at android.os.Handler.handleCallback(Handler.java:942)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loopOnce(Looper.java:201)
>         at android.os.Looper.loop(Looper.java:288)
>         at android.app.ActivityThread.main(ActivityThread.java:7898)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by baywet** [comment]
Hi @Squall-Huang 
Thanks for reaching out and for using the Java SDK.
The error you're getting would indicate the SDK is not able to establish a connection with Microsoft Graph or that it was dropped (and unable to reconnect).
Could you check the DNS/network settings of the emulator/device to make sure connectivity to graph.microsoft.com works?

**Comment by Squall-Huang** [comment]
Hi  @baywet 
Thank you for replay.
I use android kotlin coroutine IO solve this problem as follow:

```kotlin
val graphServiceClient = GraphServiceClient
   .builder()
     .authenticationProvider(object : IAuthenticationProvider {
       override fun getAuthorizationTokenAsync(requestUrl: URL)
         : CompletableFuture<String> {
CompletableFuture<String>().also { completableFuture ->
  completableFuture.complete(accessToken)
   }.also { completableFuture ->
 return completableFuture
 }
   }
   }).buildClient()

viewLifecycleOwner.lifecycleScope.launch(Dispatchers.IO) {
                                        viewLifecycleOwner.repeatOnLifecycle(Lifecycle.State.STARTED) {
  val user = graphServiceClient.me().buildRequest().get()
   Log.d(TAG, "Graph:displayName: ${user?.displayName}")
  }
 }
```
