### ISSUE TITLE
Can I use this SDK to authenticate as a service user (app-only credentials)?

### ISSUE THREAD

**Issue by henricook** [microsoftgraph/msgraph-sdk-java#127]
All the examples seem to be focused on a user being involved in the authentication flow rather than me logging in as a 'service user' - is it possible?

Thanks,

Henri

**Comment by darrelmiller** [comment]
We don't have a sample to show how to do this currently.  With applications that are registered [here](https://apps.dev.microsoft.com/) you can do [client credential flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow) against the Microsoft Graph using any OAuth2 compatible library.  Our Java SDK has a single [interface](https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/authentication/IAuthenticationProvider.java) that needs to be implemented to enable authorizing requests.

I realize this is not ideal and we are working to improve our Auth support and the samples around the different scenarios.

**Comment by henricook** [comment]
Thanks for getting back to me Darren, I understand it's a work in progress, we'll use a 3rd party until this is ready

Cheers,

Henri

**Comment by davidmoten** [comment]
@henricook That is how we are using the SDK now (authenticating as a service user). I can release the code and O365 admin instructions as an open source repo if you like. To create the service account do this as O365 admin (very roughly):

* Go to portal.azure.com - Azure Active Directory - Enterprise Applications - Create new
* The redirect uri can be anything but you will need to reuse the value: https://localhost:8080
* Add permissions
* Create new key
* Copy the ApplicationId and generated new key and they are your client id and client secret

I'll refine those instructions for our business' documentation soon and can share.

We then do this to authenticate:

```java
private static IGraphServiceClient createMsGraphClient(Options options) {
		final String tenantName = options.getTenantName();
		final String clientId = options.getAzureClientId();
		final String clientSecret = options.getAzureClientSecret();
		MsGraphAccessTokenProvider accessTokenProvider = MsGraphAccessTokenProvider //
				.tenantName(tenantName) //
				.clientId(clientId) //
				.clientSecret(clientSecret) //
				.refreshBeforeExpiry(5, TimeUnit.MINUTES) //
				.build();
		ILogger logger = new MsGraphLog4jLogger();
		logger.setLoggingLevel(LoggerLevel.DEBUG);

		MsGraphAuthenticationProvider authProvider = MsGraphAuthenticationProvider.from(accessTokenProvider);

		return GraphServiceClient.builder() //
				.authenticationProvider(authProvider) //
				.logger(logger) //
				.buildClient();
	}
```
MsGraphAccessTokenProvider.java:
```java
package au.gov.amsa.msgraph;

import java.io.DataOutputStream;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URL;
import java.net.URLEncoder;
import java.util.concurrent.TimeUnit;

import javax.net.ssl.HttpsURLConnection;

import com.github.davidmoten.guavamini.Preconditions;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

//ThreadSafe
public final class MsGraphAccessTokenProvider {

    private static final int OK = 200;
    private static final String POST = "POST";
    private static final String APPLICATION_JSON = "application/json";
    private static final String REQUEST_HEADER = "Accept";
    private static final String SCOPE_MS_GRAPH_DEFAULT = "https://graph.microsoft.com/.default";
    private static final String GRANT_TYPE_CLIENT_CREDENTIALS = "client_credentials";
    private static final String RESOURCE_MS_GRAPH = "https://graph.microsoft.com/";
    private static final String OAUTH2_TOKEN_URL_PREFIX = "https://login.windows.net/";
    private static final String OAUTH2_TOKEN_URL_SUFFIX = "/oauth2/token";

    private static final String PARAMETER_SCOPE = "scope";
    private static final String PARAMETER_CLIENT_SECRET = "client_secret";
    private static final String PARAMETER_GRANT_TYPE = "grant_type";
    private static final String PARAMETER_CLIENT_ID = "client_id";
    private static final String PARAMETER_RESOURCE = "resource";

    private final String tenantName;
    private final String clientId;
    private final String clientSecret;
    private final long refreshBeforeExpiryMs;

    private long expiryTime;
    private String accessToken;

    private MsGraphAccessTokenProvider(String tenantName, String clientId, String clientSecret,
            long refreshBeforeExpiryMs) {
        Preconditions.checkNotNull(tenantName);
        Preconditions.checkNotNull(clientId);
        Preconditions.checkNotNull(clientSecret);
        Preconditions.checkArgument(refreshBeforeExpiryMs >= 0, "refreshBeforeExpiry must be >=0");
        this.tenantName = tenantName;
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.refreshBeforeExpiryMs = refreshBeforeExpiryMs;
    }

    public static Builder tenantName(String tenantName) {
        return new Builder(tenantName);
    }

    public synchronized String get() {
        long now = System.currentTimeMillis();
        if (accessToken != null && now < expiryTime - refreshBeforeExpiryMs) {
            return accessToken;
        } else {
            return refreshAccessToken();
        }
    }

    private String refreshAccessToken() {
        try {
            URL url = new URL(OAUTH2_TOKEN_URL_PREFIX + tenantName + OAUTH2_TOKEN_URL_SUFFIX);
            HttpsURLConnection con = (HttpsURLConnection) url.openConnection();
            con.setRequestMethod(POST);
            con.setRequestProperty(REQUEST_HEADER, APPLICATION_JSON);
            StringBuilder params = new StringBuilder();
            add(params, PARAMETER_RESOURCE, RESOURCE_MS_GRAPH);
            add(params, PARAMETER_CLIENT_ID, clientId);
            add(params, PARAMETER_GRANT_TYPE, GRANT_TYPE_CLIENT_CREDENTIALS);
            add(params, PARAMETER_CLIENT_SECRET, clientSecret);
            add(params, PARAMETER_SCOPE, SCOPE_MS_GRAPH_DEFAULT);
            con.setDoOutput(true);
            try (DataOutputStream dos = new DataOutputStream(con.getOutputStream())) {
                dos.writeBytes(params.toString());
            }
            int responseCode = con.getResponseCode();

            String json = Util.readString(con.getInputStream());

            if (responseCode != OK) {
                throw new RuntimeException("Response code=" + responseCode + ", output=" + json);
            } else {
                JsonObject o = new JsonParser().parse(json).getAsJsonObject();
                // update the cached values
                expiryTime = o.get("expires_on").getAsLong() * 1000;
                accessToken = o.get("access_token").getAsString();
                return accessToken;
            }
        } catch (IOException e) {
            // reset stuff
            expiryTime = 0;
            accessToken = null;
            throw new RuntimeException(e);
        }
    }

    private static void add(StringBuilder params, String key, String value) {
        if (params.length() > 0) {
            params.append("&");
        }
        params.append(key);
        params.append("=");
        try {
            params.append(URLEncoder.encode(value, "UTF-8"));
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(e);
        }
    }

    public static final class Builder {
        final String tenantName;
        String clientId;
        String clientSecret;
        
        // default to refresh access token on every call of get()
        long refreshBeforeExpiryMs = Long.MAX_VALUE;

        Builder(String tenantName) {
            this.tenantName = tenantName;
        }

        public Builder2 clientId(String clientId) {
            this.clientId = clientId;
            return new Builder2(this);
        }

    }

    public static final class Builder2 {
        private final Builder b;

        Builder2(Builder b) {
            this.b = b;
        }

        public Builder3 clientSecret(String clientSecret) {
            b.clientSecret = clientSecret;
            return new Builder3(b);
        }

    }

    public static final class Builder3 {

        private final Builder b;

        Builder3(Builder b) {
            this.b = b;
        }

        /**
         * The access token is returned from AD with an expiry time. If you call
         * {@code get()} within {@code duration} of the expiry time then a refresh of
         * the access token will be performed. If this value is not set then the access
         * token is refreshed on every call of {@code get()}.
         * 
         * @param duration
         * @param unit
         * @return
         */
        public Builder3 refreshBeforeExpiry(long duration, TimeUnit unit) {
            b.refreshBeforeExpiryMs = unit.toMillis(duration);
            return this;
        }

        public MsGraphAccessTokenProvider build() {
            return new MsGraphAccessTokenProvider(b.tenantName, b.clientId, b.clientSecret, b.refreshBeforeExpiryMs);
        }
    }

}
```
and MsGraphAuthenticationProvider.java:
```java
package au.gov.amsa.msgraph;

import com.microsoft.graph.authentication.IAuthenticationProvider;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.http.IHttpRequest;
import com.microsoft.graph.options.HeaderOption;

public final class MsGraphAuthenticationProvider implements IAuthenticationProvider {

    private static final String AUTHORIZATION_HEADER_NAME = "Authorization";
    private static final String OAUTH_BEARER_PREFIX = "Bearer ";
    private final MsGraphAccessTokenProvider accessToken;

    private MsGraphAuthenticationProvider(MsGraphAccessTokenProvider accessToken) {
        this.accessToken = accessToken;
    }
    
    public static MsGraphAuthenticationProvider from(MsGraphAccessTokenProvider accessToken) {
        return new MsGraphAuthenticationProvider(accessToken);
    }

    @Override
    public void authenticateRequest(IHttpRequest request) {
        // If the request already has an authorization header, do not intercept it.
        for (final HeaderOption option : request.getHeaders()) {
            if (option.getName().equals(AUTHORIZATION_HEADER_NAME)) {
                // Found an existing authorization header so don't add another
                return;
            }
        }
        try {
            final String token = accessToken.get();
            request.addHeader(AUTHORIZATION_HEADER_NAME, OAUTH_BEARER_PREFIX + token);
        } catch (ClientException e) {
            final String message = "Unable to authenticate request, No active account found";
            throw new ClientException(message, e);
        }
    }

}
```

**Comment by gnumarco** [comment]
I do the OAuth2 part using ScribeJava which supports AAD OAuth2. Then when you get the token, you can do whatever you want to do with the Graph SDK.

**Comment by davidmoten** [comment]
Thanks @gnumarco, can you share some code so we can see it in action?

**Comment by laguiz** [comment]
I was able to use the api with `Application` type permissions using @davidmoten code above (thank you). 
For others, don't forget to ask your Azure Administrator to `concent` your requested permissions from Azure Portal : https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app
In fact even if you configured your application here https://apps.dev.microsoft.com it's only a `wish` that needs approval.
Would be nice to have this code built-in in the sdk or at least mention this thread on the readme.

**Comment by selimelawwa** [comment]
@davidmoten  Hello, have you tried using Apache HttpClient within Microsoft Graph SDK to authenticate with username / password instead of the client-id/ access token approach?
something similar to [Authentication to SharePoint from Java with username/password](https://stackoverflow.com/a/29609502/8863925)

Our use case is to allow the Java app to connect to SharePoint and query lists, but authenticate using only username/password while still benefiting from Microsoft Graph SDK classes.

**Comment by davidmoten** [comment]
@selimelawwa nope, good luck.

**Comment by darrelmiller** [comment]
@selimelawwa  You should be able to use this [auth provider](https://github.com/microsoftgraph/msgraph-sdk-java-auth/blob/dev/src/main/java/com/microsoft/graph/auth/publicClient/UsernamePasswordProvider.java) to do username/password auth.

**Comment by selimelawwa** [comment]
@darrelmiller Thanks alot I have checked it, do you know what should be the value of client ID or where should it be obtained from?

**Comment by ingoschaefer** [comment]
I use the Azure AD Library for Java (https://github.com/AzureAD/azure-activedirectory-library-for-java) for aquiring the tokens and implemented a very small Class implementing the IAuthenticationProvider Interface. So there is no need to parse the AD response myself.

**Comment by heyalistair** [comment]
Looks like Microsoft recently provided a new repo to do this: https://github.com/microsoftgraph/msgraph-sdk-java-auth

I just tested it out and it works well for the Client Credentials flow, which was mentioned at the start of the issue. It's still in beta, but it seems relatively feature-complete and plays nicely with the MS graph java api

I found out about it by reading through this issue and following the reference to issue #134, which mentions it. (FWIW I think this issue can be closed!)

**Comment by kumbhaj** [comment]
Hi @heyalistair Can you please share the code sample? I tried and getting issues. [https://github.com/microsoftgraph/msgraph-sdk-java-auth/issues/25](Issue)

**Comment by kumbhaj** [comment]
Hi @heyalistair  Can you please share the code for  using msgraph-sdk-java-auth. I tried and getting erros. [https://github.com/microsoftgraph/msgraph-sdk-java-auth/issues/25](url)

**Comment by Budlee** [comment]
These Auth libs shouldreally get integrated into this project. Also the problem with the msgraph-sdk-java-auth is that it is currently still snapshot!

@darrelmiller  it would be good to get an update on what MSFT are thinking regarding auth being added to this project or getting a stable release of the auth library

**Comment by wimvanhouts** [comment]
Regarding authentication as a service user, maybe have a look at : https://xqting.wordpress.com/2020/03/13/using-ms-graph-and-msal-to-fetch-ms-teams-data-in-java-or-net/

**Comment by baywet** [comment]
Hey everyone,
Providing a refresh here before I close the issue. (using [the auth library](https://github.com/microsoftgraph/msgraph-sdk-java-auth))
```Java
private static final String clientId = "<appid>";
private static final String clientSecret = "<appsecret>";
private static final String tenantId = "<tenantid>";
private static final NationalCloud endpoint = NationalCloud.Global;
private static final List<String> scopes = Arrays.asList("https://graph.microsoft.com/.default");
final ClientCredentialProvider authProvider = new ClientCredentialProvider(clientId, scopes,
                clientSecret, tenantId, endpoint);
final IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider(authProvider)
                .buildClient();
```

**Comment by muthu1712** [comment]
Hi @baywet ,
As @Budlee pointed out, the auth library is still in preview version. We can't be using it in a enterprise wide solution, where there'll be tech debt created, which should migrate to the actual version instead of snapshot, and it doesn't seem to be a pretty good idea.
Any thoughts, when the actual release would be done?

**Comment by baywet** [comment]
Hey @muthu1712 
Thanks for your feedback. I don't have any timeline to share. There is ongoing work to replace this auth library by azure identity (which uses MSAL under the covers) here https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/42

At this time your options are:
- use the auth library 
- manually integrate the SDK with MSAL/azure identity (more code to build/maintain on your side, so obviously more technical debt)
- wait for the azure identity work to be completed (again, no timeline at this time)

**Comment by muthu1712** [comment]
> Hey @muthu1712
> Thanks for your feedback. I don't have any timeline to share. There is ongoing work to replace this auth library by azure identity (which uses MSAL under the covers) here [microsoftgraph/msgraph-sdk-java-core#42](https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/42)
> 
> At this time your options are:
> 
> * use the auth library
> * manually integrate the SDK with MSAL/azure identity (more code to build/maintain on your side, so obviously more technical debt)
> * wait for the azure identity work to be completed (again, no timeline at this time)

Thanks @baywet . We would probably be going with the first option for now. Thank you.
