### ISSUE TITLE
How to remove filter from worksheet column using microsoft graph api?

### ISSUE THREAD

**Issue by SudipRai** [microsoftgraph/msgraph-sdk-java#1273]
Due to column filters, following microsoft graph api "https://graph.microsoft.com/v1.0/groups/{ {group-id}}/drive/items/{ {item-id}}/workbook/worksheets/test/range(address='A1:Q1')/delete" throws "The operation failed because it conflicts with a filtered range." error. Is there any way to remove filters from the column?

**Comment by baywet** [comment]
Hi @SudipRai ,
Thanks for reaching out. This repository and the issues associated are focused on the SDK itself. The service teams are not watching this place.
The best thing to do for those sorts of questions is to post [on the dedicated Q&A forum](https://docs.microsoft.com/answers/topics/microsoft-graph-workbooks.html?filter=unanswered) were somebody from the service team will be able to help.

**Comment by SudipRai** [comment]
GraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

String shift = "shift-value";

graphClient.me().drive().items("{id}").workbook().names("{name}")
	.range()
	.delete(WorkbookRangeDeleteParameterSet
		.newBuilder()
		.withShift(shift)
		.build())
	.buildRequest()
	.post();

This wont work in Java SDK as well when there is any filter applied in the any column of excel sheet. Is there any workaround? Or may be any way to remove the filter from column?

**Comment by baywet** [comment]
Are you getting the same issue when you run the query [in graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer#) ?

**Comment by SudipRai** [comment]
I havent tested it in graph explorer.
But i have tried the api through postman, getting the same issue .

**Comment by baywet** [comment]
Thanks, then please reach out on the Microsoft Q&A forum since it's not an issue related to the SDK specifically but to an API in particular. Closing.
