### ISSUE TITLE
Memory leak executing token MSgraph OAuth2.0 X509CRLImpl.java and sun.security.util.DerValue

### ISSUE THREAD

**Issue by eosolovyev** [microsoftgraph/msgraph-sdk-java#1279]
Our application have temporary problem when executing token MSgraph OAuth2.0 with certificate process exceed application memory and we face our internal MemoryShortageException. Executing can take more than 1000Mb (at 1500Mb total).
Main objects which takes memory are:
- sun.security.util.DerValue.java
- sun.security.x509.X509CRLImpl

### Expected behavior
Application's memory does not fill.

### Actual behavior
Memory periodically fill when application try to execute token MSgraph OAuth2.0 certificate

### Method
>     protected AccessToken executeGetAccessTokenRequest(HttpEntity body, URI tokenServerUri) throws IOException {
        String methodName = "executeGetAccessTokenRequest";
        HttpPost httpPostRequest = new HttpPost(tokenServerUri);
        httpPostRequest.addHeader("Content-Type", body.getContentType().getValue());
        httpPostRequest.setEntity(body);
        try (CloseableHttpResponse response = httpClient.execute(httpPostRequest)) {
            int statusCode = response.getStatusLine().getStatusCode();
            if (statusCode < 200 || statusCode > 299) {
                String reason = response.getStatusLine().getReasonPhrase();
                getLog().error(methodName, null, "Failed to get access token");
                return null;
            }
            String jsonResponse = EntityUtils.toString(response.getEntity());
            AccessTokenResponse accessTokenResponse = mapper.readValue(jsonResponse, AccessTokenResponse.class);
            getLog().info(methodName, null, "Access token received: [{}]", accessTokenResponse);
            long expiresAtMilliseconds = System.currentTimeMillis() + (long) (accessTokenResponse.getExpiresIn() * 1000);
            return new AccessToken(accessTokenResponse.getAccessToken(), new Date(expiresAtMilliseconds));
        } catch (Exception e) {
            getLog().error(methodName, null, e, "Failed to get access token");
            return null;
        }
    }

### TRACE

![This is an image](https://user-images.githubusercontent.com/57712771/206125799-a6f8e61f-7b83-42f0-8264-6c9dfdb2b81d.png)

Central-5
sun.security.x509.X509CRLImpl.parse(DerValue) X509CRLImpl.java  <--- Here
sun.security.x509.X509CRLImpl.<init>(byte[]) X509CRLImpl.java:137  <--- Here
sun.security.provider.X509Factory.engineGenerateCRL(InputStream) X509Factory.java:390
java.security.cert.CertificateFactory.generateCRL(InputStream) CertificateFactory.java:497
sun.security.provider.certpath.URICertStore.engineGetCRLs(CRLSelector) URICertStore.java:419
java.security.cert.CertStore.getCRLs(CRLSelector) CertStore.java:181
sun.security.provider.certpath.DistributionPointFetcher.getCRL(URIName) DistributionPointFetcher.java:261
sun.security.provider.certpath.DistributionPointFetcher.getCRLs(X509CRLSelector, X509CertImpl, DistributionPoint, boolean[], boolean, PublicKey, X509Certificate, String, List, Set, Date, String) DistributionPointFetcher.java:205
sun.security.provider.certpath.DistributionPointFetcher.getCRLs(X509CRLSelector, boolean, PublicKey, X509Certificate, String, List, boolean[], Set, Date, String) DistributionPointFetcher.java:137
sun.security.provider.certpath.RevocationChecker.checkCRLs(X509Certificate, PublicKey, X509Certificate, boolean, boolean, Set, Set) RevocationChecker.java:579
sun.security.provider.certpath.RevocationChecker.checkCRLs(X509Certificate, Collection, Set, PublicKey, boolean) RevocationChecker.java:464
sun.security.provider.certpath.RevocationChecker.check(X509Certificate, Collection, PublicKey, boolean) RevocationChecker.java:366
sun.security.provider.certpath.RevocationChecker.check(Certificate, Collection) RevocationChecker.java:336
sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(CertPath, List, List) PKIXMasterCertPathValidator.java:125
sun.security.provider.certpath.PKIXCertPathValidator.validate(TrustAnchor, PKIX$ValidatorParams) PKIXCertPathValidator.java:233
sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIX$ValidatorParams) PKIXCertPathValidator.java:141
sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(CertPath, CertPathParameters) PKIXCertPathValidator.java:80
java.security.cert.CertPathValidator.validate(CertPath, CertPathParameters) CertPathValidator.java:292
sun.security.validator.PKIXValidator.doValidate(X509Certificate[], PKIXBuilderParameters) PKIXValidator.java:381
sun.security.validator.PKIXValidator.engineValidate(X509Certificate[], Collection, List, AlgorithmConstraints, Object) PKIXValidator.java:279
sun.security.validator.Validator.validate(X509Certificate[], Collection, List, AlgorithmConstraints, Object) Validator.java:271
sun.security.ssl.X509TrustManagerImpl.validate(Validator, X509Certificate[], List, AlgorithmConstraints, String) X509TrustManagerImpl.java:315
sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509Certificate[], String, Socket, boolean) X509TrustManagerImpl.java:223
sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509Certificate[], String, Socket) X509TrustManagerImpl.java:129
sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(ClientHandshakeContext, X509Certificate[]) CertificateMessage.java:638
sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(ClientHandshakeContext, CertificateMessage$T12CertificateMessage) CertificateMessage.java:473
sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(ConnectionContext, ByteBuffer) CertificateMessage.java:369
sun.security.ssl.SSLHandshake.consume(ConnectionContext, ByteBuffer) SSLHandshake.java:377
sun.security.ssl.HandshakeContext.dispatch(byte, ByteBuffer) HandshakeContext.java:444
sun.security.ssl.HandshakeContext.dispatch(byte, Plaintext) HandshakeContext.java:422
sun.security.ssl.TransportContext.dispatch(Plaintext) TransportContext.java:182
sun.security.ssl.SSLTransport.decode(TransportContext, ByteBuffer[], int, int, ByteBuffer[], int, int) SSLTransport.java:149
sun.security.ssl.SSLSocketImpl.decode(ByteBuffer) SSLSocketImpl.java:1143
sun.security.ssl.SSLSocketImpl.readHandshakeRecord() SSLSocketImpl.java:1054
sun.security.ssl.SSLSocketImpl.startHandshake() SSLSocketImpl.java:394
org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(Socket, String, int, HttpContext) SSLConnectionSocketFactory.java:275
org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(int, Socket, HttpHost, InetSocketAddress, InetSocketAddress, HttpContext) SSLConnectionSocketFactory.java:254
org.apache.http.impl.conn.HttpClientConnectionOperator.connect(ManagedHttpClientConnection, HttpHost, InetSocketAddress, int, SocketConfig, HttpContext) HttpClientConnectionOperator.java:123
org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(HttpClientConnection, HttpRoute, int, HttpContext) PoolingHttpClientConnectionManager.java:318
org.apache.http.impl.execchain.MainClientExec.establishRoute(AuthState, HttpClientConnection, HttpRoute, HttpRequest, HttpClientContext) MainClientExec.java:363
org.apache.http.impl.execchain.MainClientExec.execute(HttpRoute, HttpRequestWrapper, HttpClientContext, HttpExecutionAware) MainClientExec.java:219
org.apache.http.impl.execchain.ProtocolExec.execute(HttpRoute, HttpRequestWrapper, HttpClientContext, HttpExecutionAware) ProtocolExec.java:195
org.apache.http.impl.execchain.RetryExec.execute(HttpRoute, HttpRequestWrapper, HttpClientContext, HttpExecutionAware) RetryExec.java:86
org.apache.http.impl.execchain.RedirectExec.execute(HttpRoute, HttpRequestWrapper, HttpClientContext, HttpExecutionAware) RedirectExec.java:108
org.apache.http.impl.client.InternalHttpClient.doExecute(HttpHost, HttpRequest, HttpContext) InternalHttpClient.java:184
org.apache.http.impl.client.CloseableHttpClient.execute(HttpUriRequest, HttpContext) CloseableHttpClient.java:82
org.apache.http.impl.client.CloseableHttpClient.execute(HttpUriRequest) CloseableHttpClient.java:106
com.OUR_APPLICATION.emailcommon.mail.oauth.ClientCredentials.executeGetAccessTokenRequest(HttpEntity, URI) ClientCredentials.java:78

**Comment by ramsessanchez** [comment]
Hi @eosolovyev , I have a few questions. Firstly, which version of the SDK are you using and what is the authentication method that you are using for your application. Secondly, which environment are you develpoing with/developing for? We leverage the Azure SDK library for much of our authentication, depending on the auth method, so perhaps that would be a better place to start. However, depending on the information you can provide regarding the dependencies you are using I may be able to assist you as well. Thanks for using our graph SDK.
