### ISSUE TITLE
Update Online meeting participant's with coorganizer role using msgraph-sdk-java

### ISSUE THREAD

**Issue by pjpraveenjayakumar** [microsoftgraph/msgraph-sdk-java#1281]
One of our partners were trying to assign a coorganizer role to the online meeting participants using msgraph-sdk-java (com.microsoft.graph.models.OnlineMeetingRole) function / method to create and manage meetings.update the meeting participants with the COORGANIZER role public enum OnlineMeetingRole { ATTENDEE, PRESENTER, COORGANIZER, PRODUCER, UNEXPECTED_VALUE; private OnlineMeetingRole() { } } When the value that is returned after they execute the update is Null.When they get the OnlineMeetingRole it does not include the COORGANIZER role.

 when we tried the same scenario in Graph explorer and Http post request then it gives the (200 ok) response with participant role mentioned as ""unknownFutureValue" as shown below." but it successfully sets up the coorganizer in meeting UI.
![image](https://user-images.githubusercontent.com/109327327/206619170-d36faa66-d57b-4fc7-99a2-81ad7de0ef08.png)

Partner have tried with v5.35.0 (Released Sep 15, 2022) and v5.41.0 (Released Nov 10, 2022), but neither support the "COORGANIZER" role in the com.microsoft.graph.models.OnlineMeetingRole class.

could you please let us know whether updating the online meeting participants with coorganizer role is supported or not via msgraph-sdk-java? and is it recommended to use it in production?

### Steps to reproduce the behavior
create online meeting then update the participants with coorganizer role using public enum OnlineMeetingRole { ATTENDEE, PRESENTER, COORGANIZER, PRODUCER, UNEXPECTED_VALUE; private OnlineMeetingRole() { } } When the value that is returned after they execute the update is Null.

**Comment by baywet** [comment]
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
