### ISSUE TITLE
Unable to add members to group using batch request (ref serialization)

### ISSUE THREAD

**Issue by mkarczewski85** [microsoftgraph/msgraph-sdk-java#1287]
### Expected behavior

I'm trying to add group member using code from following example: https://learn.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=java 
I have multiple groups and multiple users. Every user should be added as new member for each of the group. I'm preparing requests for each user and  trying to send all requests in batch. I'm expecting status code 204 for every single request in a batch. 

### Actual behavior: 

Each time I receive 400 status code for every request in a batch with following message:

> {"error":{"code":"Request_BadRequest","message":"An unexpected 'EndOfInput' node was found when reading from the JSON reader. A 'StartObject' node was expected.","innerError":{"date":"2022-12-15T07:56:51","request-id":"7214eefb-d1e3-455b-8b63-41ff62529e3c","client-request-id":"a40cf639-7385-4de5-ab47-5bab324293a4"}}}

### Steps to reproduce the behavior

The code I use:

```java
@Override
public void assignGroups(final Collection<User> users, final Collection<String> groupIds, final String environment) {
	final GraphServiceClient<Request> graph = GraphUtility.getGraph(environment);
	final BatchRequestContent batchRequestContent = new BatchRequestContent();
	groupIds.forEach(groupId -> users.forEach(user -> batchRequestContent.addBatchRequestStep(graph.groups(groupId)
                        .members()
                        .references()
                        .buildRequest(),
                HttpMethod.POST,
                user)));
        BatchResponseContent post = graph.batch()
                .buildRequest()
                .post(batchRequestContent);
}
```
I double checked that all users and groups existed in AAD during code execution. 
I tried to map User to DirectoryObject with the same result.

I use:
- Microsoft Graph Java SDK **5.42.0** 
- JDK 17 Temurin
- Spring Boot 2.7.1
- IntelliJ IDEA 2022.1.3 (Ultimate Edition)

I think the problem is with the id field. Graph API reference endpoint expects field with prefixed name: '@odata.id'.

**Comment by baywet** [comment]
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
