### ISSUE TITLE
Duplicate Search Hits

### ISSUE THREAD

**Issue by gaddscientist** [microsoftgraph/msgraph-sdk-java#1320]
I posted a detailed question to the Microsoft Q&A forum and was directed to post here instead by the dev that answered as there does seem to be a valid issue.

Link to the Q&A post: https://learn.microsoft.com/en-us/answers/questions/1159898/microsoft-graph-java-sdk-duplicate-search-hits

Hi I'm having an issue with the Java SDK for the Microsoft Graph API returning duplicate search hits for a given request. I'm using the endpoint `https://graph.microsoft.com/v1.0/search/query` with a body that contains

```
{
  "requests": [
    {
      "entityTypes": [
        "driveItem", "listItem", "list"
      ],
      "query": {
        "queryString": "bunny"
      }
    }
  ]
}
```

When making this request via the Java SDK, I am getting returned a `SearchHitsContainer` object with multiple hits with identical hit ID's. The file in question is hosted on SharePoint and any files uploaded via OneDrive are not exhibiting this behavior. Note that this happens with any file i've uploaded to any of the SharePoint site's I'm testing with.

Here are the request and response Java objects i'm seeing in my debugger

![Screenshot 2023-01-10 at 2 07 33 PM](https://user-images.githubusercontent.com/46936775/212923884-8e44649a-af29-4694-aa17-43263f0aa2b8.png)

![Screenshot 2023-01-10 at 2 06 44 PM](https://user-images.githubusercontent.com/46936775/212923905-fc416676-1b40-4ef9-acfe-dad3076666be.png)

However, when making identical requests via the Graph Explorer and Postman, I am not getting duplicated search hits

![Screenshot 2023-01-10 at 2 15 06 PM](https://user-images.githubusercontent.com/46936775/212924134-b6a3a253-7aaf-4a34-83b3-cae712d6007c.png)

![Screenshot 2023-01-10 at 2 16 09 PM](https://user-images.githubusercontent.com/46936775/212924223-6ca5f900-0c64-4d9c-b721-df9dae700858.png)

![Screenshot 2023-01-10 at 2 17 35 PM](https://user-images.githubusercontent.com/46936775/212924253-acce9e85-c363-4314-aecb-95b50d88b09c.png)

Please let me know if I can provide any additional information to help narrow down this issue. Thanks!

**Comment by baywet** [comment]
Hi,
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
