### ISSUE TITLE
Guest user information not available in IdentitySet in callRecords api via sdk

### ISSUE THREAD

**Issue by sbasuroy5** [microsoftgraph/msgraph-sdk-java#1325]
CallRecords API using curl returns guest user in the list of participants, where each participant is an IdentitySet. However, using the microsoft-graph java sdk, the CallRecord response does not include any guest key in participants. Response should be consistent across both and guest user should be included in response from graph sdk. 

The endpoint is https://graph.microsoft.com/v1.0/communications/callRecords/{callId}

### Expected behavior
API Response from curl: 
`{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#communications/callRecords/$entity",
    "id": "db40fbff-aa11-4b39-b00b-af443448f605",
    "version": 1,
    "type": "groupCall",
    "modalities": [
        "audio"
    ],
    "lastModifiedDateTime": "2023-01-18T00:43:30.6105093Z",
    "startDateTime": "2023-01-18T00:22:32.6704702Z",
    "endDateTime": "2023-01-18T00:26:45.7830838Z",
    "joinWebUrl": "<redacted>",
    "organizer": {
        "acsUser": null,
        "spoolUser": null,
        "phone": null,
        "guest": null,
        "encrypted": null,
        "onPremises": null,
        "acsApplicationInstance": null,
        "spoolApplicationInstance": null,
        "applicationInstance": null,
        "application": null,
        "device": null,
        "user": {
            "id": "c55922b2-3794-47be-b7d9-2d3ef9f3c24c",
            "displayName": "User1 T2Test1",
            "tenantId": "c39b037a-f4c8-4305-87b3-37d7655d6816"
        }
    },
    "participants": [
        {
            "acsUser": null,
            "spoolUser": null,
            "phone": null,
            "guest": null,
            "encrypted": null,
            "onPremises": null,
            "acsApplicationInstance": null,
            "spoolApplicationInstance": null,
            "applicationInstance": null,
            "application": null,
            "device": null,
            "user": {
                "id": "c55922b2-3794-47be-b7d9-2d3ef9f3c24c",
                "displayName": "User1 T2Test1",
                "tenantId": "c39b037a-f4c8-4305-87b3-37d7655d6816"
            }
        },
        {
            "acsUser": null,
            "spoolUser": null,
            "phone": null,
            "guest": null,
            "encrypted": null,
            "onPremises": null,
            "acsApplicationInstance": null,
            "spoolApplicationInstance": null,
            "applicationInstance": null,
            "application": null,
            "device": null,
            "user": {
                "id": "bdd75849-e0a6-4cce-8fc1-d7c0d4da43e5",
                "displayName": null,
                "tenantId": "c39b037a-f4c8-4305-87b3-37d7655d6816"
            }
        },
        {
            "user": null,
            "acsUser": null,
            "spoolUser": null,
            "phone": null,
            "guest": {
                "id": "b2aa2839a6d245438f97eaf3014b938b",
                "displayName": "Guest user",
                "tenantId": null
            },
            "encrypted": null,
            "onPremises": null,
            "acsApplicationInstance": null,
            "spoolApplicationInstance": null,
            "applicationInstance": null,
            "application": null,
            "device": null
        },
        {
            "acsUser": null,
            "spoolUser": null,
            "phone": null,
            "guest": null,
            "encrypted": null,
            "onPremises": null,
            "acsApplicationInstance": null,
            "spoolApplicationInstance": null,
            "applicationInstance": null,
            "application": null,
            "device": null,
            "user": {
                "id": "311d902f-b440-402b-944a-f9665ee9b0ba",
                "displayName": "User3 T2Test3",
                "tenantId": "c39b037a-f4c8-4305-87b3-37d7655d6816"
            }
        }
    ]
}`
Notice how participants is a list. One of the participants has user=null but guest details are populated in the guest key. 

`"guest": {
                "id": "b2aa2839a6d245438f97eaf3014b938b",
                "displayName": "Guest user",
                "tenantId": null
            },
`

### Actual behavior

See below image for actual response from microsoft-graph sdk. It appears that participants is returned as an [IdentitySet](https://learn.microsoft.com/en-us/graph/api/resources/identityset?view=graph-rest-1.0) (https://learn.microsoft.com/en-us/graph/api/resources/identityset?view=graph-rest-1.0) which consists of application, device, and user only. Guest is not included in IdentitySet. 

<img width="578" alt="callRecord response from graph api sdk" src="https://user-images.githubusercontent.com/75806106/214141304-42420b60-44d9-4ab7-8696-36377ddc11c2.png">

### Steps to reproduce the behavior

1. Make a MS Teams call. 
2. Get call record details using by making a GET request to https://graph.microsoft.com/v1.0/communications/callRecords/{callId}
3. Notice discrepancy in curl response and sdk response. SDK response should include guest as part of list of participants just like how curl api returns guest 
`
"guest": {
                "id": "b2aa2839a6d245438f97eaf3014b938b",
                "displayName": "Guest user",
                "tenantId": null
            },`

**Comment by ramsessanchez** [comment]
Hi @sbasuroy5 , thanks for bringing this up. The 'Guest' property which you see missing in the response from the SDK should be located in the additionalDataManager of that identitySet instance as it is not guaranteed that it will always be property of an IdentitySet, different API's add different information as they see fit. Unfortunately, we have had issues with the additionalDataManager and proper serialization of added properties to openType resources. We are currently working on a new version of the SDK which we hope will address these issues.

**Comment by sbasuroy5** [comment]
Thank you for the response @ramsessanchez. I checked the additionalDataManager and it is also empty. See [above screenshot](https://user-images.githubusercontent.com/75806106/214141304-42420b60-44d9-4ab7-8696-36377ddc11c2.png) where additionalDataManager with size = 0. Is there a timeline for the fix to make these added properties available in additionalDataManager?

**Comment by sbasuroy5** [comment]
Hi @ramsessanchez, just want to confirm that all the metadata currently available in the guest key such as id and displayName will be available in the additionalDataManger as well? We need the id to uniquely identify participants.

`"guest": { "id": "b2aa2839a6d245438f97eaf3014b938b", "displayName": "Guest user", "tenantId": null }`

Please let us know what the timeline for the fix is. Thank you!

**Comment by ramsessanchez** [comment]
Hi @sbasuroy5 , yes that information should be available as entities in the additional data manager. Unfortunately this would result in a major version update for the Java Core Library which is currently not a priority. I have two suggestions: 1) I would suggest you try to use the preview version of the next generation SDK which does a better job of handling these scenarios or 2) Create a method to manually serialize the response given the known/expected properties that we see in your sample response. I believe solution 1 would be the easiest given your current situation. Note that the preview does not support large file upload or batch requests at the moment however.
