### ISSUE TITLE
Duplicate class error with 5.45 due to jcip-annotations

### ISSUE THREAD

**Issue by slowcar** [microsoftgraph/msgraph-sdk-java#1331]
When building the project with release 5.45 i get a duplicate class error:
`Duplicate class net.jcip.annotations.GuardedBy found in modules jetified-jcip-annotations-1.0 (net.jcip:jcip-annotations:1.0) and jetified-jcip-annotations-1.0-1 (com.github.stephenc.jcip:jcip-annotations:1.0-1)
Duplicate class net.jcip.annotations.Immutable found in modules jetified-jcip-annotations-1.0 (net.jcip:jcip-annotations:1.0) and jetified-jcip-annotations-1.0-1 (com.github.stephenc.jcip:jcip-annotations:1.0-1)
Duplicate class net.jcip.annotations.NotThreadSafe found in modules jetified-jcip-annotations-1.0 (net.jcip:jcip-annotations:1.0) and jetified-jcip-annotations-1.0-1 (com.github.stephenc.jcip:jcip-annotations:1.0-1)
Duplicate class net.jcip.annotations.ThreadSafe found in modules jetified-jcip-annotations-1.0 (net.jcip:jcip-annotations:1.0) and jetified-jcip-annotations-1.0-1 (com.github.stephenc.jcip:jcip-annotations:1.0-1)`

running gradlew app:dependencies shows

```
+--- com.microsoft.graph:microsoft-graph:5.45.0
|    \--- com.microsoft.graph:microsoft-graph-core:2.0.15
|         +--- net.jcip:jcip-annotations:1.0
```

```
+--- com.microsoft.identity.client:msal:4.1.3
|    +--- com.nimbusds:nimbus-jose-jwt:9.9
|    |    \--- com.github.stephenc.jcip:jcip-annotations:1.0-1
```

Adding
exclude module: 'jcip-annotations'
to gradle for graph fixes the build.

Downgrading to 5.44 also fixes the issue.
It looks like the dependency change originates in https://github.com/microsoftgraph/msgraph-sdk-java-core/compare/v2.0.14...v2.0.15
that added jcip-annotations from compileonly to api

**Comment by baywet** [comment]
Hi @slowcar,
Thanks for calling this out, we're putting a fix together https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/736
