### ISSUE TITLE
Provide out-of-the-box authentication support (automatic token refresh, etc.)

### ISSUE THREAD

**Issue by Kitanotori** [microsoftgraph/msgraph-sdk-java#134]
### Expected behavior

- Should be simple and intuitive to authenticate with [methods supported by Azure AD](https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-scenarios#web-application-to-web-api)
- Should automatically refresh access tokens and preferably provide ways for persistence, similar to [google-api-java-client](https://developers.google.com/api-client-library/java/google-api-java-client/oauth2#data_store)

### Actual behavior

- No obvious way to handle OAuth2 authentication flow to Azure AD
- No obvious way to automatically refresh access tokens when making Graph API requests

### Notes

I guess [azure-activedirectory-library-for-java](https://github.com/AzureAD/azure-activedirectory-library-for-java) is the official way to handle authentication to Azure AD with Java? Would it make sense to integrate it to this SDK in order to provide unified user experience covering authentication flow, automatically authenticating requests, and automatically refreshing tokens?

**Comment by NakulSabharwal** [comment]
@Kitanotori We have provided [msgraph-sdk-java-auth](https://github.com/microsoftgraph/msgraph-sdk-java-auth) that can be used for authentication currently its in preview and it takes care of authentication.

**Comment by Kitanotori** [comment]
@NakulSabharwal How do I set authentication provider for GraphServiceClient using refresh token?

**Comment by kumbhaj** [comment]
Hi @Kitanotori  Can you please share how you used microsoft-graph-auth library to access services
