### ISSUE TITLE
Attempting to send a subscription request fails with an error 409 Invalid Request

### ISSUE THREAD

**Issue by JulKav** [microsoftgraph/msgraph-sdk-java#1344]
Description of the bug:
Executing a subscription to presence request for users with the SDK targeting the MS Graph API is resulting in an error:

409Graph service exception Error code: InvalidRequest
Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: InvalidRequest
Error message: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
POST https://graph.microsoft.com/v1.0/subscriptions
SdkVersion : graph-java/v5.16.0
SdkVersion : graph-java/v5.16.0
[...]
400 : Bad Request
[...]

My subscription request includes the following:

SUBSCRIPTION REQUEST applicationId: null
SUBSCRIPTION REQUEST changeType: UPDATED
SUBSCRIPTION REQUEST clientState: 7fc6bf6b-6cc2-438d-a293-aa47539ad02a
SUBSCRIPTION REQUEST creatorId: null
SUBSCRIPTION REQUEST id: null
SUBSCRIPTION REQUEST latestSupportedTlsVersion: null
 SUBSCRIPTION REQUEST lifecycleNotificationUrl: null
 SUBSCRIPTION REQUEST notificationQueryOptions: null
SUBSCRIPTION REQUEST notificationUrl: https://<myhost:port>/graph/listen
SUBSCRIPTION REQUEST notificationUrlAppId: null
SUBSCRIPTION REQUEST oDataType: null
SUBSCRIPTION REQUEST resource: /communications/presences?$filter=id in ('932b90ca-e5a4-42c7-a985-f4ddfc6d6715','6be2455d-63ac-4423-aa3e-7188fdbd5e73','41b3d168-5c28-4596-ba3b-d5c70a3c3967','8830a8bc-f882-4c13-b33a-7031423b5a24','ab548af7-d5a9-4388-9800-7668a20bb2b9')
SUBSCRIPTION REQUEST expirationDateTime: 2023-02-02T16:41:11.737+02:00
SUBSCRIPTION REQUEST includeResourceData: false

I have included in  my pom.xml:

-<dependency>
<groupId>com.microsoft.graph</groupId>
<artifactId>microsoft-graph</artifactId>
<version>5.16.0</version>
</dependency>

-<dependency>
<groupId>com.azure</groupId>
<artifactId>azure-identity</artifactId>
<version>1.4.6</version>
</dependency>

I saw this article regarding the beta version of the sdk https://learn.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0. 
It indcate "Subscriptions to resources marked with an asterisk (*) are available on the /beta endpoint only." and presence is one of those resources. Is this related to my error?
I tried to use this version instead, but I still have the same Invalid request error.

Please advise.
Thank you,
J.

**Comment by ramsessanchez** [comment]
Hi @JulKav, Could you include a snippet of the code you are using to construct the request? This may also be an issue with the way we are constructing the request under the hood. To verify this request is possible I would suggest using [Graph Explorer] (https://developer.microsoft.com/en-us/graph/graph-explorer) and constructing the request using Http format. If the issue does not present itself in Graph Explorer then it is possible that there is an issue with our request construction which I can help debug if needed. Also, I would suggest updating to the latest version, 5.55.0, as there may have been an update to the api itself.
