### ISSUE TITLE
UploadSession for LargeFileUpload can not be created with conflictBehavior

### ISSUE THREAD

**Issue by ajweber** [microsoftgraph/msgraph-sdk-java#1351]
When using latest SDK (v5.47.0) against Java 8, adding a non-empty DriveItemUploadableProperties object to the UploadSession [builder] results in an invalid request.

Specifying an empty (newly initalized/created DriveItemUploadableProperties) to the builder succeeds with all other variables and content remaining the same.

I have tried to mimic/copy the examples provided in the learn.microsoft.com docs and the GitHub samples/tests for the java sdk.  The UploadSession should be able to be built specifying a non-default conflictBehavior.  (This was previously an issue - supposedly resolved - where the json was not correctly generated when specifying the conflictBehavior via the additionalDataManager.)

`
. . .
                DriveItemUploadableProperties cfBehavior = new DriveItemUploadableProperties();
                cfBehavior.name = fname;
                //cfBehavior.fileSize = fsize;
                cfBehavior.additionalDataManager().put("@microsoft.graph.conflictBehavior", new JsonPrimitive("rename"));

                DriveItemCreateUploadSessionParameterSet uploadParams = DriveItemCreateUploadSessionParameterSet.newBuilder()
                        .withItem(cfBehavior).build();

                //create the upload session
                UploadSession uploadSession = graphClient.drives(GetDriveIdFromItem(folder)).items(properId).itemWithPath(fname)
                        .createUploadSession(uploadParams).buildRequest().post();

                LargeFileUploadTask<DriveItem> largeFileUploadTask = new LargeFileUploadTask<DriveItem>(uploadSession,
                        graphClient, is, fsize, DriveItem.class);

                //.upload is the synchronous version
                LargeFileUploadResult<DriveItem> result = largeFileUploadTask.upload(CHUNK_SIZE, null, callback);
                if ((result != null) && (result.responseBody != null))
                    uploadedFile = result.responseBody;
                else {
                    logger.error("LargeFileUploadFailed?");
                }
`
This code fails when creating the UploadSession (on .post() call).  If you comment-out adding the name and additionalDataManager (just leave the 'cfBehavior' object with defaults), this code is successful.  Thus, I believe there is an issue with the DriveItemUploadableProperties class and/or where it is included in the UploadSession via the builder.

Log snippet on failure:
`
Feb 21, 2023 4:32:07 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: invalidRequest
Error message: The request is malformed or incorrect.

POST https://graph.microsoft.com/v1.0/drives/b!XXXXXX.../items/01...X:/Re%20%20%20Our%20Ref%20%20%2010854%20P-5.msg:/microsoft.graph.createUploadSession
SdkVersion : graph-java/v5.47.0
[...]

400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]
16:32:10,845 ERROR ExportFileToFolder.java:210 - UploadLocalFolder - Could not complete upload!
com.microsoft.graph.http.GraphServiceException: Error code: invalidRequest
Error message: The request is malformed or incorrect.

POST https://graph.microsoft.com/v1.0/drives/b!XXXXXX.../items/01...X:/Re%20%20%20Our%20Ref%20%20%2010854%20P-5.msg:/microsoft.graph.createUploadSession
SdkVersion : graph-java/v5.47.0
[...]

400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:419)
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:378)
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:512)
	at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:442)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:408)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:225)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:202)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:335)
	at com.microsoft.graph.requests.DriveItemCreateUploadSessionRequest.post(DriveItemCreateUploadSessionRequest.java:55)
`

**Comment by ajweber** [comment]
So this issue has been sitting for over 5 months with no action by devs.  In the case of uploading a large file and there already exists a file with the same name, you will overwrite the existing driveItem.  This, in many cases, is considered a loss of data.

Why is there no work on this?

**Comment by ramsessanchez** [comment]
Hi @ajweber 
It seems the bug here is that when we create the object for the DriveUploadableProperties we serialize the object to the following:
```json
{
    "item": {
        "name": "HelloWorld!.txt",
        "@microsoft.graph.conflictBehavior": "rename"
    }
} 
```
This is because the additionalData is serialized last.
However, the correct json object would be: 
```Json
{
    "item": {
        "@microsoft.graph.conflictBehavior": "rename",
        "name": "HelloWorld!.txt",
    }
} 
```
Thus if you were to not include the name, just the additional data I believe your request would go through. I recommend creating a json object and passing that in directly to the request so that the malformed object is corrected. Unfortunately, due to our soon expected preview of our next generation java sdk we will likely not be addressing this issue explicitly as we expect our new sdk to handle uploads better. In the meantime, I suggest explicitly creating a correctly formed json body the parameter set, or simply leaving the name property unfilled. Our convention for the sdk has always been to serialize/deserialize additional data last, so making a change for this specific edge case could lead to breaking changes or unexpected consequences for the rest of the sdk.
