### ISSUE TITLE
Sev1 Issue faced in MIB project for MS Graph 

### ISSUE THREAD

**Issue by Andy-MIB** [microsoftgraph/msgraph-sdk-java#1353]
Pega on-prem and PegaCloud based systems that are currently experiencing this issue where email Cases are not getting created through Email Listeners. From a Pega perspective, we are seeing an Invalid HTTP Response from MSGraph after sending the request.Invalid HTTP Response.Stack:at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1614)at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)at com.microsoft.graph.http.UrlConnection.getResponseCode(UrlConnection.java:110)at com.pega.platform.integrationcore.client.email.internal.msgraph.MSGraphHttpProvider.sendRequestInternal(MSGraphHttpProvider.java:226)at (:)

Is anyone available to join the bridge call with pega & MIB https://pega.webex.com/meet/umesh.sanwal

This issue has been raised with MS Support but we have been advised this is an SDK issue and to raise on this forum

**Comment by baywet** [comment]
Hi @Andy-MIB 
Thanks for reaching out.
We're not structured to join customers on their bridges. Your best bet for time sensitive requests is to work with our support team, and depending on the impact they might pull us in or not.

Looking at the stack trace, it seems the client you're using is still leveraging URL connections. That seems to be from v2 or v1 of the SDK, which went out of support a number of years ago. We're currently on v5, and working towards shipping a v6.
The advice would be for you to upgrade your client to benefit from the switch to OkHttp under the hood and the numerous bugfixes that have been implemented over the years.

**Comment by Andy-MIB** [comment]
Hi Anil (aniln@microsoft.com)

Can you please join the bridge with Arpita, to discuss this critical issue which is now affecting multiple industry users, this is not just affecting MIB and Pega Support are wanting to work with Microsoft on a solution for all affected clients.

The details to join are: https://pega.webex.com/meet/umesh.sanwal

**Comment by Andy-MIB** [comment]
Hi Vincent.
We require information, can you please help us with our issues?

1. When did support for 1.4.0 expire?
2. What is the policy for support if we are in version 1.0 or 2.0 ?
3. Is it possible for you to join a bridge call and triage this issue as this is not the only account facing this issue?

**Comment by baywet** [comment]
1. may 2021 for v1 and august 2022 for v2
2. no support is provided anymore for those versions.
3. no, our team is not setup to handle customer calls, we provide some level of help through GitHub issues, and the support team provides support, reaching out to us if/when needed.

v3: support ends in 3 weeks. (March 16th)
v4: support ends July 2023.
v5: actively supported since their is no v6 yet.

v4 and v5 are just increments of v3 because of breaking service change according to policy (we expect the vast majority to have no code changes when upgrading from v3 to v5) so we advice customers upgrading from v1/v2 to v3 to go straight to v5 for that reason.
