### ISSUE TITLE
Issue with uploading large attachment to message.

### ISSUE THREAD

**Issue by KalokheMrunal** [microsoftgraph/msgraph-sdk-java#1380]
While uploading large attachment to draft message using uploadSession  gives the following error:
Error message: The audience claim value is invalid for current resource. Audience claim is 'https://graph.microsoft.com/', request url is 'https://outlook.office.com' and resource type is 'Exchange'.

Below are some details over the upload session request and response:
uploadSession Request:
requestUrl: https://graph.microsoft.com/v1.0/users/fpuser1@onmicrosoft.com/messages/AQMkADg2YjJhMjllLTEyOGMtNGFiNC04NTNhLWY5NTBhYzEzNDNjZQBGAAADWE5uphGqd0qgU3WL3EJEPgcASkeKc_3nR0_H_j7PT90LWwAAAgEPAAAASkeKc_3nR0_H_j7PT90LWwACfvcsewAAAA==/attachments/microsoft.graph.createUploadSession
Client: https://graph.microsoft.com/v1.0
uploadSession Response:
UploadUrl:
https://outlook.office.com/api/gv1.0/users('2bcc2d71-d3d6-4930-91c7-c2479c960b4c@f1e36a47-46fc-49ec-930d-8eb35f621db8')/messages('AQMkADg2YjJhMjllLTEyOGMtNGFiNC04NTNhLWY5NTBhYzEzNDNjZQBGAAADWE5uphGqd0qgU3WL3EJEPgcASkeKc_3nR0_H_j7PT90LWwAAAgEPAAAASkeKc_3nR0_H_j7PT90LWwACfvcsewAAAA==')/AttachmentSessions('AAMkADg2YjJhMjllLTEyOGMtNGFiNC04NTNhLWY5NTBhYzEzNDNjZQBGAAAAAABYTm6mEap3SqBTdYvcQkQ_BwBKR4pz7edHT4f6Ps9P3QtbAAAAAAEBAABKR4pz7edHT4f6Ps9P3QtbAAJ_9z-1AAA=')?authtoken={access token}
SdkVersion : graph-java/v5.31.0

**Comment by andrueastman** [comment]
Thanks for raising this @KalokheMrunal.

Any chance the suggestion in the https://github.com/microsoftgraph/msgraph-sdk-java/issues/1355 works out for you?

**Comment by KalokheMrunal** [comment]
@andrueastman
The suggestion available on https://github.com/microsoftgraph/msgraph-sdk-java/issues/1355 did not work in my case.

**Comment by andrueastman** [comment]
Thanks for following up. Any chance you can share a code sample of how you are creating the upload task and initializing the GraphClient?

As the URL is unique, the client passed should ideally be one that does not send an auth header.

**Comment by KalokheMrunal** [comment]
@andrueastman  
Below is the same code: 
//graphClient initialization
SimpleAuthProvider authProvider = new SimpleAuthProvider(accessToken);
            GraphServiceClient graphClient = GraphServiceClient.builder()
                        .authenticationProvider(authProvider)
                        .buildClient();

//creating upload session for large attachment
 AttachmentItem attachmentItem = new AttachmentItem();
                                attachmentItem.attachmentType = AttachmentType.FILE;
                                attachmentItem.name = attachmentData.getName();
                                attachmentItem.size = streamSize;
                                final AttachmentCreateUploadSessionParameterSet upParams =
                                    AttachmentCreateUploadSessionParameterSet.newBuilder()
                                        .withAttachmentItem(attachmentItem)
                                        .build();

                                final UploadSession uploadSession = graphClient.users(messagingItem.getFromAddress())
                                    .messages(newMessage.id)
                                    .attachments()
                                    .createUploadSession(upParams)
                                    .buildRequest()
                                    .post();

                                LargeFileUploadTask<FileAttachment> uploadTask =
                                    new LargeFileUploadTask<FileAttachment>(uploadSession,
                                        graphClient,
                                        fileStream,
                                        streamSize,
                                        FileAttachment.class);
                                int chunkSize = CHUNK_SIZE;
                                uploadTask.uploadAsync(chunkSize);

**Comment by andrueastman** [comment]
Thanks for following up @KalokheMrunal.

Any chance you also implemented this in the AuthProvider to only send the access token when the host is `graph`? I believe this is the solution to the issue here.

```cs
	@Override
	public CompletableFuture<String> getAuthorizationTokenAsync(URL requestUrl) {
		CompletableFuture<String> future = new CompletableFuture<>();
    	if(requestUrl.getHost().toLowerCase().contains("graph")){
    		future.complete(accessToken);
        }
    	else {
            future.complete(null);
        }
		return future;
    }
```

**Comment by KalokheMrunal** [comment]
@andrueastman 
I made the suggested changes, but the large attachment is still not attached to the sent email.

**Comment by andrueastman** [comment]
Does the large file upload complete successfully after the change? And is the message created in draft state before sending?
