### ISSUE TITLE
LargeFileUploadTask on retry gives message Error code: invalidRequest Error message: The Content-Range header is missing or malformed

### ISSUE THREAD

**Issue by ankush-salesforce** [microsoftgraph/msgraph-sdk-java#1393]
### Expected behavior

 retry should have succeeded

### Actual behavior
getting below error on retry
com.microsoft.graph.core.ClientException: Error code: invalidRequest
Error message: The Content-Range header is missing or malformed.

PUT https://salesforcecontracts.sharepoint.com/sites/testsharing/_api/v2.0/drives/b!EcyE7fkzeU2X_fkf9jfmYi2KFvbXrE5HiW3FvA_Xz_apFcWsxlDpRIk5XNu4BRfz/items/01DFTAAMMN32XAVRE44RCIFOVURQCAQWYL/uploadSession?guid=%276f557860-2ac2-4e8f-9d40-1764555482e5%27&overwrite=True&rename=False&dc=0&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvc2FsZXNmb3JjZWNvbnRyYWN0cy5zaGFyZXBvaW50LmNvbUBhZmU4NTc4YS1hZWJlLTRkNTctYTQ0ZS02ZjBhYTY2NmJkNWIiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNjgwMjcwNjUyIiwiZXhwIjoiMTY4MDM1NzA1MiIsImVuZHBvaW50dXJsIjoic1pMUGFCa0Nxd1VJVUVPRFAzZDZUYWR3SXE0WXJ1bVNxbDhTT2pwLytjdz0iLCJlbmRwb2ludHVybExlbmd0aCI6IjI3NiIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiTURGak1Ea3lORGt0WkdSa015MDBNVEE0TFRnNVpqUXRNalprTXpjNE9USTFPR1ZqIiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6IlpXUTROR05qTVRFdE16Tm1PUzAwWkRjNUxUazNabVF0WmpreFptWTJNemRsTmpZeSIsImFwcF9kaXNwbGF5bmFtZSI6InRlc3Rhbmt1c2giLCJnaXZlbl9uYW1lIjoiQW5rdXNoIiwiZmFtaWx5X25hbWUiOiJHdXB0YSIsInNpZ25pbl9zdGF0ZSI6IltcImttc2lcIl0iLCJhcHBpZCI6IjcxN2FjZjU4LWY4YTUtNDZkNS04YzhkLTE2ZGQ3MmZhNjY5ZiIsInRpZCI6ImFmZTg1NzhhLWFlYmUtNGQ1Ny1hNDRlLTZmMGFhNjY2YmQ1YiIsInVwbiI6ImFua3VzaGd1cHRhQHNhbGVzZm9yY2Vjb250cmFjdHMub25taWNyb3NvZnQuY29tIiwicHVpZCI6IjEwMDMyMDAyM0JGMEZFMjEiLCJjYWNoZWtleSI6IjBoLmZ8bWVtYmVyc2hpcHwxMDAzMjAwMjNiZjBmZTIxQGxpdmUuY29tIiwic2NwIjoibXlmaWxlcy53cml0ZSBhbGxmaWxlcy53cml0ZSBhbGxwcm9maWxlcy5yZWFkIiwidHQiOiIyIiwidXNlUGVyc2lzdGVudENvb2tpZSI6bnVsbCwiaXBhZGRyIjoiMjAuMTkwLjE2My4yOSJ9.dEJ0bzZwSThqS3dNZUlpYWh2ZGp2bVo1RVowL2VraU83blJ5bFBCSHl0az0
SdkVersion : graph-java/v5.42.0
Content-Range : bytes 15728640-15728639/20331387

400 : 
[...]

[Some information was truncated for brevity, enable debug logging for more details]

### Steps to reproduce the behavior

i have the below code which fails on client exception-
```
 try {
                driveItem = largeFileUploadTask.upload(0, null, callback).responseBody; // request 1
            } catch (ClientException e){
                driveItem = largeFileUploadTask.upload( 0, null, callback).responseBody; // request 2
            }
```
on tracking requests i see the  content range header in request 1 is Content-Range: bytes 15728640-20331386/20331387

but on request 2 , it is Content-Range: bytes 15728640-15728639/20331387

which is exactly the problem . Also the default retry which should have retriggered on  failure of request 1 in graphserviceclient is not getting triggered.

**Comment by ramsessanchez** [comment]
Hi @ankush-salesforce, unfortunately it seems this is a failure on our end. The current upload task does not handle retries correctly and does not trigger the retry handler. 
The header currently being populated is dependent on the stream bytes read, when there is a failure, the value returned is -1, unfortunately the current implementation populates the header with the:
"<startIndex>"-"<startIndex>+bytesRead"/"<totalUploadLength>" thus on failure the second value of the header is 1 less than the start value of the content range. 
My suggestion is to catch the failure and retry the upload by instantiating a new LargeFileUploadTask and going from there, this should result in the correct ranges being used.

**Comment by ankush-salesforce** [comment]
> Hi @ankush-salesforce, unfortunately it seems this is a failure on our end. The current upload task does not handle retries correctly and does not trigger the retry handler. The header currently being populated is dependent on the stream bytes read, when there is a failure, the value returned is -1, unfortunately the current implementation populates the header with the: ""-"+bytesRead"/"" thus on failure the second value of the header is 1 less than the start value of the content range. My suggestion is to catch the failure and retry the upload by instantiating a new LargeFileUploadTask and going from there, this should result in the correct ranges being used.

@ramsessanchez  thanks i will try that, but by when can we expect the fix in sdk for this?

**Comment by ramsessanchez** [comment]
It is unlikely that this fix will come in for the current version of the SDK as we are currently working to deploy the next major version. We hope to release version 6+ in the next few months, this would also include an updated largeFileUploadTask, though it will likely lead to breaking changes as the syntax for graph calls will change.

**Comment by ankush-salesforce** [comment]
i tried recreating new LargeFileUploadTask  but that also fails with same exception. Looks like i will have to wait for 6+ then.
