### ISSUE TITLE
Intermittent issue while uploading large file into the Sharepoint through Graph API.

### ISSUE THREAD

**Issue by gel111004** [microsoftgraph/msgraph-sdk-java#1406]
### Expected behavior
The files (upto 2GB) should upload Successfully through my Custom Application into SharePoint Online. 

### Actual behavior

The file is uploading intermittently(Sometimes it is failing and sometimes Successful) into the SharePoint. More than 500 Members are using this Application. We are using Microsoft Graph API Version 3.0.0 to communicate with the SharePoint Online. Unfortunately, I could not find anything and went through the code as well of class LargeFileUploadTask.

All I want is to upload files into the SharePoint through my Custom application without any latency. I can provide data related to my issue at any requested format.
Looking forward for your help in advance.

Thank you!

**Comment by ramsessanchez** [comment]
Hi @gel111004, When you say you are using the Graph API v3.0 are you referring to the Java SDK version 3.0? We are currently supporting v5+ of the SDK and the LargeFileUploadTask that you may be referring to will only work with an SDK verison 5+. Could you clarify if this is what you are referring to as well as providing the code you are currently using to handle your upload. Thank you!
