### ISSUE TITLE
rooms() method missing in GraphServiceClient, places() not working

### ISSUE THREAD

**Issue by josch0** [microsoftgraph/msgraph-sdk-java#1408]
Maybe I haven't understood the Java SDK properly, but I have a problem retrieving a list of rooms.

According to the graph reference, Place is only the base type for Room and Roomlist. So a bare "/places" endpoint does not exist, you have to pass the concrete type as a subpath, e.g. "/places/microsoft.graph.room".

Now, the GraphServiceClient provides a places() method. But when I call it, I get a "406 NOT ACCEPTABLE" error.

I think the GraphServiceClient is missing a rooms() method with the correct path.

Surprisingly, room Models, Requests and RequestBuilder are existing, only the call in ServiceClient is missing.

```
    @Nonnull
    public com.microsoft.graph.requests.RoomCollectionRequestBuilder rooms() {
        return new com.microsoft.graph.requests.RoomCollectionRequestBuilder(getServiceRoot() + "/places/microsoft.graph.room", this, null);
    }
```

**Comment by ramsessanchez** [comment]
Hi @josch0, it appears this is a known issue for our current Java version which we address in our version 6 release of our SDK, this version is currently still in preview but can be used via the maven-SNAPSHOTS directory. This issue appeared in our previous dotNet version as well and can be read about here: https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/97
I would like to provide this workaround in the meantime while we work to launch the next version of the Java SDK.
``` Java 
        String roomRequestString = graphClient.places().getRequestUrlWithAdditionalSegment("microsoft.graph.room");
        List<Room> roomPage = new RoomCollectionRequestBuilder(roomRequestString, graphClient, null).buildRequest().get().getCurrentPage();
        for(Room room : roomPage) {
            System.out.println(room.displayName);
        }
```
