### ISSUE TITLE
toomanyrequests in graph api occurred, please help

### ISSUE THREAD

**Issue by senthinil** [microsoftgraph/msgraph-sdk-java#1420]
Hi

We are using msgraph-sdk-java as follows:

                <dependency>
                    <groupId>com.microsoft.graph</groupId>
                    <artifactId>microsoft-graph</artifactId>
                    <version>5.41.0</version>
                </dependency> 

We are facing toomanyrequests frequently :

* We are just having 4 schedulers two are scheduled for every 10 seconds and other two are scheduled for every 30 seconds for email fetching using azure graph email fetch api, and we are iterating through the fetched emails one by one we are getting toomanyrequests errors weekly once, the api getting called for every iterated email are update email read flag using this api https://learn.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&tabs=http Throttling limits for Microsoft link: https://learn.microsoft.com/en-us/graph/throttling API says that We are running beyond throttling limits. Please advise

* We referred to this link https://learn.microsoft.com/en-us/graph/throttling for throttling limits, and we found a youtube video https://youtu.be/J4CFxVuzNMA for reproducing toomanyrequests error, they have mentioned headers and Retry-After parameters in their response, which is not getting in our toomanyrequests api response log : 

{"error":{"code":"TooManyRequests","message":"Too many requests from Identifier:5489968a-4066-4cbd-b7d6-4a81c75a4a93+f24a269f-cc78-40db-87b7-1e980880d4ed under category:servicecommsplatform.readService.perMinute. Please try again later.","innerError":{"date":"2023-04-18T13:02:00","request-id":"3db82899-a510-486d-925d-a44de6fd6c08","client-request-id":"1ff4c0d3-7730-4360-8367-e319280d48a0"}}} Please advise to get the Retry-After and headers in our response. 

* We are not able to capture com.microsoft.graph.http.GraphServiceException using basic java try/catch block , though its been thrown from the API for toomanyrequests, how to capture this exception in our code. Please advise. 

Regards
Sentil

**Comment by ramsessanchez** [comment]
Hi @senthinil , could you please include the code block in which you are attempting to catch these errors as well as where you are making the requests? I would also like to refer you to our core library which includes the [default retry handler](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/dev/src/main/java/com/microsoft/graph/httpcore/RetryHandler.java) for our SDK. 
I don't believe we throw an exception for a 429 error, rather the api will notify you that you must wait some time before attempting this call again. I suggest checking the retry handler for the current implementation for this error handling, if this retry handler does not meet your requirements, I suggest creating your own implementation using the OkHttp3 Interceptor framework.

**Comment by senthinil** [comment]
Hi @ramsessanchez 

Thanks for your response

We are not able to get the toomanyrequests error in our QA environment, its happening only in our live environment once in a week, we have 4 schedulers two are scheduled for every 10 seconds and other two are scheduled for every 30 seconds for email fetching 100 unread emails at a time in two schedulers using azure graph email fetch api, and we are iterating through the fetched emails one by one , the api getting called for every iterated email are update email read flag using this api https://learn.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&tabs=http 

As you asked  code, the code is given below

```
    public void test()
    {
     ServiceUpdateMessageMarkReadParameterSet t = ServiceUpdateMessageMarkReadParameterSet
		.newBuilder()
		.withMessageIds(messageIdsList)
		.build();
           try{ 
               graphClient.admin().serviceAnnouncement().messages()
           .markRead(t).buildRequest().post();
           }
          catch(GraphServiceException e)
          {
		  /* Not getting caught */
  System.out.println("error class : " + t2.getClass());
/* Do some action goes here*/
            }
           catch(Throwable t2)
           {
		     /* Getting caught */
                   System.out.println("error class : " + t2.getClass());
                   if(t2 instanceof GraphServiceException)
                   {
			   
                      GraphServiceException e = (GraphServiceException) t2;
                      System.out.println("rawObject | "+ e.getError().rawObject);
                   }
                    t2.printStackTrace();
                 }
            }



```
When we try to catch GraphServiceException its not getting captured, hence we are capturing in Throwable object in java.

 Please help us on the following :
* Please give some code snippet for using RetryHandler class
*  why toomanyrequests happens when we are using api below throttling limits of ATMOST below 60 emails processing in 10 seconds
* when GraphServiceException is thrown why its not being catched in try/catch block and why we need to capture in Throwable clause. 

Regards

Sentil

**Comment by ramsessanchez** [comment]
Hi, I believe the reason you are not catching an exception is because it is not being thrown until after the retry handler tries the request again. As far as your question on how to customize the retry handler I can provide you this snippet:
```Java
        RetryOptions options = new RetryOptions(null, <NumberOfRetries>, <DelayTime> ); 
        OkHttpClient client = HttpClients.custom()
                .addInterceptor(new AuthenticationHandler(authProvider))
                .addInterceptor(new RetryHandler(options))
                .addInterceptor(new RedirectHandler()).build();

        graphClient = GraphServiceClient.builder()
                .httpClient(client)
                .authenticationProvider(authProvider)
                .logger(logger)
                .buildClient();
```
NumberOfRetries defaults to 3 and DelayTime defaults to 3 as well. I would suggest increasing the DelayTime value first and the NumberOfRetries value after that if there are still issues. The method, [getRetryAfter()](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/2c51f85ab3f1b19670b7ca8e35cb1b1343d2d286/src/main/java/com/microsoft/graph/httpcore/RetryHandler.java#L128), explains the relationship between the two values, as you can see these values become important where the Retry-After header is not present which seems to be the case in your scenario.

**Comment by senthinil** [comment]
Hi @ramsessanchez 

Your code solution for capturing toomanyrequests error working fine and works efficiently, thanks for the same. 

Please tell us why the toomanyrequests error pops up when we are running the application below the throttling limits https://learn.microsoft.com/en-us/graph/throttling-limits?source=recommendations#service-communications-service-limits , which mentions :

**Request type | Limit per app per tenant
Any | 240 requests per 60 seconds
Any | 800 requests per hour**


 We are not able to get the toomanyrequests error in our QA environment, its happening only in our live environment once in a week, we have 4 schedulers two are scheduled for every 10 seconds and other two are scheduled for every 30 seconds for email fetching 100 unread emails at a time in two schedulers using azure graph email fetch api, and we are iterating through the fetched emails one by one , the api getting called for every iterated email are update email read flag using this api https://learn.microsoft.com/en-us/graph/api/serviceupdatemessage-markread?view=graph-rest-1.0&tabs=http.

 How to prevent this toomanyrequests error from occurring?

Regards
Sentil

**Comment by ramsessanchez** [comment]
Hi @senthinil, based on the information you have provided it does seem that you are hitting the throttling limit. My understanding is that you are attempting to iterate through a maximum of 200 unread emails per 30 seconds, 2 schedulers each fetching attempting to fetch 100 emails every 30 seconds (please correct me if I'm wrong). You are attempting to mark these emails as read through the serviceAnnouncement api via admin/serviceAnnouncement/messages/markRead, the documentation says that any request type, this includes markRead which calls POST, will count towards the throttling limit amount. Though you may not be marking 240 emails as 'read' per minute it is possible that you may be hitting the limit of 800 per hour. My suggestion would be to reduce the number of requests that you are making to the serviceAnnouncement api, from your description it does seem like you are attempting to go beyond the throttling limit which we cannot workaround as this limit is service specific and thus not enforced by us. Please correct me if I've misunderstood the requests and request count that you described.

**Comment by senthinil** [comment]
Hi @ramsessanchez 

You analysis is right, hence we have to increase the scheduler's duration to every 1 minute and number of fetch mails to <15 mails per minute. Thanks for the analysis and clarification. Please proceed to close this issue

Regards
Sentil

**Comment by ramsessanchez** [comment]
Glad I could help @senthinil, thanks for continuing to use our Java SDK.
