### ISSUE TITLE
Access Review with on reviewer filter giving error when calling from msgraph sdk java

### ISSUE THREAD

**Issue by vamsinalluri** [microsoftgraph/msgraph-sdk-java#1425]
AccessReviewScheduleDefinitionFilterByCurrentUserCollectionPage filterByCurrentUser = graphServiceClient.identityGovernance().accessReviews().definitions()
        .filterByCurrentUser(AccessReviewScheduleDefinitionFilterByCurrentUserParameterSet
            .newBuilder()
            .withOn(AccessReviewScheduleDefinitionFilterByCurrentUserOptions.REVIEWER)
            .build())
        .buildRequest()
        .get();

The above code is giving below error:
GET https://graph.microsoft.com/v1.0/identityGovernance/accessReviews/definitions/microsoft.graph.filterByCurrentUser(on=REVIEWER)
SdkVersion : graph-java/v5.5.0

The AccessReviewScheduleDefinitionFilterByCurrentUserParameterSet  enum is not resolving to a string which is giving the problem.

**Comment by ramsessanchez** [comment]
We need to append the filter to the request string manually. The metho call .filterByCurrentUser(<Filter>) expects an enum as the filter param, however the service will not accept the enum as part of the request. A workaround to this is the following:
```Java
String filter = graphClient.identityGovernance()
     .accessReviews()
     .definitions()
     .getRequestUrlWithAdditionalSegment("filterByCurrentUser(on='reviewer')");
AccessReviewScheduleDefinitionFilterByCurrentUserCollectionRequestBuilder withFiler = new AccessReviewScheduleDefinitionFilterByCurrentUserCollectionRequestBuilder(filter, graphClient, null);
//Use newly created requestBuilder to complete the request builder
```

**Comment by vamsinalluri** [comment]
Thanks @ramsessanchez , the solution is working.
