### ISSUE TITLE
How can I mention a tag when sending a message?

### ISSUE THREAD

**Issue by LeeLi888** [microsoftgraph/msgraph-sdk-java#1444]
I want to mention a tag that was created on Teams, but the following document only shows me the ability to mention users or channels.

https://learn.microsoft.com/en-us/graph/api/chatmessage-post

and I noticed that `ChatMessageMentionedIdentitySet.java` support `user`, `device`, `application`, `conversation`, no `tag`

**Comment by ramsessanchez** [comment]
Hi @LeeLi888 , It seems that the functionality for that has not been included for Graph v1. The functionality that is available is set by the service, in this case Teams, we have no control over when they will add this functionality to the v1 endpoint. However, it is available in [Graph beta ](https://learn.microsoft.com/en-us/graph/api/resources/chatmessagementionedidentityset?view=graph-rest-beta). I recommend trying the [Beta SDK](https://github.com/microsoftgraph/msgraph-beta-sdk-java). As the name suggests, the Beta SDK is subject to more breaking changes so tread carefully when implementing.

**Comment by LeeLi888** [comment]
Thank you very much for your answer. It was extremely helpful.
