### ISSUE TITLE
teamwork installedApps User Id not found

### ISSUE THREAD

**Issue by onyas** [microsoftgraph/msgraph-sdk-java#1445]
### Expected behavior

graphServiceClient.users(userId).teamwork().installedApps()
                    .buildRequest(buildAuthHeader(teamsUser))
                    .post(userScopeTeamsAppInstallation);

install apps for this userId should be successful. 

### Actual behavior

{
    "error": {
        "code": "NotFound",
        "message": "User Id 'xxx' not found.",
        "innerError": {
            "date": "2023-05-16T05:41:28",
            "request-id": "1dd61eec-27d7-40e0-a236-50ddaa512e87",
            "client-request-id": "1dd61eec-27d7-40e0-a236-50ddaa512e87"
        }
    }
}

I can list the user through /users api. The request-id is 7212dc7e-d831-4f01-956b-9e45731f3a2e 

### Steps to reproduce the behavior

see above code

**Comment by ramsessanchez** [comment]
Hi @onyas , can you verify that the userId that you are using for this request works? I recommend visiting [Graph Explorer ](https://developer.microsoft.com/en-us/graph/graph-explorer) and running the following GET query.
https://graph.microsoft.com/v1.0/users/{USER ID}/teamwork/installedApps
It may be possible that the teamsUser you are using for the buildAuthHeader() is invalid, please verify that this user is also valid for the scope of your initial request.
