### ISSUE TITLE
Shared channel member added from graph API  doesn't have privilege to access chat messages

### ISSUE THREAD

**Issue by kang-mansher** [microsoftgraph/msgraph-sdk-java#1450]
### Expected behavior
Using Graph api,
I use a team owner to add itself as a member to a shared channel in the team.
The member is added successfully.
The member tries to access messages in the chat and can fetch a valid response from /messages.

### Actual behavior
The graph api to add member is working fine.
But the added member is not able to access the messages.

List channels in the team:
![listchannels](https://github.com/microsoftgraph/msgraph-sdk-java/assets/67425059/129ea30e-4214-498d-b81a-7ce283fd991c)

add member to shared channel:
![addsharedmember](https://github.com/microsoftgraph/msgraph-sdk-java/assets/67425059/96468be4-93a6-4683-8fac-f59ad4d2f691)

list all members of the channel:
![listsharedmembers](https://github.com/microsoftgraph/msgraph-sdk-java/assets/67425059/09abe322-122e-4e09-bda4-697bbcb0a46f)

access messages in the channel:
![listsharedmessages](https://github.com/microsoftgraph/msgraph-sdk-java/assets/67425059/3d9d2248-1c92-47d8-944c-3743666920f2)

### Steps to reproduce the behavior

Create a team and add one additional member as team owner.
Create a shared channel in the team and do not shared the channel with existing team members.
Use the additional team owner to add itself to the shared channel using /members graph API
Try to access shared channel chat using /messages API using the same user

**Comment by baywet** [comment]
Thanks for reaching out. This repository and its issues are dedicated to the SDK itself. Service teams are not monitoring it. The best ways to get attention from the service teams are to either open a support ticket or create a discussion on the Microsoft graph Microsoft q&a forum.
Closing
