### ISSUE TITLE
Email not delivered when .postAsync() used to send mail-MS Graph API Java

### ISSUE THREAD

**Issue by jc1709** [microsoftgraph/msgraph-sdk-java#1451]
Hello,

We are using Client credential flow to send mail in MS Graph Java and email is not delivered for few requests when multiple requests placed at same time/shorter time. Please check and let me know correct code to send mail in postasynchronous mode

Here is code
_app is Graph service client
_app.users(user)
                          .sendMail(UserSendMailParameterSet
                                       .newBuilder()
                                       .withMessage(message)
                                        .withSaveToSentItems(null)
                                       .build())
                                 .buildRequest()
                                 .postAsync();

**Comment by ramsessanchez** [comment]
Hi @jc1709 , can you provide information as to which version of the java sdk you are using? How many emails are you attempting to send and in what is the duration of the time window in which you hope to send these emails?
