### ISSUE TITLE
msgraph-sdk-java bookingservice NaN on coordinates

### ISSUE THREAD

**Issue by thekarin19** [microsoftgraph/msgraph-sdk-java#1455]
### Expected behavior
GET /v1.0/solutions/bookingBusinesses/{bookingBusiness-id}/services/{bookingService-id}
When calling this endpoint I want to receive data about services of a bookingBusiness as Object (BookingService) or List.

### Actual behavior
Calls on this endpoint throws: java.lang.NumberFormatException: JSON forbids NaN and infinities: NaN

After some researches, I found out that the API is giving services back with defaultLocation.coordinates object with every field as NaN.

On the delegated auth, all coordinates fields are returned as null values.

"defaultLocation": {
  "displayName": "",
  "locationEmailAddress": "",
  "locationUri": "",
  "locationType": "default",
  "uniqueId": null,
  "uniqueIdType": null,
  "address": {
    "street": "",
    "city": "",
    "state": "",
    "countryOrRegion": "",
    "postalCode": ""
  },
  "coordinates": {
    "altitude": "NaN",
    "latitude": "NaN",
    "longitude": "NaN",
    "accuracy": "NaN",
    "altitudeAccuracy": "NaN"
  }
}
msgraph 5.46.0 maven repo

I search on the services GUI where I can remove this coordinates object, because we don't want to use it but I didn't found anything.

I tried to update the service through the API with nulls or doubles but the outcome in the SDK call is the same, only NaN comes.

**Comment by baywet** [comment]
Thanks for reaching out. Out of curiosity, as a workaround, have you tried using $select to select only the fields you care about and omit this one?
