### ISSUE TITLE
Received incorrect email address

### ISSUE THREAD

**Issue by mmhforjavaweb** [microsoftgraph/msgraph-sdk-java#1479]
```xml
<dependency>
<groupId>com.microsoft.graph</groupId>
      <artifactId>microsoft-graph</artifactId>
      <version>5.61.0</version>
</dependency>
```

code:

```
Event event=graphServiceClient.users("xxxx").events("xxxxx")
                .buildRequest()
                .get();
```

We get the organizer's email,the email like "/o=ExchangeLabs/ou=Exchange Administrative Group (xxx)/cn=Recipients/cn=xxx-tsangchotip"

How do I know the correct email address,like "xx@xx.com"?

**Comment by ramsessanchez** [comment]
Hi @mmhforjavaweb , Can you please provide a code snippet along with the expected output? Once you retrieve the event object you should be able to retrieve the email through: 
``` Java
EmailAddress email = event.organizer.emailAddress();
```

**Comment by ramsessanchez** [comment]
@mmhforjavaweb The email address field of the organizer is simply a string that is returned by the service, the SDK does not manipulate or process this, we simply assign it to the correct field. If the organizers email is not easy to distinguish then I recommend looking into the creation of the event as that would be when the email value is set.
