### ISSUE TITLE
sendMail Response returning Retry-After header on 202 response code

### ISSUE THREAD

**Issue by denny-miller** [microsoftgraph/msgraph-sdk-java#1487]
### Expected behavior
**API used:** sendMail https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http

When a request is sent, a response should return `202 Accepted` or, when rate limited, `429` along with a `Retry-After` header value.

### Actual behavior
**API used:** sendMail https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http

We were experiencing responses that were `202 Accepted` codes, but also containing a `Retry-After` header.

**Related documentation**: https://learn.microsoft.com/en-us/graph/outlook-things-to-know-about-send-mail

When following the documentation, the expected outcome would be to retry these events. However, this would cause duplicate requests, causing duplicate `202 Accepted` responses, resulting in multiple of the same email being sent (mailbox 'Sent' folder shows a separate sent mail for each retry attempt).

Due to this impacting our usage by sending duplicate of the same email, we made the decision to **not** retry requests when a `202 Accepted` response code also contains a `Retry-After` header. (Documentation is lacking for this situation). **This is not documented, but was the only way to prevent duplicate of the same mail being sent** (Any further information on what to do in this scenario would be great)

After contacting MS support (TrackingID#2306160050002364), they pointed us to raise an issue here.

### Steps to reproduce the behavior

Java SDK used in production code. Using the sendMail method from the GraphServiceClient
`client.me().sendMail(...`

The issue occurred in our production environment.

We were not able to reproduce this error locally (We were even hitting our max allowed mail sends ~10k per day attempting to replicate), as default expected behaviour would be to have a `Retry-After` header on `429` responses (This we were able to do locally, but we then experienced multiple sendMail requests due to our RetryInterceptor finding a `Retry-After` header, despite the response code being `202`, and the sendMail request was successfully requested).

One final thing:
The documentation indicates that a 202 response may be rejected later, but there is no indication of how we can know this? (After receiving an accepted response, Graph Client communication ends). In the scenario a 202 response contains a header, should we be retrying? This causes duplicate mail sends.

**Comment by denny-miller** [comment]
Hi @baywet ,

I probably should have mentioned, we have had to adopt our own RetryInterceptor that intercepts the requests (Which implements the okHttp3 Interceptor), due to wanting to filter out the response body from returning the sent request body to avoid Memory Issues (Related to https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/750 ). Due to this, it means we are in control of what we Retry/Don't Retry.

The code that calls the sendMail is all automated (so no UI double click issues etc, we are certain the duplicate emails came from our RetryInterceptor retrying due to the response returning 202 with a Retry-After header value - custom logging within the custom interceptor confirmed this, matching duplicate email times with retry times).

Right now we are inhibiting retries for 2xx series codes. We will look into following the default Interceptor to only worry about the above codes (Thank you).

As for what the response means, if the default interceptor doesn't deem them worthy of a retry, we should also follow this approach, but any clarification on what causes this? (Local replication could not trigger this issue, we hit the usual 429 response codes when throttling rate limit issues were tested)

**Comment by baywet** [comment]
We (the people behind the repo) don't have access to service logs or changes. Opening a support ticket to get information about service behavior changes that impact production applications is the right thing to do.

It sounds that your issue is not being caused by code from the Java SDK itself, but rather by a combination of service behaviour change and your own custom implementation. If that is the case, please feel free to close the issue.

**Comment by denny-miller** [comment]
Ok thanks, have requested an escalation on our support ticket.
