### ISSUE TITLE
HuntingRowResult class not include the property row data  

### ISSUE THREAD

**Issue by gilb77** [microsoftgraph/msgraph-sdk-java#1495]
Hi 

The HuntingRowResult class not include the the row data field in the class,
only the fields oDataType and additionalDataManager, 

I am using version com.microsoft.graph:microsoft-graph:5.62.0

![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/21139764/62b332f0-6e33-4865-a327-e0b3b34a18fd)

**Comment by baywet** [comment]
Hi @gilb77 
Thanks for using the Java SDK and for reaching out.
This is because this model is described as an Open Type on the service and doesn't describe its properties. Therefore, we can't generate a strongly typed property on the corresponding class.
You should be able to find the value you're looking for in the additional data manager.

**Comment by gilb77** [comment]
Thank you @baywet,

There is problem in the sdk mapping, its not mapping the result row to additional data manager. 

In my opinion, because there is schema for advance hunting i think it's can be good addition to add mapping to object that present the tables, for example if i query data from the table DeviceProcessEvents, the sdk can map the row result to class that present DeviceProcessEvents with the same  columns and other values to  additional data manager.

**Comment by baywet** [comment]
Could you share more details about the JSON payload your application is receiving and what information you are finding in the additional data manager?

**Comment by gilb77** [comment]
Sure here example, 

        {
            "timestamp": "2023-06-26T17:24:36.6574431Z",
             "processId": 9848,
            "processCommandLine": "schtasks  /Run /I /TN SBSimulationTask ",
            "processCreationTime": "2023-06-26T17:24:35.743288Z",
            "fileName": "schtasks.exe",
            "folderPath": "C:\\Windows\\System32\\schtasks.exe",
            "sha1": "ccaa6ee9ef6d0f9c8157adc996ffd477f73b5d02",
            "sha256": "013c013e0efd13c9380fad58418b7aca8356e591a5cceffdb910f7d8b0ad28ef",
            "fileSize": 235008,
            "initiatingProcessId": 4184,
            "initiatingProcessCommandLine": "cmd.exe /c \"echo sb_359484_bs >NUL & schtasks /Run /I /TN SBSimulationTask & exit\"",
            "initiatingProcessCreationTime": "2023-06-26T17:24:35.7157351Z",
            "initiatingProcessFolderPath": "c:\\windows\\system32\\cmd.exe",
            "initiatingProcessFileName": "cmd.exe",
            "initiatingProcessFileSize": 289792,
            "initiatingProcessSHA1": "f1efb0fddc156e4c61c5f78a54700e4e7984d55d",
            "initiatingProcessSHA256": "b99d61d874728edc0918ca0eb10eab93d381e7367e377406e65963366c874450"
        }

**Comment by baywet** [comment]
Thanks.
From those, which fields are missing from the additional data manager?

**Comment by gilb77** [comment]
@baywet Here full example for reporoduce:
(new SecurityRunHuntingQueryRequestBuilder("https://graph.microsoft.com/beta/security/runHuntingQuery", getSdk().me().getClient(),null, SecurityRunHuntingQueryParameterSet
.newBuilder()
.withQuery("DeviceProcessEvents | where Timestamp <= datetime(2023-06-15T11:15:49.226113400Z) | limit 10")
.build()).buildRequest().post()

Sdk result:

{"results":[{},{},{},{},{},{},{},{},{},{}],"schema":[{"name":"Timestamp","type":"DateTime"},{"name":"DeviceId","type":"String"},{"name":"DeviceName","type":"String"},{"name":"ActionType","type":"String"},{"name":"FileName","type":"String"},{"name":"FolderPath","type":"String"},{"name":"SHA1","type":"String"},{"name":"SHA256","type":"String"},{"name":"MD5","type":"String"},{"name":"FileSize","type":"Int64"},{"name":"ProcessVersionInfoCompanyName","type":"String"},{"name":"ProcessVersionInfoProductName","type":"String"},{"name":"ProcessVersionInfoProductVersion","type":"String"},{"name":"ProcessVersionInfoInternalFileName","type":"String"},{"name":"ProcessVersionInfoOriginalFileName","type":"String"},{"name":"ProcessVersionInfoFileDescription","type":"String"},{"name":"ProcessId","type":"Int64"},{"name":"ProcessCommandLine","type":"String"},{"name":"ProcessIntegrityLevel","type":"String"},{"name":"ProcessTokenElevation","type":"String"},{"name":"ProcessCreationTime","type":"DateTime"},{"name":"AccountDomain","type":"String"},{"name":"AccountName","type":"String"},{"name":"AccountSid","type":"String"},{"name":"AccountUpn","type":"String"},{"name":"AccountObjectId","type":"String"},{"name":"LogonId","type":"Int64"},{"name":"InitiatingProcessAccountDomain","type":"String"},{"name":"InitiatingProcessAccountName","type":"String"},{"name":"InitiatingProcessAccountSid","type":"String"},{"name":"InitiatingProcessAccountUpn","type":"String"},{"name":"InitiatingProcessAccountObjectId","type":"String"},{"name":"InitiatingProcessLogonId","type":"Int64"},{"name":"InitiatingProcessIntegrityLevel","type":"String"},{"name":"InitiatingProcessTokenElevation","type":"String"},{"name":"InitiatingProcessSHA1","type":"String"},{"name":"InitiatingProcessSHA256","type":"String"},{"name":"InitiatingProcessMD5","type":"String"},{"name":"InitiatingProcessFileName","type":"String"},{"name":"InitiatingProcessFileSize","type":"Int64"},{"name":"InitiatingProcessVersionInfoCompanyName","type":"String"},{"name":"InitiatingProcessVersionInfoProductName","type":"String"},{"name":"InitiatingProcessVersionInfoProductVersion","type":"String"},{"name":"InitiatingProcessVersionInfoInternalFileName","type":"String"},{"name":"InitiatingProcessVersionInfoOriginalFileName","type":"String"},{"name":"InitiatingProcessVersionInfoFileDescription","type":"String"},{"name":"InitiatingProcessId","type":"Int64"},{"name":"InitiatingProcessCommandLine","type":"String"},{"name":"InitiatingProcessCreationTime","type":"DateTime"},{"name":"InitiatingProcessFolderPath","type":"String"},{"name":"InitiatingProcessParentId","type":"Int64"},{"name":"InitiatingProcessParentFileName","type":"String"},{"name":"InitiatingProcessParentCreationTime","type":"DateTime"},{"name":"InitiatingProcessSignerType","type":"String"},{"name":"InitiatingProcessSignatureStatus","type":"String"},{"name":"ReportId","type":"Int64"},{"name":"AppGuardContainerId","type":"String"},{"name":"AdditionalFields","type":"String"}],"@odata.context":"[https://graph.microsoft.com/beta/$metadata#microsoft.graph.security.huntingQueryResults"}](https://graph.microsoft.com/beta/$metadata#microsoft.graph.security.huntingQueryResults%22%7D)

![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/21139764/cf02ead2-eff9-4d35-a87a-f9dfad08584e)

**Comment by baywet** [comment]
Thanks for all the details. I'm going to hand it over to @ramsessanchez from now on (last week was a holiday in the US, I was just gathering the basic information)

**Comment by ramsessanchez** [comment]
Hi @gilb77 , unfortunately our deserialization as it pertains to the additional data handler, in particular when populating the additional data of a child entity, has been lacking. We are nearing the release of version 6.0 of the Java-Sdk, which should resolve this issue. In the meantime I recommend manually deserializing the 'results' from this query. I am including a block of code which can help with this. 
``` Java
JsonObject obj = JsonParser.parseString(<RESPONSE JSON>).getAsJsonObject();
        DefaultSerializer serializer = new DefaultSerializer(new DefaultLogger(), true);
        JsonArray rowResults = obj.get("results").getAsJsonArray();
        ArrayList<HuntingRowResult> results = new ArrayList<>();
        for (JsonElement e : rowResults) {
            HuntingRowResult result = serializer.deserializeObject(e, HuntingRowResult.class);
            results.add(result);
        }

```
