### ISSUE TITLE
Some urls use "microsoft.graph." prefixes 

### ISSUE THREAD

**Issue by aferre** [microsoftgraph/msgraph-sdk-java#1496]
### Expected behavior

When sending a message through the SDK, the URL used should be (per MSgraph documentation https://learn.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&tabs=http):
POST /users/{id | userPrincipalName}/messages/{id}/send

### Actual behavior

When seding an email through the SDK, the URL used is
 
POST /users/{id | userPrincipalName}/messages/{id}/microsoft.msgraph.send

See all occurrences of this URL being used here : https://github.com/search?q=repo%3Amicrosoftgraph%2Fmsgraph-sdk-java+microsoft.graph.send&type=code

### Steps to reproduce the behavior

` Message message = ...;
graphClient.users("myEmail").messages(message.id)
				.send()
				.buildRequest()
				.post();`

**Comment by baywet** [comment]
Bonjour @aferre,
Thanks for using the Java SDK and for reaching out.
This is expected. Microsoft Graph is based on OData conventions. microsoft.graph is the namespace name before the function name. The default and recommended way to address an action/function (sendMail) is [through the fully qualified name](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_AddressingOperations).
Let us know if you have other questions.

**Comment by aferre** [comment]
Hi @baywet , thanks for your feedback. Could you give me a link of the description of the OData convention you are talking about on the msgraph api documentation please?

**Comment by baywet** [comment]
Here is something [specifically about namespacing](https://learn.microsoft.com/en-us/graph/use-the-api#odata-namespace) for Microsoft Graph. Let me know if you need anything else.

**Comment by aferre** [comment]
Thanks!
