### ISSUE TITLE
msgraph-sdk-java bookingappointment response contains NaN on coordinates

### ISSUE THREAD

**Issue by neobahamut-software** [microsoftgraph/msgraph-sdk-java#1503]
Expected behavior:
(POST /v1.0/solutions/bookingBusinesses/{bookingBusiness-id}/appointments)
graphServiceClient.solutions()
                .bookingBusinesses(businessId)
                .appointments()
                .buildRequest()
                .post(bookingAppointment);
When calling this endpoint I want to receive the newly created appointment object

Actual behavior:
Calls on this endpoint throws: java.lang.NumberFormatException: JSON forbids NaN and infinities: NaN on parsing response into BookingAppointment object because the data in the serviceLocation.coordinates are NaNs

Example JSON
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#solutions/bookingBusinesses('Post%40zqy1n.onmicrosoft.com')/appointments/$entity",
    "id": "AAMkAGU5ZGZlZjI1LTA0MWMtNDUwMS1hZmQxLTJlOTgwNWE5ZWE4ZgBGAAAAAABtjhqUz_edRoKnYqUGc10pBwAs2MNEUfWCQ4OA4FSA3vTkAAAAAAENAAAs2MNEUfWCQ4OA4FSA3vTkAABx7NAEAAA=",
    "selfServiceAppointmentId": "tkWKyLh5nEOiGQwTNsxzTQ2",
    "additionalInformation": "",
    "isLocationOnline": false,
    "joinWebUrl": "",
    "customerTimeZone": "",
    "serviceId": "2dfdcf41-6376-4aa3-86c4-7b18749a09cc",
    "serviceName": "Paket versenden",
    "duration": "PT1H",
    "preBuffer": "PT15M",
    "postBuffer": "PT15M",
    "priceType": "undefined",
    "price": 0.0,
    "serviceNotes": "",
    "optOutOfCustomerEmail": false,
    "staffMemberIds": [
        "5ad1fde7-3839-4871-a344-5265428a54f6"
    ],
    "smsNotificationsEnabled": false,
    "anonymousJoinWebUrl": null,
    "maximumAttendeesCount": 1,
    "filledAttendeesCount": 1,
    "startDateTime": {
        "dateTime": "2023-07-14T10:45:00.0000000",
        "timeZone": "W. Europe Standard Time"
    },
    "endDateTime": {
        "dateTime": "2023-07-14T11:45:00.0000000",
        "timeZone": "W. Europe Standard Time"
    },
    "serviceLocation": {
        "displayName": "",
        "locationEmailAddress": "",
        "locationUri": "",
        "locationType": "default",
        "uniqueId": null,
        "uniqueIdType": null,
        "address": {
            "street": "",
            "city": "",
            "state": "",
            "countryOrRegion": "",
            "postalCode": ""
        },
        "coordinates": {
            "altitude": "NaN",
            "latitude": "NaN",
            "longitude": "NaN",
            "accuracy": "NaN",
            "altitudeAccuracy": "NaN"
        }
    },
    "reminders": [],
    "customers": [
        {
            "@odata.type": "#microsoft.graph.bookingCustomerInformation",
            "customerId": "",
            "name": "",
            "emailAddress": "",
            "phone": "",
            "timeZone": "",
            "notes": "",
            "location": null,
            "customQuestionAnswers": []
        }
    ]
}
msgraph 5.46.0 maven repo

I cannot make a select on the data I want because it is a POST request.

**Comment by ramsessanchez** [comment]
Hi @neobahamut-software , Perhaps I am misunderstanding the issue, but it seems that the Location coordinates should be doubles or nulls which the default serializer should have no issue handling. When you are creating the BookingAppointment object that you are passing to the Post method, are you instantiating it with NaN values? Or are these NaN values being returned from the service? I would recommend bumping to the latest version, 5.65.0 just in case. Also, if you could share the code in which you are instantiating that BookingAppointment object that would be very helpful in further understanding what is going on. Thanks!

**Comment by neobahamut-software** [comment]
Hello @ramsessanchez Sorry for the delayed response.
I tried to update to 5.65.0 to test but same result.
Here the code I use to make the request to msgraph:
BookingAppointment bookingAppointment = new BookingAppointment();
        bookingAppointment.startDateTime = getDateTimeTimeZone(data.getStartDateTime());
        bookingAppointment.endDateTime = getDateTimeTimeZone(data.getEndDateTime());
        bookingAppointment.postBuffer = DatatypeFactory.newInstance().newDuration(data.getPostBuffer());
        bookingAppointment.preBuffer = DatatypeFactory.newInstance().newDuration(data.getPreBuffer());
        bookingAppointment.serviceId = data.getServiceId();
        bookingAppointment.serviceName = data.getServiceName();
        bookingAppointment.staffMemberIds = data.getStaffMemberIds();
        bookingAppointment.joinWebUrl = getAppointmentURL(shortId);

        try {
            return graphServiceClient.solutions()
                    .bookingBusinesses(businessId)
                    .appointments()
                    .buildRequest()
                    .post(bookingAppointment);
        } catch (Exception e) {
            log.error(e.toString());
        }
The exception which comes is : java.lang.NumberFormatException: JSON forbids NaN and infinities: NaN
When I use the same request through HTTP request (Postman) I see that the coordinates are NaNs
