### ISSUE TITLE
LICENSE file missing for the project

### ISSUE THREAD

**Issue by gauntface** [microsoftgraph/msgraph-sdk-java#152]
Apologies for the fly by comment.

I just noticed that the license information on the README is currently pointing to a file that doesn't exist. Would it be possible to add the LICENSE file back in to the project?

[See License Section Here](https://github.com/microsoftgraph/msgraph-sdk-java#8-license)

**Comment by darrelmiller** [comment]
Thanks for the heads up.  @deepak2016 Can we get that file added back please?

**Comment by deepak2016** [comment]
sure, I will get this done.

**Comment by kanchengcao** [comment]
Thanks Deepak, We wish to use this SDK in our product, so it would be great it you can update the licence file soon!

Frank

**Comment by deepak2016** [comment]
@gauntface @kanchengcao I have added License in the repo. https://github.com/microsoftgraph/msgraph-sdk-java/pull/156

**Comment by deepak2016** [comment]
This will get bundled in our next release. Closing the issue.
