### ISSUE TITLE
SDK client sends incompatible requests for China country cloud POST /me/events

### ISSUE THREAD

**Issue by ortonomy** [microsoftgraph/msgraph-sdk-java#1524]
### Expected behavior

- Events creation requests are accepted and processed correctly by the China Graph API endpoint

### Actual behavior

- When you generate particular payloads for the POST `/me/events` endpoint for China country cloud (https://microsoftgraph.chinacloudapi.cn/v1.0), if the payloads contain location information, the payload may be rejected with an error message.
- so far, it seems that particularly `Location` object info is particularly poorly handled and causes errors at the CN endpoint:
  - location.coordinates.latitude/longitude 
  - location.locationUri
 
- **If I use the payload with the API endpoint directly, the request succeeds**

### Steps to reproduce the behavior

1. Setup the SDK to use MS China
2. Add authentication for a China user

```java
// ...other logic
this.accessToken = accessToken; // this is a previously authenticated token

IAuthenticationProvider provider = new TokenCredentialAuthProvider(
  scopes,
  v -> Mono.fromCallable(
    () -> new AccessToken(
      accessToken, 
      TimeUtil.odtNowUtc().plusSeconds(3600)
    )
   )
);

final OkHttpClient client = HttpClients.createDefault(provider);

ILogger logger = new DefaultLogger();
logger.setLoggingLevel(LoggerLevel.DEBUG);

// graphClient is a property on the data provider class
graphClient = GraphServiceClient
        .builder()
        .authenticationProvider(provider)
        .httpClient(client)
        .logger(logger)
        .buildClient();
graphClient.setServiceRoot(MS_API_GRAPH_URL); // this is the China API endpoint 
```

3. Try to create an event using the SDK

```java
public Event createEvent(Event event) {
        try {
            return graphClient.me()
                    .events()
                    .buildRequest()
                    .post(event);
         } catch (...) {
           // ... other code
         }
}
```

4. Get logs of request:

Note the logging of the payload. Copy this payload and use it graph explorer, or in postman, you'll see the request is a success!

```
2023-08-08 14:47:19.745  INFO 21539 --- [nio-8080-exec-1] global                                   : Handling error response
2023-08-08 14:47:19.746  INFO 21539 --- [nio-8080-exec-1] global                                   : Serializing type Event
2023-08-08 14:47:19.756  INFO 21539 --- [nio-8080-exec-1] global                                   : Deserializing type GraphErrorResponse
2023-08-08 14:47:19.758 ERROR 21539 --- [nio-8080-exec-1] global                                   : CoreHttpProvider[sendRequestInternal] - 408Graph service exception
2023-08-08 14:47:19.758 ERROR 21539 --- [nio-8080-exec-1] global                                   : Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: UnableToDeserializePostBody
Error message: were unable to deserialize

POST https://microsoftgraph.chinacloudapi.cn/v1.0/me/events
SdkVersion : graph-java/v5.42.0
SdkVersion : graph-java/v5.42.0
{"attendees":[{"type":"optional","emailAddress":{"address":"gregoryorton@4qrfm1.onmicrosoft.com","name":"Greegory Orton"}}],"end":{"dateTime":"2023-09-01T13:00","timeZone":"China Standard Time"},"location":{"coordinates":{"latitude":0.0,"longitude":0.0},"displayName":"Is this a real place?"},"start":{"dateTime":"2023-09-01T12:00","timeZone":"China Standard Time"},"subject":"Hello world"}

400 : Bad Request
Cache-Control : private
client-request-id : f2375214-e2c8-4ac0-aa76-4318aac0d3f8
Content-Type : application/json
Date : Tue, 08 Aug 2023 06:47:18 GMT
request-id : f0d0d210-722f-466d-9a73-e7b3e56586b0
Strict-Transport-Security : max-age=31536000
Transfer-Encoding : chunked
Vary : Accept-Encoding
x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"China East","Slice":"E","Ring":"6","ScaleUnit":"000","RoleInstance":"SH1NEPF00000745"}}
{
  "error": {
    "code": "UnableToDeserializePostBody",
    "message": "were unable to deserialize ",
    "innerError": {
      "date": "2023-08-08T06:47:19",
      "request-id": "f0d0d210-722f-466d-9a73-e7b3e56586b0",
      "client-request-id": "f2375214-e2c8-4ac0-aa76-4318aac0d3f8"
    }
  }
}
```

**Comment by mmhforjavaweb** [comment]
世纪互联版跟国际版有差异，我都是自己封装sdk调用graph api的。官方文档里的字段跟实际调用有差异，可能是某个字段的首字母，也可能是别的原因，很久之前遇到过。
但是我试了你那个location，大概率猜测是世纪互联版不支持经纬度，因为我直接在outlook上也无法添加带经纬度的地址，国际版就可以。
国际版：
<img width="704" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-java/assets/19813166/a35030b0-d14f-4093-943f-8982aedd1c41">
世纪互联版：
<img width="687" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-java/assets/19813166/f5441a99-afaf-4c98-973f-b77bc1a9731d">

**Comment by ramsessanchez** [comment]
Hi @ortonomy , was the response from @mmhforjavaweb helpful?

**Comment by ramsessanchez** [comment]
Also, @ortonomy does the same, or similar, payload go through successfully when using a different endpoint?

**Comment by ortonomy** [comment]
@ramsessanchez - I have no idea if it was useful. The response and images are in Chinese which I don't understand. Maybe @mmhforjavaweb can translate?

**Comment by ortonomy** [comment]
This shouldn't be closed @ramsessanchez 😔

**Comment by ortonomy** [comment]
Either way @ramsessanchez - if the China cloud version doesn't support certain fields, this really really needs to be documented ...

**Comment by ortonomy** [comment]
> endpoint

Yes

**Comment by ortonomy** [comment]
> Also, @ortonomy does the same, or similar, payload go through successfully when using a different endpoint? 

Yes. It does.

**Comment by ortonomy** [comment]
Why was this closed? Why is it still closed?
