### ISSUE TITLE
Error while connecting to 5.58.0 graph

### ISSUE THREAD

**Issue by murals2** [microsoftgraph/msgraph-sdk-java#1529]
Hi, I updated to the latest graph version 5.58.0 in pom.xml
### Expected behavior

While connecting to the Test mailbox using the TokenAuth class,Iam getting error.

### Actual behavior

Error while connecting to the mailbox:

![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/142218514/f585c407-d318-4f07-8697-53780d534775)

**Graph Client.java**

 private GraphClient(GraphClientBuilder graphClientBuilder) {

        ClientSecretCredential credential =
                new ClientSecretCredentialBuilder()
                        .clientId(graphClientBuilder.clientId)
                        .tenantId(graphClientBuilder.tenant)
                        .clientSecret(graphClientBuilder.clientSecret)
                        .build();

        final TokenCredentialAuthProvider provider =new TokenCredentialAuthProvider(SCOPE, credential);

         this.graphClient = GraphServiceClient
                .builder()
                .authenticationProvider(provider)
                .buildClient();
        this.defaultMailbox = graphClientBuilder.defaultMailbox;

    }

**AuthenticationProvider class**:

package com.selective.utils.graph;

import com.azure.identity.ClientSecretCredential;
import com.azure.identity.ClientSecretCredentialBuilder;
import com.microsoft.graph.authentication.IAuthenticationProvider;
import com.microsoft.graph.authentication.TokenCredentialAuthProvider;
import com.microsoft.graph.http.IHttpRequest;

import java.net.URL;
import java.util.*;
import java.util.concurrent.CompletableFuture;

public class AuthenticationProvider implements IAuthenticationProvider {

    private CompletableFuture<String> accessTokenFuture;
    public static final String AUTH_URL = "https://login.microsoftonline.com/";
    private final String tenantId;
    private final String clientId;
    private final String clientSecret;

    private final List<String> SCOPE = Arrays.asList("https://graph.microsoft.com/.default");

    public AuthenticationProvider(
            final String tenantId,
            final String clientId,
            final String clientSecret) {
        this.tenantId = tenantId;
        this.clientId = clientId;
        this.clientSecret = clientSecret;

    }

    @Override
    public CompletableFuture<String> getAuthorizationTokenAsync(URL requestUrl) {

        return this.accessTokenFuture;
    }

    private String getAuthorityLink() {
        return AUTH_URL + tenantId + "/";
    }

}

### Steps to reproduce the behavior

IDE version:5.58.0

**Comment by murals2** [comment]
Can i get help on this please?

**Comment by ramsessanchez** [comment]
Hi @murals2 , Could you provide me with the version that you were using prior to updating to this version?  Also, can you include the code to the GraphClientBuilder class in particular where you are creating the defaultMailbox, thanks!

**Comment by murals2** [comment]
The previous version was 2.5.0.
![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/142218514/fae6f8c2-d035-4f10-8852-d2a660994a3c)

**Comment by murals2** [comment]
![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/142218514/d9588f70-5d3c-42db-95f5-451cfd6de8a2)

**Comment by ramsessanchez** [comment]
Hi @murals2 , apologies, but I am a bit unsure as to what you mean by connecting to the defaultMailbox? Are you running into the issue while authenticating? Or when making the request to graph? If you could also provide to code in which you are connecting to graph so that I may attempt to reproduce the error that would be helpful. Also, if you could provide the full stack trace to get a better understanding that would be helpful.
