### ISSUE TITLE
[Question] Encoding of relative paths

### ISSUE THREAD

**Issue by Syed-SnapLogic** [microsoftgraph/msgraph-sdk-java#1572]
Folks,
  I am talking to MS one drive endpoint thru java graph sdk 5.5.0.
  I heard the sdk automatically encodes the paths (meaning encodes special characters).  If I do not want the SDK to encode the paths then how can I achieve this?  I am already having encoded path.  I want the SDK to avoid encoding as its already encoded and make the API call.  Is this possible?

**Comment by ramsessanchez** [comment]
Hi @Syed-SnapLogic , could you share the code snippet in which you are talking to MS OneDrive and passing paths? I am curious as to why you are passing paths as the sdk should be handling all the URL work so you should not be needing to pass paths along. If you could provide a code snippet so I may better understand your problem that would be very helpful. Thank you!

**Comment by Syed-SnapLogic** [comment]
@ramsessanchez , I shall share the details soon.  Give me some time.

**Comment by ssapa** [comment]
@ramsessanchez We are using graph sdk file for uploading a file to Onedrive.

**Without encoding Relative Path :** 
So, when we use Relative path as "root:/snap test" and conflict_behaviour=Replace, the file is getting replaced and we can see the updated version as well.
**Request :** 
https://graph.microsoft.com/v1.0/drives/b!A5GL7aV13EOiocvwYtGLxMooxz3vr0JPqZA9_DpzUKTJ9HQROSuuRrmVDBpuHNw6/root:/snap%20test/testfile.json:/content?%40microsoft.graph.conflictBehavior=replace

**request-id**: e29dfbf9-f483-4f98-9e4c-4d7e03b660a4

**Response :** 
![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/50152071/4fa2e5f3-cd11-4c3e-af52-f8e288f1f78b)

**With Encoding Relative Path :** 
When we use Relative path as **"root:/snap%20test" and conflict_behaviour=Replace**, we are getting 200 response from api, but the file is not getting replaced.
**Request :** 
https://graph.microsoft.com/v1.0/drives/b!A5GL7aV13EOiocvwYtGLxMooxz3vr0JPqZA9_DpzUKTJ9HQROSuuRrmVDBpuHNw6/root:/snap%2520test/testfile.json:/content?%40microsoft.graph.conflictBehavior=replace

**request-id:** b5f74f4a-c3e7-45d7-b863-18e0bcddf204

**Response :** 
![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/50152071/30767bd9-e01b-45c1-8dac-9b59d6547f66)

But when we use Conflict-behaviour : fail or rename, the api is working as expected even if we give encoded relative path. So we are expecting the api should work fine incase of conflict-bahaviour=replace .

**Comment by ssapa** [comment]
@ramsessanchez As this issue is closed, created new ticket for the same : https://github.com/microsoftgraph/msgraph-sdk-java/issues/1593
