### ISSUE TITLE
Api returns a response with fields with a null value used in the SDK

### ISSUE THREAD

**Issue by EliorYomTov** [microsoftgraph/msgraph-sdk-java#1574]
### Expected behavior
Hello, I am using the Microsoft Graph SDK
As part of the development of an integration with SharePoint in the java language with the intellij IDE.

When I try to use the following API:
https://learn.microsoft.com/en-us/graph/api/drive-list?view=graph-rest-1.0&tabs=java

The response returned through the IDE is received with fields with a NULL value.
On the other hand, when I make the same request using graph-explorer, the resulting answer appears correctly when all the fields are filled

in AZURE
In App registrations -> applications -> API permissions

We have added the permissions according to the document on the website.
Screenshot screenshot.
![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/39540940/1ea425e9-266f-4b06-8037-b110f8399d1b)

I am attaching a JSON file with the response received using the SDK
And another JSON file of the answer received from graph-explorer

### Actual behavior

The answer received through graph-explorer comes with full field values
Compared to the answer from IDE received with missing fields

### Steps to reproduce the behavior

I used the following code to connect to the graph:

final String clientId = "YOUR_CLIENT_ID";
final String tenantId = "YOUR_TENANT_ID";
final String clientSecret = "YOUR_CLIENT_SECRET";

// The client credentials flow requires that you request the
// /. default scope, and pre-configure your permissions on the
// app registration in Azure. An administrator must grant consent
// to those permissions beforehand.
final List<String> scopes = Arrays.asList("https://graph.microsoft.com/.default");

final ClientSecretCredential credential = new ClientSecretCredentialBuilder()
     .clientId(clientId).tenantId(tenantId).clientSecret(clientSecret).build();

if (null == scopes || null == credential) {
     throw new Exception("Unexpected error");
}
final TokenCredentialAuthProvider authProvider = new TokenCredentialAuthProvider(
     scopes, credentials);

final GraphServiceClient<Request> graphClient = GraphServiceClient.builder()
     .authenticationProvider(authProvider).buildClient();
     
---------------------------------------------------------------
And in the following API call:

GraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

ListCollectionPage lists = graphClient.sites("{site-id}").lists()
.buildRequest()
.get();

I would appreciate your assistance
Best regards,
Elior
[Answer_received_via_SDK.json](https://github.com/microsoftgraph/msgraph-sdk-java/files/12882513/Answer_received_via_SDK.json)
[answer_received_via_graph-explorer.json](https://github.com/microsoftgraph/msgraph-sdk-java/files/12882514/answer_received_via_graph-explorer.json)

**Comment by ramsessanchez** [comment]
Hi @EliorYomTov , after looking at the examples you shared it seems that the response received in both cases contains the same information. The response from graph explorer seems to omit all the values that are set to null while the sdk call maintains them, however, the same information is present in both cases.

**Comment by EliorYomTov** [comment]
Hi, if you look again
You will notice that the answer received in the SDK omits values, i.e. returns null in most fields.
I am attaching a screenshot for demonstration:
<img width="500" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-java/assets/39540940/d29c150a-4a0e-4418-ac59-f6fa7f90f5aa">


On the other hand, the answer received in graph explorer returns an answer with full values ​​(without null).

Anyway, I need to know the ID of each list and directory
for me to access
to the files
And currently the answer received in the SDK returns null in the id field.

How to solve this problem?

**Comment by ramsessanchez** [comment]
@EliorYomTov the values that you have highlighted are not the same corresponding values. In the first screenshot you highlight the missing id value for the ParentReference object however, in the second you highlight the ID of the createdBy user, these two are not the same. I have reviewed the samples you sent and can confirm that the CreatedBy user ID is present in both responses. 



```json
//sdk version 
"createdBy": {
				"oDataType": null,
				"application": null,
				"device": null,
				"user": {
					"oDataType": null,
					"displayName": "Itay Hudedi",
					"id": "65b173c1-e132-4467-baca-b2737e9e09c6"
				}
				
// graph explorer version
"createdBy": {
				"user": {
					"email": "mft_team@8ctjsc.onmicrosoft.com",
					"id": "65b173c1-e132-4467-baca-b2737e9e09c6",
					"displayName": "Itay Hudedi"
				}
			},
```
