### ISSUE TITLE
How to specify proxy server

### ISSUE THREAD

**Issue by klehmann** [microsoftgraph/msgraph-sdk-java#158]
We would like to use the API in an application server. Is there a way to specify a proxy server to be used for Graph API requests?

**Comment by davidmoten** [comment]
Setting the system properties `https.proxyHost` and `https.proxyPort` works for me.

**Comment by klehmann** [comment]
I know the setting, but our app is not running as the only application on the application server. Cannot set this globally.

Would be good to have a way to configure the proxy server via IConfig / builder and then use URL.openConnection(Proxy) here:

https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/http/UrlConnection.java#L59

Does not seem easy to use a custom UrlConnection.

**Comment by darrelmiller** [comment]
We are currently experimenting with using the Apache HttpClient to bring interceptor support within the SDK.  As part of this work we will ensure that being able to set the proxy is something that is easy to do.

**Comment by klehmann** [comment]
Thanks a lot! HttpClient sounds good. We have customers with NTLM proxy authentication. HttpClient would work for them.

**Comment by ingoschaefer** [comment]
Hello @darrelmiller ,

how is the progress gone in integrating HttpClient or another solution for this? I have the exact same problem as @klehmann that we are running behind a http proxy server in a shared environment, where other http connection (e.g. to internal systems) can not use the proxy server. So the need is to have the proxy server setting in the application code.
The ADAL library for Java has this option.

Regards,
Ingo

**Comment by Samhithgb** [comment]
Hi @darrelmiller,

Is there anyway exposed to set proxy in the SDK now?

**Comment by atulkhurana27** [comment]
@Samhithgb  you got any workaround or solution for the same ?

**Comment by JTApps-1** [comment]
Same here. Is there a resolution on the near term roadmap?

**Comment by atulkhurana27** [comment]
https://stackoverflow.com/questions/66602439/how-to-customize-microsoft-graph-client-using-okhttpclient
Worked for me, you may need to customize okhttpclient based on the type of azure authentication you are using.

**Comment by baywet** [comment]
Hi everyone,
This has been possible in the V2 of the SDK since at least September 2020.
With the v3 of the SDK, things evolved a little (compared to the solution @atulkhurana27 is referring to).

```Java
final List<String> SCOPES = Arrays.asList("Mail.Read", "User.Read");
final TokenCredential tokenCredential = new DeviceCodeCredentialBuilder() // you can use any credential type, using this one as a place holder and omitting the configuration for brevity 
.build();
final TokenCredentialAuthProvider tokenCredAuthProvider = new TokenCredentialAuthProvider(SCOPES, deviceCodeCred);
final OkHttpClient httpClient = HttpClients.createDefault(authenticationProvider)
                                .newBuilder()
                                .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort)))
                                 .proxyAuthenticator(proxyAuthenticator)
                                .build();
GraphServiceClient<Request> graphClient = GraphServiceClient
                                                    .builder()
                                                    .authenticationProvider(tokenCredAuthProvider)
                                                    .httpClient(httpClient)
                                                    .buildClient();
final User me = graphClient.me().buildRequest().get();
```

More on the proxy settings from OkHttpClient [here](https://stackoverflow.com/questions/35554380/okhttpclient-proxy-authentication-how-to)

**Comment by baywet** [comment]
Note: you might also have to set the proxy for the client credentials, more information [here](https://stackoverflow.com/a/66781429/3808675)

**Comment by suryaanand** [comment]
Hi @baywet,

Need your suggestion on below, earlier I was getting Failed to authenticate with proxy error 

```
com.microsoft.grpah.core.ClientException: Error during http request
    at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:471)
Caused by: java.io.IOException: Failed to authenticate with proxy
```

So I have added below code ,

```
Proxy proxy = new Proxy(Prox.type.HTTP, new InetSocketAddress("hostname", port));

void setProxy(Proxy proxy, IGraphSericeClient graphClient){
       CoreHttpProvider prov = (CoreHttpProvider)graphClient.getHttpProvider();
      IConnectionConfig connectionConfig = prov.getConnectionConfg();
      OkHttpClient.Builder okBuilder = HttpClients.createDefault(new ICoreAuthenticationProvider(
             @override
             public Request authenticateRequest(Request arg0){
                    return null;
             }
)).newBuilder();
}


okBuilder.proxy(proxy).connectionTimeout().readTimeout().followRedirects(false).retryOnConnectionFailure(false);

try{
      FieldUtils.writeField(prov,"corehttpClient", okBuilder.build(), true);
}catch(IllegalAccessException e){
    throw new IllegalStateException(e); 
}
}
```
Now Failed to authenticate with proxy error has solved but I am getting 

```
com.microsoft.grpah.core.ClientException: Error during http request
    at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:471)
Caused by: java.lang.NullPointerException
    at com.microsoft.graph.httpcore.RetryHandler.intercept(RetryHandler.java:136)
    at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java31)
    at okhttp3.RealCall.execute(RealCall.java:81)
```

I am using microsoft-graph-2.6.0 and its dependent jars.

Please suggest, your suggestion will be more valuable for me.

Thanks

**Comment by baywet** [comment]
@suryaanand Can you first upgrade to version 3.2 and see whether you get a more explicit error message?

**Comment by suryaanand** [comment]
> @suryaanand Can you first upgrade to version 3.2 and see whether you get a more explicit error message?

Okay, sure. Thanks a lot.

**Comment by suryaanand** [comment]
> @suryaanand Can you first upgrade to version 3.2 and see whether you get a more explicit error message?

Hi baywet,

As per your suggestion I have upgraded to version 3.2 but bit confused from where to start the same. As there are changes in IAuthenticationProvider interface etc.
As I am referring this https://docs.microsoft.com/en-us/graph/sdks/customize-client?view=graph-rest-1.0&tabs=java
 and found as I have to fix proxy issue,

final OkHttpClient httpClient = HttpClients.createDefault(authenticationProvider)
                                .newBuilder()
                                .followSslRedirects(false) // sample configuration to apply to client
                                .build();

final GraphServiceClient graphServiceClient = GraphServiceClient
                .builder()
                .httpClient(httpClient)
                .buildClient();

What should I use authenticationProvider or TokenCredentialAuth provider? I was using ClientCredentialFactory.createFromSecret(clientSecret) to get access token.

 Could you please share the upgraded version API documentation. 
And if possible could you please provide sample to get access token from the client secret using upgraded version 3.2.0.

Thank you

**Comment by suryaanand** [comment]
Hi @baywet, 

As you suggested upgraded my SDK to 3.2.0. and referring this https://docs.microsoft.com/en-us/graph/sdks/customize-client?view=graph-rest-1.0&tabs=java link as well. Could you please tell me "how we can authorized access token which we have get from the client secret using IAuthenticationProvider? 

Thank you

**Comment by baywet** [comment]
https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?view=graph-rest-1.0&tabs=Java
