### ISSUE TITLE
Booking appointment work halfways but send a 500 staff not available

### ISSUE THREAD

**Issue by neobahamut-software** [microsoftgraph/msgraph-sdk-java#1581]
Hello msgraph team.

I have a strange behaviour on the graph SDK when booking an appointment.

I have available staff and every request to have its availability is ok but when I call the endpoint to book the appointment for the same slot, the appointment is actually booked on booking app (and I can see it in the web view) but I receive a 500 error "Staff not available" on my application as return from the endpoint.

Every other getStaffAvailability endpoint said that the slot for the appointment is free but it still gives an error back. And when we try again, the slot is really not available because already booked at the error call

You will find some stacktrace in an attached file and I also give you a file with some logs of the msgraph sdk. You can see some requests made and at the end the request which give the error.

We don't always have this problem. It is not very easy to reproduce and it could take time to come again.

Is this a problem with the SDK, graph or the booking app itself ?

Thanks

[booking_error_staffNotAvailable.txt](https://github.com/microsoftgraph/msgraph-sdk-java/files/12928210/booking_error_staffNotAvailable.txt)
[booking_logs_from_staffAvailability_to_error.txt](https://github.com/microsoftgraph/msgraph-sdk-java/files/12928211/booking_logs_from_staffAvailability_to_error.txt)

**Comment by ramsessanchez** [comment]
Hi @neobahamut-software ,
From the error you shared it seems you are making a POST request, which is used to create a booking appointment, I believe what you want to do is update that booking appointment which would require a PATCH request. If you could clarify, are you attempting to create a new booking appointment? Or are you attempting to book an already existing appointment? Thanks !

**Comment by neobahamut-software** [comment]
Hello @ramsessanchez 
Thanks for your reply. I have the case when creating a new appointment. It is indeed in the POST request.
I know it's confusing, it is for me too but I try to create a new appointment with POST, it takes 30 secs until I receive the 500 staff not available BUT the appointment is booked in the calendar.

**Comment by ramsessanchez** [comment]
@neobahamut-software , Could you share the code you are currently experiencing the issue with? I would like to replicate the issue, thanks!

**Comment by neobahamut-software** [comment]
@ramsessanchez Yes I would give some extracts of the code:
POST request :
```
public BookingAppointment bookAppointment(String businessId, TimeSlotsRequestDto data, String shortId, AppointmentDuration duration, String staffId, String serviceNote) {
        BookingAppointment bookingAppointment = null;

        try {
            BookingAppointment appointment = new BookingAppointment();
            appointment.startDateTime = toDateTimeTimeZone(data.getStartDateTime());
            appointment.endDateTime = toDateTimeTimeZone(data.getEndDateTime());
            appointment.postBuffer = DatatypeFactory.newInstance().newDuration(duration.getPostBuffer().toString());
            appointment.preBuffer = DatatypeFactory.newInstance().newDuration(duration.getPreBuffer().toString());
            appointment.serviceId = duration.getServiceId();
            appointment.staffMemberIds = List.of(staffId);
            appointment.serviceNotes = getServiceNoteComment(shortId, serviceNote);
            appointment.serviceLocation = getServiceLocation(shortId);

            bookingAppointment = graphServiceClient.solutions()
                    .bookingBusinesses(businessId)
                    .appointments()
                    .buildRequest()
                    .post(appointment);
        } catch (DatatypeConfigurationException e) {
            log.warn(e.toString());
        } catch (IllegalArgumentException e) {
            log.error(e.toString());
        }

        return bookingAppointment;
    }

```
And the appointment related data comes as body of an api request like so:
```
{
    "startDateTime": "2023-08-10T10:15:00+0200",
    "endDateTime": "2023-08-10T10:45:00+0200",
    "serviceIds": [
        "74a2a4aa-f5ba-41c2-920c-591422f507d1",
        "2dfdcf41-6376-4aa3-86c4-7b18749a09cc"
    ],
   [other data]
}
```

**Comment by baywet** [comment]
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
