### ISSUE TITLE
[Issue] Encoding of Relative path for upload file

### ISSUE THREAD

**Issue by ssapa** [microsoftgraph/msgraph-sdk-java#1593]
This is in reference to : https://github.com/microsoftgraph/msgraph-sdk-java/issues/1572
@ramsessanchez We are using graph sdk file for uploading a file to Onedrive and observing an issue while sending encoded relative path with Conflict-behaviour=replace.

**Without encoding Relative Path** :
So, when we use Relative path as "root:/snap test" and conflict_behaviour=Replace, the file is getting replaced and we can see the updated version as well.
**Request :**
https://graph.microsoft.com/v1.0/drives/b!A5GL7aV13EOiocvwYtGLxMooxz3vr0JPqZA9_DpzUKTJ9HQROSuuRrmVDBpuHNw6/root:/snap%20test/testfile.json:/content?%40microsoft.graph.conflictBehavior=replace

**request-id:** e29dfbf9-f483-4f98-9e4c-4d7e03b660a4

**Response :**
![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/50152071/a6bbe3d1-5531-4c7f-93c0-80b50c3c8211)

**With Encoding Relative Path :**
When we use Relative path as **"root:/snap%20test" and conflict_behaviour=Replace**, we are getting 200 response from api, but the file is not getting replaced.
**Request :**
https://graph.microsoft.com/v1.0/drives/b!A5GL7aV13EOiocvwYtGLxMooxz3vr0JPqZA9_DpzUKTJ9HQROSuuRrmVDBpuHNw6/root:/snap%2520test/testfile.json:/content?%40microsoft.graph.conflictBehavior=replace

**request-id:** b5f74f4a-c3e7-45d7-b863-18e0bcddf204

**Response :**
![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/50152071/a809dcce-3ba2-4210-848d-b5909360722c)

But when we use Conflict-behaviour : fail or rename, the api is working as expected even if we give encoded relative path. So we are expecting the api should work fine incase of conflict-bahaviour=replace as well .

**Comment by baywet** [comment]
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
