### ISSUE TITLE
Error with android (Api<26)

### ISSUE THREAD

**Issue by gilshallem** [microsoftgraph/msgraph-sdk-java#1617]
Hi.
I am getting the error:
com.android.tools.r8.internal.k2: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)

when trying to compile via android. upping the android version support is not an option
![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/8035623/a75911c6-7b4b-4dcc-912a-5ac4410a6c67)

Any solution?
thanks :)

**Comment by gilshallem** [comment]
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

implementation 'com.microsoft.graph:microsoft-graph:5.76.0'

**Comment by baywet** [comment]
Hi @gilshallem,
Thanks for using the Java SDK and for reaching out.
This SDK is only supported [for API level 26 and higher](https://github.com/microsoftgraph/msgraph-sdk-java#7-supported-java-versions), please change your [min SDK version](https://github.com/microsoftgraph/msgraph-sdk-java/blob/7488b93680c09ac3c1375e011071c28aaa9ed052/android/build.gradle#L33)
