### ISSUE TITLE
How can I reserve a room?

### ISSUE THREAD

**Issue by yidaimi** [microsoftgraph/msgraph-sdk-java#1621]
I want to book a room for meeting by sdk. I have spent many time to find out solution in https://learn.microsoft.com/. 
I just found this :https://learn.microsoft.com/en-us/graph/outlook-calendar-concept-overview.
In this page , it told me to add the room in event.Location:  
"
In Outlook, booking a meeting room is as straight-forward as adding an attendee to the event. The calendar API represents a meeting room as an [emailAddress](https://learn.microsoft.com/en-us/graph/api/resources/emailaddress) object. You can [get rooms](https://learn.microsoft.com/en-us/graph/api/place-list#example-1-list-all-the-rooms-defined-in-the-tenant) and [get room lists](https://learn.microsoft.com/en-us/graph/api/place-list#example-2-list-all-the-room-lists-defined-in-the-tenant) that are available in a tenant. To organize a meeting in a specific room, assign it to the location property of the event." 

Here is my code. It doesn't work.
`        Event event = new Event();
        event.subject = "subject";
        ItemBody body = new ItemBody();
        body.contentType = BodyType.HTML;
        body.content = "content";
        event.body = body;
        DateTimeTimeZone start = new DateTimeTimeZone();
        start.dateTime = "2023-11-14T07:00:00";
        start.timeZone = "Pacific Standard Time";
        event.start = start;
        DateTimeTimeZone end = new DateTimeTimeZone();
        end.dateTime = "2023-11-14T07:00:00";
        end.timeZone = "Pacific Standard Time";
        event.end = end;

	**//set the location
        Location location = new Location();
        location.displayName = "Lumina 2F-Gothenburg (8)";   //conference display name
        location.uniqueId = "0e6f1899-c694-4c13-a561-5c2e69f8cd03"; //conference id
        location.locationEmailAddress = "conf0220@polestar-auto.com";  //conference email address
        event.location = location;**

	//set the attendee
        LinkedList<Attendee> attendeesList = new LinkedList<Attendee>();
        Attendee attendees1 = new Attendee();
        EmailAddress emailAddress1 = new EmailAddress();
        emailAddress1.address = "aaa@google.com";
        emailAddress1.name = "aaa";
        attendees1.emailAddress = emailAddress1;
        attendees1.type = AttendeeType.REQUIRED;
        attendeesList.add(attendees1);

        event.attendees = attendeesList;

        //sponsor user id
        Graph._appClient.users("dde85447-7342-4b65-ac5f-c3982ec7fa71").calendar().events().buildRequest().post(event);`

Finally , I can get the calendar in the attendee's outlook. However , I can't find the booking in the room's calendar. 
How can I reserve the room correctlly?

**Comment by baywet** [comment]
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
