### ISSUE TITLE
UrlConnection does not have neither connect timeout nor read timeout set

### ISSUE THREAD

**Issue by rgrebski** [microsoftgraph/msgraph-sdk-java#166]
There is no read/connect timeouts set for UrlConnection. Because of that when any endpoint is called during which network goes down connection gets stuck (by default there is infinite timeout)

### Expected behavior
Connection times outs when network is down during a call

### Actual behavior
Connection gets stuck when network is down

### Steps to reproduce the behavior
while(true){
  graphClient.anyRequest();
}

Disable network during executing the loop

**Comment by deepak2016** [comment]
Thanks for reporting the issue, we are reviewing the PR

**Comment by Krisoblucki-okta** [comment]
@rgrebski @deepak2016 would it make sense to allow these values to be custom set instead of being hardcoded?

**Comment by rgrebski** [comment]
Definately a good idea
