### ISSUE TITLE
Fails to parse mailboxSettings

### ISSUE THREAD

**Issue by kitherill** [microsoftgraph/msgraph-sdk-java#168]
### Prerequisites

I'm trying to fetch mailboxSettings property for 'sandbox' user 48d31887-5fad-4d73-a9f5-3c356e68a038 via msgraph java SDK. For MS Graph API explorer it would be following URL: 'https://graph.microsoft.com/v1.0/users/48d31887-5fad-4d73-a9f5-3c356e68a038?$select=mailboxSettings'.

### Expected behavior

User is read successfully

### Actual behavior

Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 866 path $.mailboxSettings.workingHours.startTime

### Steps to reproduce the behavior

Try to deserialise a response of `https://graph.microsoft.com/v1.0/me/?$select=mailboxSettings`

```
DefaultSerializer defaultSerializer = new DefaultSerializer(new ILogger() {
            @Override
            public void setLoggingLevel(LoggerLevel loggerLevel) {
            }

            @Override
            public LoggerLevel getLoggingLevel() {
                return LoggerLevel.DEBUG;
            }

            @Override
            public void logDebug(String s) {

            }

            @Override
            public void logError(String s, Throwable throwable) {

            }
        });
        User user = defaultSerializer.deserializeObject("\n"
                + "{\n"
                + "    \"@odata.context\": \"https://graph.microsoft.com/v1.0/$metadata#users(mailboxSettings)/$entity\",\n"
                + "    \"id\": \"48d31887-5fad-4d73-a9f5-3c356e68a038@dcd219dd-bc68-4b9b-bf0b-4a33a796be35\",\n"
                + "    \"mailboxSettings\": {\n"
                + "        \"archiveFolder\": \"AAMkAGVmMDEzMTM4LTZmYWUtNDdkNC1hMDZiLTU1OGY5OTZhYmY4OAAuAAAAAAAiQ8W967B7TKBjgx9rVEURAQAiIsqMbYjsT5e-T7KzowPTAAAAAAFNAAA=\",\n"
                + "        \"timeZone\": \"Pacific Standard Time\",\n"
                + "        \"automaticRepliesSetting\": {\n"
                + "            \"status\": \"disabled\",\n"
                + "            \"externalAudience\": \"all\",\n"
                + "            \"internalReplyMessage\": \"\",\n"
                + "            \"externalReplyMessage\": \"\",\n"
                + "            \"scheduledStartDateTime\": {\n"
                + "                \"dateTime\": \"2018-11-27T00:00:00.0000000\",\n"
                + "                \"timeZone\": \"UTC\"\n"
                + "            },\n"
                + "            \"scheduledEndDateTime\": {\n"
                + "                \"dateTime\": \"2018-11-28T00:00:00.0000000\",\n"
                + "                \"timeZone\": \"UTC\"\n"
                + "            }\n"
                + "        },\n"
                + "        \"language\": {\n"
                + "            \"locale\": \"en-US\",\n"
                + "            \"displayName\": \"English (United States)\"\n"
                + "        },\n"
                + "        \"workingHours\": {\n"
                + "            \"daysOfWeek\": [\n"
                + "                \"monday\",\n"
                + "                \"tuesday\",\n"
                + "                \"wednesday\",\n"
                + "                \"thursday\",\n"
                + "                \"friday\"\n"
                + "            ],\n"
                + "            \"startTime\": \"08:00:00.0000000\",\n"
                + "            \"endTime\": \"17:00:00.0000000\",\n"
                + "            \"timeZone\": {\n"
                + "                \"name\": \"Pacific Standard Time\"\n"
                + "            }\n"
                + "        }\n"
                + "    }\n"
                + "}", User.class);
```

### PS
There probably should be type adapter registered for `TimeOfDay.class` in `com.microsoft.graph.serializer.GsonFactory#getGsonInstance`

**Comment by kitherill** [comment]
I have a fix ready and tested, but I'm not able to push it. Please ping me if you're interested.

**Comment by NakulSabharwal** [comment]
Thanks for reporting this issue. We are looking into it. You can comment here your suggested fix and we can have a look into that also.

**Comment by davidmoten** [comment]
@kitherill Can help with your git problem too if you like. Did you fork the repository and push your fix branch to that fork?

**Comment by kitherill** [comment]
@NakulSabharwal 
@davidmoten 

https://github.com/microsoftgraph/msgraph-sdk-java/pull/170

**Comment by deepak2016** [comment]
PR looks good, approving and merging to dev. 
Please also raise a PR to register serializer, as in the current PR only deserializer has been registered.

**Comment by steffen-harbich-cognitum** [comment]
Is the serialization fixed? I am getting the following error when trying to update the startTime of working hours:

```
com.microsoft.graph.http.GraphServiceException: Error code: RequestBodyRead
Error message: An unexpected 'StartObject' node was found for property named 'startTime' when reading from the JSON reader. A 'PrimitiveValue' node was expected.

PATCH https://graph.microsoft.com/v1.0/users/6947272f-1908-49d2-b610-55418494e15f/mailboxSettings
SdkVersion : graph-java/v3.5.0
```

Looking into GsonFactory there is no serializer registered for TimeOfDay.

**Comment by baywet** [comment]
Hi @steffen-harbich-cognitum ,
Thanks for reaching out. Yes the serialization has been improved a lot since this initial post. However, something was probably missed at the time as [only a deserializer is registered](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/c5f4936aefe26bac2e29f439a7382452064f9c5d/src/main/java/com/microsoft/graph/serializer/GsonFactory.java#L246)

Can you [open a new issue in the core repo](https://github.com/microsoftgraph/msgraph-sdk-java-core) to describe your issue fully and the fact the serializer is missing please? Thanks!

**Comment by steffen-harbich-cognitum** [comment]
@baywet done, and thanks for fast reply.
