### ISSUE TITLE
Microsoft Graph app only authentication error on websphere

### ISSUE THREAD

**Issue by giulioram** [microsoftgraph/msgraph-sdk-java#1702]
Due to migration to office 365 email management, I need to read email through Microsoft Graph app only authentication; the following code works as expected running the class 
through "Run As -> Run Configurations..." setting as JRE an alternate JRE: a jdk 1.8 installed locally; 
when running the class through the "Project JRE(WebSphere Application Server V8.5 JRE)" I got an error: looks like the remote host closes the connection.

I noticed the generated token is handled by an object: reactor.core.publisher.Mono<AccessToken> what I guess is that the method block() used to retrieve the AccessToken, tryes to make the thread wait for the outcome and this may trigger an exception because the Websphere environment wouldn't allow a direct thread handling

Here the code, the libraries and the results and screenshots
CODE:
	
	public TestGraph() {
		initializeGraphForAppOnlyAuth();
	}
	private ClientSecretCredential _clientSecretCredential;
	
    private GraphServiceClient<Request> _appClient;
	
	public static void main(String[] args) {
		TestGraph tg = new TestGraph();
		try {
			tg.getInbox();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	private void initializeGraphForAppOnlyAuth() {
        try {
        	if (_clientSecretCredential == null) {
			    final String clientId = "<APP_ID>";
			    final String tenantId = "<TENANT>";
			    final String clientSecret = "<SECRET>";

			    _clientSecretCredential = new ClientSecretCredentialBuilder()
			        .clientId(clientId)
			        .tenantId(tenantId)
			        .clientSecret(clientSecret)
			        .build();
			}

			if (_appClient == null) {
			    final TokenCredentialAuthProvider authProvider =
			        new TokenCredentialAuthProvider(
			            Arrays.asList("https://graph.microsoft.com/.default"), _clientSecretCredential);

			    _appClient = GraphServiceClient.builder()
			        .authenticationProvider(authProvider)
			        .buildClient();
			}
		} catch (Exception ex) {
			ex.printStackTrace();
		}
    }

	private void getInbox() throws Exception {
		String p_folder = "INBOX";
		int numEmail = 5;
		if (_clientSecretCredential == null) {
			initializeGraphForAppOnlyAuth();
		}
		
		if(_appClient == null) throw new Exception("GraphServiceClient could not be initialized");
		
		MessageCollectionPage mcp = _appClient
				.users()
				.byId("<MY_EMAIL>@<MY_DOMAIN>.it")
				.mailFolders(p_folder)
				.messages()
				.buildRequest()
				.select("from, isRead, receivedDateTime, subject, body, attachments")
				.top(numEmail)
				.orderBy("receivedDateTime DESC")
				.get();
		for(com.microsoft.graph.models.Message msg: mcp.getCurrentPage()) {
			System.out.println(msg.id + " " + msg.subject);
		}
	}
	
LIBRARIES:
	
accessors-smart-2.4.9.jar
annotations-13.0.jar
asm-9.3.jar
azure-core-1.44.1.jar
azure-core-http-netty-1.13.9.jar
azure-identity-1.10.4.jar
azure-json-1.1.0.jar
castor-0.9.5.3-xml.jar
checker-qual-3.37.0.jar
content-type-2.2.jar
error_prone_annotations-2.21.1.jar
failureaccess-1.0.1.jar
gson-2.6.2.jar
guava-32.1.3-jre.jar
httpclient-4.5.14.jar
httpcore-4.4.16.jar
jackson-annotations-2.13.5.jar
jackson-core-2.13.5.jar
jackson-databind-2.13.5.jar
jackson-datatype-jsr310-2.13.5.jar
jcip-annotations-1.0-1.jar
jdom.jar
json-smart-2.4.10.jar
junit-3.8.1.jar
kotlin-stdlib-1.9.10.jar
kotlin-stdlib-common-1.9.10.jar
kotlin-stdlib-jdk8-1.9.10.jar
microsoft-graph-5.75.0.jar
microsoft-graph-core-2.0.19.jar
msal4j-1.13.9.jar
msal4j-persistence-extension-1.2.0.jar
NetComponents.jar
netty-buffer-4.1.100.Final.jar
netty-codec-4.1.100.Final.jar
netty-codec-dns-4.1.100.Final.jar
netty-codec-http2-4.1.100.Final.jar
netty-codec-http-4.1.100.Final.jar
netty-codec-socks-4.1.100.Final.jar
netty-common-4.1.100.Final.jar
netty-handler-4.1.100.Final.jar
netty-handler-proxy-4.1.100.Final.jar
netty-resolver-4.1.100.Final.jar
netty-resolver-dns-4.1.100.Final.jar
netty-resolver-dns-classes-macos-4.1.100.Final.jar
netty-resolver-dns-native-macos-4.1.100.Final-osx-x86_64.jar
netty-tcnative-boringssl-static-2.0.62.Final.jar
netty-tcnative-classes-2.0.62.Final.jar
netty-transport-4.1.100.Final.jar
netty-transport-classes-epoll-4.1.100.Final.jar
netty-transport-classes-kqueue-4.1.100.Final.jar
netty-transport-native-epoll-4.1.100.Final-linux-x86_64.jar
netty-transport-native-kqueue-4.1.100.Final-osx-x86_64.jar
netty-transport-native-unix-common-4.1.100.Final.jar
nimbus-jose-jwt-9.30.2.jar
oauth2-oidc-sdk-10.7.1.jar
okhttp-4.12.0.jar
okio-jvm-3.6.0.jar
reactive-streams-1.0.4.jar
reactor-core-3.4.33.jar
reactor-netty-core-1.0.38.jar
reactor-netty-http-1.0.38.jar
spotbugs-annotations-4.7.3.jar
log4j-1.2.15.jar
commons-beanutils-1.8.2.jar
commons-codec-1.4.jar
commons-collections-3.2.1.jar
commons-configuration-1.6.jar
commons-digester-2.0.jar
commons-fileupload-1.2.1.jar
commons-io-1.3.2.jar
commons-jxpath-1.3.jar
commons-lang-2.4.jar
commons-logging-1.1.1.jar
jboss-logging-3.1.0.CR2.jar
slf4j-api-1.6.1.jar
slf4j-simple-1.6.1.jar

RESULT RUNNING WITH INSTALLED JDK 1.8:

63 [main] INFO com.azure.core.implementation.ReflectionUtilsMethodHandle - Unable to create MethodHandles to use Java 9+ MethodHandles.privateLookupIn. Will attempt to fallback to using the package-private constructor.
1727 [ForkJoinPool.commonPool-worker-1] INFO com.azure.identity.ClientSecretCredential - Azure Identity => getToken() result for scopes [https://graph.microsoft.com/.default]: SUCCESS
AAMkADUzYjY2OTFmLWI0MjYtNGJmOS1iODBjLTk0NWJkN2UxNjI2MABGAAAAAAAtpLPKPrOlR5gsJpH_xCOwBwBRJtugbZ8oRK1mAGP5m6BnAAAAAAEMAABRJtugbZ8oRK1mAGP5m6BnAABc02prAAA= prova all immagine
AAMkADUzYjY2OTFmLWI0MjYtNGJmOS1iODBjLTk0NWJkN2UxNjI2MABGAAAAAAAtpLPKPrOlR5gsJpH_xCOwBwBRJtugbZ8oRK1mAGP5m6BnAAAAAAEMAABRJtugbZ8oRK1mAGP5m6BnAABc02pqAAA= prova allegato
AAMkADUzYjY2OTFmLWI0MjYtNGJmOS1iODBjLTk0NWJkN2UxNjI2MABGAAAAAAAtpLPKPrOlR5gsJpH_xCOwBwBRJtugbZ8oRK1mAGP5m6BnAAAAAAEMAABRJtugbZ8oRK1mAGP5m6BnAABcG9gvAAA= Annullata: test item
AAMkADUzYjY2OTFmLWI0MjYtNGJmOS1iODBjLTk0NWJkN2UxNjI2MABGAAAAAAAtpLPKPrOlR5gsJpH_xCOwBwBRJtugbZ8oRK1mAGP5m6BnAAAAAAEMAABRJtugbZ8oRK1mAGP5m6BnAABX7YePAAA= test allegato
AAMkADUzYjY2OTFmLWI0MjYtNGJmOS1iODBjLTk0NWJkN2UxNjI2MABGAAAAAAAtpLPKPrOlR5gsJpH_xCOwBwBRJtugbZ8oRK1mAGP5m6BnAAAAAAEMAABRJtugbZ8oRK1mAGP5m6BnAABQuteXAAA= test subject

RESULT RUNNING WITH Websphere Application Server V8.5 JRE:

15 [main] INFO com.azure.core.implementation.ReflectionUtilsMethodHandle - Unable to create MethodHandles to use Java 9+ MethodHandles.privateLookupIn. Will attempt to fallback to using the package-private constructor.
1879 [ForkJoinPool.commonPool-worker-1] ERROR com.azure.core.http.netty.NettyAsyncHttpClient - java.io.IOException: Connessione in corso interrotta forzatamente dall'host remoto.
1879 [reactor-http-nio-1] WARN reactor.netty.http.client.HttpClientConnect - [6a5b115d, L:/192.168.1.16:62458 - R:login.microsoftonline.com/20.190.177.83:443] The connection observed an error
java.io.IOException: Connessione in corso interrotta forzatamente dall'host remoto.
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:55)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:235)
	at sun.nio.ch.IOUtil.read(IOUtil.java:204)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:394)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:254)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:822)
2789 [reactor-http-nio-2] WARN reactor.netty.http.client.HttpClientConnect - [07c6124a, L:/192.168.1.16:62460 - R:login.microsoftonline.com/20.190.177.83:443] The connection observed an error
java.io.IOException: Connessione in corso interrotta forzatamente dall'host remoto.
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:55)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:235)2789 [ForkJoinPool.commonPool-worker-1] ERROR com.azure.core.http.netty.NettyAsyncHttpClient - java.io.IOException: Connessione in corso interrotta forzatamente dall'host remoto.

	at sun.nio.ch.IOUtil.read(IOUtil.java:204)
	....
![run_configuration_alternate_jdk](https://github.com/microsoftgraph/msgraph-sdk-java/assets/82027199/96a1a10d-4c23-46c4-b3f4-28f4a6c6e027)
![run_configuration_websphere_app_server_jre](https://github.com/microsoftgraph/msgraph-sdk-java/assets/82027199/056ac364-b6f3-4fe1-b72a-e54c149103b4)

**Comment by baywet** [comment]
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
