### ISSUE TITLE
Administrative Unit - Create a new group - Issue

### ISSUE THREAD

**Issue by rgreil** [microsoftgraph/msgraph-sdk-java#1743]
### Expected behavior

As described on https://learn.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-1.0&tabs=http#request-body, the following code should create a new group.

```
GraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

Group directoryObject = new Group();
directoryObject.description = "Self help community for golf";
directoryObject.displayName = "Golf Assist";
LinkedList<String> groupTypesList = new LinkedList<String>();
groupTypesList.add("Unified");
directoryObject.groupTypes = groupTypesList;
directoryObject.mailEnabled = true;
directoryObject.mailNickname = "golfassist";
directoryObject.securityEnabled = false;

graphClient.directory().administrativeUnits("{id}").members()
	.buildRequest()
	.post(directoryObject);
```

### Actual behavior

It tries to create a reference to a null object.

### Steps to reproduce the behavior

```
GraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

Group directoryObject = new Group();
directoryObject.description = "Self help community for golf";
directoryObject.displayName = "Golf Assist";
LinkedList<String> groupTypesList = new LinkedList<String>();
groupTypesList.add("Unified");
directoryObject.groupTypes = groupTypesList;
directoryObject.mailEnabled = true;
directoryObject.mailNickname = "golfassist";
directoryObject.securityEnabled = false;

graphClient.directory().administrativeUnits("{id}").members()
	.buildRequest()
	.post(directoryObject);
```

graphClient.directory().administrativeUnits("{id}").members() returns DirectoryObjectCollectionWithReferencesRequestBuilder instead of DirectoryObjectCollectionRequest

**Comment by rgreil** [comment]
Is anybody looking into such issues?

**Comment by baywet** [comment]
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
