### ISSUE TITLE
Birthday of contact not updating when the birthday passed as null in PATCH api of ms-graph SDK (Java)

### ISSUE THREAD

**Issue by ssharma-cloudlex** [microsoftgraph/msgraph-sdk-java#1777]
### Issue

I am using the patch api of graph sdk to update the birthday for outlook contacts.
If the outlook contact already has a birthday, and I pass null as the birthday in the requestbody, I expect the birthday to be removed, as it happens in the HTTP request. But the birthday field is not being updated and it retains the old value. 
The api does not return any error and other fields are being updated properly.
I am using Microsoft Graph SDK version 5.80.0 and azure-identity version 1.4.6 for graph dependencies. 

Please note that the update operation works fine using an HTTP request, but fails on SDK.
How can I remove an already added birthday using the graph sdk?

### Expected behavior

For contacts already having a birthday, the birthday field on the outlook contact should be removed, when I pass null as birthday in the com.microsoft.graph.models.Contact object while using the patch() method to update the contact.

### Actual behavior

The birthday field of the outlook contact is not updated when I pass null as birthday.

### Steps to reproduce the behavior

Step 1 -  Create any outlook contact with a non empty birthday field.
Step 2 - Use the graph sdk patch() method to update the contact. Set the birthday property of the com.microsoft.graph.models.Contact object as null.

You will notice that the birthday is not updated.

This is the api I am using in the graph SDK. ⬇️
![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/159136043/30f69de4-fb85-4d82-97a1-c8a410ad9d01)

and this is the code to get the graph client ⬇️
![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/159136043/fab1a08f-f0c5-4fb7-91f7-0ecc819376d3)

**Comment by ramsessanchez** [comment]
Hi @ssharma-cloudlex , This appears to be an issue with the default serializer that is used when the request is being built. Right before the request is sent we deserialize the updated object and turn into a JSON body. Unfortunately, the default behavior ignores 'null' values and thus the updated JSON body does not include a Birthday property. In order to update it my recommendation is to update the instance of the default serializer and then send a custom request with the raw JSON values. For example: 
``` Java
//First set up the graph client as follows:
        graphClient = GraphServiceClient.builder()
                .authenticationProvider(authProvider)
                .logger(logger)
                .serializer(new DefaultSerializer(logger, true)) // Setting the value 'true' here will enable 'null' serialization. 
                .buildClient();
// Then try sending the request as such. 
        JsonElement birthdayElement = JsonParser.parseString("{\"birthday\": null}");
        graphClient.customRequest("/me/contacts/<contact id>").buildRequest().patch(birthdayElement);

```

**Comment by ssharma-cloudlex** [comment]
Thank you for your prompt response and the suggested solution. I understand that utilizing the default serializer and sending a custom request with the raw JSON values can help in updating specific fields such as the birthday in this case.
 
However, I would like to clarify my understanding regarding this approach. It seems that this method involves constructing a custom request for each field that needs to be updated. This could potentially become cumbersome, especially when dealing with scenarios where multiple fields need to be updated simultaneously, such as the address fields, where we face the same issue that passing null as an address, does not remove the existing addresses from outlook.
 
If I'm interpreting this correctly, updating multiple fields would require constructing a JSON payload containing all the fields that need updating and then sending a custom request for each combination of updated fields. This approach could lead to increased complexity, especially when dealing with a large number of fields or complex update scenarios.
 
Could you please confirm if my understanding is accurate? Additionally, is there a more efficient approach, perhaps through the Microsoft Graph SDK, that allows for updating multiple fields in a single request without the need to construct custom requests for each field?
 
Thank you once again for your assistance.

**Comment by ramsessanchez** [comment]
My suggestion would be to make note/create a map of values that may need to be set to 'null' as those are what is causing the issue, passing those null values in a separate request while updating the other fields via the regular format. While I have not yet tried it, it should be possible to use the default serializer to call the 'deserialize()' method on the 'Contact' object and retrieve the json String to then turn to an element. Alternatively, I would suggest moving to version 6.0 which is slated for release in the next few weeks and which is already in Release Candidate preview stage, check the upgrade guide here: 
https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/docs/upgrade-to-v6.md

**Comment by ssharma-cloudlex** [comment]
Thank you for your suggestion and the provided insights. After reviewing your recommendations and considering the impact on our current application, I agree with your approach of sending a separate request to handle the null values. Incorporating major changes from the upcoming 6.0 version could introduce major changes to our existing workflow. Therefore, I believe it's better for me to proceed with the solution of sending null values separately at this stage.

**Comment by ssharma-cloudlex** [comment]
Does custom request support passing org.json.JSONObject or string for the request body?

**Comment by baywet** [comment]
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
