### ISSUE TITLE
Clean up long term branches after 6.1.0 Release

### ISSUE THREAD

**Issue by ramsessanchez** [microsoftgraph/msgraph-sdk-java#1782]
Clean up refs to feature/6.0 in Dependabot scripts, GitHub Actions, Policies, and finally delete the branch.

**Comment by andrueastman** [comment]
Related to the failure [here](https://github.com/microsoftgraph/msgraph-beta-sdk-java/actions/runs/7822230473). One of the breaking changes in the upload artifacts actions v4 is that names need to be unique(See [here](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes))

So, these names will need to be unique if the jobs are running at the same time.
- https://github.com/microsoftgraph/msgraph-beta-sdk-java/blob/8a92eeb0d8c99c5c25c3b6430580a4b70a07f0c7/.github/workflows/preview-and-release.yml#L100
- https://github.com/microsoftgraph/msgraph-beta-sdk-java/blob/8a92eeb0d8c99c5c25c3b6430580a4b70a07f0c7/.github/workflows/preview-and-release.yml#L53

(Just as an FYI @ramsessanchez as this may be irrelevant given that one of the jobs may be removed in the cleanup work here either way)
