### ISSUE TITLE
Getting Paginated list of sessions in a call record 

### ISSUE THREAD

**Issue by priya2395** [microsoftgraph/msgraph-sdk-java#1786]
Do we need to make a separate call for getting paginated list of sesssions in a call record.
Can't see any way to get it from callRecord response.
```java
com.microsoft.graph.models.callrecords.CallRecord result = graphClient.communications().callRecords().byCallRecordId("{callRecord-id}").get(); // to get call record basic data

com.microsoft.graph.models.callrecords.SessionCollectionResponse result = graphClient.communications().callRecords().byCallRecordId("{callRecord-id}").sessions().get(requestConfiguration -> {
requestConfiguration.queryParameters.expand = new String []{"segments"};
}); // to get sessions data
```

Or can we get it using below call?
```java
com.microsoft.graph.models.callrecords.CallRecord result = graphClient.communications().callRecords().byCallRecordId("{callRecord-id}").get(requestConfiguration -> {
requestConfiguration.queryParameters.expand = new String []{"sessions($expand=segments)"};
});
```
I can see the nextPageLink for sessions coming in additionalDataManager in callRecord response.

**Comment by baywet** [comment]
Thanks for the additional information. I'm not clear on what you're trying to achieve here?
Are you trying to list out all the sessions for a call record?
Or are you trying to list out all the segments for a call record (which means listing out all the sessions) ?
