### ISSUE TITLE
Can't understand the error via graph api in v 6.1.0

### ISSUE THREAD

**Issue by ihudedi** [microsoftgraph/msgraph-sdk-java#1812]
Hi,
Any error comes from the graph API for any api call getting
Exception in thread "main" java.time.format.DateTimeParseException: Text '2024-02-13T21:14:10' could not be parsed at index 19
For example get site not exist.
Thanks,
Itay

**Comment by nagendrakamisetti** [comment]
**I am experiencing the same issue as described in the following questions that I posted:**

1. [MS Graph SDK API POST applications is failing when creating application](https://learn.microsoft.com/en-us/answers/questions/1531641/ms-graph-sdk-api-post-applications-is-failing-when.html)
2. [MS Graph SDK API GET application by ID is failing](https://learn.microsoft.com/en-us/answers/questions/1531646/ms-graph-sdk-api-get-application-by-id-is-failing.html)

I am eagerly awaiting a response and would appreciate any assistance or guidance in resolving this issue.

Thank you.

**Comment by nagendrakamisetti** [comment]
### **Attention @rocketraman, @MaximRouiller, and @davidmoten,**

I'd like to bring your attention to a critical issue that has arisen and is causing significant disruption. Others have also reported encountering the same problem.

Could you please investigate this issue promptly? It has been logged on GitHub as [Issue #1813](https://github.com/microsoftgraph/msgraph-sdk-java/issues/1813).

Addressing this on a high priority basis would greatly assist us.

Thank you.

**Comment by Ndiritu** [comment]
Closing this as it's related to https://github.com/microsoftgraph/msgraph-sdk-java/issues/1785

Fix has been merged and should be released later today.
