### ISSUE TITLE
Site List doesn't fetch sub sites - v 5.8

### ISSUE THREAD

**Issue by ihudedi** [microsoftgraph/msgraph-sdk-java#1817]
Hi,
When using graph v5.8 .sites() method doesn't fetch sub lists.
When use search parameter and set to empty or asterices he fetched the sub sites but not the personal sites.
Thanks,
Itay

**Comment by Ndiritu** [comment]
Closing as related to https://github.com/microsoftgraph/msgraph-sdk-java/issues/1807

Fix will only be made for v6 if there's need to.
