### ISSUE TITLE
V6.x.x missing ability to set service root, causes gov cloud connections to fail

### ISSUE THREAD

**Issue by The-Funk** [microsoftgraph/msgraph-sdk-java#1825]
I had been using V5.x.x for a while and am refactoring to upgrade to V6.x.x and I noticed the ability to override the serviceRoot is gone.

I am in Azure Gov Cloud and in Gov Cloud all requests made without specifying the service root fail with invalid audience. I am guessing that the client attempts to set service root to graph.microsoft.com instead of graph.microsoft.us which causes the failure.

Here are the previous docs indicating the need to override serviceRoot:
https://learn.microsoft.com/en-us/graph/sdks/national-clouds?tabs=java

**Comment by baywet** [comment]
Hi @The-Funk 
Thanks for using the latest version of the SDK and for reaching out.
We're still working on getting the latest snippets published to the documentation.

In the meantime, the first part of the snippet (for Azure Identity) still applies.
As for the later part, you should be able to do the following:


```java
client.getRequestAdapter().setBaseUrl("https://graph.microsoft.us/v1.0");
```

**Comment by The-Funk** [comment]
Hi @baywet that did the trick, thank you! I suppose I should have looked at the request adaptor class a little more closely. Appreciated!
