### ISSUE TITLE
com.microsoft.graph.models.odataerrors.ODataError exception when trying to create OnlineMeeting

### ISSUE THREAD

**Issue by ccea-dev-team** [microsoftgraph/msgraph-sdk-java#1836]
private static final SimpleDateFormat DATETIME_FORMAT = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSXXX");

    OnlineMeeting meeting = new OnlineMeeting();   	
    meeting.setSubject(meetingName);
    meeting.setStartDateTime(OffsetDateTime.parse(DATETIME_FORMAT.format(meetingStartTime.getTime())));
    meeting.setEndDateTime(OffsetDateTime.parse(DATETIME_FORMAT.format(meetingEndTime.getTime())));
    MeetingParticipants meetingAttendees = new MeetingParticipants();
    List<MeetingParticipantInfo> meetingParticipants = new ArrayList<>();
    	
    for(String attendeeEmail : attendeesEmailList)
    {
        MeetingParticipantInfo meetingPar = new MeetingParticipantInfo(); 		
        meetingPar.setUpn(attendeeEmail);
        meetingParticipants.add(meetingPar);
    }
    	   	
    meetingAttendees.setAttendees(meetingParticipants);
    meeting.setParticipants(meetingAttendees);	
    JoinMeetingIdSettings joinMeetingIdSettings = new JoinMeetingIdSettings();
    joinMeetingIdSettings.setIsPasscodeRequired(false);
    meeting.setJoinMeetingIdSettings(joinMeetingIdSettings);
    OnlineMeeting newMeeting = graphClient.users().byUserId(emailOfMeetingOwner).onlineMeetings().post(meeting);

This is throwing an exception below.  I am using 6.2.1.  Previously when I tried this on 6.1.0 I was getting the date parsing error #1785

![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/99395943/de85e914-6b2f-4251-992e-0150ce511430)

**Comment by UXMichael** [comment]
Funny. When i am trying to upload a file there is a odata exception too. Maybe the 6.x version java sdk should be marked as unstable until all problems are fixed. Or the documentation is wrong ( https://learn.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http ) .

**Comment by ccea-dev-team** [comment]
Still getting this issue on 6.3.0.  We have checked the azure app registrations and the app does have access to create and edt online meetings.

**Comment by ccea-dev-team** [comment]
@Ndiritu Hi, yes I tried wrapping it in an ApiExcpetion as suggested above but the e.getMessage() was null and the stacktrace was the same as above.

**Comment by Ndiritu** [comment]
@ccea-dev-team looks like it's a permission issue. Based on the [reference docs](https://learn.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http#permissions) Applications permissions are not supported for this endpoint. You'd need to create an application access policy as explained more in the doc.

**Comment by ccea-dev-team** [comment]
@Ndiritu great thanks for you help.  I will talk to our admins and see about setting up an access policy

**Comment by ccea-dev-team** [comment]
Hi, we set up the application access policy as in the link above but we are still getting the ODataError.  Can someone check if they can create OnlineMeetings through the OnlineMeeting endpoint?  The error we are getting does not provide any useful information.  When we use the Event endpoint to create an Online Meeting everything works fine, we are just having problems with the OnlineMeeting endpoint (which we need to use to set a meeting co-organizer - can't be done through the Event endpoint)

            OnlineMeeting onlineMeeting = new OnlineMeeting();
		OffsetDateTime startDateTime = OffsetDateTime.parse("2024-03-01T19:00:00.0000000+00:00");
		onlineMeeting.setStartDateTime(startDateTime);
		OffsetDateTime endDateTime = OffsetDateTime.parse("2024-03-01T20:00:00.0000000+00:00");
		onlineMeeting.setEndDateTime(endDateTime);
		onlineMeeting.setSubject("Auto test");
		
		try 
		{
			OnlineMeeting result = graphClient.users().byUserId(emailOfMeetingOwner).onlineMeetings().post(onlineMeeting);
			
			System.out.println(result.getId());
		}
		catch(ODataError ex)
		{
			if(ex.getError() != null)
			{
				System.out.println("Error code: " + ex.getError().getCode());
			}
			else
			{
				System.out.println("Error code is null");
			}
			
			System.out.println("Response status code: " + ex.getResponseStatusCode());
			
			System.out.println("Error message: " + ex.getMessage());
			
			ex.printStackTrace();
		}


2024-02-27 16:36:42.573  INFO 16148 --- [nio-8080-exec-4] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2024-02-27 16:36:42.574  INFO 16148 --- [nio-8080-exec-4] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2024-02-27 16:36:43.343  INFO 16148 --- [nio-8080-exec-4] ccea.onlinemeetings.msgraph.BaseGraph    : Initialising Graph Client
Error code: UnknownError
Response status code: 404
Error message: null
com.microsoft.graph.models.odataerrors.ODataError: 
	at com.microsoft.graph.models.odataerrors.ODataError.createFromDiscriminatorValue(ODataError.java:36)
	at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:210)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.lambda$throwIfFailedResponse$0(OkHttpRequestAdapter.java:672)
	at com.microsoft.kiota.ApiExceptionBuilder.<init>(ApiExceptionBuilder.java:26)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.throwIfFailedResponse(OkHttpRequestAdapter.java:671)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:279)
	at com.microsoft.graph.users.item.onlinemeetings.OnlineMeetingsRequestBuilder.post(OnlineMeetingsRequestBuilder.java:120)
	at com.microsoft.graph.users.item.onlinemeetings.OnlineMeetingsRequestBuilder.post(OnlineMeetingsRequestBuilder.java:104)
	at ccea.onlinemeetings.msgraph.MeetingsGraph.createEventForUser(MeetingsGraph.java:64)
	at ccea.onlinemeetings.webservice.impl.MeetingWebServiceImpl.createOnlineMeetings(MeetingWebServiceImpl.java:63)

**Comment by ccea-dev-team** [comment]
Got to the bottom of this eventually - the user we were trying to create an online meeting for didn't have a license in azure.

**Comment by baywet** [comment]
Thanks for the follow-up, it shouldn't be different, services are mandated to enable support for both the UPN and the id when receiving user related requests.
Since this is not an SDK issue but a service issue, I'll go ahead and close it (the service teams are not monitoring our repositories)
I strongly suggest that you open a support ticket showing the difference in behaviour in Graph Explorer (so the support doesn't end up re-routing you here believing it's an SDK issue).
As an alternative, you can try posting to the [dedicated Microsoft Q&A forum](https://learn.microsoft.com/en-us/answers/tags/282/microsoft-graph-teamwork-api/) which the service team is monitoring.
Closing.

**Comment by ccea-dev-team** [comment]
Yeah reading the documentation for online meeting it does say it needs the object id so I guess I should have read that closely - easy to miss and different from some other endpoints.

![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/99395943/f0e0cd96-31b6-404c-bf14-19b96ac7d20b)

**Comment by baywet** [comment]
I also took the time to circle back with one of our architects internally. And I stand corrected, *most* but not *all* services will accept a UPN in place of an ID. Supporting both is not a requirement being enforced.
