### ISSUE TITLE
Issues with the imports related to com.microsoft.graph after latest updates i.e. 6.1.X

### ISSUE THREAD

**Issue by ashwani945** [microsoftgraph/msgraph-sdk-java#1838]
These are the following imports that's throwing error after version 6.1.X of com.microsoft.graph groupid
import com.microsoft.graph.authentication.TokenCredentialAuthProvider;
import com.microsoft.graph.models.DriveItemCreateUploadSessionParameterSet;
import com.microsoft.graph.models.DriveItemUploadableProperties;
import com.microsoft.graph.models.UploadSession;
import com.microsoft.graph.requests.GraphServiceClient;
import com.microsoft.graph.tasks.IProgressCallback;
import com.microsoft.graph.tasks.LargeFileUploadTask;

till 5.80.0 the above imports is working fine.

Working dependency--> Old dependency till the imports are working
groupId-->com.microsoft.graph
			artifactId-->microsoft-graph
			version-->5.80.0

Not working dependency--> Latest dependency after which imports are not working
			groupId-->com.microsoft.graph
			artifactId-->microsoft-graph
			version-->6.1.0

Can anyone help me if there is any changes in the structure of imports and if yes then what would be the structure of the above imports

**Comment by Synneks** [comment]
I am having the same issue coming from 5.77.0 -> 6.x.x. None of the imports work anymore.

**Comment by lilylafDSG** [comment]
@Ndiritu it looks like the upgrade guide brings you to a 404 page. Can guidelines for upgrading be found in a different place?

**Comment by Ndiritu** [comment]
Apologies, we changed our default branch recently. Please check this [link](https://github.com/microsoftgraph/msgraph-sdk-java/blob/main/docs/upgrade-to-v6.md#authentication)
