### ISSUE TITLE
Retrieve user photo results in java.time.format.DateTimeParseException: Text '2024-02-21T06:27:37' could not be parsed at index 19

### ISSUE THREAD

**Issue by MaHa6543** [microsoftgraph/msgraph-sdk-java#1839]
Trying to fetch a photo for a user that does not have a photo results in a DateTimeParseException:

![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/102298932/5a719262-f476-41d4-9868-783592d96f56)

### Expected behavior

The ImageNotFoundException should be raised, which seems to be earlier catched:

![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/102298932/9af5f7bf-7cc9-49e3-b687-d03968c4c375)

### Actual behavior

The required time zone for UTC (e.g. +01:00) is missing for the datetime string to parse:

![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/102298932/3ecb74a8-9de0-4124-bc6b-c71811c7ee31)

### Steps to reproduce the behavior

Search for a user without a photo:

this.graphClient
          .users()
          .byUserId(oid)
          .photos()
          .byProfilePhotoId(PHOTO_ID_X_48)
          .content()
          .get();

**Comment by Ndiritu** [comment]
Thanks for reporting this @MaHa6543. This was fixed in version `6.2.1`. Please let me know if you're using this version and still facing the same issue.

**Comment by MaHa6543** [comment]
Thanks for the hint @Ndiritu.
Internally the DateTimeException seems to be thrown furthermore - but as a result I get the OData/ImageNotFoundException. So resolved. Thanks!
