### ISSUE TITLE
The specified filter to the reference property query is currently not supported

### ISSUE THREAD

**Issue by MichalChotvac** [microsoftgraph/msgraph-sdk-java#1841]
### Expected behavior
Groups will be filtered according to query parameters.

### Actual behavior
When filter query parameter used, client throws an exception, also in case if any of below conditions is used alone in filter
```java
The specified filter to the reference property query is currently not supported.
```

### Steps to reproduce the behavior
```java
GroupCollectionResponse collectionResponse = graphServiceClient
        .users()
           .byUserId("user_in_entra")
                  .memberOf()
                          .graphGroup()
                                    .get(
                                              requestConfiguration -> {
                                                     requestConfiguration.queryParameters.filter = "mailEnabled eq false and securityEnabled eq true";
                                              });
```
Lib:

```java
    <dependencies>

        <dependency>
            <groupId>com.microsoft.graph</groupId>
            <artifactId>microsoft-graph</artifactId>
            <version>6.2.1</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.11.1</version>
        </dependency>

    </dependencies>
```

**Comment by baywet** [comment]
Hi @MichalChotvac 
Can you try:
1. Adding a "ConsistencyLevel" to "eventual" header. (through the request configuration lambda)
2. Adding a "Count" to "true" query parameter (same as filter)

Doing so will route your request [to the newer backend service](https://devblogs.microsoft.com/microsoft365dev/build-advanced-queries-with-count-filter-search-and-orderby/) which should support that query.

**Comment by MichalChotvac** [comment]
Hello @baywet Thank you, that worked!
