### ISSUE TITLE
Gradle 6.x isn't able to pick right Guava variant

### ISSUE THREAD

**Issue by GeertZijlmans1** [microsoftgraph/msgraph-sdk-java#1860]
### Expected behavior
That my application builds fine

### Actual behavior
Building app runs into a failure
It complains that it could not resolve the guava library required by the Graph SDK v6.3.0:

> Could not resolve com.google.guava:guava:33.0.0-jre.
>         Required by:
>             project :ourapp > com.microsoft.graph:microsoft-graph:6.3.0

Trough transitive dependency it will complain that it is unable to select the correct variant for Guava:

> Failed to build and package the app, because: 
> 	AmbiguousConfigurationSelectionException: Cannot choose between the following variants of com.google.guava:guava:33.0.0-jre:
>   - androidRuntimeElements
>   - jreRuntimeElements
> All of them match the consumer attributes:
>   - Variant 'androidRuntimeElements' capabilities com.google.collections:google-collections:33.0.0-jre and com.google.guava:guava:33.0.0-jre:
>       - Unmatched attributes:
>           - Provides org.gradle.category 'library' but the consumer didn't ask for it
>           - Provides org.gradle.dependency.bundling 'external' but the consumer didn't ask for it
>           - Provides org.gradle.jvm.environment 'android' but the consumer didn't ask for it
>           - Provides org.gradle.jvm.version '8' but the consumer didn't ask for it
>           - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
>           - Provides org.gradle.status 'release' but the consumer didn't ask for it
>           - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
>   - Variant 'jreRuntimeElements' capabilities com.google.collections:google-collections:33.0.0-jre and com.google.guava:guava:33.0.0-jre:
>       - Unmatched attributes:
>           - Provides org.gradle.category 'library' but the consumer didn't ask for it
>           - Provides org.gradle.dependency.bundling 'external' but the consumer didn't ask for it
>           - Provides org.gradle.jvm.environment 'standard-jvm' but the consumer didn't ask for it
>           - Provides org.gradle.jvm.version '8' but the consumer didn't ask for it
>           - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
>           - Provides org.gradle.status 'release' but the consumer didn't ask for it
>           - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it

### Steps to reproduce the behavior
* Install Gradle 6.x (e.g. 6.8.3) 
* Create an application and add the Graph SDK v6.3.0 as a dependency.

**Comment by baywet** [comment]
Thanks for reporting this. I think this is a miss on our side. One of the benefits of this newer version is that it doesn't depend on guava, and the dependency should have been removed (probably a bad merge at some point)

Here are the places it needs to be removed
- https://github.com/microsoftgraph/msgraph-sdk-java/blob/0b01ad52da7cd4eb904e5e7550ed8e76d1c82e09/gradle/dependencies.gradle#L2
- https://github.com/microsoftgraph/msgraph-sdk-java/blob/0b01ad52da7cd4eb904e5e7550ed8e76d1c82e09/pom.xml#L22
- https://github.com/microsoftgraph/msgraph-sdk-java/blob/0b01ad52da7cd4eb904e5e7550ed8e76d1c82e09/README.md?plain=1#L25
- https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/5e0137b10100ad769386bfaa2fc551afb0c233c5/pom.xml#L26

Would you be willing to submit pull requests to address this?

**Comment by GeertZijlmans1** [comment]
@baywet Do I understand you correctly that I need to make these changes to the SDK? And create a pull request for you to review and merge?

**Comment by baywet** [comment]
Correct

**Comment by GeertZijlmans1** [comment]
@baywet I don't have write access and therefore cannot publish my local branch.

**Comment by baywet** [comment]
@GeertZijlmans1 [fork](https://github.com/microsoftgraph/msgraph-sdk-java/fork) the repository first, add this new origin to your local repository, and push that branch to your fork instead :)

**Comment by GeertZijlmans1** [comment]
@baywet Will do that :) instead ... just figuring out your development process

**Comment by baywet** [comment]
This is a skill you'll use for years to come as [forking and submitting a pull request](https://davidsmatlak.github.io/git-fork-pull-request) is a coming practice across open source development.

**Comment by GeertZijlmans1** [comment]
Right. That said I've created two Pull Requests:

- https://github.com/microsoftgraph/msgraph-sdk-java/pull/1869
- https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/1530

**Comment by baywet** [comment]
perfect! you just need to sign the CLA on the first one and we should be good to merge those!

**Comment by GeertZijlmans1** [comment]
Signed the CLA.

**Comment by baywet** [comment]
perfect!
Would you mind submitting a third pull request to the beta SDK as well while at it please?
https://github.com/search?q=repo%3Amicrosoftgraph%2Fmsgraph-beta-sdk-java%20guava&type=code

**Comment by GeertZijlmans1** [comment]
Added a Pull Request for the beta SDK: https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/896
