### ISSUE TITLE
Pass a delta token to the call with 6.x

### ISSUE THREAD

**Issue by slowcar** [microsoftgraph/msgraph-sdk-java#1870]
We are performing a delta call to the users endpoint.
However, the documentation does not mention how to set the deltatoken on subsequent requests.
Documentation: https://learn.microsoft.com/en-us/graph/api/user-delta?view=graph-rest-1.0&tabs=java
Call in Graph Explorer:
https://graph.microsoft.com/v1.0/users/microsoft.graph.delta()?$deltatoken=yAcBzbMbxpy[...]

Code:
`DeltaGetResponse deltaGetResponse = graphClient.users().delta().get(getRequestConfiguration -> {
	getRequestConfiguration.queryParameters.select = new String[]{"id"};
});`

### Expected behavior

I would expect 
getRequestConfiguration.queryParameters
to expose a deltalink parameter

### Actual behavior

there is no deltalink parameter

### Steps to reproduce the behavior

try to execute a delta call with an existing deltalink

**Comment by slowcar** [comment]
An additional question would be: How do i retrieve the deltalink using the PageIterator mechanism?
The (initial) DeltaGetResponse does not contain the deltalink, it has only the @odata.nextLink parameter, and i have not found a way to call the "next page" manually.
The PageIterator exposes only the User objects, but not the deltalink.

**Comment by baywet** [comment]
Have you tried the following:
```java
// 1 get the delta link from the previous response
String deltaLink = deltaGetResponse.getOdataDeltaLink();
// 2 use the delta link to query for more potential changes
DeltaGetResponse deltaGetResponse2 = graphClient.users().delta().withUrl(deltaLink).get()
```

**Comment by slowcar** [comment]
Thank you for the explaination, creating the request this way works.

I guess i cannot use the PageIterator for delta requests and have to create new calls with the OdataNextLink manually as before?
