### ISSUE TITLE
Version 6.4.0 Not able to serialise CallRecord Object.

### ISSUE THREAD

**Issue by priya2395** [microsoftgraph/msgraph-sdk-java#1879]
### Expected behavior

Proper Serialisation of Call Record object into Json string.

### Actual behavior

CallRecord Object getting serialised to  empty json string "{}"

### Steps to reproduce the behavior

```java

   final GraphServiceClient graphServiceClient = new GraphServiceClient(TestData.MSGraphTestData.clientSecretCredential(),
                TestData.MSGraphTestData.DEFAULT_SCOPE);

  final CallRecord callRecord = graphServiceClient
                .communications()
                .callRecords()
                .byCallRecordId(callRecordId)
                .get();
                
 try (SerializationWriter writer = graphServiceClient
                .getRequestAdapter()
                .getSerializationWriterFactory()
                .getSerializationWriter(MediaType.APPLICATION_JSON_VALUE)) {
         writer.writeObjectValue("", callRecord);
         try (InputStream stream = writer.getSerializedContent()) {
               final String json =  new String(Compatibility.readAllBytes(stream), StandardCharsets.UTF_8);
                System.out.println(json);
         }
} catch (final Exception e) {
            System.out.println(e);
           
}
            

```

**Comment by priya2395** [comment]
Can someone please help with this ?

**Comment by priya2395** [comment]
@ramsessanchez 
Can you please help with this ?

**Comment by baywet** [comment]
Hi @priya2395 
Thanks for using the SDK and for reaching out.
This is expected, by default only the changed properties will be serialized.

adding this line before you call the writeObjectValue method should solve your issue.

```java
callRecord.getBackingStore().setReturnOnlyChangedValues(false):
```

**Comment by priya2395** [comment]
Hi @baywet 
Its already false.
Still its not working.
I observed that the serialised is not able to serialise the fields with value0 as false in InMemoryBackingStorePair.
I am setting sessions using setSessions method in callRecord. So its value0 is coming as true and its getting serialised. But all others have value0 as false and are not getting serialised.
 Please find the screenshot attached.
<img width="819" alt="Screenshot 2024-03-12 at 10 13 54 PM" src="https://github.com/microsoftgraph/msgraph-sdk-java/assets/25197740/6aa67c4b-e7ce-468d-9473-539a2cab617b">

**Comment by priya2395** [comment]
If I serialise using jackson or any other serialiser, I am getting json structure with backingstore, fieldSerialisers, additionalData etc.
However, I want a json structure similiar to postman API response. So using the default serialiser in graphserviceClient.
Can you please help with this?

**Comment by priya2395** [comment]
Hello team,

Can someone please help with this issue ?

**Comment by baywet** [comment]
The Serialization methods from those two classes probably need additional overloads that accept a boolean parameter "SerializeUnchangedFields"
https://github.com/microsoft/kiota-java/blob/main/components/abstractions/src/main/java/com/microsoft/kiota/serialization/KiotaJsonSerialization.java
https://github.com/microsoft/kiota-java/blob/main/components/abstractions/src/main/java/com/microsoft/kiota/serialization/KiotaSerialization.java

Whenever this boolean parameter is passed to true, we'd need a coroutine that'd recursively walk the tree and flip the backing store setting so the user (you) don't have to do it yourself.

Is that something you're interested in sending a pull request for?

**Comment by priya2395** [comment]
@baywet 
For the quick solution, is it fine if we use  new JsonSerializationWriter() instead of graphServiceClient .getRequestAdapter().getSerializationWriterFactory().getSerializationWriter(MediaType.APPLICATION_JSON_VALUE) ?

Its serialising all properties not just the changed ones. However ms graph sdk has kiota-serialisation library as runtime dependency. So, we need to add it as compile time dependency separately in our project.

Just wanted to check if cause dependency version conflict ?

**Comment by baywet** [comment]
That's a good workaround and it shouldn't cause any issues.
For other readers, by instantiating a new factory/writer, you don't get the proxies injected by the backing store, and so all backing store behaviour is disabled on those serializers when they are used.
