### ISSUE TITLE
Deserialization/Serialization error of User & Group objects in Graph v6.4 with Java SDK

### ISSUE THREAD

**Issue by mahiarmody** [microsoftgraph/msgraph-sdk-java#1886]
**Deserialization of Graph _User_ object will result in the following stack trace:**
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.microsoft.kiota.store.BackingStore` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (String)"{"backingStore":{"isInitializationCompleted":true,"returnOnlyChangedValues":false},"events":null,"settings":null,"displayName":"xxx, yyyyy zzzz","userPrincipalName":"aa@compay.org","state":null,"drive":null,"calendar":null,"country":null,"extensions":null,"authentication":null,"deviceManagementTroubleshootingEvents":null,"manager":null,"jobTitle":"My Title","department":null,"accountEnabled":null,"fieldDeserializers":{"scopedRoleMemberOf":{},"@odata.type":{},"companyNam"[truncated 5261 chars]; line: 1, column: 17] (through reference chain: com.microsoft.graph.models.User["backingStore"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1915)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:414)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1360)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:274)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
	at com.xxx.yyy.general.GraphObjectSerializationDeserializationTest.testUserObjectDeserialized(GraphObjectSerializationDeserializationTest.java:87)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Serialization of _Group_ object results in the following stacktrace:**
```
com.fasterxml.jackson.databind.JsonMappingException: Array must have size 1, but has size 0 (through reference chain: com.microsoft.graph.models.Group["additionalData"]->java.util.HashMap["creationOptions"]->com.google.gson.JsonArray["asInt"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:323)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:780)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:808)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4719)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3964)
	at com.xxx.yyyy.general.GraphObjectSerializationDeserializationTest.testGroupObjectSerialized(GraphObjectSerializationDeserializationTest.java:72)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.IllegalStateException: Array must have size 1, but has size 0
	at com.google.gson.JsonArray.getAsSingleElement(JsonArray.java:236)
	at com.google.gson.JsonArray.getAsInt(JsonArray.java:342)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	... 16 more
```

**Graph _Group_ object deserialization can't be tested because I'm unable to successfully serialize the Graph _Group_ object to JSON, which is required to test the deserialization .**

### Expected behavior
The serialization and deserialization processes work and give JSON from the Microsoft objects and visa versa.

### Actual behavior
Exceptions thrown during serialization and deserialization.

### Steps to reproduce the behavior
In the test cases below, the Jackson ObjectMapper object named _objMapper_ is created like so:
```java
ObjectMapper objMapper = new ObjectMapper();
objMapper.registerModule(new JavaTimeModule()); 
```

In the test cases below, the _GraphServiceClient_ object named _graphClient_ is created as detailed in link:
[https://learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=java#using-a-client-certificate-2](https://learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=java#using-a-client-certificate-2)

**User deserialization test case to produce the above-mentioned exception stacktrace:**
```java
@Test
public void testUserObjectDeserialized() throws JsonProcessingException
{
	String userId = "e...............";
			
	User expectedUsr = graphClient.users().byUserId(userId).get();		
	String userJson = objMapper.writeValueAsString(expectedUsr);
		
	User actualUsr = objMapper.readValue(userJson, User.class); // above exception thrown here
		
	Assertions.assertEquals(expectedUsr.getUserPrincipalName(), actualUsr.getUserPrincipalName(), "expected upn differes");
}
```

**Group serialization test case to produce the above-mentioned exception stacktrace:**
```java
@Test
public void testGroupObjectSerialized() throws JsonProcessingException
{
	String grpId = "0f.........";
	String expectedDispNm = "bla bla bla";
		
	Group grp = graphClient.groups().byGroupId(grpId).get();
		
	String grpJson = objMapper.writeValueAsString(grp); //above exception thrown here
		
	Assertions.assertTrue(grpJson.contains(expectedDispNm), "expected disp name not found");
}
```

**Comment by baywet** [comment]
Hi @mahiarmody 
I'm not sure why you're trying to use jackson since:
- the implementation using gson
- models implement auto-serialization to avoid using reflection and being tied to a specific serialization library

Have you tried using the methods available here instead?

https://github.com/microsoft/kiota-java/blob/main/components/abstractions/src/main/java/com/microsoft/kiota/serialization/KiotaJsonSerialization.java

**Comment by mahiarmody** [comment]
Thank you for your reply. I was not aware of `KiotaJsonSerialization.java`. Is there any documentation, tutorial, or some java doc that you could point me to for using it (rather than reading the source code)? The reason for using Jackson is because the rest of code in the project is using Jackson.  With Graph version 5.x the code had no issues with Jackson. So, I was not aware that Graph version 6.x did not support Jackson anymore but only gson. That's good to know. Thank you.

So, if I swap out Jackson for gson things should work ok without the need for explicitly using `KiotaJsonSerialization`? Please let me know.

Thank you very much.

**Comment by baywet** [comment]
unfortunately our documentation is lagging behind and this topic is missing. I just created another issue in our documentation repository https://github.com/MicrosoftDocs/openapi-docs/issues/64

No, you need to explicitly use those methods, again auto-serialization only works on its own, it isn't compatible with "annotated serialization" which is what Gson/jackson do

**Comment by mahiarmody** [comment]
Thank you for clarifying. I'm unable to serialize the _User_ and _Group_ Graph objects. This is what I'm doing:
```
Group grp = graphClient.groups().byGroupId(grpId).get();
String grpJson = KiotaJsonSerialization.serializeAsString(grp);
System.out.println(grpJson);
```
However, the output is always: `{}`. I've checked that the returned _grp_ Group object is correctly returned and is correctly filled  with data. However, after serialization via `KiotaJsonSerialization.serializeAsString(grp);` only an empty JSON object is returned viz. `{}`. 

Similarly, if I do the following instead:
```
try(BufferedInputStream bis = new BufferedInputStream(KiotaJsonSerialization.serializeAsStream(grp)))
{
	byte[] allBytes = bis.readAllBytes();
	String grpJson = new String(allBytes, StandardCharsets.UTF_8);
	System.out.println(grpJson);
}
```
I still get `{}` as the JSON serialized Group object.

Same behavior is observed when attempting to serialize a Graph _User_ object. The serialized Graph _User_ object is also, always returned as `{}`.

Why is this happening? What am I doing wrong? Could you please tell me.
Thank you.

**Comment by baywet** [comment]
This is expected behaviour, the serializer will only serialize changed properties when a model has been retrieved from the service.
You can see the details in #1879, but effectively you'd need to instantiate the JsonSerializationWriter directly, and call writeObject.
A bit more work, but it should do the trick.

**Comment by mahiarmody** [comment]
I'm unable to find the Maven dependency to get the `JsonSerializationWriter`. Could you please point me to the name of the dependency that I need to include in my `pom.xml` file.

Currently I have:
```
<dependency>
	<groupId>com.microsoft.graph</groupId>
	<artifactId>microsoft-graph</artifactId>
	<version>6.4.0</version>
</dependency>
<dependency>
	<groupId>com.azure</groupId>
	<artifactId>azure-identity</artifactId>
	<version>1.11.3</version>
</dependency>
```
What other dependencies do I need to download to get the `JsonSerializationWriter`. Please let me know. Thank you.

**Comment by mahiarmody** [comment]
Ok, looking reading [bug# 1879](https://github.com/microsoftgraph/msgraph-sdk-java/issues/1879) more carefully, I came across your comment:

>  However ms graph sdk has kiota-serialisation library as runtime dependency. So, we need to add it as compile time dependency separately in our project.

That statement provided the solution. All I really needed to do was update the `pom.xml` like so:
```
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>com.microsoft.kiota</groupId>
			<artifactId>microsoft-kiota-serialization-json</artifactId>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
```
Adding in the above _&lt;dependencyManagement&gt;_ tag fixed it. Also, it looks like for each serilalization call, a new `JsonSerializationWriter` object is to be instantiated and closed. Could you please confirm or refute this.

Also, if a new `JsonSerializationWriter` object does not need to be instantiated, could you please tell me if `JsonSerializationWriter` objects are thread-safe? I don't think so, as nothing in the source indicates any kind of concurrency support. However, it would be best if you could let me know.

Thank you.

**Comment by baywet** [comment]
> Adding in the above <dependencyManagement> tag fixed it. Also, it looks like for each serilalization call, a new JsonSerializationWriter object is to be instantiated and closed. Could you please confirm or refute this.

correct

> Also, if a new JsonSerializationWriter object does not need to be instantiated, could you please tell me if JsonSerializationWriter objects are thread-safe?

Are you planning to have multiple thread access a single instance? I'm not sure why you'd do that? (doesn't bring any benefit as far as I can tell). I'd keep those instances short-lived, in the scope of a method (static or not).

**Comment by mahiarmody** [comment]
Thank you for your reply. The reason for the concurrency question was that I'm using the `JsonSerializationWriter` object in a custom Jackson serializer, which will be used concurrently. Restricting the `JsonSerializationWriter` object to method avoids the concurrency problem. This answers all my questions.

For the benefit of those who encounter the same bug, here are the steps that I took to resolve the serialization & deserialization issues when using Microsoft Graph version 6.4.0 with Java and Jackson. Here's what needs to be done.

1. Update the `pom.xml` to include the _com.microsoft.kiota:microsoft-kiota-serialization-json:jar:1.0.4_ as a compile dependency rather than just a runtime dependency.
2. Create custom Jackson serializers and deserializers for all the Graph objects like _User_ and _Group_ that wrap the corresponding Microsoft serializers & deserializers.
3. Upon creating the Jackson ObjectMapper object, register all the custom serializers and deserializers.

That should get you going.

So here's what the `pom.xml` should look like (showing only the relevant parts of the pom.xml below):
```
<!--
The following <dependencyManagement> tag is needed only to ensure that the scope of
the "com.microsoft.kiota:microsoft-kiota-serialization-json:jar:1.0.4" dependency
is changed from the default scope of "runtime" to "compile".
This is needed to ensure that the "JsonSerializationWriter" object can be instantiated
in code for use in the custom Jackson serializer.
A custom Jackson serializer is needed because Microsoft Graph version 6.4.0 objects like
"User" and "Group" can no lnoger be directly serialized / deserialized via Jackson. This
was possible in the previous versions of Graph. Such objects must only be serialized via the
"JsonSerializationWriter" and deserialized via the "KiotaJsonSerialization.deserialize()"
method.
See:
https://github.com/microsoftgraph/msgraph-sdk-java/issues/1886
-->
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>com.microsoft.kiota</groupId>
			<artifactId>microsoft-kiota-serialization-json</artifactId>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
	
<dependencies>
	<!-- Start Azure Cloud dependencies
	See: https://docs.microsoft.com/en-us/graph/sdks/sdk-installation#install-the-microsoft-graph-java-sdk
	-->
	<dependency>
		<groupId>com.microsoft.graph</groupId>
		<artifactId>microsoft-graph</artifactId>
		<version>6.4.0</version>
	</dependency>
	<dependency>
		<groupId>com.azure</groupId>
		<artifactId>azure-identity</artifactId>
		<version>1.11.3</version>
	</dependency>
	<!-- End Azure cloud dependencies -->
</dependencies>
```

Next, create the custom Jackson serializers. I'm showing only the Graph _Group_ object serializer here. The Graph _User_ object serializer will be similarly written.

```
package com.xx.yy.utils;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.microsoft.graph.models.Group;
import com.microsoft.kiota.serialization.JsonSerializationWriter;

public class JacksonGraphGroupSerializer extends StdSerializer<Group>
{
	private static final long serialVersionUID = 1L;

	public JacksonGraphGroupSerializer()
	{
		super(Group.class);
	}

	@Override
	public void serialize(Group graphGroupObj, JsonGenerator jsonGen, SerializerProvider serialProv) throws IOException
	{
		try(JsonSerializationWriter jsw = new JsonSerializationWriter())
		{
			jsw.writeObjectValue(null, graphGroupObj, new Group[0]);
				
			try(BufferedInputStream bis = new BufferedInputStream(jsw.getSerializedContent()))
			{
				byte[] allBytes = bis.readAllBytes();
				String grpJson = new String(allBytes, StandardCharsets.UTF_8);
		
				jsonGen.writeRaw(grpJson);
			}
		}
	}
}
```

Next, create the custom Jackson deserializers. I'm showing only the Graph _Group_ object deserializer here. The Graph _User_ object deserializer will be similarly written.
```
package com.xx.yyy.utils;

import java.io.IOException;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.microsoft.graph.models.Group;
import com.microsoft.kiota.serialization.KiotaJsonSerialization;

public class JacksonGraphGroupDeserializer extends StdDeserializer<Group>
{
	private static final long serialVersionUID = 1L;
	
	public JacksonGraphGroupDeserializer()
	{
		super(Group.class);
	}
	

	@Override
	public Group deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException
	{
		if(jp.getCurrentToken() == JsonToken.START_OBJECT)
		{
			jp.nextToken();
		}
		
		JsonNode jn = jp.getCodec().readTree(jp);
		
		String jsonGroupStr = jn.toString();
		
		Group graphGroupObj = KiotaJsonSerialization.deserialize(jsonGroupStr, Group::createFromDiscriminatorValue);
		
		return graphGroupObj;
	}
}
```

Next, register all the custom serilaizers and deserializers in the Jackson ObjectMapper object like so:
```
public ObjectMapper jsonObjectMapper()
{
	/*
	Now to handle the correct serialization and deserialization of Graph version 6.4.0 "User"
	and "Group" objects. Graph version 6.4.0 objects cannot be serialized/deserialized via
	Jackson directly. Thus, custom Jackson serializers and deserializers are needed to
	wrap the Microsoft specific serializers and deserializers.
	See:
	https://github.com/microsoftgraph/msgraph-sdk-java/issues/1886
	*/
	SimpleModule simpleModule = new SimpleModule();
	simpleModule.addDeserializer(User.class, new JacksonGraphUserDeserializer());
	simpleModule.addDeserializer(Group.class, new JacksonGraphGroupDeserializer());
	simpleModule.addSerializer(User.class, new JacksonGraphUserSerializer());
	simpleModule.addSerializer(Group.class, new JacksonGraphGroupSerializer());
	
	/*
	Mapper instances are fully thread-safe provided that ALL configuration of the instance occurs before ANY read or write calls
	See:
	https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/ObjectMapper.html
	*/
	ObjectMapper objMapper = new ObjectMapper();
	objMapper.registerModules(new JavaTimeModule(), simpleModule);
	return objMapper;
}
```

That should be it. Now you can directly use Graph 6.4.0 with Jackson just like before.
Serialization test case now works:
```
@Test
public void testGroupObjectSerialized() throws IOException
{
	String grpId = "0fxxxxxx-xxxxxx-xxxxx-xxx";
	String expectedDispNm = "Foo - Bar";
		
	Group grp = graphClient.groups().byGroupId(grpId).get();
		
	String grpJson = objMapper.writeValueAsString(grp);
		
	Assertions.assertTrue(grpJson.contains(expectedDispNm), "expected disp name not found");
}
```

Deserialization test case now works:
```
@Test
public void testGroupObjectDeserialized() throws JsonProcessingException
{
	String grpId = "0fxxxxxx-xxxxxx-xxxxx-xxx";
			
	Group expectedGrp = graphClient.groups().byGroupId(grpId).get();
	String grpJson = objMapper.writeValueAsString(expectedGrp);
		
	Group actualGrp = objMapper.readValue(grpJson, Group.class);
		
	Assertions.assertEquals(expectedGrp.getDisplayName(), actualGrp.getDisplayName(), "expected display names differ");
}
```

For those of you who use Spring Boot and WebFlux, if you choose to test your handler functions with `WebTestClient` then you would need to explicitly register the auto-configured _ObjectMapper_ bean, in the _WebTestClient_ used for the test case. Here's what worked for me:

```
@BeforeAll
public static void setup()
{
	int memBufferSizeInBytes = Integer.MAX_VALUE;
	
	webTestClient = WebTestClient
		.bindToRouterFunction(userRouter)
		//.bindToApplicationContext(context)
		//.apply(SecurityMockServerConfigurers.springSecurity()) //apply Spring security. Pointless when not bound to ApplicationContext
		//See: https://gist.github.com/tuzhms/b1e9c616049f40c964fd4854d659047e
		.handlerStrategies(
			HandlerStrategies.builder().codecs(clientCodecConfigurer ->
				{
					ServerDefaultCodecs sdc = clientCodecConfigurer.defaultCodecs();
					sdc.jackson2JsonDecoder(new Jackson2JsonDecoder(objMapper));
					sdc.jackson2JsonEncoder(new Jackson2JsonEncoder(objMapper));
				}).build()
		)
		.configureClient()
		.exchangeStrategies(
				ExchangeStrategies.builder().codecs( clientCodeConfigurer ->
						clientCodeConfigurer.defaultCodecs().maxInMemorySize(memBufferSizeInBytes) //done so that large return types don't cause Spring memory issues.
					).build()
				)
		.responseTimeout(Duration.ofSeconds(60))
		.build();
}
```

I hope this helps someone else.

**Comment by mahiarmody** [comment]
Reopening this issue just so that it can show up in Google searches. No point having provided the whole solution, when it does not show up in Google searches.

**Comment by baywet** [comment]
@mahiarmody thanks for providing the solution here.
Since there's no outstanding work here, I have closed it again.
It reduces the clutter and makes it much easier to identify what still needs attention.
