### ISSUE TITLE
Unable to upload a file when file size is specified in the request body

### ISSUE THREAD

**Issue by varunrathi1910** [microsoftgraph/msgraph-sdk-java#1896]
Hi,
I am unable to upload a file via the Microsoft Graph Java SDK when file size is specified in the request body.

Code : 

```java
DriveItemUploadableProperties driveItemUploadableProperties = new DriveItemUploadableProperties();
Optional.ofNullable("fileSize").ifPresent(driveItemUploadableProperties::setFileSize);

CreateUploadSessionPostRequestBody createUploadSessionPostRequestBody = new CreateUploadSessionPostRequestBody();
Optional.ofNullable(driveItemUploadableProperties).ifPresent(createUploadSessionPostRequestBody::setItem);

CreateUploadSessionRequestBuilder request = graphServiceClient.drives().byDriveId("driveId").items().byDriveItemId("itemid").createUploadSession();

UploadSession uploadSession = request.post(createUploadSessionPostRequestBody, requestConfiguration ->{
	requestConfiguration.headers.add("header-key", "header-value");
}));
 // actual code to upload the file
```

However, if the filesize is specified as an additional data, issue isn't thrown.

**Comment by baywet** [comment]
Hi @varunrathi1910 
Thanks for reaching out and for using the Graph SDK.
Which OneDrive are you trying to upload files to? Personal or for busines?

**Comment by varunrathi1910** [comment]
Hi @baywet,
We are using Sharepoint.

Furthermore, according to the learn Microsoft documentation, the request body is required in the below format:
{
  "@microsoft.graph.conflictBehavior": "fail (default) | replace | rename",
  "description": "description",
  "driveItemSource": { "@odata.type": "microsoft.graph.driveItemSource" },
  "fileSize": 1234,
  "name": "filename.txt",
  "mediaSource": { "@odata.type": "microsoft.graph.mediaSource" }
}

However, the fileSize property is being set in the "item" key, something like : 
{
    "item":{
        "fileSize": 1234
    }
}

**Comment by baywet** [comment]
Thanks for the additional information and your patience.
Can you please share the JSON payload that's working and the one that's not? I'm failing to understand what's the issue here.
