### ISSUE TITLE
Strange notification-behavior from Exchange in certain scenarios

### ISSUE THREAD

**Issue by GeertZijlmans1** [microsoftgraph/msgraph-sdk-java#1899]
### Context

We see some strange notification behavior in our application for certain scenarios

#### Room Resource A
We have configured a Room Resource with the following Calendar Processing configuration:
`Set-CalendarProcessing -Identity <Resource’s email address>
-AutomateProcessing AutoUpdate
-DeleteSubject $false
-AddOrganizerToSubject $false
-AllowConflicts $true
-EnforceSchedulingHorizon $false
-MaximumDurationInMinutes 0
-RemoveOldMeetingMessages $false (for In-the-Lead)
-RemovePrivateProperty $false
-BookingWindowInDays 900​​​​​​​`

In our application we have subscribed ourselves to **"created"** events happening in the **Inbox** folder of the Room Resource

Also we set the Organization Config in Exchange
`Set-OrganizationConfig -VisibleMeetingUpdateProperties "Location,Subject,Sensitivity"`

#### Room Resource B
We have configured a Room Resource with the following Calendar Processing configuration:
`Set-CalendarProcessing -Identity <Resource’s email address>
-AutomateProcessing AutoAccept
-DeleteSubject $false
-AddOrganizerToSubject $false
-AllowConflicts $true
-EnforceSchedulingHorizon $false
-MaximumDurationInMinutes 0
-RemoveOldMeetingMessages $true
-RemovePrivateProperty $false
-BookingWindowInDays 900​​​​​​​`

In our application we have subscribed ourselves to **"created,updated,deleted"** events happening in the **Calendar** folder of the Room Resource

#### Room Resource C with delegation of requests
We have configured a Room Resource with the following Calendar Processing configuration:
`Set-CalendarProcessing -Identity <Resource’s email address>
-AutomateProcessing AutoAccept
-DeleteSubject $false
-AddOrganizerToSubject $false
-AllowConflicts $true
-EnforceSchedulingHorizon $false
-MaximumDurationInMinutes 0
-RemoveOldMeetingMessages $true
-RemovePrivateProperty $false
-BookingWindowInDays 900​​​​​​​`

In our application we have subscribed ourselves to **"created,updated,deleted"** events happening in the **Calendar** folder of the Room Resource

#### 1) Use feature **This-and-the-following** for a recurrent Meeting in Room Resource A
1. A User A creates a recurrent Meeting (e.g. 5 occurrences) and selects Room Resource A
2. User A decides that from the third occurrence onwards, using the feature _this-and-the-following_, that the Meeting should take place at a different time period (e.g. and hour later)

#### 2) Use feature **This-and-the-following** for a recurrent Meeting in Room Resource B
1. A User A creates a recurrent Meeting (e.g. 5 occurrences) and selects Room Resource B
2. User A decides that from the third occurrence onwards, using the feature _this-and-the-following_, that the Meeting should take place at a different time period (e.g. and hour later)

#### 3) Approval-flow by delegation using Room Resource C
1. A User A creates a Meeting and selects Room Resource C
2. A User B (who has been configured as the delegate for Room Resource C) accepts the Meeting Request on behalf of Room Resource C

#### 4) Update of a recurrent Meeting that once was a single Meeting
1. A User A creates a Meeting and selects Room Resource A
2. User A decides after creating the Meeting that it should have been a recurrent Meeting and turns the original Meeting into a recurrent Meeting
3. After some time User A updates the time and subject of the recurrent Meeting

#### 1) Use feature **This-and-the-following** for a recurrent Meeting in Room Resource A
1. We receive a notification about an incoming Event Message for the series master
4. We receive three notifications about exceptions for the third, fourth and fifth occurrence OR an update of the original recurrent Meeting and a new recurrent Meeting for the three occurrences.

#### 2) Use feature **This-and-the-following** for a recurrent Meeting in Room Resource B
1. We receive a notification about an incoming Event Message for the series master
2. We receive three notifications about exceptions for the third, fourth and fifth occurrence OR an update of the original Event for the series master and a new Event for the series master of the three occurrences.

#### 3) Approval-flow by delegation using Room Resource C
1. We receive a notification about the Event being created
2. We receive a notification about the Event's response status being changed

#### 4) Update of a recurrent Meeting that once was a single Meeting
1. We receive a notification about an incoming Event Message for the single Meeting
2. We receive a notification about an incoming Event Message for the series master
3. We receive a notification about an Event Message containing an update for the series master

#### 1) Use feature **This-and-the-following** for a recurrent Meeting in Room Resource A
1. We receive a notification about an incoming Event Message for the series master --> OK
2. We receive a notification for a new recurrent Meeting for the three occurrences --> **Not OK** --> It would be OK if prior to receiving the new recurrent Meeting we would get an updated recurrent Meeting for the original recurrent Meeting. I noticed that in the **Deleted Items** folder it shows that the third, fourth and fifth occurrence are cancelled from the original recurrent Meeting, yet we did not receive a notification for a Meeting Cancellation.

#### 2) Use feature **This-and-the-following** for a recurrent Meeting in Room Resource B
1. We receive a notification about an incoming Event for the series master --> OK
2. We receive a notification for a new Event for the series master of the three occurrences --> **Not OK** --> It would be OK if prior to receiving the new Event (representing the series master) we would get an updated Event for the original series master.

#### 3) Approval-flow by delegation using Room Resource C
1. We receive a notification about the Event being created --> OK --> We receive an Event for which the response status is **Tentatively Accepted**
2. We receive a notification about the Event being deleted and right after that that it's updated --> **Not OK** --> We don't expect that the Event gets deleted.

#### 4) Update of a recurrent Meeting that once was a single Meeting
1. We receive a notification about an incoming Event Message for the single Meeting --> OK
2. We receive a notification about an incoming Event Message for the series master --> OK --> The Event ID of the original single Meeting is used as the series master ID so we can correlate that, hence we can conclude that the single Meeting was turned into a recurrent Meeting
3. We receive a notification about an incoming Event Message for a **new** series master --> **Not OK** --> There is no notification about the Cancellation of the other recurrent Meeting (this is done silently)

**Comment by Ndiritu** [comment]
@GeertZijlmans1 thank you for reaching out. 
Unfortunately this repo handles issues specific to the Java SDK and what you describe seems like an API specific issue/clarification.
I recommend posting this in [Microsoft Graph's Q&A](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) to get support from the relevant API team.

**Comment by GeertZijlmans1** [comment]
@Ndiritu
Thanks for redirecting me to the correct Q&A.
For others that want to follow this thread:
https://learn.microsoft.com/en-us/answers/questions/1658803/strange-notification-behavior-from-exchange-in-cer

**Comment by GeertZijlmans1** [comment]
Solution:
I had to update my subscription model such that I also observe new items being created in the Deleted Items folder. As with the above use case Exchange "silently" handles the update of the old recurrence.
