### ISSUE TITLE
Access denied error when trying to send an email using AzureCliCredential

### ISSUE THREAD

**Issue by ppodgorsek** [microsoftgraph/msgraph-sdk-java#1900]
### Expected behavior

The Azure CLI token credential should work like any other credential provider, as described in the official Java SDK documentation for developers: https://learn.microsoft.com/en-us/azure/developer/java/sdk/identity-dev-env-auth#azure-cli-credential

Sending email works correctly with other credential types such as device code or client ID+secret.

### Actual behavior

When trying to send an email, a token is exchanged successfully but the email sending fails with the following error:
> ODataError: Access is denied. Check credentials and try again.

### Steps to reproduce the behavior

Using the latest SDK version (6.4.0), this issue can be reproduced with little code: (simplified for readability)

```java
final String MICROSOFT_GRAPH_SCOPE = "https://graph.microsoft.com";

TokenCredential credential = new AzureCliCredentialBuilder().build();
GraphServiceClient graphServiceClient = new GraphServiceClient(credential, MICROSOFT_GRAPH_SCOPE);

// Checking the permissions before sending the email (see logs below)
OAuth2PermissionGrantCollectionResponse response = graphServiceClient.me().oauth2PermissionGrants().get();
log.debug("Permission grants: {}", response.getValue().stream()
    .map(value -> value.getConsentType() + ":" + value.getScope()).toList());

// Creating the email
SendMailPostRequestBody sendMailPostRequestBody = new SendMailPostRequestBody();
sendMailPostRequestBody.setMessage(createMessage());

// Sending the email fails
graphServiceClient.me().sendMail().post(sendMailPostRequestBody);
```

The following logs can be seen from the code above: (notice `Mail.Send` in the permission grants)

> com.mycompany.example.MicrosoftGraphEmailServiceImpl : Permission grants: [Principal: User.Read openid email profile offline_access, Principal: openid profile offline_access Mail.Send]
> com.azure.identity.implementation.IdentityClient      : Azure CLI Authentication => A token response was received from Azure CLI, deserializing the response into an Access Token.
> com.azure.identity.AzureCliCredential    : Azure Identity => getToken() result for scopes [https://graph.microsoft.com]: SUCCESS

An exception is then thrown:

> Caused by: com.microsoft.graph.models.odataerrors.ODataError: Access is denied. Check credentials and try again.
> 	    at com.microsoft.graph.models.odataerrors.ODataError.createFromDiscriminatorValue(ODataError.java:36)
> 	    at com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:210)
> 	    at com.microsoft.kiota.http.OkHttpRequestAdapter.lambda$throwIfFailedResponse$0(OkHttpRequestAdapter.java:672)
> 	    at com.microsoft.kiota.ApiExceptionBuilder.<init>(ApiExceptionBuilder.java:26)
> 	    at com.microsoft.kiota.http.OkHttpRequestAdapter.throwIfFailedResponse(OkHttpRequestAdapter.java:671)
> 	    at com.microsoft.kiota.http.OkHttpRequestAdapter.sendPrimitive(OkHttpRequestAdapter.java:341)
> 	    at com.microsoft.graph.users.item.sendmail.SendMailRequestBuilder.post(SendMailRequestBuilder.java:58)
> 	    at com.microsoft.graph.users.item.sendmail.SendMailRequestBuilder.post(SendMailRequestBuilder.java:44)

An access token can anyway be fetched successfully using the Azure CLI via the following command: `az account get-access-token --output json --resource "https://graph.microsoft.com"`

**Comment by andrueastman** [comment]
Thanks for raising this @ppodgorsek 

Do you get a different result if you change the scope to "https://graph.microsoft.com/.default"? 

If you fetch the access token using the CLI, are you able to paste it at http://jwt.ms and confirm if the `scp` property has all the excpected claims?

**Comment by ppodgorsek** [comment]
Thanks @andrueastman for your rapid reply!

I tried using "https://graph.microsoft.com/.default", which led to the same result.

Manually checking the JWT token indeed revealed that the `scp` claim type was missing the `Mail.Send` value.
Surprisingly, the token includes permissions which are quite different from what `graphServiceClient.me().oauth2PermissionGrants()` returns:
* `graphServiceClient.me().oauth2PermissionGrants()` => `[Principal: User.Read openid email profile offline_access, Principal: openid profile offline_access Mail.Send]`
* Azure CLI JWT token => `AuditLog.Read.All Directory.AccessAsUser.All email Group.ReadWrite.All openid profile User.ReadWrite.All`

Do you know why there can be such a difference?

This last question might be slightly off-topic as this is the SDK repo, but do you know how I can add the missing claims to Azure CLI, by any chance? (the CLI doesn't appear in Entra ID's app registrations nor enterprise apps)

**Comment by andrueastman** [comment]
> Do you know why there can be such a difference?

I believe permissions are also based on the application registration is use and therefore a user (or tenant admin) has to consent for permissions when using another principal/app. So, a user using one application will have different permissions based on what they consented to than when they call the Api using a different application e.g. Graph Explorer.

> This last question might be slightly off-topic as this is the SDK repo, but do you know how I can add the missing claims to Azure CLI, by any chance? (the CLI doesn't appear in Entra ID's app registrations nor enterprise apps)

Are you by any chance able to try a search on the tenant homepage using the `appid` property value from the decoded token from jwt.ms page? 
<img width="1349" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-java/assets/6464005/cc3b8fb7-4a76-4d2f-b5c7-058951f384f3">

**Comment by andrueastman** [comment]
Thanks for this @ppodgorsek 

We'll close this here for now as this is being followed up in https://github.com/Azure/azure-cli/issues/28628 to identify the credential difference.
