### ISSUE TITLE
Version 6.5: java.lang.ClassNotFoundException: com.microsoft.kiota.serialization.UntypedNode

### ISSUE THREAD

**Issue by vipetrov-bg** [microsoftgraph/msgraph-sdk-java#1906]
### Expected behavior

The exception java.lang.ClassNotFoundException: com.microsoft.kiota.serialization.UntypedNode should not be thrown

The msgraph-sdk-java should use the latest kiota version!

### Actual behavior
java.lang.NoClassDefFoundError: com/microsoft/kiota/serialization/UntypedNode

java.lang.ClassNotFoundException: com.microsoft.kiota.serialization.UntypedNode

### Steps to reproduce the behavior

    TokenCredential tokenCredential = new ClientCertificateCredentialBuilder().tenantId(tenantId)
    .clientId(clientId).pfxCertificate(pfxCertificatePath).clientCertificatePassword(pfxPassword)
    .build();

    String[] scopes = new String[] { "https://graph.microsoft.com/.default" };

    GraphServiceClient graphClient = new GraphServiceClient(tokenCredential, scopes);

    Application app = graphClient.applications().byApplicationId("<my app id>").get();

### Workaround:

Add in pom the latest kiota:

<groupId>com.microsoft.kiota</groupId>
      <artifactId>microsoft-kiota-abstractions</artifactId>
      <version>1.1.2</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.kiota</groupId>
      <artifactId>microsoft-kiota-authentication-azure</artifactId>
      <version>1.1.2</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.kiota</groupId>
      <artifactId>microsoft-kiota-http-okHttp</artifactId>
      <version>1.1.2</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.kiota</groupId>
      <artifactId>microsoft-kiota-serialization-json</artifactId>
      <version>1.1.2</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.kiota</groupId>
      <artifactId>microsoft-kiota-serialization-text</artifactId>
      <version>1.1.2</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.kiota</groupId>
      <artifactId>microsoft-kiota-serialization-form</artifactId>
      <version>1.1.2</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.kiota</groupId>
      <artifactId>microsoft-kiota-serialization-multipart</artifactId>
      <version>1.1.2</version>
    </dependency>

**Comment by baywet** [comment]
Hi @vipetrov-bg 
Thanks for using the SDK and for reporting this.
It's caused by a dependencies misalignment, I've authored #1908 to address that in a new patch release.
