### ISSUE TITLE
What is the reason behind SDK size increase from v6.1 to v6.2?

### ISSUE THREAD

**Issue by GeertZijlmans1** [microsoftgraph/msgraph-sdk-java#1907]
I just noticed that the size of the SDK's jar increased from 11MB to nearly 50MB between v6.1 and v6.2.
What is the cause of this sudden increase in size?

**Comment by baywet** [comment]
Hi @GeertZijlmans1 
Thanks for using the SDK and for reaching out.
This is caused because a lot of the URI templates we were using were actually wrong, fixing the bug in the generator ultimately resulted in more strings being emitted across the SDK.
https://github.com/microsoft/kiota/issues/4148

**Comment by GeertZijlmans1** [comment]
Is there a way to reduce the size of the API in general?
In our case we are using the following sub-APIs of the Graph API:
* Mail API
* Calendar API
* User API

**Comment by baywet** [comment]
If you care about the size of the client, the best thing yet is to generate your own with kiota, the same generator used for this SDK.
You'll get the same exact experience as here, but with only the operations you care about.
https://learn.microsoft.com/en-us/graph/sdks/generate-with-kiota

**Comment by GeertZijlmans1** [comment]
Thanks for the reply. I'll try once to generate my own client using Kiota.

**Comment by GeertZijlmans1** [comment]
Forgot to close
