### ISSUE TITLE
How can I Increase Timeout (v5.80.0)

### ISSUE THREAD

**Issue by cuong02n** [microsoftgraph/msgraph-sdk-java#1910]
When I send PATCH Update for excel range (1200 rows and 60 colums) about 72000 cells. Sometimes it work well, sometimes it returns 504: Unknown Error, and sometimes it returns 504: Timeout. And I know max timeout is 30 second when logging, how can increase it. 

Can I pass it in headers ?

**Comment by baywet** [comment]
Hi @cuong02n 
Thanks for using the java SDK and for reaching out.
Since version 6.x is out, we won't provide support for the 5.x version except for security issues.
Please upgrade and reach out again if you still have issues.
Closing

**Comment by cuong02n** [comment]
@baywet Is there any way to increase MS GRAPH API Internal Timeout in version 6.x?, I will migrate soon.

**Comment by andrueastman** [comment]
@cuong02n I don't believe there is a way to increase the timeout on the API end using a method like headers. 
I would suggest posting the same question at the link below and hopefully get feedback from the Api owners on this.

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
