### ISSUE TITLE
Not able to send attachment with this API https://graph.microsoft.com/v1.0/me/sendMail

### ISSUE THREAD

**Issue by poonamsehjwani** [microsoftgraph/msgraph-sdk-java#192]
Getting 400 Bad Request with error body : "Property attachments in payload has a value that does not match schema."

Trying to upload the attachment as shown below where message is initialized as 
Message message = new Message(); 
and filled other message values like subject, body etc. It is working fine without attachment upload.

final BaseAttachmentCollectionResponse response = new BaseAttachmentCollectionResponse();
        try {
            response.value = Arrays.asList(getFileAttachment());
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        message.attachments = new AttachmentCollectionPage(response, null);
       
    }
  
    private FileAttachment getFileAttachment() throws Exception{
        FileAttachment fileAttachment = new FileAttachment();
        fileAttachment.name = "document.pdf";
        File pdfFile = new File("src/main/resources/document.pdf");
        InputStream fileStream = new FileInputStream(pdfFile);
        fileAttachment.contentBytes = getByteArray(fileStream);
        fileAttachment.oDataType = "#microsoft.graph.fileAttachment";
        return fileAttachment;
}

API used to send the email is : https://graph.microsoft.com/v1.0/me/sendMail
I am not sure where I am doing wrong.

Appreciate your help here..

**Comment by deepak2016** [comment]
@poonamsehjwani thanks for reporting the issue Poonam, we we looking into it and will come back with our findings. Thanks

**Comment by harrbca** [comment]
Hi there, I was wondering if there has been any movement with this issue. It does not look like the proposed changes were merged in.

Thanks.

**Comment by kavitha1051** [comment]
Issue : Unable to send mail with attachment, Any update on this

**Comment by kavitha1051** [comment]
Unable to send mail with attachment using Microsoft graph.

**Comment by wendersonsouza** [comment]
Hi @deepak2016,
 is Microsoft Graph Rest endpoint sendMail  able to send an email with attachments?
I have been using microsoft-graph version 1.7.0 on a java project so I have gotten that erro message :
![image](https://user-images.githubusercontent.com/15347782/86037745-c63bd900-ba37-11ea-90a9-e07969011260.png)

**Comment by baywet** [comment]
Hi everyone,
Thanks for the feedback and the patience on the matter.
I was able to update and review, test and fix PR #202 which never had been merged for some reason and which addresses this issue. It should go out with version 2.1.0, either this week or the following.
Once the PR gets merged, it'll close this issue.
