### ISSUE TITLE
specifying .select causes a 400 : Bad Request

### ISSUE THREAD

**Issue by Krisoblucki-okta** [microsoftgraph/msgraph-sdk-java#193]
### Expected behavior
Specifying .select(FIELDS_TO_RETURN) should return a specific set of fields on each request to post/get/patch

### Actual behavior
400 Bad Request the $select field appears twice in the request url

### Steps to reproduce the behavior
IUserCollectionRequest request = graphServiceClient.users().buildRequest().select(FIELDS_TO_RETURN);
            return request.post(user);

**Comment by Krisoblucki-okta** [comment]
The changes for 1-3 above https://github.com/microsoftgraph/msgraph-sdk-java/pull/197

**Comment by Krisoblucki-okta** [comment]
@NakulSabharwal I also have a change to the MSGraph-SDK-Code-Generator but it's not clear to me what the steps are to satisfy the dependencies.  The changes in this PR would have to go in first, because the generated code would rely on these changes.

**Comment by NakulSabharwal** [comment]
Since this statement `final String requestUrl = getBaseRequest().getBaseUrl();` appends once and then `...buildRequest(getBaseRequest().getOptions())
            .post(newUser);` appends again so I got your solution but instead we can add a function only in BaseRequest.java - 
```
public String getBaseRequestUrl() {
	return this.requestUrl;
} 
```
Then in MSGraph-SDK-Code-Generator we can have 
BaseEntityCollectionRequest - 
    
```
public void post(final <#=TypeName(c)#> new<#=TypeName(c)#>, finaI Callback<<#=TypeName(c)#>> callback) {
    final String requestUrl = getBaseRequest().getBaseRequestUrl();
    new <#=TypeRequestBuilder(c)#>(requestUrl, getBaseRequest().getClient(), /* Options */ null)
        .buildRequest(getBaseRequest().getOptions())
        .post(new<#=TypeName(c)#>, callback);
}

public <#=TypeName(c)#> post(final <#=TypeName(c)#> new<#=TypeName(c)#>) throws ClientException {
    final String requestUrl = getBaseRequest().getBaseRequestUrl();
    return new <#=TypeRequestBuilder(c)#>(requestUrl, getBaseRequest().getClient(), /* Options */ null)
        .buildRequest(getBaseRequest().getOptions())
        .post(new<#=TypeName(c)#>);
}

```

This way first the sdk change will go in and then generator change will go in.

**Comment by Krisoblucki-okta** [comment]
@NakulSabharwal apologies for this taking for ever, it fell off my radar. I rebased the PR, is there anything else that you need from me on this?

**Comment by baywet** [comment]
thanks for your patience on the matter. I just authored https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/281 which fixes the issue by passing only the header options and you can see the resulting code changes in #445 .
This issue will be closed when the PR gets merged.
