### ISSUE TITLE
Unable to fetch the call segments

### ISSUE THREAD

**Issue by sudhamadhuri** [microsoftgraph/msgraph-sdk-java#1938]
I have upgraded the GraphAPI version from v5.80.0 to 6.5.1. Using the guide, I am trying to fetch the call segments within sessions [List sessions - Microsoft Graph v1.0 | Microsoft Learn](https://learn.microsoft.com/en-us/graph/api/callrecords-callrecord-list-sessions?view=graph-rest-1.0&tabs=java) like below: 

graphClient ->
    graphClient
        .communications()
        .callRecords()
        .byCallRecordId(id)
        .sessions()
        .withUrl(odataLink)
        .get(requestConfiguration -> {
requestConfiguration.queryParameters.expand = new String[]{"segments"};
requestConfiguration.headers.add("Prefer", "odata.maxpagesize=" + maxPageSize)
}))

But the GraphAPI threw the error "**Received error Parsing OData Select and Expand failed: Term 'segments)' is not valid in a $select or $expand expression. while calling Graph API resource**"
- Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.
--> I am trying this with graph v6.5.1, core v3.1.7:

1. First fetching the call record first: 
CallRecord res = graphClient
          .communications()
          .callRecords()
          .byCallRecordId(id)
          .get(requestConfiguration ->
              requestConfiguration.headers.add("Prefer", "odata.maxpagesize=" + maxPageSize)
          );

2. Fetching sessions for each callRecord:
graphClient ->
    graphClient
        .communications()
        .callRecords()
        .byCallRecordId(id)
        .sessions()
        .withUrl(odataLink)
        .get(requestConfiguration -> {
requestConfiguration.queryParameters.expand = new String[]{"segments"};
requestConfiguration.headers.add("Prefer", "odata.maxpagesize=" + maxPageSize)
}))

3. Fetching segments for each session by sessionId:
 
graphClient
              .communications()
              .callRecords()
              .byCallRecordId(callRecordId)
              .sessions()
              .bySessionId(sessionId)
              .segments()
              .withUrl(odataLink)
              .get(requestConfiguration -> {
                requestConfiguration.queryParameters.expand = new String[]{"segments"};
                requestConfiguration.headers.add("Prefer", "odata.maxpagesize=" + maxPageSize);
              }));

### Expected behavior
Segment information being fetched along with each session

### Actual behavior
Throwing error that 'segments' expression is not valid in $select or $expand expression in point 2.

### Steps to reproduce the behavior
Get the callRecords and session data with each request

**Comment by Ndiritu** [comment]
Thanks for raising this @sudhamadhuri

Approach 2 & 3 will fail because of using `withUrl(odataLink)`. `withUrl()` overrides everything and sends the request to the URL provided. $select & $expand are not enabled for nextLink URLs. In case I misunderstood your implementation, please clarify.

Do you get an error with approach 1? Would you mind sharing a stacktrace?
