### ISSUE TITLE
Provide the ability to customize the connection timeout values while also allowing default value

### ISSUE THREAD

**Issue by Krisoblucki-okta** [microsoftgraph/msgraph-sdk-java#196]
### Expected behavior
As a production tool, the ability to customize connection timeouts is of paramount importance.  

### Actual behavior
connection timeouts are hardcoded to an arbitrary value and can't be changed

### Steps to reproduce the behavior
try to configure the read timeout to a custom value

PR for this: https://github.com/microsoftgraph/msgraph-sdk-java/pull/190

**Comment by NakulSabharwal** [comment]
Thanks for reporting this issue. I am discussing with team that functionality to provide change of timeout to any arbitrary value should be added or some minimum-maximum range. We will try to resolve this issue asap.

**Comment by Krisoblucki-okta** [comment]
@NakulSabharwal the PR for this retains the already merged default values for the timeouts but also allows arbitrary configuration.
