### ISSUE TITLE
Add Java 8 compatibility checks to CI

### ISSUE THREAD

**Issue by tsmalls93** [microsoftgraph/msgraph-sdk-java#1979]
### Expected behavior

The SDK should work with Java 8 according to the Readme.

### Actual behavior

I received the following error:

java.lang.UnsupportedClassVersionError: JVMCFRE199E bad major version 55.0 of class=jakarta/annotation/Resource, the maximum supported major version is 52.0; offset=6

### Steps to reproduce the behavior

Run an app that uses javax.javaee-api 7.0 on Open Liberty that uses the SDK on version 6.6.0 or later.

**Comment by baywet** [comment]
HI @tsmalls93 
Thanks for using the SDK and for reporting this.
This was caused by the upgrade to kiota dependencies 1.1.9 in #1970
Which in turns had upgraded jakarta annotations https://github.com/microsoft/kiota-java/pull/1186
@Ndiritu I believe we should rollback that change in kiota libraries, and then cascade the updates. Thoughts?

**Comment by baywet** [comment]
Out of curiosity, why are you still running on Java 8 for server applications?

**Comment by andrueastman** [comment]
> HI @tsmalls93 Thanks for using the SDK and for reporting this. This was caused by the upgrade to kiota dependencies 1.1.9 in #1970 Which in turns had upgraded jakarta annotations [microsoft/kiota-java#1186](https://github.com/microsoft/kiota-java/pull/1186) @Ndiritu I believe we should rollback that change in kiota libraries, and then cascade the updates. Thoughts?

If this error can be caught at compile time, does it make sense to update the CI to probably run on Java 8 as well?

**Comment by Ndiritu** [comment]
> HI @tsmalls93 Thanks for using the SDK and for reporting this. This was caused by the upgrade to kiota dependencies 1.1.9 in #1970 Which in turns had upgraded jakarta annotations [microsoft/kiota-java#1186](https://github.com/microsoft/kiota-java/pull/1186) @Ndiritu I believe we should rollback that change in kiota libraries, and then cascade the updates. Thoughts?

Makes sense to rollback for now.
Working on adding the compile time checks to the build workflows as suggested by @andrueastman

**Comment by Ndiritu** [comment]
@tsmalls93 this should be working from `v6.9.0`

**Comment by tsmalls93** [comment]
Thanks @Ndiritu, it is working now.

**Comment by Ndiritu** [comment]
Re-opening to track CI changes.
