### ISSUE TITLE
Java sdk is giving null value in get cell action

### ISSUE THREAD

**Issue by ashish777gupta** [microsoftgraph/msgraph-sdk-java#1981]
When trying to fetch cell values via the Java SDK, we're encountering an unexpected problem: the value returned is null. Strangely, in Postman and Graph Explorer, the values display correctly. 

Our goal was to smoothly retrieve the cell value using the Java SDK, but it's not working. 
Please assist, with the mentioned issue.

Postman screenshot:
![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/81915943/7aea863d-74f6-4d10-ad29-bceec4bf014e)

Java sdk screenshot:
![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/81915943/10d32189-baae-4fef-b701-bee91f2740fb)

**Comment by ashish777gupta** [comment]
Kindly assist with the above comment. Thanks!

**Comment by ashish777gupta** [comment]
Pleases assist us. Thanks!

**Comment by petrhollayms** [comment]
OK I did confirm with @Ndiritu that it should work, given the support in Kiota for microsoft.graph.Json was added recently. So, we need to look into the issue.

CC @sebastienlevert

**Comment by ashish777gupta** [comment]
Thanks for the response @petrhollayms . Can you please let me know that, is this issue new and if it's new then what is the expected time it would take to fix it. And also if fixed then how to consume the fixed version?

**Comment by Ndiritu** [comment]
@ashish777gupta the value is not null. The actual value is nested under some abstractions which we can simplify. To get the value, try this:
```java

if (workbook.getValues() != null) {
    UntypedArray untypedValues = (UntypedArray) workbook.getValues();
    java.util.List<UntypedNode> cellValuesList = (java.util.List<UntypedNode>) untypedValues.getValue();
    UntypedArray untypedFirstCellValue = (UntypedArray) cellValuesList.get(0);
    java.util.List<UntypedNode> cellValues = (java.util.List<UntypedNode>) untypedFirstCellValue.getValue();
    Double cellValue = ((UntypedDouble) cellValues.get(0)).getValue();
}
```

**Comment by ashish777gupta** [comment]
Thanks for the response @Ndiritu
