### ISSUE TITLE
Does graph api support checksum verification when uploading file to sharepoint

### ISSUE THREAD

**Issue by ihudedi** [microsoftgraph/msgraph-sdk-java#1983]
Hi,
I would like to know if the upload file in graph support checksum verification in server side?
Thanks,
Itay

**Comment by baywet** [comment]
Hi @ihudedi 
This repository is dedicated to the Java SDK itself.
For questions about the API, [please use Microsoft Q&A](https://learn.microsoft.com/en-us/answers/products/161/ms-graph/)
Closing.
