### ISSUE TITLE
Lack of movement in the project

### ISSUE THREAD

**Issue by Krisoblucki-okta** [microsoftgraph/msgraph-sdk-java#200]
I am wondering what is going to be the release cadence as the last release was in November and it's January, there are pretty big bugs in a GA version that I come across every day yet not much is going forward.  Is this a hobby project that isn't going to be really supported to any significant degree?

**Comment by deepak2016** [comment]
@Krisoblucki-okta we are planning for monthly release for the library and infra work for the same is in progress. We will be doing a release soon in January. Appreciate you taking time and reporting the issue, we are working hard to get the fixes out as soon as possible. Thanks
