### ISSUE TITLE
SDK 6 missing client.drives(driveId).items(driveItemId).itemWithPath(path)?

### ISSUE THREAD

**Issue by denysobukh** [microsoftgraph/msgraph-sdk-java#2001]
Hi
Previously MS graph [SDK 5 allowed to get drive item by path](https://javadoc.io/doc/com.microsoft.graph/microsoft-graph/5.80.0/com/microsoft/graph/requests/DriveItemRequestBuilder.html#itemWithPath(java.lang.String))

```
client.drives(driveId)
    .items(itemId)
    .itemWithPath(filename)
    .buildRequest()
    .get()
```

Is `itemWithPath` was removed from SDK 6? How to make such a request with SDK 6?

**Comment by denysobukh** [comment]
it seem with SDK 6 it can be replaced by
```
client.drives()
    .byDriveId(driveId)
    .searchWithQ(filename)
    .get()
```

**Comment by jdimeo** [comment]
I mentioned this here: https://github.com/microsoftgraph/msgraph-sdk-java/issues/1961#issuecomment-2077458215
They were intentionally removing "non-canonical" paths from the SDK
