### ISSUE TITLE
ItemReference.getPath() returns an unescaped HTML String

### ISSUE THREAD

**Issue by kekolab** [microsoftgraph/msgraph-sdk-java#2027]
The method ItemReference.getPath() returns an unescaped HTML String

### Expected behavior

Shoulnd't this method returns an escaped HTML?

### Actual behavior

The method ItemReference.getPath() returns an unescaped HTML String

### Steps to reproduce the behavior

```java
DriveItem item; // grab an item whose parent path has, for example, spaces
item.getParentReference().getPath(); //<-- it is an unescaped HTML String
```
This method returns an unescaped string, such as:
```HTML
"/drive/root:/tmp/Festa%20della%20mamma%202024"
```

**Comment by Ndiritu** [comment]
@kekolab the path is a URL encoded string. To get the actual value, you'd need to decode it.
I suspect the path is returned as URL-encoded so that it can be re-used as a driveItemId in future requests to /drive/{driveId}/item/{driveItemId}

**Comment by kekolab** [comment]
@Ndiritu thanks a lot for your answer.
IMHO either it returns a non-encoded URL or the supporting [documentation](https://learn.microsoft.com/en-us/graph/api/resources/itemreference?view=graph-rest-1.0) should be updated. The only reference to the path property of the object is:

> The path value is an API path relative to the target drive, for example: /drive/root:/Documents/myfile.docx.
> To retrieve the human-readable path for a breadcrumb, you can safely ignore everything up to the first : in the path string.

Maybe a reference to the fact that the restult will be encoded should be done just to make things clear.
Feel free to close the issue if you think nothing should be done and thanks a lot again.

**Comment by Ndiritu** [comment]
@kekolab you make a fair point about documentation being clearer or an change in the API response payload.

In case you're interested, you could fork the docs & submit a PR for that change [here](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/blob/main/api-reference/v1.0/resources/itemreference.md)

Alternatively, this feedback would be helpful to to API team by posting this in Microsoft [Q&A](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph)

**Comment by kekolab** [comment]
@Ndiritu as per you suggestion: [PR](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/pull/9361) submitted
