### ISSUE TITLE
Default JSON serializer fails to serialize Graph objects returned from the service.

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-sdk-java#2064]
### Describe the bug

```java
final Subscription subscription = graphClient.subscriptions().post(subscriptionRequest);
final var subscriptionJson = KiotaJsonSerialization.serializeAsString(subscription);
```

This results in `subscriptionJson` being `{}`. This was originally reported in #1879.

The suggested fix to call `subscription.getBackingStore().setReturnOnlyChangedValues(false);` did not change the result. It should be noted that `subscription.getBackingStore().getReturnOnlyChangedValues();` returned false before this anyway. On a whim, I tried calling `subscription.getBackingStore().setReturnOnlyChangedValues(true);` before serializing, and I got a partial result:

```json
{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#subscriptions/$entity"}
```

### Expected behavior

`subscriptionJson` should be a full JSON representation of the subscription object returned by the service.

### How to reproduce

Code above.

### SDK Version

6.13.0

### Known Workarounds

This works but is way less convenient than using the static methods. It also requires an explicit reference to microsoft-kiota-serialization-json in your dependencies, which I suspect can cause problems down the line as the SDK bumps its versions.

```java
final var writer = new JsonSerializationWriter();
writer.writeObjectValue(null, subscription);
final var bytes = writer.getSerializedContent().readAllBytes();
final var subscriptionJson = new String(bytes, "UTF-8");
writer.close();
```

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @jasonjoh 

I believe the suggestion below is incorrect
```java
subscription.getBackingStore().setReturnOnlyChangedValues(false);
```

This should actually be as below

```java
subscription.getBackingStore().setIsInitializationCompleted(false);
```

Any chance you can confirm this works out?

**Comment by jasonjoh** [comment]
Thanks @andrueastman yes, that does work, but definitely isn't intuitive. I think @baywet's ID about creating an override would make this more friendly for developers.

**Comment by baywet** [comment]
Can you create an issue in https://github.com/microsoft/kiota-java instead asking for the override please? (can't transfer issues between orgs)

**Comment by baywet** [comment]
Thanks for opening the new one, closing this to avoid duplication
