### ISSUE TITLE
Getting GraphFatalServiceException in getting permissions for few oneDrive files with 500 Internal Server Error message

### ISSUE THREAD

**Issue by cruxifix94** [microsoftgraph/msgraph-sdk-java#207]
### Expected behavior
On using  IGraphServiceClient.users("user-id").drive().items("file-id").permissions(), we should get the IPermissionCollectionPage object in the result with the list of file permissions in it.

### Actual behavior
Few times, while doing multiple and many concurrent calls to get file permissions of different files, I got a streak of GraphFatalServiceException type exceptions for about 2 hrs straight. 

Exception Details --> 
Throwable detail: com.microsoft.graph.http.GraphFatalServiceException: Unexpected exception returned from the service.Error code: generalException Error message: An unspecified error has occurred. GET https://graph.microsoft.com/v1.0/users/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/drive/items/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxEAI/permissions
SdkVersion : graph-java-v0.2.0 500 : Internal Server Error [...]

### Steps to reproduce the behavior

The issue seems to be random for me. I was able to get the permissions of the same files by retrying again. Also, there were 2 other instances ( 1st - just for one file, 2nd - for 3 files ) at different time periods similar to this.

Why or when do we see such errors. What is the appropriate way to handle these ?

**Comment by darrelmiller** [comment]
Hey @cruxifix94 .  Thanks for the detailed report.  Can you provide a requestId for one of the failures?  If you don't want to include it here, you can email it to me at darrel.miller@microsoft.com 

The fact that it said Internal Server Error indicates that it is a backend server error.  We are working on making the current availability of backend services more visible to users.  Stay tuned for updates on that.

**Comment by cruxifix94** [comment]
I am not sure if I can get the requestId. But I have the timestamp and something called trace

timestamp:  "2019-01-11T17:44:15.626Z"  
 trace:  "b743089c289ceb0329b270935da95e95"  

Will this help ?

**Comment by NakulSabharwal** [comment]
Hi @cruxifix94 , The error seems to be from server can you include more information from stacktrace like error message, code and innerError ? Also, I am not able to repro your issue using GET graphClient.me().drive().items("item-id").permissions() using Java SDK version 1.0.2.

**Comment by cruxifix94** [comment]
Hey @darrelmiller @NakulSabharwal 
Can you give me some specific time frame for which I should wait to make the next request in case I get such error. 
The thing is I am syncing the users' drive files with delta token API concurrently. So, I don't want to miss any files' permissions in my syncing. So, I need to know how long should I wait so that I don't get this error again

**Comment by darrelmiller** [comment]
@cruxifix94 The requestId is usually included in the error response body.  I'm not exactly sure what that trace field is.  I will ask around.  If you could share your clientId with me privately I can review the logs and see if that error is happening specifically for you, or whether it was a service wide issue.  Transient 500 errors are somewhat unusual.

**Comment by NakulSabharwal** [comment]
@cruxifix94 We are not able to repro this issue. Please let us know if you are still facing the issue.

**Comment by baywet** [comment]
Closing as unable to repro.
