### ISSUE TITLE
Cannot create a folder with parent-item-path on Ms graph v6.13

### ISSUE THREAD

**Issue by achilep** [microsoftgraph/msgraph-sdk-java#2077]
### Describe the bug

Following this documentation,  https://learn.microsoft.com/en-us/graph/api/driveitem-post-children?view=graph-rest-1.0&tabs=http
I try to create a folder with a parent-item-path like this: 
```
   DriveItem folder = new DriveItem();
            folder.setName(fileName);
            folder.setFolder(new Folder());
            String parentPath="root:folder1/folder2/folder3";
            HashMap<String, Object> additionalData = new HashMap<String, Object>();
            additionalData.put("@microsoft.graph.conflictBehavior", "fail");
            folder.setAdditionalData(additionalData);


            graphClient.drives()
                    .byDriveId("driveId")
                    .items()
                    .byDriveItemId(parentPath).children()
                    .post(folder);
```
and I got the error bellow: 
`com.microsoft.graph.models.odataerrors.ODataError: Invalid request com.microsoft.graph.models.odataerrors.ODataError.createFromDiscriminatorValue(ODataError.java:36)`

### Expected behavior

To create a folder at this location `folder1/folder2/folder3`

### How to reproduce

Try this piece of code 

```
DriveItem folder = new DriveItem();
            folder.setName(fileName);
            folder.setFolder(new Folder());
            String parentPath="root:folder1/folder2/folder3";
            HashMap<String, Object> additionalData = new HashMap<String, Object>();
            additionalData.put("@microsoft.graph.conflictBehavior", "fail");
            folder.setAdditionalData(additionalData);```

             graphClient.drives()
                    .byDriveId("driveId")
                    .items()
                    .byDriveItemId(parentPath).children()
                    .post(folder);
```

### SDK Version

6.13.0

### Latest version known to work for scenario above?

5.80

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by Ndiritu** [comment]
Hi @achilep, thanks for reaching out.
Adding a colon at the end of the folder path should work: `"root:folder1/folder2/folder3:"`
Please confirm.

**Comment by achilep** [comment]
Thanks @Ndiritu for your suggestion but it did not work.
I try this path 
`root:folder1/folder2/folder3:
`
and I got this error 
`com.microsoft.graph.models.odataerrors.ODataError: Invalid request
`

I also try this path with a slash after the colon:
`root:/folder1/folder2/folder3:
`
and I got this error
`com.microsoft.graph.models.odataerrors.ODataError: Item not found
`

**Comment by Ndiritu** [comment]
Thanks for catching the missing `/` after `root:`. Updated my previous sample.

`Item not found` means the request is now valid but the path doesn't exist on the drive. You'll need to double-check the path

**Comment by achilep** [comment]
Thanks @Ndiritu
` root:/folder1/folder2/folder3: 
` works well for me.

I have one last question, is there a way to create 3 children subfolders with one MS graph request?

**Comment by Ndiritu** [comment]
Yes, you can send batch requests. [docs](https://learn.microsoft.com/en-us/graph/sdks/batch-requests?view=graph-rest-1.0&tabs=java)

**Comment by achilep** [comment]
Thanks @Ndiritu for your support. I just wanted to let you know that I'm closing this issue as resolved.
