### ISSUE TITLE
Create multiple folder with Ms graph batch throw a timeout exception

### ISSUE THREAD

**Issue by achilep** [microsoftgraph/msgraph-sdk-java#2086]
### Describe the bug

I'm trying to use the MS graph batch request to create multiple folders in a single request, but the MS graph request gets stuck and a timeout exception is thrown after some time.

### Expected behavior

Should create all 8 folders and return the `driveitems`.

### How to reproduce

You can just run the source code below. MS graph request will get stuck and throw a timeout exception
```
BatchRequestContentCollection batchRequestContent = new BatchRequestContentCollection(graphClient);
        List<String> folderNames = List.of("folder1", "folder2", "folder3", "folder4", "folder5", "folder6", "folder7", "folder8");
        for (String folderName : folderNames) {
                  DriveItem folder = new DriveItem();
                  folder.setName(folderName);
                  folder.setFolder(new Folder());
                  HashMap<String, Object> additionalData = new HashMap<String, Object>();
                  additionalData.put("@microsoft.graph.conflictBehavior", "fail");
                  folder.setAdditionalData(additionalData);
                  batchRequestContent.addBatchRequestStep(graphClient.drives().byDriveId("drive- 
                id").items().byDriveItemId("root:/path/to/parent:").children().toPostRequestInformation(folder));
        }
        BatchResponseContentCollection batchResponseContent = graphClient.getBatchRequestBuilder().post(batchRequestContent, null);



```

### SDK Version

6.18.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by AnujShahSifthub** [comment]
This is also happening for sometimes when using the Batch API to write to worksheet, apply fonts to a cell, etc.

Please take this on priority.

**Comment by Ndiritu** [comment]
Hi @achilep @AnujShahSifthub
Before we ship an update to the `microsoft-graph` package, you could take a direct dependency on `microsoft-graph-core` and use the latest [version](https://central.sonatype.com/artifact/com.microsoft.graph/microsoft-graph-core/3.1.15) which should fix this.
Please let me know if this helps.
