### ISSUE TITLE
GraphServiceClient empty identities

### ISSUE THREAD

**Issue by rakithasuranga** [microsoftgraph/msgraph-sdk-java#2087]
### Describe the bug

```
GraphServiceClient graphClient = new GraphServiceClient(requestAdapter);

User result = graphClient.users().byUserId("{user-id}").get(requestConfiguration -> {
	requestConfiguration.queryParameters.select = new String []{"displayName", "givenName", "identities"};
});

logger.info("result.displayName); // User04 Testbatch
logger.info("result.getIdentities().size()); // size 0
```

I made a query using the Graph API directly and it returned the "identities".

`https://graph.microsoft.com/v1.0/users?$select=givenName,surname,identities`

```
"value": [
        {
            "givenName": "User04",
            "surname": "Testbatch",
            "identities": [
                {
                    "signInType": "emailAddress",
                    "issuer": "xxxxx.onmicrosoft.com",
                    "issuerAssignedId": "user04.testbatch@xxxx.com"
                },
                {
                    "signInType": "userPrincipalName",
                    "issuer": "xxxxx.onmicrosoft.com",
                    "issuerAssignedId": "01c37a54-c3f9-4505-96e0-xxxxxxx@xxxxxxx.onmicrosoft.com"
                }
            ]
        }
]
```

### Expected behavior

logger.info("result.getIdentities().size()); // size >=1

### How to reproduce

```
GraphServiceClient graphClient = new GraphServiceClient(requestAdapter);

User result = graphClient.users().byUserId("{user-id}").get(requestConfiguration -> {
	requestConfiguration.queryParameters.select = new String []{"displayName", "givenName", "identities"};
});
```
logger.info("result.displayName); // User04 Testbatch
logger.info("result.getIdentities().size()); // size 

### SDK Version

6.13.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by mkomko** [comment]
In your Graph API example, you are querying for all users. In your Graph SDK example, you are querying for one user with the ID "{user-id}", which obviously does not exist. You have to remove the `.byUserId("{user-id}")`.

**Comment by andrueastman** [comment]
> In your Graph API example, you are querying for all users. In your Graph SDK example, you are querying for one user with the ID "{user-id}", which obviously does not exist. You have to remove the .byUserId("{user-id}").

Any chance you can confirm if this works for you @rakithasuranga?
