### ISSUE TITLE
Support for update ranges with values., writing notes in a cell, cell formatting in a workbook.

### ISSUE THREAD

**Issue by AnujShahSifthub** [microsoftgraph/msgraph-sdk-java#2088]
### Describe the solution you'd like.

I want full support for microsoft excel writing using java sdk.(Notes, comments). I cannot find anything to do so currently.

**Comment by Ndiritu** [comment]
Hi @AnujShahSifthub,
Please check these [docs](https://learn.microsoft.com/en-us/graph/api/resources/excel?view=graph-rest-1.0) for code samples.
