### ISSUE TITLE
/drives/{id}/items/{id}/listItem/fields

### ISSUE THREAD

**Issue by denis3119** [microsoftgraph/msgraph-sdk-java#2093]
![image](https://github.com/user-attachments/assets/225a78eb-45b7-4376-94a8-ed261bff9100)

**v5.xx**
I used code like this to update the fields:
`var sourceFieldValueSet = new FieldValueSet();
        sourceFieldValueSet.additionalDataManager().putAll(fields);
        getGraphClient()
                .drives(microsoftOauthProperties.getDriveId())
                .items(id)
                .listItem()
                .fields()
                .buildRequest()
                .patch(sourceFieldValueSet);`

`PATCH https://graph.microsoft.com/v1.0/drives/{id}/items/{id}/listItem/fields`

**v6.xx**
patch was removed. 

So, how can I patch the columns via Microsoft Graph?

**Comment by Ndiritu** [comment]
Hi @denis3119 

Please consider accessing the list item fields via the `sites()` root URL path:

```java

graphServiceClient.sites().bySiteId("").lists().byListId("").items().byListItemId("").fields().patch();

```

However, you can still overwrite the request URL & use your preferred endpoint using `withUrl`:

```java

graphServiceClient.sites().bySiteId("").lists().byListId("").items().byListItemId("").fields().withUrl(
    "https://graph.microsoft.com/v1.0/drives/{id}/items/{id}/listItem/fields"
).patch(null);

```
