### ISSUE TITLE
UnknownHostException login.microsoftonline.com thrown by authenticateWithConfidentialClient

### ISSUE THREAD

**Issue by jasonslater2000** [microsoftgraph/msgraph-sdk-java#2094]
### Describe the bug

This exception is getting thrown when I try to list sites, list drives, or any other operation.

- I am not behind a proxy.  
- Other applications on the same box are able to do a GET of login.microsoftonline.com without issue.
 
- I did not have any issue w/ using the microsoft-graph package, v5.80.0
- These issues occur with the following dependencies

`
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.13.1</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.graph</groupId>
            <artifactId>microsoft-graph-core</artifactId>
            <version>3.1.14</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-abstractions</artifactId>
            <version>1.1.13</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-authentication-azure</artifactId>
            <version>1.1.13</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-http-okHttp</artifactId>
            <version>1.1.13</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-serialization-form</artifactId>
            <version>1.1.13</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-serialization-json</artifactId>
            <version>1.1.13</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-serialization-multipart</artifactId>
            <version>1.1.13</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-serialization-text</artifactId>
            <version>1.1.13</version>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
            <version>4.1.112.Final</version>
        </dependency>
`

`Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.microsoft.aad.msal4j.MsalClientException: java.io.UncheckedIOException: java.net.UnknownHostException: login.microsoftonline.com:-1
	at com.azure.identity.implementation.IdentitySyncClient.authenticateWithConfidentialClient(IdentitySyncClient.java:148)
	at com.azure.identity.ClientSecretCredential.getTokenSync(ClientSecretCredential.java:136)
	at com.microsoft.kiota.authentication.AzureIdentityAccessTokenProvider.getAuthorizationToken(AzureIdentityAccessTokenProvider.java:146)
	at com.microsoft.kiota.authentication.BaseBearerTokenAuthenticationProvider.authenticateRequest(BaseBearerTokenAuthenticationProvider.java:46)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.getHttpResponseMessage(OkHttpRequestAdapter.java:711)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:276)
`

for reference, I am authenticating this way:
`
                final String[] graphScopes = new String[] {"https://graph.microsoft.com/.default"};
                final String[] allowedHosts = new String[] { "graph.microsoft.com" };
                final ClientSecretCredential credential = new ClientSecretCredentialBuilder()
                        .clientId(sharepointClientId)
                        .tenantId(sharepointTenantId)
                        .clientSecret(sharepointClientSecret)
                        .build();
                if (null == graphScopes || null == credential) {
                    throw new Exception("Unexpected error");
                }
                AzureIdentityAuthenticationProvider authProvider = new AzureIdentityAuthenticationProvider(credential,allowedHosts,graphScopes);
                requestAdapter = new OkHttpRequestAdapter(authProvider);
`

### Expected behavior

Authentication should work as before

### How to reproduce

i have not isolated a minimal set of code yet, will update if i have time to do so

### SDK Version

1.1.13

### Latest version known to work for scenario above?

5.8.0

### Known Workarounds

none known

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Configuration

Linux 4.14.336-257.562.amzn2.x86_64 

### Other information

none

**Comment by jasonslater2000** [comment]
trying to re-paste dependencies for formatting

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.13.1</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.graph</groupId>
            <artifactId>microsoft-graph-core</artifactId>
            <version>3.1.14</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-abstractions</artifactId>
            <version>1.1.13</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-authentication-azure</artifactId>
            <version>1.1.13</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-http-okHttp</artifactId>
            <version>1.1.13</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-serialization-form</artifactId>
            <version>1.1.13</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-serialization-json</artifactId>
            <version>1.1.13</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-serialization-multipart</artifactId>
            <version>1.1.13</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-serialization-text</artifactId>
            <version>1.1.13</version>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
            <version>4.1.112.Final</version>
        </dependency>

**Comment by jasonslater2000** [comment]
and re-pasting authentication code, for formatting

                final String[] graphScopes = new String[] {"https://graph.microsoft.com/.default"};
                final String[] allowedHosts = new String[] { "graph.microsoft.com" };
                final ClientSecretCredential credential = new ClientSecretCredentialBuilder()
                        .clientId(sharepointClientId)
                        .tenantId(sharepointTenantId)
                        .clientSecret(sharepointClientSecret)
                        .build();
                if (null == graphScopes || null == credential) {
                    throw new Exception("Unexpected error");
                }
                AzureIdentityAuthenticationProvider authProvider = new AzureIdentityAuthenticationProvider(credential,allowedHosts,graphScopes);
                requestAdapter = new OkHttpRequestAdapter(authProvider);

**Comment by timayabi2020** [comment]
@jasonslater2000 could you kindly share code after the request adapter because I am currently unable to reproduce the issue.
