### ISSUE TITLE
ItemAttachment content bytes

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#21]
When I process an email message retrieved from a user's mailbox  I need to be able to read attachments to the message that are embedded emails themselves. A standard `FileAttachment` has a `contentBytes` field but I have not been able to discover how to retrieve the bytes of an `ItemAttachment`. Any suggestions?

**Comment by davidmoten** [comment]
> I'm going to have to circle back on this after I ask questions around here.

@MIchaelMainer any word on this issue?

**Comment by MIchaelMainer** [comment]
Right now, you are unable to do what you want to do. I'm trying somethings out and will need to circle back later.

**Comment by MIchaelMainer** [comment]
@davidmoten I'm putting in a request for this feature. This is a must have since there is no workaround for getting nested item attachments.

**Comment by MIchaelMainer** [comment]
@davidmoten I've put in a request to get deep nested attachment expansion.

**Comment by davidmoten** [comment]
Thanks @MIchaelMainer

**Comment by davidmoten** [comment]
@MIchaelMainer any suggestions for how I can track progress on this request?

**Comment by SuperEvenSteven** [comment]
@MIchaelMainer, any progress on this request please?

Thanks Stephen

**Comment by MIchaelMainer** [comment]
@SuperEvenSteven I've followed up on this again. Thank you for voicing your interest in this feature. Every consecutive voice helps.

**Comment by shubhamgujarathi07** [comment]
Is there any way to retrieve the attachment through the api?
Not just java but api would be fine for me!
Can the attachment be retrieved via MS graph rest api?

Example Scenario:
I want to save the fileAttachment attached to a ItemAttachment!

@davidmoten Did you find a way out?

**Comment by davidmoten** [comment]
@shubhamgujarathi07 you are referring to an ItemAttachment not a FileAttachment? In the above discussion you can see code that brings back some info of an ItemAttachment but if the ItemAttachment has an attachment itself the Graph API does not support retrieving it (not this SDK but the Graph API itself). @MIchaelMainer has registered an issue internally and we'll just wait to hear progress.

**Comment by MIchaelMainer** [comment]
Letting PM know that this is a hot topic.... Thank you for riding this feature request/issue.

**Comment by bartrikers** [comment]
Hi @MIchaelMainer,

I'm having the same problem, so good to read the work has been scheduled. Any idea when this will be fixed? I assume it will be fixed in the msGraph/OutlookAPI in general, not just the java implementation? And will this fix be part of the v2 outlook api?

**Comment by zhiangli** [comment]
Hi @MIchaelMainer, any updates from your side? We also have the same issue.

**Comment by erickbp** [comment]
Hi @MIchaelMainer, is there an update on this?

**Comment by erickbp** [comment]
Hi @davidmoten, did you find a workaround? did you workaround it with EWS?

**Comment by davidmoten** [comment]
@erickbp I used EWS instead yes.

**Comment by erickbp** [comment]
@davidmoten thanks for your reply, I will PM to email address in your profile.

**Comment by nimeesh-msft** [comment]
@davidmoten , @erickbp , @MIchaelMainer 
We have enable support for ItemAttachment as MIME on beta endpoint and it will take ~3 weeks for worldwide roll-out.

**Comment by erickbp** [comment]
thanks @nimeesh-msft was the beta documentation updated so we can see how to use it? or do you have a api request example?
thanks again

**Comment by nimeesh-msft** [comment]
We will update documentation when its available on all servers.

**Comment by idybil** [comment]
Is anybody knows how we could test it ?  Thanks

**Comment by mcsnolte** [comment]
@nimeesh-msft any update on this?  Do we have to contact outlookapibeta@microsoft.com for private beta or is available to the public yet?

**Comment by nimeesh-msft** [comment]
It will be available in public beta endpoint in couple of weeks.

**Comment by jschipp-r7** [comment]
Awesome, let us know when there's more news. I noticed the uservoice thread was removed https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/12253464-expose-the-entire-email-mime-stream-whole-mail-co

**Comment by mcsnolte** [comment]
@nimeesh-msft happy Friday!  do you happen to have any more updates on this?  many thanks

**Comment by nimeesh-msft** [comment]
It's available on public beta endpoint.

**Comment by mcsnolte** [comment]
Thanks for the update, but I can't find updated docs that reference "enable support for ItemAttachment as MIME".  Perhaps I'm missing them, can you please point me to the right spot?

**Comment by nimeesh-msft** [comment]
https://docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta#get-the-raw-contents-of-a-file-or-item-attachment

**Comment by tsavxaj** [comment]
Any idea of when the MSGRAPH SDK BaseAttachmentRequestBuilder class will support the ability to use the $value segment?:

GET /users/{id | userPrincipalName}/mailFolders/{id}/messages/{id}/attachments/{id}/$value

This is currently support with the com.microsoft.graph.requests.generated.BaseProfilePhotoRequestBuilder class, with content() method which adds $value segment to the URL.

    public IProfilePhotoStreamRequestBuilder content() {
        return new ProfilePhotoStreamRequestBuilder(getRequestUrlWithAdditionalSegment("$value"), getClient(), null);
    }

**Comment by georgechr** [comment]
We have the same issue. We don't care what type of Attachment we're dealing with. We just want its content. 

Our workaround was to create our implementation of `AttachmentStreamRequest  extends BaseStreamRequest<Attachment>` and `AttachmentStreamRequestBuilder extends BaseRequestBuilder<InputStream>`. We followed through the implementation for MessageStreamRequest. 

Seems to work but not sure if there are any side effects ??

**Comment by whammoed** [comment]
I am able to get the InputStream of an Attachment (ItemAttachment) using the latest java API (The java API is missing the .content() option on Attachments but you can build the url and append $value instead):

```
       URL requestUrl = graphClient.users("user@***.com").messages("*****").attachments("****").buildRequest().getRequestUrl();
        InputStream is = new FileAttachmentStreamRequestBuilder(requestUrl.toString() + "/$value", graphClient, null).buildRequest().get();
//save the file
        Files.copy(is, Paths.get(fileName + extension), StandardCopyOption.REPLACE_EXISTING);
```

**Comment by mahendrabaghel** [comment]
Was this issue every resolved? Our use case is similar, nested attachments (ItemAttachment) with attachments (FileAttachment). Is there a way to grab the attachments from nested attachments using java graphs SDK?

**Comment by mahendrabaghel** [comment]
> I am able to get the InputStream of an Attachment (ItemAttachment) using the latest java API (The java API is missing the .content() option on Attachments but you can build the url and append $value instead):
> 
> ```
>        URL requestUrl = graphClient.users("user@***.com").messages("*****").attachments("****").buildRequest().getRequestUrl();
>         InputStream is = new FileAttachmentStreamRequestBuilder(requestUrl.toString() + "/$value", graphClient, null).buildRequest().get();
> //save the file
>         Files.copy(is, Paths.get(fileName + extension), StandardCopyOption.REPLACE_EXISTING);
> ```

How are you getting the attachment IDs? I do not see an way to grab the id from attachment objects.

**Comment by whammoed** [comment]
> > I am able to get the InputStream of an Attachment (ItemAttachment) using the latest java API (The java API is missing the .content() option on Attachments but you can build the url and append $value instead):
> > ```
> >        URL requestUrl = graphClient.users("user@***.com").messages("*****").attachments("****").buildRequest().getRequestUrl();
> >         InputStream is = new FileAttachmentStreamRequestBuilder(requestUrl.toString() + "/$value", graphClient, null).buildRequest().get();
> > //save the file
> >         Files.copy(is, Paths.get(fileName + extension), StandardCopyOption.REPLACE_EXISTING);
> > ```
> 
> How are you getting the attachment IDs? I do not see an way to grab the id from attachment objects.

Just using ".id" for Attachment object returned from:
graphClient.users(*******).messages(*******).attachments().buildRequest(options).top(1000).expand("microsoft.graph.itemattachment/item").get();

**Comment by mahendrabaghel** [comment]
> > > I am able to get the InputStream of an Attachment (ItemAttachment) using the latest java API (The java API is missing the .content() option on Attachments but you can build the url and append $value instead):
> > > ```
> > >        URL requestUrl = graphClient.users("user@***.com").messages("*****").attachments("****").buildRequest().getRequestUrl();
> > >         InputStream is = new FileAttachmentStreamRequestBuilder(requestUrl.toString() + "/$value", graphClient, null).buildRequest().get();
> > > //save the file
> > >         Files.copy(is, Paths.get(fileName + extension), StandardCopyOption.REPLACE_EXISTING);
> > > ```
> > 
> > 
> > How are you getting the attachment IDs? I do not see an way to grab the id from attachment objects.
> 
> Just using ".id" for Attachment object returned from: graphClient.users(_******).messages(******_).attachments().buildRequest(options).top(1000).expand("microsoft.graph.itemattachment/item").get();

Hi,

This works fine, to grab the attachment. My issue is the attachment is another message and I need the attachments attached to that nested message.  Is there a way to grab that?

Thanks,

Mahendra

**Comment by whammoed** [comment]
> > > > I am able to get the InputStream of an Attachment (ItemAttachment) using the latest java API (The java API is missing the .content() option on Attachments but you can build the url and append $value instead):
> > > > ```
> > > >        URL requestUrl = graphClient.users("user@***.com").messages("*****").attachments("****").buildRequest().getRequestUrl();
> > > >         InputStream is = new FileAttachmentStreamRequestBuilder(requestUrl.toString() + "/$value", graphClient, null).buildRequest().get();
> > > > //save the file
> > > >         Files.copy(is, Paths.get(fileName + extension), StandardCopyOption.REPLACE_EXISTING);
> > > > ```
> > > 
> > > 
> > > How are you getting the attachment IDs? I do not see an way to grab the id from attachment objects.
> > 
> > 
> > Just using ".id" for Attachment object returned from: graphClient.users(_******).messages(******_).attachments().buildRequest(options).top(1000).expand("microsoft.graph.itemattachment/item").get();
> 
> Hi,
> 
> This works fine, to grab the attachment. My issue is the attachment is another message and I need the attachments attached to that nested message. Is there a way to grab that?
> 
> Thanks,
> 
> Mahendra

Sorry, I did not come across a way to do that.  You may be able to use JavaMail and create a MimeMessage from the input stream of the .eml file that you can get from graph....then you can parse through with the JavaMail api.
