### ISSUE TITLE
Channel isArchived is missing

### ISSUE THREAD

**Issue by BradPlayerZero** [microsoftgraph/msgraph-sdk-java#2100]
### Describe the bug

According to the documentation, channels are supposed to have an isArchived flag.  See https://learn.microsoft.com/en-us/graph/api/team-list-allchannels?view=graph-rest-1.0&tabs=http.

Unfortunately, this API doesn't have the isArchived flag in channels.  See https://github.com/microsoftgraph/msgraph-sdk-java/blob/fdd899b62b31fbb637b25d9b4bab11d49a0060ee/src/main/java/com/microsoft/graph/generated/models/Channel.java#L11

Not sure how this can happen, as this is supposed to be autogenerated code.

Note the isArchived flag is in the [msgraph-beta-sdk-java](https://github.com/microsoftgraph/msgraph-beta-sdk-java) sdk, see https://github.com/microsoftgraph/msgraph-beta-sdk-java/blob/346c3d15d975a8d1a9d8ee0b4cbf70f7d3ccd6fc/src/main/java/com/microsoft/graph/beta/generated/models/Channel.java#L11

As the isArchived flag doesn't seem updated recently, there doesn't seem any logical reason for the omission.

### Expected behavior

Channels should have an isArchived flag

### How to reproduce

Observe the channel object is missing the isArchived property

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by baywet** [comment]
Hi @BradPlayerZero 
Thanks for using the SDK and for reporting this.
I've created an incident for the relevant service team (you won't be able to access this link)
https://portal.microsofticm.com/imp/v3/incidents/incident/528182959/summary

This is most likely to take a couple of weeks, the schema changes are locked for security reasons.
(we use the schema to generate the SDK)

**Comment by BradPlayerZero** [comment]
Not following.  Schema seems publicly available here: https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml.  Why is there a security issue with the java SDK not using an up-to-date version of that specification?

**Comment by BradPlayerZero** [comment]
This seems to have been fixed with more recent builds.  Thanks.
