### ISSUE TITLE
Implementing pagination in a middleware scenario

### ISSUE THREAD

**Issue by cascer1** [microsoftgraph/msgraph-sdk-java#2107]
Hi,

I'm working on an API to manage users using the Graph API. One of the operations I'm implementing is a list endpoint that supports some filtering and pagination.

Building the request for the first page was trivial, but I'm having issues with subsequent pages. Namely, because we do not want to expose the full `@odata.nextLink` to our users, I need a way of reconstructing this from just the `skipToken` which I'll send to the user and expect back in subsequent requests for the same result set (but pages beyond the first page).

The SDK does not allow me to simply set the skipToken. So, I figured I could rebuild the URL using something like this:

```java
graphClient.users()
    .withUrl("https://graph.microsoft.com/v1.0/users?$skipToken=something")
    .get(getRequestConfiguration -> {
          getRequestConfiguration.queryParameters.select = getUserFields();
          getRequestConfiguration.queryParameters.filter = buildFilterString(filter);
          getRequestConfiguration.queryParameters.top = 25;
      });
```

This doesn't work because I get a 500 response. 

So, my question is: Is there a way for me to proxy the pagination operation to my users without exposing the full `nextLink` URL? Simply using the built-in pagination stuff like pageIterator is fine if I'm the final consumer of the data, but in my case I am not. 

Thanks

**Comment by baywet** [comment]
Hi @cascer1 
Thank you for using the SDK and for reaching out.
From an OData perspective, if you have a skiptoken in the URL already you're not supposed to provide any other query parameter as the skip token already encodes the previously passed query parameters.
You should also not attempt to parse the nextlink, but treat is as opaque and use it as is. This is because attempting to parse it leads to errors like these when rebuilding it. Also the format could change over time.
Do you still query errors if you remove all additional query parameters?

**Comment by cascer1** [comment]
Hi, thanks for your explanation.

If I understand correctly, there is no supported method of storing just the skipToken so that I can reduce the back-and-forth traffic between my middleware and end-users. 

If only the skiptoken is required, why does the `nextLink` response include all my original query parameters as well? Can I get away with removing those?

My ultimate goal is to reduce the size of the data I have to send back and forth between the middleware and client applications, especially when our customers start using the middleware API directly.

Currently, I've settled for Base-64 encoding the entire nextLink and passing it to the client. That way, I'm not reconstructing a URL and don't have to update my implementation when any changes are made in the Graph API. However, if I could remove those supposed superfluous query parameters from the link, that would significantly reduce the encoded string length.

Thanks

**Comment by baywet** [comment]
Allow me to correct my previous statement: the additional parameters are already encoded in the next link, not the skip token.
Again, the next link should be treated as opaque, and no attempt should be made at parsing/rebuilding it on the client side (client as in Microsoft Graph client).
Base64 encoding results in a ~30% size increase in general, you could just pass the link as is back and forth and save this.
However, there are security considerations to passing a link as is to the client size and executing it, regardless of the base64 encoding (somebody could try to inject a different link to try and access different data).
You should instead consider storing those next links in your middleware service and return a hash to the client.
Let us know if you have any additional comments or questions.
