### ISSUE TITLE
Batch Steps in random order

### ISSUE THREAD

**Issue by dan-drewes** [microsoftgraph/msgraph-sdk-java#2109]
### Describe the bug

The SDK uses java.util.HashMap to store the RequestSteps that are added to BatchRequestContent with addBatchRequestStep().
These are retrieved in BatchRequestContent#getBatchRequestContent() via this.batchRequestSteps.values().
java.util.HashMap however, does not guarantee that elements are iterated over in the same order they were added, according to official java docs.
This results in error {"error":{"code":"BadRequest","message":"Invalid dependency for request Id... when specifying dependencies via the BatchRequestStep#addDependsOnId method, because dependant steps may be listed in the json batch BEFORE the step they are depending on.
Currently, imho, this makes batching with dependencies in the java sdk impossible for many usecases. 

### Expected behavior

BatchRequestContent stores and sends RequestSteps in the same order they were added.

### How to reproduce

// Create the batch request content with the steps
final BatchRequestContent batchRequestContent = new BatchRequestContent(
    graphClient);

final ZoneOffset localTimeZone = OffsetDateTime.now().getOffset();
final OffsetDateTime today = OffsetDateTime.of(LocalDate.now(),
    LocalTime.MIDNIGHT, localTimeZone);
final OffsetDateTime tomorrow = today.plusDays(1);

// Create a new event for today at 5:00 PM
final Event newEvent = new Event();
newEvent.setSubject("File end-of-day report");
// 5:00 PM
final DateTimeTimeZone start = new DateTimeTimeZone();
start.setDateTime(
    today.plusHours(17).format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
start.setTimeZone(ZoneOffset.systemDefault().getId());
newEvent.setStart(start);
// 5:30 PM
final DateTimeTimeZone end = new DateTimeTimeZone();
end.setDateTime(today.plusHours(17).plusMinutes(30)
    .format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
end.setTimeZone(ZoneOffset.systemDefault().getId());
newEvent.setEnd(end);

// Use the Graph client to generate the requestInformation
// GET /me/calendarView?startDateTime="start"&endDateTime="end"
final RequestInformation calendarViewRequestInformation = graphClient.me()
    .calendarView().toGetRequestInformation(requestConfiguration -> {
        requestConfiguration.queryParameters.startDateTime = today.toString();
        requestConfiguration.queryParameters.endDateTime = tomorrow.toString();
    });

final String firstCalendarViewRequestId = batchRequestContent
    .addBatchRequestStep(calendarViewRequestInformation);

// Use the Graph client to add the requestInformation for POST /me/events
RequestInformation postEventRequestInformation = graphClient.me().events()
    .toPostRequestInformation(newEvent);

// Get the id assigned to the request
String postEventRequestId = batchRequestContent
    .addBatchRequestStep(postEventRequestInformation);
// Set the dependsOnId to 'postEventRequestId'
batchRequestContent.getBatchRequestSteps().get(postEventRequestId)
    .addDependsOnId(firstCalendarViewRequestId );

final String secondCalendarViewRequestId = batchRequestContent
    .addBatchRequestStep(calendarViewRequestInformation);
// Set the dependsOnId to 'postEventRequestId'
batchRequestContent.getBatchRequestSteps().get(secondCalendarViewRequestId )
    .addDependsOnId(postEventRequestId);

// Send the batch request content to the /$batch endpoint
final BatchResponseContent batchResponseContent = Objects.requireNonNull(
    graphClient.getBatchRequestBuilder().post(batchRequestContent, null));

//get the responses
Map<String, Response> responses = batchResponseContent.getResponses();

// Get the event response using the id assigned to the request
final Event postedEvent = batchResponseContent.getResponseById(postEventRequestId,
    Event::createFromDiscriminatorValue);
System.out.println(String.format("New event created with ID: %s",
    Objects.requireNonNull(postedEvent.getId())));

// Get the calendar view response by id
final EventCollectionResponse eventsResponse = Objects
    .requireNonNull(batchResponseContent.getResponseById(secondCalendarViewRequestId,
        EventCollectionResponse::createFromDiscriminatorValue));
System.out.println(String.format("You have %d events on your calendar today",
    Objects.requireNonNull(eventsResponse.getValue().size())));

### SDK Version

6.8.0 with microsoft-graph-core 3.1.15

### Debug output

<details><summary>Inspect batchResponseContent.jsonBatchResponseObject and batchRequestContent.batchRequestSteps</summary>

batchResponseContent.jsonBatchResponseObject (* replacing real Ids) : 
{"error":{"code":"BadRequest","message":"Invalid dependency for request Id ***","innerError":{"date":"2024-08-08T10:28:39","request-id":"***","client-request-id":"***"}}}

batchRequestContent.batchRequestSteps (edited for brevity):
[0]: dependsOn[1]
[1}: dependsOn[null]
[2]: dependsOn[0]

</details>

### Other information

This should be an easy fix by using java.util.LinkedHashMap(which guarantees iteration in order of insertion) instead of java.util.HashMap for storing the BatchRequestSteps.

**Comment by Ndiritu** [comment]
Thanks for reporting this @dan-drewes

**Comment by Ndiritu** [comment]
@dan-drewes before we resume releases on this package, you can temporarily get these changes by taking a direct dependency on the latest version of [`microsoft-graph-core](https://central.sonatype.com/artifact/com.microsoft.graph/microsoft-graph-core)
