### ISSUE TITLE
ChunkedUploadProvider constructor size parameter int type limits upload to 2GB

### ISSUE THREAD

**Issue by lenyt** [microsoftgraph/msgraph-sdk-java#211]
The size parameter of constructor for ChunkedUploadProvider is int type which means that the maximum upload that can be done through the ChunkedUploadProvider is 2GB. But the maximum file size limit for OneDrive and OneDrive for Business is higher at 15GB:

https://support.office.com/en-us/article/invalid-file-names-and-file-types-in-onedrive-onedrive-for-business-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa#individualfilesize

Can this size parameter be changed to long so that uploads larger than 2GB is possible?

### Expected behavior
Be able to pass size parameter larger than max int in constructor of ChunkedUploadProvider.

### Actual behavior
Cannot pass size bigger than max int since the type of the parameter is int.

### Steps to reproduce the behavior
no steps required, the type of the parameter is currently int, it needs to be changed to long to make uploads larger than 2GB possible

**Comment by deepak2016** [comment]
Thanks for reporting the issue. Will you be able to raise a pull request with corresponding changes. I will be happy to review the changes and get the changes in?

**Comment by SailReal** [comment]
If https://github.com/microsoftgraph/msgraph-sdk-android/pull/107 is merged and if desired, I could create for this repo another PR.

**Comment by NakulSabharwal** [comment]
@SailReal Please create a PR for this change. We will review it. Thank you
