### ISSUE TITLE
calling accept on an instance of recurring series makes other instances responseStatus to become tentative.

### ISSUE THREAD

**Issue by moizsj** [microsoftgraph/msgraph-sdk-java#215]
calling accept on an instance of recurring series makes other instances responseStatus to become tentative. instead expect them to remain not responded state.

API used - POST /me/events/{id}/accept
graphClient.me().events(remoteEventIdOfOccurrence).accept(...

**Comment by moizsj** [comment]
Steps -
1. create a recurring meeting
2. Fetch occurrence A  -
`graphClient.me().events(idOfOccurrenceA).buildRequest().get()`
Observe that -
occurreneA.responseStatus.response is not set (not responded)
3. call accept API on occurrence B of the recurring meeting - 
`graphClient.me().events(idOfOccurrenceB).accept(null, true).buildRequest().post()`
4. Fetch occurrence A  again -
`graphClient.me().events(idOfOccurrenceA).buildRequest().get()`
Observe that -
occurreneA.responseStatus.response is now tentative

**Comment by NakulSabharwal** [comment]
@moizsj  we are not able to repro this issue. We followed steps provided by you but they works fine with expected behavior.

**Comment by NakulSabharwal** [comment]
@moizsj As we are not able to repro the issue so we are closing it. If you still face issue kindly reopen it.
