### ISSUE TITLE
Unable to get Messages ItemAttachment content using java SDK 6.16

### ISSUE THREAD

**Issue by raghucha** [microsoftgraph/msgraph-sdk-java#2169]
### Describe the bug

current as describe in documentation to get Item attachment content we can follow this instruction 
[Items Mime ](https://learn.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&tabs=java#example-6-get-the-raw-contents-of-a-file-attachment-on-a-message)

i have attempted to get the content using 
```
 graphServiceClient.users().byUserId(mailboxAddress).messages()
                .byMessageId(parentMessageId).attachments().byAttachmentId(attachmentId).content().get()
```

however there is no such method to get the `content` , we have content Builder available on the Message . Could you suggest a way of how to implement this using JAVA SDK 6.16.0 latest version 

### Expected behavior

I expect this functionality to be available or any alternate way to do it 

### How to reproduce

try compiling this code 
```
 graphServiceClient.users().byUserId(mailboxAddress).messages()
                .byMessageId(parentMessageId).attachments().byAttachmentId(attachmentId).content().get()
```

### SDK Version

6.16.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by Ndiritu** [comment]
Hi @raghucha
We generate a slightly limited set of canonical paths to reduce the size of the generated Graph SDK.
The file attachment byte content is available as a property of the object returned [here](https://learn.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&tabs=java#example-1-get-the-properties-of-a-file-attachment)

Also, for missing fluent methods, you can always use the `withUrl()` method to overwrite the request URL
