### ISSUE TITLE
How to get drive item by path

### ISSUE THREAD

**Issue by susanYYT** [microsoftgraph/msgraph-sdk-java#2213]
Hi, 

I'm using Graph v6, and I want to get DriveItem by path.

In v5, I use:
`DriveItem item = graphClient.sites(site.id).drives(d.id).root().itemWithPath(itemPath).buildRequest().get(); 
`
Now I use
`DriveItem item = graphClient.drives().byDriveId(d.getId()).items().byDriveItemId(itemPath).get();
`
But I received error: 
**com.microsoft.graph.models.odataerrors.ODataError: Item not found**

Does the input itemPath has something special in format?

For example, if my siteUrl is `myshare.sharepoint.com/sites/test1`, then if I get site by path, I can use `myshare.sharepoint.com:/sites/test1:` as input. While for drive item, the sheet relative path is `/test1/AdapterOffice365/DPtest.xls/int`. Could you please give me an example?

Best regards,
Susan

**Comment by Ndiritu** [comment]
Hi @susanYYT
Thank you for reaching out.
Please see a similar issue [here](https://github.com/microsoftgraph/msgraph-sdk-java/issues/1961#issuecomment-2082588357)
The relative path for your drive item should be `root:/test1/AdapterOffice365/DPtest.xls/int:`

Please let me know if this helps

**Comment by susanYYT** [comment]
Could the relative path contains _ ? I actually try `root:/A_test1/AdapterOffice365/DPtest.xls/int: `, but it doesn't work.

**Comment by susanYYT** [comment]
@Ndiritu Could you give some suggestions?

**Comment by Ndiritu** [comment]
Sorry for the delay @susanYYT.

Yes, based on the guidance [here](https://learn.microsoft.com/en-us/graph/onedrive-addressing-driveitems#uri-path-characters), underscores are allowed.

I'm wondering if your path is correct, is the `/int` at the end of the URL valid?

You can test your request path using https://developer.microsoft.com/en-us/graph/graph-explorer to double-check.

If you still have trouble, you can pass a custom URL using `withUrl()` to override the entire request URL:
```java
graphClient.drives().byDriveId("").items().byDriveItemId("").withUrl(
    "https://graph.microsoft.com/v1.0/..."
).get();
```

**Comment by susanYYT** [comment]
Since I've found the drive AdapterOffice365, I actually need to use `root:/DPtest.xls:`. I can get the drive item now. Thanks very much for your help.

**Comment by Ndiritu** [comment]
Glad you were able to resolve this @susanYYT . My apologies for the delayed response.
