### ISSUE TITLE
List sites isn't working when the Site.selected permission is applied and not ReadAll or ReadWrite.All

### ISSUE THREAD

**Issue by ihudedi** [microsoftgraph/msgraph-sdk-java#2241]
### Is your feature request related to a problem? Please describe the problem.

Hi,
When trying to fetch sites using /sites the sites not fetched when the permission for the app is Site.selected.
Is there any plan to support this permission in list sites?
Thanks,
Itay

### Describe the solution you'd like.

Adding ability to list sites for the selected sites applied in graph api

**Comment by ihudedi** [comment]
Hi @Ndiritu @baywet 
Do you know if it possible to implement this or it's required for the api?
Thanks,
Itay

**Comment by baywet** [comment]
Hi @ihudedi 
Thank you for using the SDK and for reaching out.

The service teams are not watching the SDK repositories, and we don't have access to the backend logs or code for security reasons. I suggest you ask your questions in the [Microsoft Graph Q&A forums](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) where the service team will be able to reply to you.

Let us know if you have any additional comments or questions.

Closing.
