### ISSUE TITLE
Generic method to fetch all collection elements with v6

### ISSUE THREAD

**Issue by Fuzzo** [microsoftgraph/msgraph-sdk-java#2248]
### Is your feature request related to a problem? Please describe the problem.

I am trying to write a generic method to fetch all elements of a collection. With v5 it was pretty easy:

```
public static <T, B extends BaseCollectionRequestBuilder<T, ?, ?, ?, ?>> List<T> fetchWholeCollection(B builder, Option... opt) {
  Objects.requireNonNull(builder);
  List<T> allObj = new ArrayList<>();
  int i=0;
  while (builder != null) {
	  BaseEntityCollectionRequest<T, ?, ?> req = (BaseEntityCollectionRequest<T, ?, ?>) builder.buildRequest(opt);
	  LOG.trace("#{} Url:          {}", i, req.getRequestUrl());
	  BaseCollectionPage<T, ?> page = req.get();
	  List<T> chunk = page.getCurrentPage();
	  LOG.trace("#{} Count:        {}", i, chunk.size());
	  allObj.addAll(chunk);
	  LOG.trace("#{} All count:    {}", i, allObj.size());
	  builder = (B) page.getNextPage();
	  if (builder != null) {
		  LOG.trace("#{} Next builder: {}", i, builder.getRequestUrl());
		  i++;
	  } else {
		  LOG.trace("#{} Last call!", i);
	  }
  }
  return allObj;
}
```

How I can write a similar generic method with v6?
What I'm doing wrong?
Thanks

### Describe the solution you'd like.

A common base class to be used to fetch all elements of a collection

**Comment by Ndiritu** [comment]
Hi @Fuzzo
The SDK provides a [Page Iterator](https://learn.microsoft.com/en-us/graph/sdks/paging?view=graph-rest-1.0&tabs=java) that allows you to fetch each page and execute a callback on each item should you prefer. Feel free to look at the linked docs and provide any feedback.
