### ISSUE TITLE
Feature Request: ISiteRequestBuilder.root method is missing

### ISSUE THREAD

**Issue by etovian** [microsoftgraph/msgraph-sdk-java#225]
### Expected behavior

Calling ISiteRequestBuilder.sites().root() will generate the following url: https://graph.microsoft.com/v1.0/sites/root

### Actual behavior

There is no .root() method, and calls with IGraphServiceClient.sites().buildRequest().get() produce the following exception:

com.microsoft.graph.http.GraphServiceException: Error code: invalidRequest
Error message: Cannot enumerate sites

GET https://graph.microsoft.com/v1.0/sites
SdkVersion : graph-java-v1.1.0

### Steps to reproduce the behavior

Attempt to use ISiteRequestBuilder.sites().root(), and you will find that the method "root" cannot be resolved.

NOTE: Calls to IGraphServiceClient.customRequest("/sites/root").buildRequest().get() produce the expected response, albeit not marshaled into a collection of Site objects.

**Comment by NakulSabharwal** [comment]
@etovian Thanks for reporting this issue. We are looking into it.

**Comment by MIchaelMainer** [comment]
@NakulSabharwal Here's what we did for this in .Net
https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/376/files

**Comment by teradevel** [comment]
The root does not exist in GroupSitesCollectionRequestBuilder either. It is not possible to get the site of a group atm.

graphClient.Groups[groupId].Sites <- has no 'Root'

**Comment by baywet** [comment]
@MIchaelMainer do you remember why you had to go with a manual extension and couldn't rely on the codegen here?

**Comment by MIchaelMainer** [comment]
@baywet Yes, site/root wasn't or couldn't be described in CSDL terms. This API was created before Microsoft Graph.

**Comment by baywet** [comment]
root is an identifier shorthand, not a navigation property or collection.
Doing the following works
```Java
final Site site = graphClient.sites("root").buildRequest().get();
System.out.println(site.displayName);
```

Closing
