### ISSUE TITLE
Casting/creating specific sub classes of directory objects

### ISSUE THREAD

**Issue by mriegler** [microsoftgraph/msgraph-sdk-java#232]
Getting, for example, the transitive members of a group returns lists of directory objects. I can filter them based on the oDataType property. How do I cast or create this specific subclass from that object?

Rough example:
```

for (DirectoryObject d : currentPage) {
  if (d.oDataType.equals("user")) {
    User u = ?????;
  }
}

```

**Comment by davidmoten** [comment]
From memory you need to get the id of the DirectoryObject and make another call to the api requesting a User specifically OR interrogate the raw json associated with the DirectoryObject for the bit you want. Ugly!

**Comment by davidmoten** [comment]
See #154

**Comment by baywet** [comment]
closing as duplicate of #154
