### ISSUE TITLE
Skiptoken methods are not available for pagination

### ISSUE THREAD

**Issue by samrajcse** [microsoftgraph/msgraph-sdk-java#233]
Hi Team,

I want to paginate the request using Skiptoken parameter. I don't see any option to do that. How can we do that with existing api? If it is not supported can you please support that?

Few interfaces reference,
IDriveItemCollectionPage
IDriveItemSearchCollectionPage

**Comment by skakanigit** [comment]
Hello Team,

We need this feature too. It is very critical that application we have designed need to paginate based on pageToken Id/ message Id. Could someone please comment on this thread and let us know if we should keep our hopes or not?

IUserCollectionPage
IMessageCollectionPage

**Comment by samrajcse** [comment]
@NakulSabharwal Can you please consider this request? I am waiting for so long. As of now I have extended and written. But when ever the update is taken, I need to redo it again.

**Comment by baywet** [comment]
Hey everyone,
Thanks you for the patience on the matter. I just joined the team which was under staffed.
I just merged in a fix to add the skiptoken and skip methods.
This should go out with release 2.0.1

**Comment by samrajcse** [comment]
Hi @baywet , I just reviewed 2.5.0 release and it is not available for Delta api's.

**Comment by baywet** [comment]
@samrajcse under 2.5.0 you can do this for the deltaLink (which contains the delta token)
```Java
graphClient.users().delta("https://mydeltalink").buildRequest().get();
```
However there might be a few quirks when it comes to delta for OneDrive or SharePoint and indeed, the skip token query parameter support seems to be missing.

If you want to pass in the skipLink/token, you either need to parse the link and do 

```Java
graphClient.users().delta("https://mydeltalink").buildRequest(new QueryOption("$skipToken", "the token")).get();
```

or you can use a custom request builder and pass in the whole link.

with 3.0.0 preview (see #628) you can do
```Java
graphClient.users().delta().buildRequest().deltaToken("the token").get();
```

```Java
graphClient.users().delta().buildRequest().deltaLink("https://mydeltalink").get();
```

```Java
graphClient.users().delta().buildRequest().skipToken("the skip token").get();
```

Now that I'm writing that, I'm wondering whether we should also have a .skipLink method?

**Comment by baywet** [comment]
scratch the remarks about skip/next link. You should be able to iterate through the results from a nextLink simply by using getNextPage on the response page.

**Comment by samrajcse** [comment]
Hi Vincent,

buildRequest(new QueryOption("$skipToken", "the token"))

If I am setting this, this will be part of the header only right. It
is not a part of the request parameter.


Regards,
*SAMRAJ.K*

**Comment by baywet** [comment]
QueryOption is for query parameters and HeaderOption is for request headers. So you are using the right option type.
But again, you shouldn't need to handle that.

```Java
final IUserDeltaCollectionPage firstPage = graphClient.users().delta().buildRequest().get();
if(firstpage.getNextPage() != null) {
  final IUserDeltaCollectionPage secondPage = firstPage.getNextPage().buildRequest().get();
}

**Comment by Moh-inc** [comment]
@baywet Correct me if i am wrong since im a fairly young dev. We would need to handle that if there is an issue with paginating and the request fails (even with the RetryHandler). i think it's an unlikely edge case, but still an edge case that should be handled

**Comment by baywet** [comment]
transient errors are still going to be handled by the middleware. But yes, you can still get non-transient errors like a server error, or the parent resource can be deleted while you're paging (e.g. the tenant gets deleted), etc...
