### ISSUE TITLE
Migrate from Gson to Jackson

### ISSUE THREAD

**Issue by Kitanotori** [microsoftgraph/msgraph-sdk-java#234]
## Why

1. Jackson is the default in many - if not most - major frameworks, such as Spring Boot and Play
1. Jackson tends to have better performance (e.g. https://github.com/fabienrenaud/java-json-benchmark)
1. Jackson is being more actively developed (https://github.com/FasterXML/jackson-databind/graphs/contributors vs https://github.com/google/gson/graphs/contributors)

**Comment by NakulSabharwal** [comment]
Thanks for creating this issue and providing links. We will look into Jackson and compare it with Gson on basis of performance, library size and other features.

**Comment by glani** [comment]
@Kitanotori according to SDK it is possible to change serializer. It performs deserialization from the string:

        final String rawJson = streamToString(in);
        return getSerializer().deserializeObject(rawJson, clazz, responseHeaders);

**Comment by baywet** [comment]
@darrelmiller any thoughts on this one?

**Comment by darrelmiller** [comment]
At the current time there is not sufficient ROI for changing the default serializer.  We will reconsider in the future when doing other expected serialization work.
