### ISSUE TITLE
Allow access to ArchiveMsgFolderRoot

### ISSUE THREAD

**Issue by dspurling** [microsoftgraph/msgraph-sdk-java#236]
I would like to be able to access messages in In-Place Archive.  When I execute this query https://graph.microsoft.com/beta/me/mailfolders/ArchiveMsgFolderRoot in Graph Explorer I get the same results as if I had executed https://graph.microsoft.com/beta/me/mailfolders/MsgFolderRoot.

**Comment by deepak2016** [comment]
Thanks for reporting the issue. I'm looking into it.

**Comment by dspurling** [comment]
@deepak2016 Have you had a change to look into this issue?

**Comment by deepak2016** [comment]
@NakulSabharwal please have a look.

**Comment by alokob** [comment]
Hi , is this feature available now ?

**Comment by MIchaelMainer** [comment]
I don't believe it is. Please post a feature request here:
https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests?query=archive

**Comment by baywet** [comment]
I'm going to close this issue since it's pending on a service release.
More generally, we've just released a [beta version of our SDK](https://github.com/microsoftgraph/msgraph-sdk-java) which will allow you to access the beta APIs.
