### ISSUE TITLE
Making Voice/Video calls using Android Custom application

### ISSUE THREAD

**Issue by krishnaprabhas** [microsoftgraph/msgraph-sdk-java#237]
I looking out for samples to use Microsoft Graph Beta API for Audio and Video calls in my own Android application. I am not able to find any examples of this type. Request you to help me with the links which can help. Also need a suggestion whether i can use Microsoft Team Graph API / Teams SDK/ Skype for business SDK to implement Voice/Video calls in my android app. Please suggest

**Comment by NakulSabharwal** [comment]
Thanks for creating this issue. Here are few links that may help you in usage
https://docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-beta
https://docs.microsoft.com/en-us/graph/api/resources/calls-api-overview?view=graph-rest-beta

**Comment by krishnaprabhas** [comment]
Hi NakulSabharwal,

Thanks for your reply. But I am not able to see samples or SDK with Voice/video calls specific to Android/iOS mobile applications. Moreover i am also worried whether i can go with Beta APIs for production. Can you please guide me and suggest me on this. Or using Skype for Business would be a better option for Voice/Video calls. Please suggest.

**Comment by krishnaprabhas** [comment]
Can any one suggest me on my above query?

**Comment by krishnaprabhas** [comment]
@NakulSabharwal please suggest

**Comment by NakulSabharwal** [comment]
@krishnaprabhas If you're interested in new or enhanced APIs that are still in preview status, see [Microsoft Graph beta endpoint reference](https://docs.microsoft.com/en-us/graph/api/overview?toc=./ref/toc.json&view=graph-rest-beta). Be aware that APIs in preview status are subject to change, and may break existing scenarios without notice. Don't take a production dependency on APIs in the beta endpoint. Ref - https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0

For sample please elaborate on scenario you want to have in app so that I can make a sample, since currently we dont have video/voice calling samples. Thanks.

**Comment by krishnaprabhas** [comment]
@NakulSabharwal Thanks for your reply. In one of our applications we need to implement chats , Calls & Online meeting functionalities. The users of this feature have license to O365 and Microsoft Teams.
We will allow these users to chat & make calls via our own custom application which will internally should use Graph API/Teams/Skype for business.

I need your recommendation on the above.  Your recommendation will help me in freezing the Tech Stack for my project.

**Comment by krishnaprabhas** [comment]
@darrelmiller  Please suggest me on my above query. Appreciate your early response.

**Comment by MIchaelMainer** [comment]
@krishnaprabhas Please understand that all features in the beta endpoint are subject to change. 

@ksikorsk Can you provide guidance and expectations for using the Teams Graph APIs for voice and video calls?

**Comment by ksikorsk** [comment]
@krishnaprabhas we do not yet have SDK available for android/java.  Once our APIs are published to v1.0 the graph team will generate new SDKs.  Even then we will need to validate that they are working as expected.

In terms of samples, we do plan to eventually release samples in other languages, but I cannot speak as to when that will happen.  Your best bet is still to model your code based on the existing c# samples.

You mentioned `Android`... are you building a client app?  Currently the calling APIs only support bots/applications, not individuals.

Keep in mind that the Microsoft.Skype.Bots.Media nuget is a dependency for Application Hosted Media bots, and it is only supported for .NET Framework.  There is no plan to release this package cross platform that I am aware of.  That unfortunately ties you to a windows machine.  If you could speak about your specific scenario, perhaps I can suggest which APIs you'll require.

**Comment by krishnaprabhas** [comment]
@ksikorsk Thanks for sharing the information. I would like to implement Calls (audio/ Video) and online meeting feature  via my custom Android/iOS mobile application.  Request you to suggest me the right approach i.e using Graph API/Teams SDK/ Skype for Businesss SDK. Appreciate your response.

**Comment by krishnaprabhas** [comment]
@ksikorsk  can you update me with your suggestions?

**Comment by ksikorsk** [comment]
Hi @krishnaprabhas... we do have some clients that integrate our service with some hardware.  However, they have introduced a gateway service between the client and Graph Calling APIs.  Something like this:

`Hardware  <---->  Gateway <----> Graph`

There are a couple reasons why it has to be done this way:
1. App Hosted Media applications are only supported from within a Windows environment.
2. Hardware usually does not host an http service, so needs another mechanism to receive notifications from our graph service.

It is your responsibility to ensure that media and signalling flow between hardware and gateway.  For a sample Gateway implementation please look at the HueBot or AudioVideoPlaybackBot samples.  Both samples process raw video.

https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/LocalMediaSamples

**Comment by siva1545** [comment]
Hello @ksikorsk @darrelmiller 
I guess this thread is almost year old
Is there any updates on supporting audio/video calls using graph API from client side on a browser (like using Angular or JavaScript)?

I see some documentation on audio/video call graph APIs here, but I don't see any examples or SDK (Angular or JavaScript)
https://docs.microsoft.com/en-us/graph/api/resources/communications-api-overview?view=graph-rest-1.0

**Comment by baywet** [comment]
Hey @siva1545 
Please open a new issue in the [javascript repository](https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/new) it will get more visibility.
Thanks

**Comment by siva1545** [comment]
Thanks
Raised issue https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/393 <https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/393>


Thanks
Siva
