### ISSUE TITLE
Lower bounded wildcards for callbacks

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#24]
Wherever we have methods in the api like:
void post(final Calendar newCalendar, final ICallback<Calendar> callback);
we can offer more flexibility (reuse) for the caller by using this signature:
void post(final Calendar newCalendar, final ICallback<? super Calendar> callback);
I started making a PR for this but stopped when I encountered changes to the generated code. Can we sort this one out?
[AB#6041](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6041)

**Comment by deepak2016** [comment]
@davidmoten wanted to understand more on the use cases of Lower bounded wildcards for callbacks. Any insight will be helpful.

**Comment by davidmoten** [comment]
On leave this week. I'll get back to you next week.

**Comment by davidmoten** [comment]
@deepak2016 
I'll just quote from above:

>Reuse of callback instances. Depends a bit on the inheritance structure of
the objects in use. At the lowest level allows to pass a single
`Callback<Object>` instance for perf testing or logging without having to
pretend its a valid callback by casting (type erasure enables this). For me
this is a standard thing to do with a public api because I don't want to
make assumptions about how the api is used and there is no cost for me (in
terms of changes to the implementation) to provide it.

Is there anything you don't understand there?

**Comment by darrelmiller** [comment]
Hey @davidmoten !  @baywet  and I reviewed this and it makes sense to us.  Vincent will make the change in the code gen.

**Comment by baywet** [comment]
Note for myself: replace ICallback<X> by ICallback<? super X>

**Comment by baywet** [comment]
Hey @davidmoten 
Thanks for your feedback and thanks for your patience on the matter.
I authored #498 to fix this issue and merging the PR will close this issue.
