### ISSUE TITLE
Acess SharePoint using Microsoft Graph SDK for Java using username/password instead of an access token

### ISSUE THREAD

**Issue by selimelawwa** [microsoftgraph/msgraph-sdk-java#240]
I am trying to connect my Java application to SharePoint. I am able to connect to it via Apache HttpClient using only UserName, Password and Site url without the need to register my app in AAD or any access token.

I am following the connection approach of [ Authentication to SharePoint from Java](https://stackoverflow.com/a/29609502/8863925)

Now I can connect to SharePoint with only username, password and site url and query lists and so on but the responses need much parsing/handling and I can't full benefit from using the Microsoft Graph SDK. What I need to do is be able to use the Microsoft Graph SDK with this kind of authentication (username/password) instead of using an access token / client id ...etc.

Is there a way to handle to solve such a problem? any solution to implement this kind of authentication using Microsoft Graph SDK

**Comment by NakulSabharwal** [comment]
Hi @selimelawwa , Thanks for creating this issue. We provide [authentication providers](https://github.com/microsoftgraph/msgraph-sdk-java-auth), as I can understand you can use UsernamePasswordProvider along with MicrosoftGraphSDK. Also, you will need to [register your application](https://apps.dev.microsoft.com/portal/register-app) and get client id from here.

**Comment by NakulSabharwal** [comment]
Closing this issue as its related to usage. Please reopen if you are still finding any problem on this issue.
