### ISSUE TITLE
Generic typing of BaseRequest, BaseStreamRequest

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#25]
From what I can see BaseRequest and BaseStreamRequest should have a generic type corresponding to the responseClass. Applying this change is pretty straightforward but changes need to be made to the generated classes also. What do you suggest?
[AB#6044](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6044)

**Comment by davidmoten** [comment]
This is still an issue, not hard to fix for an experienced dev, happy to help and it is a *major structural deficiency under the covers*.I assume it will need some contribution on the generator side as well. 

Can this get some priority from team?

As far as I'm concerned the generator side is painful to contribute to (see https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/141) so won't be me contributing to the generator till that issue is addressed.

**Comment by darrelmiller** [comment]
@davidmoten I will bring this up with our devs.  It doesn't look like a hard fix on the surface and feels like a broken window that should be repaired.
