### ISSUE TITLE
Can I get the reservation rules for the conference room?

### ISSUE THREAD

**Issue by shibd** [microsoftgraph/msgraph-sdk-java#257]
hi, Can I get the reservation rules for the conference room?
case:

Are Conflict Meetings Permissible
Maximum reservation time
ths.

**Comment by NakulSabharwal** [comment]
Thanks for creating this issue. This api is currently in beta reference-  https://docs.microsoft.com/en-us/graph/api/user-findrooms?view=graph-rest-beta&tabs=cs .

**Comment by shibd** [comment]
This link does not see how to get the conference room configuration.
I want to get the conference room configuration.
Case:
1. Are Conflict Meetings Permissible
2. Maximum reservation time
