### ISSUE TITLE
ResourceNotFound error

### ISSUE THREAD

**Issue by bismoy2013** [microsoftgraph/msgraph-sdk-java#260]
https://social.msdn.microsoft.com/Forums/en-US/f03fef72-6670-494c-a96b-6b10daff203e/why-am-i-getting-quottoken-does-not-exist-errorquot-whenever-i-am-trying-to-call?forum=WindowsAzureAD

Request URL

https://graph.microsoft.com/v1.0/users/{user_id}/events?$select=subject,body,bodyPreview,organizer,attendees,start,end,location

Response error :
{
    "error": {
        "code": "ResourceNotFound",
        "message": "Resource could not be discovered.",
        "innerError": {
            "request-id": "2372ba00-e199-46c5-b68c-5122f22c7840",
            "date": "2019-06-11T03:38:58"
        }
    }
}

**Comment by NakulSabharwal** [comment]
@bismoy2013 Thanks for creating this issue. To verify if the resource actually exits with the user_id you are using, please use https://developer.microsoft.com/en-us/graph/graph-explorer and see if you are getting a response logging in using the same account used to make this request.
