### ISSUE TITLE
Build and deploy Beta SDK for Java

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-java#282]

**Comment by baywet** [comment]
https://github.com/microsoftgraph/msgraph-sdk-java

**Comment by davidmoten** [comment]
Why closed?

**Comment by baywet** [comment]
@davidmoten sorry, the link I originally had posted was the wrong one. https://github.com/microsoftgraph/msgraph-beta-sdk-java
We published the beta SDK last week :)
