### ISSUE TITLE
Add conflictBehavior into DriveItemUploadableProperties

### ISSUE THREAD

**Issue by guybmayor** [microsoftgraph/msgraph-sdk-java#283]
Hey,

Please add @microsoft.graph.conflictBehavior into DriveItemUploadableProperties.
It's useful when trying to replace existing files

**Comment by yashjain12yj** [comment]
Any updates on this, If not added, could let us know how we can send this additional information @microsoft.graph.conflictBehavior with DriveItemUploadableProperties?

**Comment by baywet** [comment]
Hi everyone.
Thanks for your feedback and your patience.
You can see an example on how to do it in #393.
However right now there seems to be a bug with it that I have to investigate.
I'm going to close this issue to avoid tracking duplicates, I suggest you subscribe to/upvote the other issue.
