### ISSUE TITLE
ChatMessage not implemented

### ISSUE THREAD

**Issue by PaulWoods4422** [microsoftgraph/msgraph-sdk-java#285]
There is a ChatMessage type defined on the API: 
https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta 
This is not implemented in the SDK.

Expected Behavour:
Basic types should be implemented.

**Comment by MIchaelMainer** [comment]
Need to generate Java beta service library.

**Comment by darrelmiller** [comment]
Tracked in #282
