### ISSUE TITLE
Worksheet range: the methods for the IWorkbookWorksheetRangeRequestBuilder class that are documented are missing, with the exception of buildRequest.

### ISSUE THREAD

**Issue by dmolaro-jama** [microsoftgraph/msgraph-sdk-java#289]
The java sdk client is missing the methods for the IWorkbookWorksheetRangeRequestBuilder class that are documented, with the exception of buildRequest.
        <dependency>
            <groupId>com.microsoft.graph</groupId>
            <artifactId>microsoft-graph</artifactId>
            <version>1.6.0</version>
        </dependency>

Example:
graphClient.me().drive().items("{id}").workbook().worksheets("{sheet-id}")
	.range("$A$1").format().font()
	.buildRequest()
	.patch(workbookRangeFont);

.format() is not available, as well as .clear(), .merge(), .delete() etc...

---- Davide
Expected behavior
.format() is available, as well as .clear(), .merge(), .delete() etc...
Actual behavior
Only buildRequest() is available.
Steps to reproduce the behavior
Write some code that returns a IWorkbookWorksheetRangeRequestBuilder, like the examples in the docs.
[AB#6037](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6037)

**Comment by MIchaelMainer** [comment]
I think there are two issues here. @andrueastman we may be generating incorrect sample code for this scenario. On @MIchaelMainer this is another example where we need to support composable functions in our generator.

**Comment by baywet** [comment]
Hey @dmolaro-jama 
Thanks for the feedback and for the patience on this one.
I've just authored #466 which fixes that issue.
The issue will be closed once the PR gets merged.
