### ISSUE TITLE
ChunkedUploadProvider could not upload files to personal onedrive

### ISSUE THREAD

**Issue by intelc0re** [microsoftgraph/msgraph-sdk-java#290]
Now I got the access token with scope "Files.ReadWrite.All" and generated IGraphServiceClient.
But I could only upload files to onedrive for business.When I uploaded files to personal onedrive,it catched an exception with message "Request failed with error, retry if necessary.".

### Expected behavior
IGraphServiceClient could upload files both worked in onedrive for business and personal onedrive.

### Actual behavior
Only worked in onedrive for business.

**Comment by MIchaelMainer** [comment]
Please provide an HTTP capture of the failed call and share it with us.

**Comment by intelc0re** [comment]
> Please provide an HTTP capture of the failed call and share it with us.

Thank you for your reply.When I use MsGraph version 1.4.0,it could catch an exception with http response code 407(Proxy Authentication Required).But version 1.6.0 could not catch any exceptions.


		try {
			UploadSession uploadSession = graphClient
	    			.me()
	    			.drive()
	    			.root()
	    			.itemWithPath("test.txt")
	    			.createUploadSession(new DriveItemUploadableProperties())
	    			.buildRequest()
	    			.post();

	    	ChunkedUploadProvider<DriveItem> chunkedUploadProvider = new ChunkedUploadProvider<DriveItem>(
	    			uploadSession,
	    			graphClient,
	    			uploadFile,
	    			fileSize,
	    			DriveItem.class);

	    	chunkedUploadProvider.upload(callback);

		} catch (GraphFatalServiceException e) {
			
		} catch (GraphServiceException e) {
			
		} catch (ClientException e) {
                    //MsGraph version 1.4.0 catched here
                   //java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.0 407 Proxy Authentication Required"
		} catch (Exception e) {

		}


And in the same environment,I could upload files to onedrive for business with no errors.So I think if it is because the upload url is different between onedrive for business and personal onedrive.And the proxy has banned the url of personal onedrive.

**Comment by baywet** [comment]
Hey @intelc0re 
Thanks for your feedback and for your patience on the matter.
I've just authored #481 which fixes a number of bugs in this area, including a bug specific to OneDrive consumer where the response headers are not cased the same way as the version for business and the code wasn't accounting for that and derailing... 
Merging the PR will close this issue.
