### ISSUE TITLE
Error message: The specified list was not found

### ISSUE THREAD

**Issue by kozuch** [microsoftgraph/msgraph-sdk-java#293]
I am trying to retrieve list item from Sharepoint but get following exception:
SEVERE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: itemNotFound

The same REST API url works in Graph explorer and returns valid list item (see below error).

Detailed log:

zář 13, 2019 1:17:09 ODP. com.microsoft.graph.logger.DefaultLogger logDebug
INFO: Starting to send request, URL https://graph.microsoft.com/v1.0/sites/csdevel.sharepoint.com,5fbe67ce-b5fb-4312-9ad2-db1a221bb966,ad2121f2-3c01-4fb6-bce1-ae8bd3e642e7/lists/93dcc7c0-63df-40cd-8d2c-55eb2afd7602/items/1
zář 13, 2019 1:17:09 ODP. com.microsoft.graph.logger.DefaultLogger logDebug
INFO: Request Method GET
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logDebug
INFO: Response code 404, Not Found
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logDebug
INFO: Handling error response
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logDebug
INFO: Deserializing type GraphErrorResponse
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204Graph service exception Error code: itemNotFound
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204Error message: The specified list was not found
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204GET https://graph.microsoft.com/v1.0/sites/csdevel.sharepoint.com,5fbe67ce-b5fb-4312-9ad2-db1a221bb966,ad2121f2-3c01-4fb6-bce1-ae8bd3e642e7/lists/93dcc7c0-63df-40cd-8d2c-55eb2afd7602/items/1
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204SdkVersion : graph-java/v1.6.0
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204Authorization : Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6Imtwa05pdUt3ZXdKczZQUHQxSHAyRVdqb0U0T0djeXQza1RBNmhJMjZpZHciLCJhbGciOiJSUzI1NiIsIng1dCI6ImllX3FXQ1hoWHh0MXpJRXN1NGM3YWNRVkduNCIsImtpZCI6ImllX3FXQ1hoWHh0MXpJRXN1NGM3YWNRVkduNCJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9kNjk0ZjU3NC1kZDQ0LTQ2NDQtOWE1Yi1kZmRkMTg1OTQ4Y2IvIiwiaWF0IjoxNTY4MzczMTIwLCJuYmYiOjE1NjgzNzMxMjAsImV4cCI6MTU2ODM3NzAyMCwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IjQyRmdZSmhjTU1XeXl5amtZQXovYnhQdlRjc3NTbWExbGd0NVByOXhKVWhsc2JqQTluUUEiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6IkphdmEgR3JhcGggVHV0b3JpYWwiLCJhcHBpZCI6ImEyY2NhMjYxLWM1MmMtNGU0Zi1iZGFjLTIwNWJlOWRiMGJmMSIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiS3VjZXJhIiwiZ2l2ZW5fbmFtZSI6IkphbiIsImlwYWRkciI6IjgxLjAuMTk4LjE2OCIsIm5hbWUiOiJKYW4gS3VjZXJhIiwib2lkIjoiNGRmZDk2ZDQtMmM5NS00YTI4LTk2NzUtYjNiNjMxYzk5MGY4IiwicGxhdGYiOiIxNCIsInB1aWQiOiIxMDAzMjAwMDY2Q0MxQTM4Iiwic2NwIjoiQ2FsZW5kYXJzLlJlYWQgb3BlbmlkIHByb2ZpbGUgVXNlci5SZWFkIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoiNF9fbHF4aTVzbTk3WkFDbVpxWjMwd2xLaUhMOWo4MC1zSE9iUDd6RWdFZyIsInRpZCI6ImQ2OTRmNTc0LWRkNDQtNDY0NC05YTViLWRmZGQxODU5NDhjYiIsInVuaXF1ZV9uYW1lIjoiamt1Y2VyYUBjc2RldmVsLm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6ImprdWNlcmFAY3NkZXZlbC5vbm1pY3Jvc29mdC5jb20iLCJ1dGkiOiJ1LThpdzdwM3JVYWoxRU51V1VCQUFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJmMjhhMWY1MC1mNmU3LTQ1NzEtODE4Yi02YTEyZjJhZjZiNmMiLCI2OTA5MTI0Ni0yMGU4LTRhNTYtYWE0ZC0wNjYwNzViMmE3YTgiXSwieG1zX3N0Ijp7InN1YiI6IkhKTU05V2VnWTZlU184TXg3bnNhaW9GeENrSVJWWWVlWHprQ0NoYXhOclkifSwieG1zX3RjZHQiOjE1NjQ2NjUwNTN9.ZFauDcQw1rnilISLu4f-O0njECgphs1QwHqe9jpwD8oOaE6vtVwR-o74vR8E3UDeO3hiufyckuX7dzEDS1z-eXFEux57PeeVMbmodoJHH2CH6lY-YlDcp7K_TT149UTVFS9hisphZjTsJILHWwpkZ3nqgudvGCuMFOEkY-ermHTt3fNrvo61D-hMAKDILm3fJ_v7aliM21js7cvCo9EkGSZoE7LVoPx8wWGWmfNmEQxQMWtWXmCaIy20dad_9WVhj_xivx9QY7bNuOCIwjrgIFY0lNXG85tdrTrGRRobgfs6mejC4XZwKl5jqST5aL5Yhpf_uCPynPdz-5OQXUuS1A
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204404 : Not Found
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204Transfer-Encoding : chunked
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204Strict-Transport-Security : max-age=31536000
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204Cache-Control : private
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceC","Ring":"5","ScaleUnit":"001","RoleInstance":"AGSFE_IN_19","ADSiteName":"WEU"}}
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204client-request-id : 5f896862-5b6d-4232-8fbc-e860f07db8f3
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204Duration : 992.1109
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204request-id : 4d684aa5-d899-4dd3-ab49-8505e03eec6f
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204Date : Fri, 13 Sep 2019 11:17:09 GMT
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204Content-Type : application/json
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204{
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204  "error": {
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204    "code": "itemNotFound",
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204    "message": "The specified list was not found",
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204    "innerError": {
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204      "request-id": "4d684aa5-d899-4dd3-ab49-8505e03eec6f",
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204      "date": "2019-09-13T11:17:09"
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204    }
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204  }
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204}
zář 13, 2019 1:17:10 ODP. com.microsoft.graph.logger.DefaultLogger logError
SEVERE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: itemNotFound
Error message: The specified list was not found

GET https://graph.microsoft.com/v1.0/sites/csdevel.sharepoint.com,5fbe67ce-b5fb-4312-9ad2-db1a221bb966,ad2121f2-3c01-4fb6-bce1-ae8bd3e642e7/lists/93dcc7c0-63df-40cd-8d2c-55eb2afd7602/items/1
SdkVersion : graph-java/v1.6.0
Authorization : Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6Imtwa05pdUt3ZXdKczZQUHQxSHAyRVdqb0U0T0djeXQza1RBNmhJMjZpZHciLCJhbGciOiJSUzI1NiIsIng1dCI6ImllX3FXQ1hoWHh0MXpJRXN1NGM3YWNRVkduNCIsImtpZCI6ImllX3FXQ1hoWHh0MXpJRXN1NGM3YWNRVkduNCJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9kNjk0ZjU3NC1kZDQ0LTQ2NDQtOWE1Yi1kZmRkMTg1OTQ4Y2IvIiwiaWF0IjoxNTY4MzczMTIwLCJuYmYiOjE1NjgzNzMxMjAsImV4cCI6MTU2ODM3NzAyMCwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IjQyRmdZSmhjTU1XeXl5amtZQXovYnhQdlRjc3NTbWExbGd0NVByOXhKVWhsc2JqQTluUUEiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6IkphdmEgR3JhcGggVHV0b3JpYWwiLCJhcHBpZCI6ImEyY2NhMjYxLWM1MmMtNGU0Zi1iZGFjLTIwNWJlOWRiMGJmMSIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiS3VjZXJhIiwiZ2l2ZW5fbmFtZSI6IkphbiIsImlwYWRkciI6IjgxLjAuMTk4LjE2OCIsIm5hbWUiOiJKYW4gS3VjZXJhIiwib2lkIjoiNGRmZDk2ZDQtMmM5NS00YTI4LTk2NzUtYjNiNjMxYzk5MGY4IiwicGxhdGYiOiIxNCIsInB1aWQiOiIxMDAzMjAwMDY2Q0MxQTM4Iiwic2NwIjoiQ2FsZW5kYXJzLlJlYWQgb3BlbmlkIHByb2ZpbGUgVXNlci5SZWFkIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoiNF9fbHF4aTVzbTk3WkFDbVpxWjMwd2xLaUhMOWo4MC1zSE9iUDd6RWdFZyIsInRpZCI6ImQ2OTRmNTc0LWRkNDQtNDY0NC05YTViLWRmZGQxODU5NDhjYiIsInVuaXF1ZV9uYW1lIjoiamt1Y2VyYUBjc2RldmVsLm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6ImprdWNlcmFAY3NkZXZlbC5vbm1pY3Jvc29mdC5jb20iLCJ1dGkiOiJ1LThpdzdwM3JVYWoxRU51V1VCQUFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJmMjhhMWY1MC1mNmU3LTQ1NzEtODE4Yi02YTEyZjJhZjZiNmMiLCI2OTA5MTI0Ni0yMGU4LTRhNTYtYWE0ZC0wNjYwNzViMmE3YTgiXSwieG1zX3N0Ijp7InN1YiI6IkhKTU05V2VnWTZlU184TXg3bnNhaW9GeENrSVJWWWVlWHprQ0NoYXhOclkifSwieG1zX3RjZHQiOjE1NjQ2NjUwNTN9.ZFauDcQw1rnilISLu4f-O0njECgphs1QwHqe9jpwD8oOaE6vtVwR-o74vR8E3UDeO3hiufyckuX7dzEDS1z-eXFEux57PeeVMbmodoJHH2CH6lY-YlDcp7K_TT149UTVFS9hisphZjTsJILHWwpkZ3nqgudvGCuMFOEkY-ermHTt3fNrvo61D-hMAKDILm3fJ_v7aliM21js7cvCo9EkGSZoE7LVoPx8wWGWmfNmEQxQMWtWXmCaIy20dad_9WVhj_xivx9QY7bNuOCIwjrgIFY0lNXG85tdrTrGRRobgfs6mejC4XZwKl5jqST5aL5Yhpf_uCPynPdz-5OQXUuS1A

404 : Not Found
Transfer-Encoding : chunked
Strict-Transport-Security : max-age=31536000
Cache-Control : private
x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceC","Ring":"5","ScaleUnit":"001","RoleInstance":"AGSFE_IN_19","ADSiteName":"WEU"}}
client-request-id : 5f896862-5b6d-4232-8fbc-e860f07db8f3
Duration : 992.1109
request-id : 4d684aa5-d899-4dd3-ab49-8505e03eec6f
Date : Fri, 13 Sep 2019 11:17:09 GMT
Content-Type : application/json
{
  "error": {
    "code": "itemNotFound",
    "message": "The specified list was not found",
    "innerError": {
      "request-id": "4d684aa5-d899-4dd3-ab49-8505e03eec6f",
      "date": "2019-09-13T11:17:09"
    }
  }
}

Exception in thread "main" com.microsoft.graph.http.GraphServiceException: Error code: itemNotFound
Error message: The specified list was not found

GET https://graph.microsoft.com/v1.0/sites/csdevel.sharepoint.com,5fbe67ce-b5fb-4312-9ad2-db1a221bb966,ad2121f2-3c01-4fb6-bce1-ae8bd3e642e7/lists/93dcc7c0-63df-40cd-8d2c-55eb2afd7602/items/1
SdkVersion : graph-java/v1.6.0
Authorization : Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6Imtwa05pdUt3ZXdKczZQUHQxSHAyRVdqb0U0T0djeXQza1RBNmhJMjZpZHciLCJhbGciOiJSUzI1NiIsIng1dCI6ImllX3FXQ1hoWHh0MXpJRXN1NGM3YWNRVkduNCIsImtpZCI6ImllX3FXQ1hoWHh0MXpJRXN1NGM3YWNRVkduNCJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9kNjk0ZjU3NC1kZDQ0LTQ2NDQtOWE1Yi1kZmRkMTg1OTQ4Y2IvIiwiaWF0IjoxNTY4MzczMTIwLCJuYmYiOjE1NjgzNzMxMjAsImV4cCI6MTU2ODM3NzAyMCwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IjQyRmdZSmhjTU1XeXl5amtZQXovYnhQdlRjc3NTbWExbGd0NVByOXhKVWhsc2JqQTluUUEiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6IkphdmEgR3JhcGggVHV0b3JpYWwiLCJhcHBpZCI6ImEyY2NhMjYxLWM1MmMtNGU0Zi1iZGFjLTIwNWJlOWRiMGJmMSIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiS3VjZXJhIiwiZ2l2ZW5fbmFtZSI6IkphbiIsImlwYWRkciI6IjgxLjAuMTk4LjE2OCIsIm5hbWUiOiJKYW4gS3VjZXJhIiwib2lkIjoiNGRmZDk2ZDQtMmM5NS00YTI4LTk2NzUtYjNiNjMxYzk5MGY4IiwicGxhdGYiOiIxNCIsInB1aWQiOiIxMDAzMjAwMDY2Q0MxQTM4Iiwic2NwIjoiQ2FsZW5kYXJzLlJlYWQgb3BlbmlkIHByb2ZpbGUgVXNlci5SZWFkIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoiNF9fbHF4aTVzbTk3WkFDbVpxWjMwd2xLaUhMOWo4MC1zSE9iUDd6RWdFZyIsInRpZCI6ImQ2OTRmNTc0LWRkNDQtNDY0NC05YTViLWRmZGQxODU5NDhjYiIsInVuaXF1ZV9uYW1lIjoiamt1Y2VyYUBjc2RldmVsLm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6ImprdWNlcmFAY3NkZXZlbC5vbm1pY3Jvc29mdC5jb20iLCJ1dGkiOiJ1LThpdzdwM3JVYWoxRU51V1VCQUFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJmMjhhMWY1MC1mNmU3LTQ1NzEtODE4Yi02YTEyZjJhZjZiNmMiLCI2OTA5MTI0Ni0yMGU4LTRhNTYtYWE0ZC0wNjYwNzViMmE3YTgiXSwieG1zX3N0Ijp7InN1YiI6IkhKTU05V2VnWTZlU184TXg3bnNhaW9GeENrSVJWWWVlWHprQ0NoYXhOclkifSwieG1zX3RjZHQiOjE1NjQ2NjUwNTN9.ZFauDcQw1rnilISLu4f-O0njECgphs1QwHqe9jpwD8oOaE6vtVwR-o74vR8E3UDeO3hiufyckuX7dzEDS1z-eXFEux57PeeVMbmodoJHH2CH6lY-YlDcp7K_TT149UTVFS9hisphZjTsJILHWwpkZ3nqgudvGCuMFOEkY-ermHTt3fNrvo61D-hMAKDILm3fJ_v7aliM21js7cvCo9EkGSZoE7LVoPx8wWGWmfNmEQxQMWtWXmCaIy20dad_9WVhj_xivx9QY7bNuOCIwjrgIFY0lNXG85tdrTrGRRobgfs6mejC4XZwKl5jqST5aL5Yhpf_uCPynPdz-5OQXUuS1A

404 : Not Found
Transfer-Encoding : chunked
Strict-Transport-Security : max-age=31536000
Cache-Control : private
x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceC","Ring":"5","ScaleUnit":"001","RoleInstance":"AGSFE_IN_19","ADSiteName":"WEU"}}
client-request-id : 5f896862-5b6d-4232-8fbc-e860f07db8f3
Duration : 992.1109
request-id : 4d684aa5-d899-4dd3-ab49-8505e03eec6f
Date : Fri, 13 Sep 2019 11:17:09 GMT
Content-Type : application/json
{
  "error": {
    "code": "itemNotFound",
    "message": "The specified list was not found",
    "innerError": {
      "request-id": "4d684aa5-d899-4dd3-ab49-8505e03eec6f",
      "date": "2019-09-13T11:17:09"
    }
  }
}

	at com.microsoft.graph.http.GraphServiceException.createFromConnection(GraphServiceException.java:446)
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:485)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:375)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:204)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:184)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:306)
	at com.microsoft.graph.requests.extensions.ListItemRequest.get(ListItemRequest.java:52)
	at com.contoso.Graph.getListItem(Graph.java:136)
	at com.contoso.App.main(App.java:102)

Process finished with exit code 1

-------------------

Result from calling Graph explorer with same url:

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites('csdevel.sharepoint.com%2C5fbe67ce-b5fb-4312-9ad2-db1a221bb966%2Cad2121f2-3c01-4fb6-bce1-ae8bd3e642e7')/lists('93dcc7c0-63df-40cd-8d2c-55eb2afd7602')/items/$entity",
    "@odata.etag": "\"af1b759f-f427-4f12-a0b1-0c3ea28852f0,2\"",
    "createdDateTime": "2019-09-11T07:01:21Z",
    "eTag": "\"af1b759f-f427-4f12-a0b1-0c3ea28852f0,2\"",
    "id": "1",
    "lastModifiedDateTime": "2019-09-11T07:41:57Z",
    "webUrl": "https://csdevel.sharepoint.com/sites/KomunikacniWeb1/Lists/List1/1_.000",
    "createdBy": {
        "user": {
            "email": "xxx",
            "id": "4dfd96d4-2c95-4a28-9675-b3b631c990f8",
            "displayName": "xxx"
        }
    },
    "lastModifiedBy": {
        "user": {
            "email": "xxx",
            "id": "4dfd96d4-2c95-4a28-9675-b3b631c990f8",
            "displayName": "xxx"
        }
    },
    "parentReference": {
        "siteId": "csdevel.sharepoint.com,5fbe67ce-b5fb-4312-9ad2-db1a221bb966,ad2121f2-3c01-4fb6-bce1-ae8bd3e642e7"
    },
    "contentType": {
        "id": "0x01008F0EAD8D216A0243AC46B7EA1154D3AE"
    },
    "fields@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites('csdevel.sharepoint.com%2C5fbe67ce-b5fb-4312-9ad2-db1a221bb966%2Cad2121f2-3c01-4fb6-bce1-ae8bd3e642e7')/lists('93dcc7c0-63df-40cd-8d2c-55eb2afd7602')/items('1')/fields/$entity",
    "fields": {
        "@odata.etag": "\"af1b759f-f427-4f12-a0b1-0c3ea28852f0,2\"",
        "id": "1",
        "ContentType": "Položka",
        "Title": "aaa",
        "Modified": "2019-09-11T07:41:57Z",
        "Created": "2019-09-11T07:01:21Z",
        "AuthorLookupId": "6",
        "EditorLookupId": "6",
        "_UIVersionString": "1.0",
        "Attachments": false,
        "Edit": "",
        "LinkTitleNoMenu": "aaa",
        "LinkTitle": "aaa",
        "ItemChildCount": "0",
        "FolderChildCount": "0",
        "_ComplianceFlags": "",
        "_ComplianceTag": "",
        "_ComplianceTagWrittenTime": "",
        "_ComplianceTagUserId": ""
    }
}

**Comment by kozuch** [comment]
The problem was because of missing oAuth permissions for Sites on the client.

**Comment by thejoarjunkla** [comment]
@kozuch  Please share the fix.

**Comment by demo7up** [comment]
> @kozuch Please share the fix.

Agreed, what was the fix?
