### ISSUE TITLE
Add "Automatic-Module-Name" to JAR manifest.

### ISSUE THREAD

**Issue by brcolow** [microsoftgraph/msgraph-sdk-java#297]
Expected behavior
The published JAR should have a Java Platform Module Specification (JPMS, also known as Jigsaw) Automatic-Module-Name value so that this library has a stable module name even without having an actual modularized code base (with module-info.java). A next, harder, step is to go fully modular but seeing as many of the examples are geared towards Android and not knowing if JPMS is supported there (I doubt it) this request is the next best thing.
Actual behavior
No Automatic-Module-Name in manifest.
Steps to reproduce the behavior
Ping @JonathanGiles who will surely know more about the nitty gritty of this request :) (<3 from JavaFX community, btw).
[AB#6089](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6089)

**Comment by MIchaelMainer** [comment]
Thank you for your suggestion. We will consider this for future milestones.

**Comment by baywet** [comment]
Hi @brcolow 
Thanks for the feedback and the patience on the matter.
As I wasn't familiar with JPMS, I had to learn a bit more about it, here are the resources I used for reference:
- https://stackoverflow.com/a/46742802/3808675
- https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_modular
- https://dzone.com/articles/automatic-module-name-calling-all-java-library-maintainers
- https://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html

And ended up choosing com.microsoft.graph for this lib and com.microsoft.graph.core for the core library.
Here are the PRs that enable it:
- #500
- https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/77

Merging the PRs will close this issue, I'd appreciate if you could take a look at those and let me know whether I missed something or not.

**Comment by brcolow** [comment]
Looks good @baywet - thanks for doing that!

**Comment by baywet** [comment]
> Looks good @baywet - thanks for doing that!

thanks for checking the changes @brcolow !
