### ISSUE TITLE
Add GetRequest method to BaseRequest

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-java#301]
In order to use the strongly typed builders to create a native request we need a GetRequest() method.  This is useful for constructing requests for Batch or for other scenarios where we want to make the call manually to process the response differently.

**Comment by baywet** [comment]
would you mind providing more context on this one please? What's the point of having a getRequest method on the BaseRequest class? don't you already have the request at this point? Or did you mean baseRequestBuilder?
