### ISSUE TITLE
Error 423 while trying to create new event

### ISSUE THREAD

**Issue by agatap2** [microsoftgraph/msgraph-sdk-java#305]
When I try to create a new event I receive error 423, which means that resource that is being accessed is locked, but when I try to create a new event via Graph Explorer there is no such problem.

I have application and delegation Calendars.ReadWrite permission added. What can be the reason for such an error? How to check what resource is locked, and how to unlock it?

```
E/global: CoreHttpProvider[sendRequestInternal] - 423Error during http request

E/global: Throwable detail: com.microsoft.graph.core.ClientException: Error during http request
```

**Comment by MIchaelMainer** [comment]
Can you show us the the call you tried to make? Can you capture the request/response? Also, please provide a request-id provided in the response.

**Comment by baywet** [comment]
Hey @agatap2 
I'll be closing this issue since you haven't replied to Michael's comment to provide more information. Feel free to re-open one with more details if you're still facing the issue.
