### ISSUE TITLE
Failure : java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl

### ISSUE THREAD

**Issue by Samhithgb** [microsoftgraph/msgraph-sdk-java#306]
Getting this above error at runtime when executing List Messages graph request.  Any suggestions for resolving the same?

**Comment by Samhithgb** [comment]
Still facing the issue, any suggestions will be appreciated. This is when using the SDK on Android.

**Comment by maxklint** [comment]
Is there a solution to this?

**Comment by baywet** [comment]
Hi,
Thanks for your feedback (and your patience).
I authored #449 which removes that dependency all together.
This issue will be closed when the PR gets merged.
