### ISSUE TITLE
Error message list 

### ISSUE THREAD

**Issue by Samhithgb** [microsoftgraph/msgraph-sdk-java#308]
Where do we find a list of possible error messages that the SDK can throw? I checked https://docs.microsoft.com/en-us/graph/errors but it does not contain messages like InvalidAuthenticationToken. Any documentation available for the same?

**Comment by MIchaelMainer** [comment]
There are a lot of unknown error messages returned from the service. Your example of InvalidAuthenticationToken probably comes from our auth provider. Unfortunately we don't have documentation on the full set of errors from both the client and the service.
