### ISSUE TITLE
NullPointerException while downloading file

### ISSUE THREAD

**Issue by goncaloValentim** [microsoftgraph/msgraph-sdk-java#309]
### Expected behavior
https://docs.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-1.0&tabs=java

Getting the StreamOobject corresponding to the desired item. Just like in the documentation example:

```
IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

LinkedList<Option> requestOptions = new LinkedList<Option>();
requestOptions.add(new QueryOption("format", "{format}"));

Stream stream = graphClient.customRequest("/me/drive/items/{item-id}/content", Stream.class)
	.buildRequest( requestOptions )
	.get();
```

### Actual behavior
When I try to get the excel file as a PDF I get the following error:

```
com.microsoft.graph.core.ClientException: Error during http request
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:421)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:204)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:184)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:306)
	at com.microsoft.graph.http.CustomRequest.get(CustomRequest.java:43)
	at com.polarising.ajudascusto.service.StorageService.downloadFile(StorageService.java:173)
	(...) -> ommited for ease of read purposes
Caused by: java.lang.NullPointerException: null
	at com.microsoft.graph.http.CoreH
ttpProvider.sendRequestInternal(CoreHttpProvider.java:393)
	... 183 common frames omitted
```

I follow the same steps as the official documentation:

```
Stream stream = graphClient.customRequest(String.format("%s/%s:/content?format=%s", filePath, filename,
            format.toString()), Stream.class)
            .buildRequest()
            .get();
```
The only difference is that I build the request params manually because I thought it might have something to do with this issue.

After inspecting the source of the null pointer exception I noticed that the problem was that the Content-Type header was not being obtained correctly in the CoreHttpProvider class (line 392):

```
(...)
final String contentType = headers.get(Constants.CONTENT_TYPE_HEADER_NAME);
if (contentType.contains(Constants.JSON_CONTENT_TYPE)) {
					logger.logDebug("Response json");
					return handleJsonResponse(in, CoreHttpProvider.getResponseHeadersAsMapOfStringList(response), resultClass);
				} else {
					logger.logDebug("Response binary");
					isBinaryStreamInput = true;
					//no inspection unchecked
					return (Result) handleBinaryStream(in);
				}
(...)
```
The String value for the content type is being obtained through the key present in the constant: CONTENT_TYPE_HEADER_NAME -> "Content-Type". All good so far. However, when you make a GET request to obtain the converted item, the response header for the content type has the key "content-type" which is different than the "Content-Type" assigned to the constant:
```
package com.microsoft.graph.core;

public final class Constants {
	private Constants() {
	}
	
	public static final String APPROOT = "approot";
	/**
	 * The content type header
	 */
	public static final String CONTENT_TYPE_HEADER_NAME = "Content-Type";
(...)
```
This results in a NullPointerException  in line 393 of the CoreHttpProvider class.

### Steps to reproduce the behavior
Make the get request specified in the "Convert content" documentation.

#### Other info
IDE used: IntelliJ IDEA 2019.2.1 (Ultimate Edition)
Tested in both v1.0 and beta endpoints of the Graph API.

**Comment by goncaloValentim** [comment]
In oder to workaround this issue I implemented a custom HttpProvider based on the CoreHttpProvider and injected it into the Graph Client. I basically copied your class and changed the method getResponseHeadersAsMapStringString to use a TreeMap instead of a HashMap. As follows:

```
static Map<String, String> getResponseHeadersAsMapStringString(final Response response) {
        final Map<String, String> headers = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
        int index = 0;
```

This way, you can get the map's keys in case insensitive mode.

I'm not marking this as close as I think we shouldn't be required to implement a interface in order to use one of graph's preconfigured methods in the SDK.

**Comment by baywet** [comment]
Hi @goncaloValentim 
Thanks for your feedback and patience on the matter.
This issue is the same as #331 , the documentation is incorrect. We also have support for that via the fluent API (so you don't have to build custom requests).
You should check my last answer in that thread to get the details.
Closing.
