### ISSUE TITLE
Improve IRequestBuilder

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#31]
As far as I can see, every non-abstract implementation of IRequestBuilder has these methods:
T buildRequest();
T buildRequest(final java.util.List<? extends Option> requestOptions);
where T is the return type in the implementation.
A simplification is then to move those methods to IRequestBuilder and add a generic type to IRequestBuilder corresponding to the return type (after all if there is one method that I expect to see on a RequestBuilder it is buildRequest!).
For example, this interface:
public interface IBaseAttachmentRequestBuilder extends IRequestBuilder {
    IAttachmentRequest buildRequest();
    IAttachmentRequest buildRequest(final java.util.List<? extends Option> requestOptions);
...
would become:
public interface IBaseAttachmentRequestBuilder extends IRequestBuilder<IAttachmentRequest> {
...
There are some flow on effects to abstract classes like BaseRequestBuilder but I think the generic type can be added to those classes also without issue.
[AB#6042](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6042)

**Comment by mkomko** [comment]
Is this ever going to be changed? Without this I cannot write a generic method to get paged results.

Thanks in advance!

**Comment by darrelmiller** [comment]
This issue will be addressed soon in a larger effort to simplify the request builder generation across all of our SDKs.  Stay tuned!
