### ISSUE TITLE
401 Unauthorized when trying to get free/busy slots for a shared calendar

### ISSUE THREAD

**Issue by megicivovic** [microsoftgraph/msgraph-sdk-java#316]
I tried performing this request
` ICalendarGetScheduleCollectionPage iCalendarGetScheduleCollectionNextPage =
        graphServiceClient
            .me()
            .calendar()
            .getSchedule(emails, endTime, startTime, availabilityViewInterval)
            .buildRequest()
            .post();`
and I get the following exception 
`{"scheduleId":"mary.smith.doodle@outlook.com","error":{"message":"Proxy web request failed. , inner exception: System.Net.WebException: The request failed with HTTP status 401: Unauthorized.\r\n   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)\r\n   at System.Web.Services.Protocols.SoapHttpClientProtocol.EndInvoke(IAsyncResult asyncResult)\r\n   at Microsoft.Exchange.InfoWorker.Common.Availability.Proxy.Service.EndGetUserAvailability(IAsyncResult asyncResult)\r\n   at Microsoft.Exchange.InfoWorker.Common.Availability.FreeBusyApplication.EndProxyWebRequest(ProxyWebRequest proxyWebRequest, QueryList queryList, IService service, IAsyncResult asyncResult)\r\n   at Microsoft.Exchange.InfoWorker.Common.Availability.ProxyWebRequest.EndInvoke(IAsyncResult asyncResult)\r\n   at Microsoft.Exchange.InfoWorker.Common.Availability.AsyncWebRequest.EndInvokeWithErrorHandling()","responseCode":"ErrorProxyRequestProcessingFailed"}}`
I have two outlook user accounts and I shared the first user's calendar with the second one through outlook. I also tried this request through Graph Explorer and I get the same error.

![image](https://user-images.githubusercontent.com/9380704/67964142-0ecc9980-fc00-11e9-8dce-3dafa9b9fc10.png)

**Comment by MIchaelMainer** [comment]
Thank you for raising this issue.

Unless this functionality, get schedule for shared calendar across consumer accounts, is specified in the documentation, I don't think this is supported at this time, please open a [feature request](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests) for this. This is certainly a service issue -- exposing the internal stack trace, and providing a non-OData error response object. 

This is not a client issue.
