### ISSUE TITLE
Release location missing latest source code

### ISSUE THREAD

**Issue by samrajcse** [microsoftgraph/msgraph-sdk-java#322]
Hi Team,

I can see that the latest released version in 1.7.1, but in source tag shows upto 1.6.0.
https://github.com/microsoftgraph/msgraph-sdk-java/releases

Where can I get the exact source? Also my request is still open. https://github.com/microsoftgraph/msgraph-sdk-java/issues/233

**Comment by baywet** [comment]
Hi @samrajcse 
Thanks for your feedback and sorry it took so long to get you an answer (I'm new to the team).
I created the missing releases/tags last week. Everything should be in order now :)
Closing
