### ISSUE TITLE
Getting the mime content of a message is not implement in the java sdk

### ISSUE THREAD

**Issue by curchk** [microsoftgraph/msgraph-sdk-java#323]
According to https://docs.microsoft.com/de-de/graph/outlook-get-mime-message it's possible to get the mime content representation of a mail.
This works fine using the graph explorer with this url:
/me/messages/{id}/$value
The implementation is missing in the java api.
Or is there an other way to get the mime content? I didn't find anything.
Thanks, Christoph
[AB#6051](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6051)

**Comment by davidmoten** [comment]
Interesting you say it works, I could not get this to work today (on the v1.0 endpoint):

    https://graph.microsoft.com/v1.0/users('XXX')/mailFolders('Inbox')/messages('XXX')/$value

Result was:

```
{
  "error": {
    "code": "ErrorInvalidRequest",
    "message": "The OData request is not supported.",
    "innerError": {
      "request-id": "0ddf89ba-2f1f-41da-a388-459bc5f24854",
      "date": "2020-02-09T23:39:12"
    }
  }
}
```
In addition, the v1.0 metadata should have `HasStream=true` if that stream is supported on Message entity (it doesn't).

**Comment by kumbhaj** [comment]
you can make custom request using IgraphClient object.
`JsonObject ob = graphClient.customRequest(
				"/users/ {id} /messages/ {id}/ $value")
				.buildRequest().get();`

But I believe there should be filed in Message class to get the MIME. @peombwa Right now we have to make a separate call to get the MIME. Can't this field be available in Message class

**Comment by laeeq** [comment]
> Interesting you say it works, I could not get this to work today (on the v1.0 endpoint):
> 
> ```
> https://graph.microsoft.com/v1.0/users('XXX')/mailFolders('Inbox')/messages('XXX')/$value
> ```
> 
> Result was:
> 
> ```
> {
>   "error": {
>     "code": "ErrorInvalidRequest",
>     "message": "The OData request is not supported.",
>     "innerError": {
>       "request-id": "0ddf89ba-2f1f-41da-a388-459bc5f24854",
>       "date": "2020-02-09T23:39:12"
>     }
>   }
> }
> ```
> 
> In addition, the v1.0 metadata should have `HasStream=true` if that stream is supported on Message entity (it doesn't).

This works if you modify the url to this:
https://graph.microsoft.com/v1.0/users/email@company.onmicrosoft.com/messages/MessageId/$value

Hope this helps.

**Comment by baywet** [comment]
Hi everyone,
Thanks for the feedback and the patience on the matter.
As @davidmoten rightfully pointed out, this issue is due to the fact that information is missing in the metadata we use to generate the code.
I authored https://github.com/microsoftgraph/msgraph-metadata/pull/32 which allows us to "patch" the metadata before generating the code.
The result of the generation changes can be seem in #499 which adds the missing classes/properties.
Merging those PRs will close this issue.

**Comment by bibhutik** [comment]
content() method is still not present in IMessageRequestBuilder. It was added in revision "f9b76ca" but removed in version "ad367b2". Please help me am i missing something?
Or there us another way  to  read the content.

**Comment by baywet** [comment]
Which version of the SDK are you using?

**Comment by bibhutik** [comment]
I  am using 2.3.0

**Comment by baywet** [comment]
thanks for the information.
I looked into is in the meantime and it looks like I made a mistake not coordinating my changes properly when working on the generator.
That translated into creating a git change saying to "remove those lines" and the merge subsequently applied that.
Sorry about that. I'm working on a fix as we speak.

**Comment by baywet** [comment]
There's the new PR #520. Sorry about this.
We'll roll out the changes (publishing a new version) once the weekly changes from metadata are generated (usually happens on Mondays/Tuesdays)

**Comment by bibhutik** [comment]
There should be an  API to get the content of Attachments as well in "IAttachmentRequestBuilder". Otherwise I  do not see a way  to download/save attachments.
Guys please advice.

**Comment by baywet** [comment]
there's one in IFileAttachmentStreamRequestBuilder. The only issue is that the service doesn't support odata casting see #22

**Comment by bibhutik** [comment]
I  am  new to Graphsdk . But I  do not see this API  "**attachmentsAsFileAttachment**("id)"

graphClient.me().messages("id").**attachmentsAsFileAttachment**("id").content().get();

This API  is missing in  version 2.3.0
