### ISSUE TITLE
Why depend on jersey-server ?

### ISSUE THREAD

**Issue by FelixJongleur42** [microsoftgraph/msgraph-sdk-java#328]
Why would a Client API depend on such a thing as jersey-server ?
And why is the Maven packaging "pom" and not "jar" ?
see https://search.maven.org/artifact/com.microsoft.graph/microsoft-graph/1.7.1/pom

**Comment by FelixJongleur42** [comment]
Looks like you'd better depend on these two
javax.ws.rs:javax.ws.rs-api:jar:2.0.1
org.glassfish.jersey.core:jersey-common:jar:2.25.1
(versions may differ)
at least this what I tried (instead of jersey-server)

**Comment by baywet** [comment]
As far as I can see the only concrete dependency we have on this assembly is for [URIBuilder](https://docs.oracle.com/javaee/7/api/javax/ws/rs/core/UriBuilder.html). I'm not sure why it was introduced though.
I think we could easily replace it by [this](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/utils/URIBuilder.html) instead. Would it be better in your opinion?

**Comment by baywet** [comment]
@darrelmiller the convo I was mentioning this morning

**Comment by FelixJongleur42** [comment]
If you want to introduce the dependency to org.apache.http.client.utils you should better check what (transitive) dependencies you are introducing here. 
microsoft-graph-core Already depends on okhttp3 -maybe it‘s better to look for utility code there instead of introducing another dependency.

**Comment by baywet** [comment]
right, it makes a lot of sense. I authored PR #449 to address this issue which will be closed whenever the PR is merged.
Thanks for your input!

**Comment by FelixJongleur42** [comment]
Nice! Glad I could help.
