### ISSUE TITLE
Post() function of IGraphClient generates wrong URL 

### ISSUE THREAD

**Issue by wimvanhouts** [microsoftgraph/msgraph-sdk-java#329]
The following function call generates an exception: 

```Java
try
{
      graphClient.communications().calls(callId).answer("https://<hidemyserver>/calls", mediaConfig, modalities).buildRequest().post();
    }
    catch(Exception ex)
    {
      logger.error("Exception while answering the call",ex);
    }
```
In the log output this generates following result, where you can clearly see the generated URL is wrong. Last part of https://graph.microsoft.com/v1.0/communications/calls/431f0900-401f-49d1-a94d-5335b880ca1e/microsoft.graph.answer contains full class name which is not according to documentation that can be found at https://docs.microsoft.com/en-us/graph/api/call-answer?view=graph-rest-1.0&tabs=http 

```
Jan 24, 2020 4:26:56 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204Graph service exception Error code: 
Jan 24, 2020 4:26:56 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204Error message: The request is invalid.
Jan 24, 2020 4:26:56 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204
Jan 24, 2020 4:26:56 PM com.microsoft.graph.logger.DefaultLogger logError
**SEVERE: CoreHttpProvider[send] - 204POST https://graph.microsoft.com/v1.0/communications/calls/431f0900-401f-49d1-a94d-5335b880ca1e/microsoft.graph.answer**
Jan 24, 2020 4:26:56 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204SdkVersion : graph-java/v1.7.1
Jan 24, 2020 4:26:56 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204Authorization : Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI[...]
Jan 24, 2020 4:26:56 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204{"callbackUri":"https://teamsivr.eu.ngrok.io/calls[...]
Jan 24, 2020 4:26:56 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204
Jan 24, 2020 4:26:56 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204400 : Bad Request
Jan 24, 2020 4:26:56 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204[...]
Jan 24, 2020 4:26:56 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204
Jan 24, 2020 4:26:56 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204[Some information was truncated for brevity, enable debug logging for more details]
Jan 24, 2020 4:26:56 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: 
Error message: The request is invalid.
```

**Comment by MIchaelMainer** [comment]
The docs show the unqualified name and the library is generated to emit the FQN of the action. They are both supposed to work.

Does it work with the short name, `answer` and not with the FQN, `microsoft.graph.answer`?

**Comment by wimvanhouts** [comment]
two remarks here:
- in the code I see that 3 quarters of the function actually use the short name, only the more recent added ones usethe FQN... so for consistency it would be better to use the one or the other. That is also partially why I changed it (locally)
- there is also an issue in the genration of the body. I also changed this in a local build. So the real bad request may have come from there.
It works by fixing these two, but, they were applied at the same time. I'll do another test today to see if works without the first fix and let you know the results

**Comment by wimvanhouts** [comment]
Hi, I did additional testing and the FQN name works as well, it was actually the second "error" I fixed that caused the error response from the API

As mentioned before, this is confusing in the code because the SDK uses a combination of both. If you go to the file CallRequestBuilder.java you can notice the difference on line 101 and 105 in the current dev branch (commit 0df9a0a3530697ecf9d7f3fa47499111a90a14ee). 

The actual error came from the fact that the MediaConfig object serialization does not contain a valid @odata.type specification. I have set this separately and then it works. I don 't know if this is the way to do it or whether this is a bug. I Added in my code something like this to make it work. @MIchaelMainer should I report this as a new bug?

```
MediaConfig mediaConfig = new ServiceHostedMediaConfig();
mediaConfig.oDataType = "#microsoft.graph.serviceHostedMediaConfig";
```
