### ISSUE TITLE
GraphClient.customRequest returns a BufferedInputStream instead of a Stream

### ISSUE THREAD

**Issue by jmcazaux** [microsoftgraph/msgraph-sdk-java#331]
### Expected behavior
When called with a  `Stream.class` as second parameter, `GraphClient.customRequest` should return a Stream.

### Actual behavior
`GraphClient.customRequest` returns a `java.io.BufferedInputStream` that causes a `ClassCastException`

### Steps to reproduce the behavior

Use the very same code that is shown in the [documentation](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=java).

```java
        String contentRequest = String.format(
                "/drives/%s/items/%s/content",
                DRIVE_ID,
                ITEM_ID
        );

        Stream stream = graphClient.customRequest(contentRequest, Stream.class)
                .buildRequest()
                .get();
```
When executing this code, I am getting a `ClassCastException`.

```
Exception in thread "main" java.lang.ClassCastException: java.io.BufferedInputStream cannot be cast to java.util.stream.Stream
	at com.acmeinc.msgraph.TestSharepointAccess.getFile(TestSharepointAccess.java:249)
	at com.acmeinc.msgraph.TestSharepointAccess.testSharepoint(TestSharepointAccess.java:90)
	at Main.main(Main.java:27)

```

**Comment by kumbhaj** [comment]
You can get the data in Object class variable, then typecast it.

**Comment by aukhatov** [comment]
Yes. I also faced to this issue when I read official document and try to copy a piece of code.

**Comment by baywet** [comment]
Hi everyone,
Thank you for your patience on the matter.
The documentation is wrong on this one, it should have (adapted to your 
```Java
InputStream stream = graphClient
    			.me()
    			.drives(driveid)
    			.items(itemId)
			.content()
			.buildRequest()
			.get();
```

I logged an issue about that in the graph API samples repository.
https://github.com/microsoftgraph/microsoft-graph-explorer-api/issues/312

Regardless. Should you decide to forego the fluent API and use the custom request builder, it should work. I'm going to have a look at the issue.

**Comment by baywet** [comment]
after investigating it looks like the sample using the custom request is wrong as well. Here is what it should be:
```Java
String contentRequest = String.format(
                "/drives/%s/items/%s/content",
                DRIVE_ID,
                ITEM_ID
        );

        InputStream stream = graphClient.customRequest(contentRequest, InputStream.class)
                .buildRequest()
                .get();
```

I have added a unit test for that in #459.
When the pull request gets merged, it'll close this issue.
