### ISSUE TITLE
IDriveItemInviteCollectionPage does not contain response headers

### ISSUE THREAD

**Issue by BillCollabAuth** [microsoftgraph/msgraph-sdk-java#334]
I want to log the response headers in order to grab certain information to reach out to support (client-id, request-id, etc), but I am running into difficulty retrieving the headers when the SDK successfully completes the API call.
Expected behavior
graphResponseHeaders is returned with the IDriveItemInviteCollectionPage in the additionalDataManager attribute. I believe this is expected based on #15
Actual behavior
Nothing is returned as part of additionalDataManager.
Steps to reproduce the behavior
            IDriveItemInviteCollectionPage permissionsPage = graphClient.drives(driveId)
                .items(itemId)
                .invite(requireSignIn, roles, sendInvitation, message, driveRecipients)
                .buildRequest()
                .post();
[AB#6052](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6052)

**Comment by peombwa** [comment]
Related to #335

**Comment by baywet** [comment]
Hi @BillCollabAuth 
Thanks for the feedback and thanks for your patience on the matter.
I authored PR #492 which fixes this issue and it will close this issue when merged.
