### ISSUE TITLE
Unable to access responseHeaders for GraphServiceException

### ISSUE THREAD

**Issue by BillCollabAuth** [microsoftgraph/msgraph-sdk-java#335]
I want to be able to log the responseHeaders for cases where a GraphServiceException is caught. I am running into difficulty when accessing the responseHeaders for logging, because the responseHeaders attribute is private without any public getters.

I would like to avoid using #getMessage(final boolean verbose) with verbose true since this exposes the access token.

Any suggestions? Any advice would be greatly appreciated.

**Comment by baywet** [comment]
Hi @BillCollabAuth 
Thanks for your feedback and your patience.
I just authored #460 to address this issue which will close it whenever it gets merged.
