### ISSUE TITLE
Using GRAPH API we can get mailfolders easily. Is there any way we can get public Folders/archive folders / Normal folders separately.

### ISSUE THREAD

**Issue by kumbhaj** [microsoftgraph/msgraph-sdk-java#337]
Using GRAPH API we can get mailfolders easily. Is there any way we can get public Folders/archive folders / Normal folders separately.

For Mailfolders we do :

`graphClient.users(graphUserId).mailFolders().buildRequest().get();`
Isn't there any mechanism to get only archive/public / normal folders?

**Comment by peombwa** [comment]
This currently not supported by Microsoft Graph.
Please upvote on these user voice items:
- https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/35055997-expose-in-place-archive-and-public-folders-to-grap
- https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/35370430-public-folder-support-in-graph-api
