### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by midKingKing** [microsoftgraph/msgraph-sdk-java#346]
hello!
we upload our powerpoint file to onedrive for business by graph sdk for weeks,  I don't know why and It can't work normally anyway. And I know it might not because of the 'graph api', but  I don't  where can i go for help.

here is the response message:
`{
  "error": {
    "code": "InternalServerError",
    "message": "Object reference not set to an instance of an object.",
    "innerError": {
      "request-id": "8463ad8e-65a7-4e1b-8883-8c5607101679",
      "date": "2020-03-10T05:37:18"
    }
  }
}`

eg code:

`UsernamePasswordProvider usernamePasswordProvider = new UsernamePasswordProvider(CLIENT_ID, SCOPES, USERNAME,
                PASSWORD, NationalCloud.Global, Tenants.Organizations, CLIENT_SECRET);

        IClientConfig mClientConfig = DefaultClientConfig.createWithAuthenticationProvider(usernamePasswordProvider);

        IGraphServiceClient graphClient = GraphServiceClient.fromConfig(mClientConfig);

        User user = graphClient.me().buildRequest().get();
        System.out.println(user.getRawObject());
        File file = new File("/Users/saybot/Downloads/9c1b08bfcb0c637e1291c18b47f539fc.pptx");
        FileInputStream fileInputStream = new FileInputStream(file);
        MyItem driveItemUploadableProperties = new MyItem();
        driveItemUploadableProperties.behavior = "rename";
        String alpha = graphClient.me().drive().root().children().buildRequest().get().getCurrentPage().stream().filter(
                item -> item.name.equalsIgnoreCase("alpha")).findFirst().get().id;
        UploadSession uploadSession = graphClient.me().drive().items(alpha)
                .itemWithPath("9c1b08bfcb0c637e1291c18b47f539fc.pptx")
                .createUploadSession(driveItemUploadableProperties)
                .buildRequest().post();

        ChunkedUploadProvider<DriveItem> simpleBeanChunkedUploadProvider = new ChunkedUploadProvider<>(uploadSession,
                graphClient, fileInputStream,
                Long.valueOf(file.length()).intValue(),
                DriveItem.class);

        StringBuilder sb = new StringBuilder();

        simpleBeanChunkedUploadProvider.upload(new IProgressCallback<DriveItem>() {
            @Override
            public void progress(long current, long max) {
                System.out.println(current + " progress " + max);
            }

            @Override
            public void success(DriveItem simpleBean) {
                System.out.println(simpleBean);
                sb.append(simpleBean.id);
            }

            @Override
            public void failure(ClientException ex) {
                System.out.println(ex);
            }
        });`

**Comment by mneuwohner** [comment]
Same issue here, nothing changed in my implementation, suddenly upload stopped working.

**Comment by distraught1** [comment]
We're running into this exact same issue as well with file uploads! Upload randomly succeeds but most of the time is failing. Seems like some major instability was introduced in a change that happened within the last day or less.

**Comment by distraught1** [comment]
The issue appears to now be resolved for us!

**Comment by midKingKing** [comment]
> The issue appears to now be resolved for us! Found the following thread on the .net sdk, with someone from Microsoft replying, so guessing they fixed the issue: [microsoftgraph/msgraph-sdk-dotnet#560](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/560)

Thanks a lot, I'll close this issue
