### ISSUE TITLE
There is no mechanism to use newly acquired access token in existing IGraphServiceClient object.

### ISSUE THREAD

**Issue by kumbhaj** [microsoftgraph/msgraph-sdk-java#354]
Let's say I have initialized an IGraphServiceClient object : 
`SimpleAuthProvider authProvider = new SimpleAuthProvider(token);`

		`IGraphServiceClient graphClient = GraphServiceClient
				.builder()
				.authenticationProvider(authProvider)
				.buildClient();`
Now, the token used in it will expire after an hour. Before that happens, I want to update the token in this graphClient object. The only way right now is to re-initialize. Can't we simply replace the token. Like I can do it in EWS.
`service.getHttpHeaders().replace("Authorization ", "Bearer " + tokenString);`

**Comment by MIchaelMainer** [comment]
You should use the 
https://github.com/microsoftgraph/msgraph-sdk-java-auth for getting an auth provider.

**Comment by kumbhaj** [comment]
https://github.com/microsoftgraph/msgraph-sdk-java-auth/issues/26
