### ISSUE TITLE
Getting an email's attachments in one go returns a NullPointerException

### ISSUE THREAD

**Issue by nsadeh** [microsoftgraph/msgraph-sdk-java#355]
### Expected behavior

I am writing a daemon to get the attachments from a subset of messages. If I have

```java
Set<Attachment> attachments = factory.getClient().users(emailAddress).mailFolders(
                folderIds().orElseThrow()
        ).messages().buildRequest().get().getCurrentPage().stream()
                .map(message -> message.attachments)
                .flatMap(attachmentCollectionPage -> attachmentCollectionPage.getCurrentPage().stream())
                .collect(Collectors.toSet());
```

Note that the folder here has one message and it has an attachment.`client()` is an instance of `IGraphServiceClient`).

I expect this to return my attachments

### Actual behavior

Above call fails with a NPE at the flatMap because `message.attachments` returns `[null]`.

### Steps to reproduce the behavior

Using a folder that has only messages with attachments, run the above.

Note: the following works:

```java
String id = factory.getClient().users(emailAddress).mailFolders(
                folderIds().orElseThrow(FolderNotFoundException::new)
        ).messages().buildRequest().get().getCurrentPage().stream()
                .map(message -> message.id).findAny().orElseThrow();
Attachment attachment = factory.getClient().users(emailAddress).messages(id)
                .attachments().buildRequest().get().getCurrentPage().get(0);
return factory.getClient().users(emailAddress).messages(id).attachments(attachment.id).buildRequest().get()
                .getRawObject().toString();
```

but it requires me to `get` the Future twice. Hence I say that getting the attachments in one go (resolving the messages and the attachments and only `get`ting the attachments results in a NPE, whereas getting them in two requests does work.

**Comment by baywet** [comment]
Hey @nsadeh 
Thanks for the question and for your patience on the matter.
This is not working because you're not expanding the attachments collection, which means the service is not returning that collection with each message object.

Here is the corrected code that works.
```Java
Set<Attachment> attachments = factory.getClient().users(emailAddress).mailFolders(
                folderIds().orElseThrow()
        ).messages().buildRequest().expand("attachments").get().getCurrentPage().stream()
                .map(message -> message.attachments)
                .flatMap(attachmentCollectionPage -> attachmentCollectionPage.getCurrentPage().stream())
                .collect(Collectors.toSet());
```

Closing.
