### ISSUE TITLE
I got duplicate class of json-simple. How do I exclude it from msgraph or from another sdk?

### ISSUE THREAD

**Issue by kadalcj** [microsoftgraph/msgraph-sdk-java#356]
Hi,
Recently I was adding another external (.jar) sdk to my project, and it sync well in gradle. But when I want to run it, it was giving me this on the log:
Duplicate class org.json.simple.ItemList found in modules --.jar (--.jar) and jetified-json-simple-1.1.jar (com.googlecode.json-simple:json-simple:1.1)
Duplicate class org.json.simple.JSONArray found in modules --.jar (--.jar) and jetified-json-simple-1.1.jar (com.googlecode.json-simple:json-simple:1.1)
Duplicate class org.json.simple.JSONAware found in modules --.jar (--.jar) and jetified-json-simple-1.1.jar (com.googlecode.json-simple:json-simple:1.1)
Duplicate class org.json.simple.JSONObject found in modules --.jar (--.jar) and jetified-json-simple-1.1.jar (com.googlecode.json-simple:json-simple:1.1)
Duplicate class org.json.simple.JSONStreamAware found in modules --.jar (--.jar) and jetified-json-simple-1.1.jar (com.googlecode.json-simple:json-simple:1.1)
Duplicate class org.json.simple.JSONValue found in modules --.jar (--.jar) and jetified-json-simple-1.1.jar (com.googlecode.json-simple:json-simple:1.1)
Duplicate class org.json.simple.parser.ContainerFactory found in modules --.jar (--.jar) and jetified-json-simple-1.1.jar (com.googlecode.json-simple:json-simple:1.1)
Duplicate class org.json.simple.parser.ContentHandler found in modules --.jar (--.jar) and jetified-json-simple-1.1.jar (com.googlecode.json-simple:json-simple:1.1)
Duplicate class org.json.simple.parser.JSONParser found in modules --.jar (--.jar) and jetified-json-simple-1.1.jar (com.googlecode.json-simple:json-simple:1.1)
Duplicate class org.json.simple.parser.ParseException found in modules --.jar (--.jar) and jetified-json-simple-1.1.jar (com.googlecode.json-simple:json-simple:1.1)
Duplicate class org.json.simple.parser.Yylex found in modules --.jar (--.jar) and jetified-json-simple-1.1.jar (com.googlecode.json-simple:json-simple:1.1)
Duplicate class org.json.simple.parser.Yytoken found in modules --.jar (--.jar) and jetified-json-simple-1.1.jar (com.googlecode.json-simple:json-simple:1.1)

Go to the documentation to learn how to Fix dependency resolution errors.

Can I exclude it somehow to prevent it from duplicating?
Thanks.
[AB#6054](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6054)

**Comment by davidmoten** [comment]
Can you let us know what the (transitive) dependencies in your project are that contain org.json.simple.parser classes?

**Comment by kadalcj** [comment]
I kinda know but not so sure, I am afraid that I tell the wrong name. The name of the file is "assist-android-sdk1.64.1.jar". 

And if we open the .jar file from android studio, it showing something like this:
![image](https://user-images.githubusercontent.com/43379893/79042060-abb74800-7c1e-11ea-9d43-9045b67acfc2.png)

**Comment by baywet** [comment]
Hi,
Thanks for the feedback and for the patience.
This was indirectly fixed by #464 as we removed json simple from our dependencies to align on gson.
Closing.
