### ISSUE TITLE
Empty POST request rewrites content type

### ISSUE THREAD

**Issue by Gagl0u** [microsoftgraph/msgraph-sdk-java#357]
Hello,
I'm trying to make a call to microsoft graph API in order to revoke signin sessions.
I built the graph client like this and it is working like a charm for multiple call.
  @Bean
  fun authenticationProvider(): IAuthenticationProvider =
          OAuth2AuthenticationProvider(createResourceDetails())

  @Bean
  fun graphClient(provider: IAuthenticationProvider): IGraphServiceClient =
          GraphServiceClient
                  .builder()
                  .authenticationProvider(provider)
                  .buildClient()

  private fun createResourceDetails() =
          ClientCredentialsResourceDetails().apply {
            clientId = configuration.clientId
            clientSecret = configuration.clientSecret
            accessTokenUri = configuration.accessTokenUri
            clientAuthenticationScheme = AuthenticationScheme.form
            scope = configuration.scopes
          }

I am now trying to make the revoke signin sessions call. Here is the snippet:
  private fun revokeUserToken(userId: String) {
    try {
      val jsonContentType: Option = HeaderOption("Content-Type", MediaType.APPLICATION_JSON_VALUE)
      graphClient.users(userId).revokeSignInSessions().buildRequest(mutableListOf(jsonContentType)).post()
    } catch (e: GraphServiceException) {
      LOG.error("Cannot revoke tokens for user $userId. ${e.serviceError.message}")
    }
  }

This is Kotlin code as close to Java one but do not hesitate to ask if anything is unclear.
Concretely I make the post request using the revokeSignInSessions request and I add manually the json content type.
However microsoft grph api always fails with this issue:
Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: Request_BadRequest
Error message: A supported MIME type could not be found that matches the content type of the response. None of the supported type(s) 'application/json;odata=minimalmetadata;streaming=true, application/json;odata=minimalmetadata;streaming=false, application/json;odata=minimalmetadata, application/json;odata=fullmetadata;streaming=true, application/json;odata=fullmetadata;streaming=false, application/json;odata=fullmetadata, application/json;odata=nometadata;streaming=true, application/json;odata=nometadata;streaming=false, application/json;odata=nometadata, application/json;streaming=true, application/json;streaming=false, application/json;odata=verbose, application/json' matches the content type 'application/octet-stream'.

After looking into the code, I end up in the CoreHttpProvider in the sendRequestInternal method.
And in this methods it states that if the body is null, then it rewrites content type to octetstream (beginning is line 286 of the class)
				if (serializable == null) {
					// Send an empty body through with a POST request
					// This ensures that the Content-Length header is properly set
					if (request.getHttpMethod() == HttpMethod.POST) {
						bytesToWrite = new byte[0];
						contenttype = Constants.BINARY_CONTENT_TYPE;
					}
					else {
						bytesToWrite = null;
					}
				}

From the UserRevokeSignInSessionsRequest class, I can only make post request that have no body (begin is line 36)
    /**
     * Creates the UserRevokeSignInSessions
     *
     * @param callback the callback to be called after success or failure
     */
    public void post(final ICallback<Boolean> callback) {
        send(HttpMethod.POST, callback, null);
    }

    /**
     * Creates the UserRevokeSignInSessions
     *
     * @return the Boolean
     * @throws ClientException an exception occurs if there was an error while the request was sent
     */
    public Boolean post() throws ClientException {
       return send(HttpMethod.POST, null);
    }

so I will always end up with a octet stream content type, while this API accepts only json content type.
Is there any way to bypass this content type rewritting so that I can use all the classes you made for revoking sessions ?
Thank you
[AB#6033](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6033)

**Comment by zengin** [comment]
Related issue: #270 and PR: #272

**Comment by baywet** [comment]
Hi @Gagl0u 
Thanks for your feedback and for your patience.
I've just authored PR #467 which fixes this issue.
This issue will be closed whenever the PR gets merged.
