### ISSUE TITLE
unable to remove property

### ISSUE THREAD

**Issue by omnifreefall** [microsoftgraph/msgraph-sdk-java#358]
removing a user property does not work for SdkVersion: graph-java/v1.7.1

Using graphClient.customRequest("/users/" + userID).buildRequest().patch(jUser), where juser is a JsonObject with { "city": null }, the city property does not get removed from the user specified by userID

Fiddler trace shows { } is being sent

In com.microsoft.graph.serializer.DefaultSerializer.serializeObject(), the return is outJsonTree.toString();
According to GSON docs, the default behavior is to ignore nulls.  In order to serialize nulls, one would need to do something like this:
Gson gson = new GsonBuilder().serializeNulls().create();

**Comment by MIchaelMainer** [comment]
Please checkout out this document on how to set properties to null.

https://github.com/microsoftgraph/msgraph-sdk-java/wiki/Patching-objects

**Comment by omnifreefall** [comment]
That link shows a suggestion for the Users object, but I cannot use the Users object since it doesn't support identities and doesn't support extension_* properties.



Thanks, Ken

omnifreefall freefall@me.com<mailto:freefall@me.com>

kserrine@cat.com<mailto:kserrine@cat.com>







Begin forwarded message:

**Comment by bond-** [comment]
Found it using https://web.archive.org/web/20200917005423/https://github.com/microsoftgraph/msgraph-sdk-java/wiki/Patching-objects

Can you please have this updated in the current documentation 🙏
