### ISSUE TITLE
Get the List of Applications not available

### ISSUE THREAD

**Issue by MBurchard** [microsoftgraph/msgraph-sdk-java#359]
If one follows the documentation, it should actually be quite easy to get the applications.

https://docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&tabs=java

    IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

    IApplicationCollectionPage applications = graphClient.applications()
    .buildRequest()
    .get();

I use `com.microsoft.graph:microsoft-graph:1.7.1`

	final IGraphServiceClient serviceClient =
			GraphServiceClient.builder().authenticationProvider(authProvider::authenticate)
					.buildClient();

But then there is no `applications()`. There is `users()` and a lot of other thinks, but nothing that looks like applications.

Please update documentation and tell me how to get the list of applications.

**Comment by davidmoten** [comment]
@MIchaelMainer This looks to be because code is not being generated for `EntitySet`s?

**Comment by davidmoten** [comment]
@MBurchard this msgraph java client does implement EntitySet declarations and `client.applications()` is present. Try it if you like.

https://github.com/davidmoten/odata-client

**Comment by MBurchard** [comment]
Sorry, I don't understand what this means for me @davidmoten.
We do I need another dependency?
Shouldn't the MSGraph client already have all the necessary features?

**Comment by davidmoten** [comment]
@MBurchard sure, would be nice. Depends on how soon you'd like support for `applications()`.

**Comment by MBurchard** [comment]
So this is definitely a bug. The MS Graph client must be complete.

For now I try to work this way...

	final CustomRequest<JsonObject> request =
			serviceClient.customRequest("/applications").buildRequest();
	final JsonObject result = request.get();

**Comment by davidmoten** [comment]
Custom request is a good plan till support exists.

@MIchaelMainer re the existence of my alternative msgraph java client, here are some [notes](https://github.com/davidmoten/odata-client/wiki/Microsoft-msgraph-sdk-java-problems-addressed-by-odata-client).

**Comment by MBurchard** [comment]
I took a look into the Code of MS Graph API. Sorry to say but it looks a little bloated.

I analysed the `UserCollectionResponse` and `GroupCollectionResponse` classes.

To implement the basic request for applications, I created this simple code...

	package com.uniper.cimapp.msgraph;
	
	import java.util.List;
	
	import com.google.gson.JsonArray;
	import com.google.gson.JsonObject;
	import com.google.gson.annotations.Expose;
	import com.google.gson.annotations.SerializedName;
	import com.microsoft.graph.models.extensions.DirectoryObject;
	import com.microsoft.graph.serializer.AdditionalDataManager;
	import com.microsoft.graph.serializer.IJsonBackedObject;
	import com.microsoft.graph.serializer.ISerializer;
	
	public class CollectionResponse<T extends DirectoryObject> implements IJsonBackedObject {
	
		/**
		 * The URL to the next page of this collection, or null
		 */
		@SerializedName("@odata.nextLink")
		@Expose(serialize = false)
		public String nextLink;
		@SerializedName("value")
		@Expose
		public List<T> value;
		private final transient AdditionalDataManager additionalDataManager = new AdditionalDataManager(this);
		/**
		 * The raw representation of this class
		 */
		private JsonObject rawObject;
		/**
		 * The serializer
		 */
		private ISerializer serializer;
	
		@Override
		public final AdditionalDataManager additionalDataManager() {
			return additionalDataManager;
		}
	
		/**
		 * Gets the raw representation of this class
		 *
		 * @return the raw representation of this class
		 */
		public JsonObject getRawObject() {
			return rawObject;
		}
	
		/**
		 * Gets serializer
		 *
		 * @return the serializer
		 */
		protected ISerializer getSerializer() {
			return serializer;
		}
	
		/**
		 * Sets the raw JSON object
		 *
		 * @param serializer
		 * 		the serializer
		 * @param json
		 * 		the JSON object to set this object to
		 */
		public void setRawObject(final ISerializer serializer, final JsonObject json) {
			this.serializer = serializer;
			rawObject = json;
	
			if (json.has("value")) {
				final JsonArray array = json.getAsJsonArray("value");
				for (int i = 0; i < array.size(); i++) {
					value.get(i).setRawObject(serializer, (JsonObject) array.get(i));
				}
			}
		}
	}

The simple application collection is much smaller then the croup collection or the user collection. The `setRawObject` can be override if needed...

	package com.uniper.cimapp.msgraph;

	public class ApplicationCollectionResponse extends CollectionResponse<GraphApplication> {
	}

The `GraphApplication` itself is also very small...

	package com.uniper.cimapp.msgraph;
	
	import com.google.gson.annotations.Expose;
	import com.google.gson.annotations.SerializedName;
	import com.microsoft.graph.models.extensions.DirectoryObject;
	
	public class GraphApplication extends DirectoryObject {
		@SerializedName("appId")
		@Expose
		public String clientId;
	
		@SerializedName("displayName")
		@Expose
		private String displayName;
	}

And then it is very simple to get the application data needed....

	final CustomRequest<ApplicationCollectionResponse> request =
				serviceClient.customRequest("/applications", ApplicationCollectionResponse.class)
						.buildRequest();
	final ApplicationCollectionResponse applicationCollectionResponse = request.get();
	final List<GraphApplication> graphApplications = applicationCollectionResponse.value;

**Comment by baywet** [comment]
Hey @MBurchard 
Thanks for your feedback (and your patience). The support for applications was added with version 1.8.0 around the July timeframe.
Upgrading the dependency to latest (2.0.0 at the time of writing) should fix your issue.
Closing.
