### ISSUE TITLE
No working example to get B2C Data from Graph API

### ISSUE THREAD

**Issue by MBurchard** [microsoftgraph/msgraph-sdk-java#360]
We have an Azure B2C AD in front of another AD. When using the Graph client it looks like I get users from Azure AD but not from Azure B2C. What do I need to do to get B2C Users?

    2020-04-17 12:36:36.205 DEBUG 17768 --- [    Test worker] c.u.a.a.ConfidentialClientAuthProvider   : Setup ConfidentialClientApplication for clientId XXX and authority https://login.microsoftonline.com/uniperappsnpd.onmicrosoft.com
    2020-04-17 12:36:36.621 DEBUG 17768 --- [    Test worker] c.u.a.a.ConfidentialClientAuthProvider   : acquire token for scopes [https://graph.microsoft.com/.default]

The class `ConfidentialClientAuthProvider` was written by me. It creates the `ConfidentialClientApplication`.

    cca = ConfidentialClientApplication.builder(instance.clientId, secret)
        .authority(instance.authority).build();

And acquires token by...

    /**
     * @return IAuthenticationResult
     */
    private IAuthenticationResult acquireToken() {
        final ClientCredentialParameters parameters = ClientCredentialParameters.builder(scopes).build();
        LOG.debug("acquire token for scopes {}", scopes);
        return cca.acquireToken(parameters).join();
    }

    public Optional<IAuthenticationResult> authenticate() throws AuthenticationException {
        return Optional.ofNullable(acquireTokenSilently().orElseGet(this::acquireToken));
    }

    void authenticate(final IHttpRequest request) {
        try {
            authenticate().ifPresent(
                result -> request.addHeader(AUTHORIZATION, BEARER + result.accessToken()));
        } catch (final AuthenticationException ex) {
            throw new RuntimeException("", ex);
        }
    }

This authentication result is then used in the graph client...

    final IGraphServiceClient serviceClient =
        GraphServiceClient.builder().authenticationProvider(authProvider::authenticate)
            .buildClient();

    final IUserCollectionPage userCollection = serviceClient.users().buildRequest().get();
    final List<User> users = userCollection.getCurrentPage();

So how can I get the users from B2C AD? 
[AB#7123](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7123)

**Comment by darrelmiller** [comment]
It is my understanding that tokens acquired via a B2C login cannot be used to access Microsoft Graph.  I would recommend raising this as a feature request to the B2C team.
