### ISSUE TITLE
Is there a way to turn off logging

### ISSUE THREAD

**Issue by fsjovatsen** [microsoftgraph/msgraph-sdk-java#363]
Hi,
Is thee a way to turn off logging? For example if I query for a user that does not exists there is to much logging:
 graphClient = GraphServiceClient
                .builder()
                .authenticationProvider(authProvider)
                .buildClient();

graphClient.users(id).buildRequest().get();
If the user is not found the log looks like this:
2020-04-28 18:27:45.390 ERROR 71013 --- [   scheduling-1] global                                   : Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: Request_ResourceNotFound
Error message: Resource 'test@test.no' does not exist or one of its queried reference-property objects are not present.

GET https://graph.microsoft.com/v1.0/users/test@test.no
SdkVersion : graph-java/v1.7.1
Authorization : Bearer xxxxxxxxxx[...]

404 : Not Found
[...]

[Some information was truncated for brevity, enable debug logging for more details]

Seems like there is only to log levels in LoggerLevel, DEBUG and ERROR. Would be nice to be able to decide what should end up in the log.
Frode
[AB#6055](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6055)

**Comment by darrelmiller** [comment]
There is a setLogger method on the GraphServiceClient.  If you provide an implementation of ILogger that does nothing you can update the logger and prevent logging from occuring.
