### ISSUE TITLE
createUploadSession fails with error: An upload session already exists for this file if file is open in Office Online

### ISSUE THREAD

**Issue by ukalhapu** [microsoftgraph/msgraph-sdk-java#366]
I am trying to upload file using graph java sdk API - createUploadSession to basically replace the content. The file is already open in Office online window.
I tried the conflictBehavior settings (repalce, rename), but still the same issue
DriveItemUploadableProperties itemProperties = new DriveItemUploadableProperties();
	itemProperties.additionalDataManager().put("@microsoft.graph.conflictBehavior", new JsonPrimitive("replace"));

Sample code:
 graphServiceClient
	                    .me()
	                    .drive()
	                    .root()
	                    .itemWithPath(filename)
	                    .createUploadSession(itemProperties)
	                    .buildRequest()
	                    .post(new ICallback<UploadSession>() {
	                        @Override
	                        public void failure(final ClientException ex) {
	                            log("createUploadSession.failure: Error occured durring post " + ex);	                           
	                        }
	                        @Override
	                        public void success(final UploadSession result) {
	                           
	                             log("createUploadSession.success: UploadSession= " + result);
	                            
	                            try {
	                                ChunkedUploadProvider<DriveItem> chunkedUploadProvider = new ChunkedUploadProvider<DriveItem>(
	                                        result, graphServiceClient, fis, (int) filesize, DriveItem.class);
	                                chunkedUploadProvider.upload(new IProgressCallback<DriveItem>() {
	                                    @Override
	                                    public void failure(ClientException ce) {
	                                        log("failure: Error occured durring upload " + ce);
	               
	                                        try {
	                                            queue.put("");
	                                        } catch (InterruptedException ie) {
	                                        }
	                                    }

	                                    @Override
	                                    public void success(DriveItem driveItem) {
	                                        
	                                        log("success: driveItem = " + driveItem);
	                                        
	                                        try {
	                                            queue.put(driveItem.webUrl);
	                                        } catch (InterruptedException ie) {
	                                        }
	                                    }

	                                    @Override
	                                    public void progress(long current, long max) {
	                                       
	                                         log("progress: current=" + current + ", max=" + max);
	                                        
	                                    }
	                                }, new int[] { DEFAULTCHUNKSIZE });
	                            } catch (Exception e) {
	                                log("Exception occured in upload to One Drive" + e);
	                                try {
	                                    queue.put("");
	                                } catch (InterruptedException ie) {
	                                }
	                            }
	                        }
	                    });

Is such use case supported ?
### Expected behavior
createUploadSession should be successful 

### Actual behavior
createUploadSession throw error
409 : Conflict
HTTP/1.1 409 Conflict
Strict-Transport-Security : max-age=31536000
Cache-Control : private
x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"East Asia","Slice":"SliceC","Ring":"4","ScaleUnit":"002","RoleInstance":"AGSFE_IN_26"}}
client-request-id : 6cc12299-6a5c-4b16-9b2c-c35e28764c54
request-id : 6cc12299-6a5c-4b16-9b2c-c35e28764c54
Content-Length : 249
Date : Mon, 04 May 2020 13:06:21 GMT
Content-Type : application/json
{
  "error": {
    "code": "nameAlreadyExists",
    "message": "An upload session already exists for this file",
    "innerError": {
      "request-id": "6cc12299-6a5c-4b16-9b2c-c35e28764c54",
      "date": "2020-05-04T13:06:21"
    }
  }
}

**Comment by MIchaelMainer** [comment]
This looks to be by design. Please open an issue in the [Microsoft Graph User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests) if you believe this is not the correct behavior.
