### ISSUE TITLE
Debugging InvalidAuthenticationToken issues across multiple platforms

### ISSUE THREAD

**Issue by Fabian95qw** [microsoftgraph/msgraph-sdk-java#372]
Hello

Local Platform: 
Windows 10 Pro x64
Java-Version: 1.8.0_251-b08

Target Platform: 
CentOS release 6.10 (Final)
Java-Version: 1.8.0_202-b08 (Tomcat-Catalina)

I'm currently trying to develop an add-on for a vbpx using the java-sdk for microsoft graph.
But there is an issues, i'm running into, when actually porting the code to the target platform. 

Here is a simple example.
I've a class called "O365Provider", which contains the authprovider, and the Graphclient and a simple function, to get the first page of users in O365 I can basically reduce this to three lines of code. 

```
ClientCredentialProvider authProvider = new ClientCredentialProvider(ClientID, Scopes, ClientSecret, TenantID, NationalCloud.Global);
IGraphServiceClient GC = GraphServiceClient.builder().authenticationProvider(authProvider).buildClient();
return GC.users().buildRequest().get();
```

When i test the code locally with **Hard-Coded** TenantID, ClientID, ClientSecret, and Scrope (with the ClientCredentialProvider)
Everything works. i get a IUserCollectionPage back from the code.

If i now migrate the code over to the target platform the exact same **Hard-Coded**  credentials causes a 

> code: InvalidAuthenticationToken
> Error message: CompactToken parsing failed with error code: 80049217

Now my actual question is, how do i debug such a problem? 
Can i somehow print out the Token, or the Headers in a way so i can compare them with my local ones?

### Expected behavior
Return a IUserCollectionPage 

### Actual behavior
Throws an InvalidAuthenticationToken

### Steps to reproduce the behavior
Porting the Code to the STARFACE PBX Tomcat Server, causes the same hard-coded ClientCredentialProvider to cause a InvalidAuthenticationToken

**Comment by MIchaelMainer** [comment]
You'll need to add custom middleware to capture and log out that token. Alternatively, you can use something like Wireshark to capture that token. You can use jwt.ms to decode the token to compare the contents from both scenarios.

**Comment by MIchaelMainer** [comment]
What auth library are you using in your auth provider and are you using the MSAL for Java library?

https://github.com/AzureAD/microsoft-authentication-library-for-java

**Comment by Fabian95qw** [comment]
Hello Michael

I can easily create two TCP-Dumps. But i suppose i'd have to first decryopt the ssl-connection, and then use jwt.ms to decode the actual token?

I'm using microsoft-graph-auth from the maven artifact:

	<groupId>com.microsoft.graph</groupId>
	<artifactId>microsoft-graph-auth</artifactId>
	<version>0.1.0-SNAPSHOT</version>

**Comment by Fabian95qw** [comment]
Nevermind i found the issue. 

The ClientCredentialProvider can print out the Token by Default. 
When i was printing the Token, the Tomcat Server returned nothing instead, but there were no exceptions thrown

When i printed each individual part of the variables, i was providing troug the frontend i suddendly saw it!
The scope was cast to a List<List<String>> instead of a List<String>  so the Provided Scopes looked like this:

[[https://graph.microsoft.com/.default]] insead of [https://graph.microsoft.com/.default]
Rather funny that this didn't cause an exception, and just silently caused the token to not generate instead.

With this said, the issue is resolved.
