### ISSUE TITLE
How to list all personal sharepoint sites using microsoft graph?

### ISSUE THREAD

**Issue by dpduong90** [microsoftgraph/msgraph-sdk-java#379]
### Expected behavior
I want to fetch following all members of Site using Microsoft graph API. But I can't find out any way to get it.

### Actual behavior
I could get members of Site base on the Group (https://graph.microsoft.com/v1.0/groups/{id}/members). But I could not get the members of Root Site and Communication Site because these sites have not belonged to any Group. 

I posted to StackOverflow the question but it seems nobody knows its. [Link](https://sharepoint.stackexchange.com/questions/281160/how-to-get-members-of-root-site-and-communication-site-with-graph-api)

What should I do to get all members of Site (the members are shared for the site)?

**Comment by MIchaelMainer** [comment]
Thank you for contacting us. This repo is for the Microsoft Graph Java client. Questions about the service API or configuration should be posted to StackOverflow and tagged with microsoft-graph. Once you have posted to StackOverflow, grab the link and post it in this issue.

**Comment by dpduong90** [comment]
Hi @MIchaelMainer, I already posted to StackOverflow but no nobody knows how to do it. I updated the link in the question.

**Comment by baywet** [comment]
closing as the question has been answered and accepted on stack
