### ISSUE TITLE
Calling preview() is causing an "API not found" error

### ISSUE THREAD

**Issue by av1ctor** [microsoftgraph/msgraph-sdk-java#380]
When calling client.me().drive().items(***id***).preview("0", 1.0).buildRequest().post(), the URL generated is incorrect, causing an "API not found" error.

Generated URL: https://graph.microsoft.com/v1.0/me/drive/items/***id***/microsoft.graph.preview
Expected URL: https://graph.microsoft.com/v1.0/me/drive/items/***id***/preview

**Comment by ddyett** [comment]
should check with next round of generation.

**Comment by MIchaelMainer** [comment]
@ddyett 

This is a service issue. OData specification allows for fully-qualified action/function names. We emit the fully-qualified function names in the URL for our request builders. This is becoming more important as we start to support namespaces.

Older API stacks like SharePoint/OneDrive may not use OData libraries to process the requests so this likely why it isn't being accepted by service API.

@av1ctor You mitigate by using the CustomRequest method. It will look something like this:

```java
ItemPreviewInfo previewInfo = graphServiceClient.customRequest("https://graph.microsoft.com/v1.0/me/drive/items/***id***/preview", ItemPreviewInfo.class)
					.buildRequest()
					.post(bodyJson);
```

**Comment by av1ctor** [comment]
@MIchaelMainer 

Thanks.

I tried calling the /preview method using the Graph Explorer and got the same error message. 

Reading the API docs, there's a note saying that "The preview action is currently only available on SharePoint and OneDrive for Business.". I was testing with a personal account. My bad. 

I'm closing this issue. Thanks!
