### ISSUE TITLE
Print accessToken when error happened

### ISSUE THREAD

**Issue by ling595659851** [microsoftgraph/msgraph-sdk-java#387]
### Expected behavior
https://docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&tabs=http
I use the graph sdk for java to get the event info, but I got wrong parameter to the request, the error should printed without any sensitive infomation.

### Actual behavior
the accessToken was printed in exception
![image](https://user-images.githubusercontent.com/11716573/85493822-2ed72000-b60a-11ea-9f3c-5a2a3b986d15.png)

### Steps to reproduce the behavior
graphServiceClient.me().calendars("email").events(changedEventId).buildRequest(requestOptions).expand(EXTEND_PROPERTIES).get()

**Comment by baywet** [comment]
thank you for reporting this issue and for your patience.
I just authored PR #447 to fix this issue which will be closed whenever the PR gets merged.
