### ISSUE TITLE
login without asking username and password

### ISSUE THREAD

**Issue by hamedisu** [microsoftgraph/msgraph-sdk-java#388]
Hi
I am new to graph and java.
I wand to upload a file on onedrive repeatedly (for example every 10 minutes) using java.
how can I write a code that store my username and password of microsoft and app id and etc, and do the upload for me?
many thanks in advance.

**Comment by aukhatov** [comment]
Hi @hamedisu !
Up to you. Because you use your environment.

**Comment by MIchaelMainer** [comment]
Hello @hamedisu ! I suggest that you take a look at this tutorial+sample https://github.com/microsoftgraph/msgraph-training-java
