### ISSUE TITLE
Fail to PATCH event

### ISSUE THREAD

**Issue by kernelogic** [microsoftgraph/msgraph-sdk-java#391]
Hello I just upgraded to the latest 1.8.0 version from 1.7.1 and using https://graph.microsoft.com/v1.0 service root. However when I try to update an event it gives the following error message.

Cannot invoke the action, eventually got an error: com.microsoft.graph.http.GraphServiceException: Error code: RequestBodyRead
Error message: The property 'graphResponseHeaders' does not exist on type 'Microsoft.OutlookServices.Event'. Make sure to only use property names that are defined by the type or mark the type as open type.

PATCH https://graph.microsoft.com/v1.0/users/aa6683ae-427a-44e7-836b-ec0741fc717a/events/AAMkADEwMjU3OGYyLWU0NTktNDgyNy05ODUxLWRlYzQ5OWE4MmU5MwBGAAAAAACSVpJrwKxgR5K20zCB8fQRBwC98SkOlY-sRoGpzahBToGYAAAw0TA4AAC98SkOlY-sRoGpzahBToGYAAAw0TgTAAA=
SdkVersion : graph-java/v1.7.1
Authorization : Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI[...]
{"originalStartTimeZone":"Pacific Standard Time","[...]

400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]

**Comment by MIchaelMainer** [comment]
I suggest that you use create a patch object that only sends the properties you need to patch instead of reusing an object you previously fetched. The graphResponseHeaders are stamped on the object when it comes back to provide access to that information since we don't return a response envelope. 

Also, we need to fix the header here as well.

**Comment by baywet** [comment]
Hey @kernelogic 
Thanks for reporting this issue and thank you for your patience on the matter.
I just authored PR #448 fixe this issue which will be closed once it's merged.
