### ISSUE TITLE
Properties set via AdditionalDataManager on DriveItemUploadableProperties are not serialized in the request body

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-sdk-java#393]
Repro:

- Configure your project to use Fiddler so you can capture the request
- Use code like this:

    ```
    DriveItemUploadableProperties upProps = new DriveItemUploadableProperties();
    upProps.name = "vacation.gif";
    upProps.additionalDataManager().put("@microsoft.graph.conflictBehavior", new JsonPrimitive("rename"));

    // Create an upload session
    UploadSession uploadSession = graphClient
        .me()
        .drive()
        .root()
        // itemPath like "/Folder/file.txt"
        // does not need to be a path to an existing item
        .itemWithPath(itemPath)
        .createUploadSession(upProps)
        .buildRequest()
        .post();
    ```
- Review the request body in Fiddler

Result:

The `name` property is seralized, but not `@microsoft.graph.conflictBehavior`.

```
{"item":{"name":"vacation.gif"}}
```

**Comment by ddyett** [comment]
@jasonjoh  was this with version 1.8?

**Comment by jasonjoh** [comment]
Yes with 1.8. The sdk version header still says 1.7 but I verified that 1.8 is in my class path.

**Comment by MIchaelMainer** [comment]
Related to https://github.com/microsoftgraph/msgraph-sdk-java/commit/49680bfd80833e554263b6ce86ef4d02a0cbe202

**Comment by baywet** [comment]
thanks @jasonjoh !
I've authored PR #451 to fixe this issue which will get closed once it gets merged.

**Comment by tbithell** [comment]
Where/what is this additionalDataManager()
