### ISSUE TITLE
Download or Open a file from onedRIVE

### ISSUE THREAD

**Issue by Nicholas-Barbosa** [microsoftgraph/msgraph-sdk-java#398]
Hi,

Can I upload or download a file from oneDrive using this SDK??

**Comment by ddyett** [comment]
yes, see documentation below for capabilities and some example

https://docs.microsoft.com/en-US/graph/api/resources/onedrive?view=graph-rest-1.0
https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?view=graph-rest-1.0&tabs=java
