### ISSUE TITLE
Maven Central Repository does not have msgraph-sdk-java 1.8.0

### ISSUE THREAD

**Issue by tommai78101** [microsoftgraph/msgraph-sdk-java#399]
As shown here:

https://mvnrepository.com/artifact/com.microsoft.graph/microsoft-graph

![image](https://user-images.githubusercontent.com/6444116/87718456-c817d300-c77f-11ea-8efb-a76f3075b2de.png)

The latest version available on Maven Repository is 1.7.1. However, in the README.md section, it claims we can use version 1.8.0 released in June 2020. Currently, if I copied/pasted the Maven dependency in the README.md and placed it in my POM file, I would get a "could not find microsoft-graph.jar" library error message.

May I request that the Maven Central Repository be updated, so the 1.8.0 build is published to Maven Repository? Thanks.

**Comment by ddyett** [comment]
@ramsessanchez can you check on this?

**Comment by MIchaelMainer** [comment]
@tommai78101 1.8.0 is published. https://search.maven.org/search?q=g:com.microsoft.graph

**Comment by tommai78101** [comment]
@MIchaelMainer But I didn't see 1.8.0 here:

https://mvnrepository.com/artifact/com.microsoft.graph/microsoft-graph

And which Maven Central Repository is the correct Maven? I see the Sonatype one, but is that not the original Maven?

**Comment by MIchaelMainer** [comment]
It appears to have propagated to mvnrepository:

![image](https://user-images.githubusercontent.com/8527305/88300623-8bd0ff00-ccb8-11ea-8588-fec20fc6df95.png)

**Comment by tommai78101** [comment]
@MIchaelMainer 

Oh ok, cool. So there is some delay with the propagation, and I thought you would have to republish the builds across multiple Maven repositories each time. Sorry for the misunderstanding, and thanks for the clarification.

**Comment by MIchaelMainer** [comment]
@tommai78101 It is all magic to me. 😄

**Comment by odin-delrio** [comment]
FYI, it seems this had happened again today, the latest release 3.6.0 https://mvnrepository.com/artifact/com.microsoft.graph/microsoft-graph is not there, and with @dependabot doing its magic this will make more people wondering about what is happening (this is how I knew about this).

**Comment by baywet** [comment]
@odin-delrio it takes a while for mvnrepository to index new versions. 3.6.0 was released less than 24h ago and is available on sonatype/central https://repo1.maven.org/maven2/com/microsoft/graph/microsoft-graph/3.6.0/
We don't have control over mvnrepository but I'm confident the new version will eventually show up :)
