### ISSUE TITLE
GraphServiceClient rework

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#40]
The GraphServiceClient building api needs rework.

In particular, the builder allows you to do this:

```java
GraphServiceClient
  .builder()
  .fromConfig(config)
  .logger(logger)
  .buildClient();
```

However, the built client does not use the given logger in the `httpProvider` or `serializer` because they have already been instantiated before the `.logger(logger)` call.

To set the logger and the authenticationProvider I need to do this (and it depends on #38):

```java
        IClientConfig config = new DefaultClientConfig() {

            @Override
            public ILogger getLogger() {
                return logger;
            }

            @Override
            public IAuthenticationProvider getAuthenticationProvider() {
                return authProvider;
            }
        };

        IGraphServiceClient client = GraphServiceClient.builder() //
                .fromConfig(config) //
                .buildClient();
```

I'd prefer just to do this:

```java
GraphServiceClient client = GraphServiceClient
  .builder()
  .authenticationProvider(authProvider)
  .logger(logger)
  .buildClient();
```
Happy for this to be considered a bit later but should be sorted by public release.

**Comment by dadheech115** [comment]
Hi @davidmoten, as your PR is already merged for this issue, can I go ahead and close this issue?

**Comment by davidmoten** [comment]
Yes, thanks.
