### ISSUE TITLE
Cannot use inline images above ~4 MB using Java SDK/API

### ISSUE THREAD

**Issue by AyatoKamina** [microsoftgraph/msgraph-sdk-java#400]
### Expected behavior
When using an UploadSession to upload an attachment greater than ~3-4 MB , we should be able to set the isInline property and content ID so we can use even say a 5MB attachment as an inline image.

### Actual behavior
```AttachmentItem attachmentItem = new AttachmentItem();
attachmentItem.name = attachment.getOriginalFilename();
attachmentItem.attachmentType = AttachmentType.FILE;
attachmentItem.size = attachment.getSize();
attachmentItem.isInline = true;

graphClient
                    .users(sender)
                    .messages(message.id)
                    .attachments()
                    .createUploadSession(attachmentItem)
                    .buildRequest()
                    .post();
```

Creating an upload session as above, we upload the bytes successfully and send an email with the attachment > 4 MB. However, even though we make the upload session with isInline set to true in the AttachmentItem, it is set to false when the bytes are finished uploading in the actual message object, the FileAttachment item that is attached to the message after all bytes are successively finished uploading, has false as isInline and contentId is null..

```
FileAttachment patchAttachment = new FileAttachment();
patchAttachment.isInline = true;
patchAttachment.contentId = "contentId";
graphClient.users(sender).messages(message.id).attachments(attachmentId).buildRequest().patch(patchAttachment);
```

We have also tried to use the patch option as shown above to update/patch the attachment item using its ID , and just update the two properties, content ID and isInline (since the object is too large to use any other method), however when using patch on an attachment ID to a FileAttachment that is already attached to the message and whose bytes have already been uploaded, it fails with a "Method not allowed" error. 

Surely there is some method to use even a ~ 5MB image as an inline image?

### Steps to reproduce the behavior

-Create Message Object
-Create upload session to upload large attachment to that message object
-Hit the upload sessions upload URL to successively upload bytes to that upload session
-Attempt to use the resulting file attachment on the message object as an inline image (either by setting the AttachmentItem used to create the upload sessions isInline boolean or by patching the resulting attachment)

Any help on how to accomplish using ~5MB images as inline images would be greatly appreciated, or perhaps allowing users to patch attachments as we have attempted above so we can set isInline and content ID after they have been attached to the message object

**Comment by MIchaelMainer** [comment]
@svpsiva Is this possible?

**Comment by baywet** [comment]
this is most likely a service issue and not a SDK issue, see this corresponding issue in the docs.
https://github.com/microsoftgraph/microsoft-graph-docs/issues/9140
Closing this issue, please follow the one I pointed to.
