### ISSUE TITLE
Calling ".hasAttachments" on com.microsoft.graph.models.extensions.Message returns NULL for mail with attachment. 

### ISSUE THREAD

**Issue by axk7812** [microsoftgraph/msgraph-sdk-java#403]
Expected behavior
Calling hasAttachments should be true or false on instance of com.microsoft.graph.models.extensions.Message for an email that has attachments.
Actual behavior
Calling hasAttachments  returns null.
Steps to reproduce the behavior
   below is some java code. I'm using microsoft-graph version 1.8.0 from maven. 

    ClientCredentialProvider authProvider = new ClientCredentialProvider(
            clientId,
            Collections.singletonList(scope),
            secret,
            tenant,
            NationalCloud.Global);

    IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider(authProvider).buildClient();

    List<com.microsoft.graph.models.extensions.Message> messages = graphClient.users("<user>")
            .messages()
            .buildRequest()
            .select("sender,subject")
            .get()
            .getCurrentPage();

    for (com.microsoft.graph.models.extensions.Message m : messages) {

        log.info("message has attachments: " + m.hasAttachments);

    }

In the above code the log will print "message has attachments: null". it should be true/false.
[AB#5629](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5629)

**Comment by davidmoten** [comment]
That looks like an easy one. You have `.select("sender,subject")` which means that the `hasAttachments` field won't be returned. Include `hasAttachments` in that `select` statement and see if it works then.

**Comment by axk7812** [comment]
ok that worked, I just removed the select statement. Is it possible to get/download the file attachment from the `com.microsoft.graph.models.extensions.Message` instance?

**Comment by davidmoten** [comment]
Possible but messy is the answer.  An attachment is either a FileAttachment, ItemAttachment, or ReferenceAttachment. FileAttachment and ItemAttachment are streamable, ReferenceAttachment requires different treatment. One of the big holes in msgraph-sdk-java is that there is no support for inheritance (#154) and you are forced to check the metadata to see what attachment type it is, then retrieve the attachment a second time (even though all the data was already present in memory) to get the right type and then call its stream method (if it has one).

From memory the `$expand` option can be useful as long as the attachment is small. See https://stackoverflow.com/questions/34944174/how-to-retrieve-contents-of-an-itemattachment-via-the-microsoft-graph-api.

Possibly the best approach at the moment is to get the SMTP stream of the entire Message and parse it using javax.mail. That way you are guaranteed to get the attachments regardless of their attachment type. With luck you can do it with msgraph-sdk-java but I recall that the metadata was out of sync with reality in this regard (#385) and so msgraph-sdk-java might not have the required generated method. You can do this using [odata-client-msgraph](https://github.com/davidmoten/odata-client) (an alternative client built because of problems like this):

```java
byte[] bytes = client.me().messages(id).get().getStream().get().getBytes();
```
cc @SuperEvenSteven

**Comment by axk7812** [comment]
Agree it is a bit messy to get the attachment. I solved it a different way. I use the graph client to call again with the message Id to get an attachment. And then on the attachment, I call `getRawObject()` and parse out "contentBytes" and decode it from Base64 and download it as a file. This seems to work for now.

**Comment by davidmoten** [comment]
>Agree it is a bit messy to get the attachment. I solved it a different way. I use the graph client to call again with the message Id to get an attachment. And then on the attachment, I call getRawObject() and parse out "contentBytes" and decode it from Base64 and download it as a file. This seems to work for now.

I assume this won't work once the contentBytes gets a bit large because of Graph API constraints. If your attachments are reliably small you have nothing to worry about.

**Comment by axk7812** [comment]
Do you happen to know what the download size limit is using that approach? [This](https://docs.microsoft.com/en-us/graph/api/attachment-createuploadsession?view=graph-rest-1.0&tabs=http) document mentions 150MB but that's for uploads.

**Comment by davidmoten** [comment]
4MB for requests (outside of specialized streaming endpoints which is what you would use for a large upload). I haven't seen response size limits for normal API interactions but I assume it is similar. @MIchaelMainer do you know?

**Comment by baywet** [comment]
Thank you for your patience. I'm still trying to get the repository organized and in a better shape.
I'm not aware of any global service download limit at this time. Individual services might have their own limits in place though or redirect your application to a specific location to download the file [example](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=http)

Let me know if you have more questions or if I can close this issue. :)

**Comment by axk7812** [comment]
Just want to know the (approximate if any) download limit from the method I was using

> I call getRawObject() and parse out "contentBytes" and decode it from Base64 and download it as a file. This seems to work for now.

If it's not known can close this

**Comment by baywet** [comment]
I don't know. Thanks for the response. Closing

**Comment by davidmoten** [comment]
We don't need to close this yet. Just do some tests!

**Comment by baywet** [comment]
> We don't need to close this yet. Just do some tests!

@davidmoten this repo is responsible for the java SDK. Not for the service itself. The service is actually a composition of dozens of what we call "workloads" (sets of APIs). And each of them can have different policies and limitations.
The best way to address gaps in the documentation (which in this case it is), is to open issues in the [documentation repo](https://github.com/microsoftgraph/microsoft-graph-docs/) via the Feedback menu (all the way at the bottom).
The service teams will then triage the issues and assign this to the rightful owner who has the information.

**Comment by davidmoten** [comment]
> @davidmoten this repo is responsible for the java SDK. Not for the service itself. The service is actually a composition of dozens of what we call "workloads" (sets of APIs). And each of them can have different policies and limitations.
The best way to address gaps in the documentation (which in this case it is), is to open issues in the documentation repo via the Feedback menu (all the way at the bottom).
The service teams will then triage the issues and assign this to the rightful owner who has the information.

Ok, I did a test anyway and downloaded 11MB into the contentBytes field of a FileAttachment. Looks like the payload limits don't apply for download.
