### ISSUE TITLE
HowTo Update Users mail address?

### ISSUE THREAD

**Issue by MBurchard** [microsoftgraph/msgraph-sdk-java#404]
In our Application we access users with MS Graph Beta API to get all custom properties.

```java
client =
	GraphServiceClient.builder().authenticationProvider(authProvider::authenticate)
		.buildClient();
client.setServiceRoot("https://graph.microsoft.com/beta");
```
Even reading the user data was costly and complex because some values are unexpectedly not set or accessible at different locations then expected.

To get a Graphusers email address we had to check the identities because graphuser.mail is always null.

```java

@Nonnull
private static Map<String, String> getIdentities(
		@Nonnull final com.microsoft.graph.models.extensions.User graphUser) {
	final Map<String, String> identities = new LinkedHashMap<>();
	final JsonElement jsonElement = graphUser.getRawObject().get("identities");
	if (jsonElement.isJsonArray()) {
		final JsonArray jsonArray = jsonElement.getAsJsonArray();
		for (final JsonElement element : jsonArray) {
			if (element.isJsonObject()) {
				final JsonObject jsonObject = element.getAsJsonObject();
				identities.put(jsonObject.get("signInType").getAsString(),
						jsonObject.get("issuerAssignedId").getAsString());
			}
		}
	}
	return identities;
}

@Nonnull
public static User map(@Nonnull final com.microsoft.graph.models.extensions.User graphUser) {
	final User user = new User();
	final Map<String, String> identities = getIdentities(graphUser);

	user.setId(graphUser.id);
	// graphUser.mail is always null
	user.setEmail(identities.get("emailAddress"));

```

Now I want to change that email address.

I found some .NET Code, that I translated into Java...

```java
private static void setSignInEmail(@Nonnull final com.microsoft.graph.models.extensions.User user,
		@Nonnull final String email) {
	final JsonArray signInNamesArray = new JsonArray();
	final JsonObject signInNameObject = new JsonObject();
	signInNameObject.add("emailAddress", new JsonPrimitive(email));
	signInNamesArray.add(signInNameObject);
	user.additionalDataManager().put("signInNames", signInNamesArray);
}
```

Sadly this Code doesn't work.

	A value without a type name was found and no expected type is available. When the model is specified, each value in the payload must have a type which can be either specified in the payload, explicitly by the caller or implicitly inferred from the parent value.

Can someone please show me an example of how I can change the email address in our scenario?

**Comment by davidmoten** [comment]
Is that error message from the Graph API or from the SDK. Stack trace?

Would be helpful to see what JSON went to the server on this one. I do note from https://docs.microsoft.com/en-us/graph/api/resources/objectidentity?view=graph-rest-beta that the `issuer` field may need to be set as well.

**Comment by MIchaelMainer** [comment]
Can you provide links to the documentation for the APIs you want to use? Also, can you share a sanitized http request and response with us?

**Comment by MBurchard** [comment]
@davidmoten Thank you very much for posting this link.

I don't know why the .NET Code works when setting `signInNames`.

With the Java SDK the following code works

```java
	private static void setSignInEmail(@Nonnull final com.microsoft.graph.models.extensions.User user,
			@Nonnull final String email, @Nonnull final String tenant) {
		final JsonArray signInNamesArray = new JsonArray();
		final JsonObject signInNameObject = new JsonObject();
		signInNameObject.add("signInType", new JsonPrimitive("emailAddress"));
		signInNameObject.add("issuer", new JsonPrimitive(String.format("%s.onmicrosoft.com", tenant)));
		signInNameObject.add("issuerAssignedId", new JsonPrimitive(email));
		signInNamesArray.add(signInNameObject);
		user.additionalDataManager().put("identities", signInNamesArray);
	}
```

@MIchaelMainer I found out, that setting debug mode as follows:

```java
	protected void init() {
		if (state == State.created) {
			state = State.initialized;
			final IClientConfig config =
					DefaultClientConfig.createWithAuthenticationProvider(authProvider::authenticate);
			config.getLogger().setLoggingLevel(LoggerLevel.DEBUG);
			client = GraphServiceClient.fromConfig(config);
			client.setServiceRoot("https://graph.microsoft.com/beta");
		}
	}
```
It then shows the JSON request on failure but not in general. Is there a way to show all requests and responses?

The issue itself is solved, thank you for your support...
