### ISSUE TITLE
Using skipToken in calendarView delta results in Access Denied Error

### ISSUE THREAD

**Issue by vcupelloni** [microsoftgraph/msgraph-sdk-java#405]
In our application we access the calendarView of a room mailbox by delta in this way

```java
requestOptions = new LinkedList<Option>();
requestOptions.add(new HeaderOption("Prefer", "odata.maxpagesize=10"));
requestOptions.add(new QueryOption("startdatetime", OffsetDateTime.now(ZoneOffset.UTC).toString()));
requestOptions.add(new QueryOption("enddatetime", OffsetDateTime.now(ZoneOffset.UTC).plusYears(1).toString()));
			
delta = msGraphClient.users("resource-account")
		     .calendars("calendar-id")
  		     .calendarView()
		     .delta()
		     .buildRequest( requestOptions )
		     .get();
```

And then, until is present, we use the skipToken to retrieve the next pages like this

```java
requestOptions = new LinkedList<Option>();
requestOptions.add(new HeaderOption("Prefer", "odata.maxpagesize=10"));
requestOptions.add(new QueryOption("$skiptoken", "skip-token-obtained"));
				
delta = msGraphClient.users(subscription.getResource().getResourceAccount())
		     .calendars(subscription.getResource().getExternalId())
		     .calendarView()
		     .delta()
		     .buildRequest( requestOptions )
		     .get();
```

The former call works fine but the latter result is:
```
403 : Forbidden
Strict-Transport-Security : max-age=31536000
Cache-Control : private
x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceC","Ring":"5","ScaleUnit":"004","RoleInstance":"AGSFE_IN_28"}}
client-request-id : f5518047-1cfa-41c4-9a33-d9f6b828f4e6
request-id : f0ec3b91-a4f0-4245-bf78-ccba482e4f39
Content-Length : 253
Preference-Applied : odata.track-changes
Date : Thu, 06 Aug 2020 09:30:05 GMT
Content-Type : application/json
{
  "error": {
    "code": "ErrorAccessDenied",
    "message": "Access is denied. Check credentials and try again.",
    "innerError": {
      "date": "2020-08-06T09:30:05",
      "request-id": "f0ec3b91-a4f0-4245-bf78-ccba482e4f39"
    }
  }
}
```

The user we use is a delegated account with full access to the room mailbox and our application has Calendar.ReadWrite and Calendar.ReadWrite.Shared permission on that delegated account.

Is there something more that we have to configure on the permissions?
Are  Calendar.ReadWrite and Calendar.ReadWrite.Shared enough to have full access to the calendarView?

**Comment by MIchaelMainer** [comment]
Can you try this example: https://github.com/microsoftgraph/msgraph-sdk-java/wiki/Working-with-collections#getting-the-next-page? Let me know the results.

The nextPage request should be initialized with the skiptoken URL. The skip token is not a URL fragment, it is a complete URL to request the next page.

**Comment by vcupelloni** [comment]
I've already tried the code on that example and even doing the calls directly from Postman but nothing worked.... until our client finally double checked his configuration and reassigned all the delegate permissions from scratch. 
Now it works perfectly....  Sorry for the inconvenience.
