### ISSUE TITLE
Confusing information about latest version of SDK

### ISSUE THREAD

**Issue by hosmanagic-axcient** [microsoftgraph/msgraph-sdk-java#407]
At first, it indicates the latest version is 1.9.0:
<img width="474" alt="Screen Shot 2020-08-11 at 12 44 46" src="https://user-images.githubusercontent.com/57673206/89890042-f51aa280-dbd2-11ea-8ae7-1eae47910714.png">

Source code indicates the same: https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/core/Constants.java#L31

The installation instructions indicate it's 1.8.0:
<img width="450" alt="Screen Shot 2020-08-11 at 12 45 30" src="https://user-images.githubusercontent.com/57673206/89890058-02d02800-dbd3-11ea-8e9d-c1fdee649458.png">

The releases and tags, though, say it's 1.6.0:
<img width="780" alt="Screen Shot 2020-08-11 at 12 46 18" src="https://user-images.githubusercontent.com/57673206/89890142-285d3180-dbd3-11ea-9084-c5dc66cd41df.png">

It would be good to have the information up-to-date, especially the installation instructions. Unless there's a specific reason for this discrepancy (such as 1.9 being a snapshot, and 1.8 being GA), I'll be free to open a PR to update the README.

**Comment by MIchaelMainer** [comment]
We plan on fixing our releases and getting these semvers in sync.

**Comment by hosmanagic-axcient** [comment]
@MIchaelMainer That's some good news. 👍  Thanks for the information!

**Comment by baywet** [comment]
thanks for bringing this to our attention!
I went ahead a created PR #415 to address the issue. This issue will be closed when the pull request gets merged.
I also created the tags and releases retroactively.
Let me know if I missed something
