### ISSUE TITLE
There is no way to get and update MSTeams ChannelSetttings

### ISSUE THREAD

**Issue by Shubh-arya** [microsoftgraph/msgraph-sdk-java#408]
Hi There,

I have a use case where I have to view and update MS Teams Channel setting such a moderation and permissions but at SDK response for getChannel does not return ChannelSettings and in update channel it does not have any option to update the channel settings.

please update if it is supported via java SDK? if yes provide any pointer to do the same.

Thanks,
Shubham

**Comment by MIchaelMainer** [comment]
This isn't supported by the service API. This is planned, I have no eta.
