### ISSUE TITLE
Is there a way to get guest user from api.

### ISSUE THREAD

**Issue by Shubh-arya** [microsoftgraph/msgraph-sdk-java#425]
Hi There,

I have a use case where I have get a guest user. I have the email address with me but when I am trying graph api get user, it returns me below error.

404 : Not Found.

Please let me how can I fix this issue or is it not possible?

**Comment by MIchaelMainer** [comment]
Can you show us what you have tried? Please include links to the documentation that you are using. You should cross post this to StackOverflow as you'll get more views for your question. Post the link here once you post there. Please reopen when you have more information for us.
