### ISSUE TITLE
Guest user is not shown in MS Teams team

### ISSUE THREAD

**Issue by Shubh-arya** [microsoftgraph/msgraph-sdk-java#426]
Hi There,

I have created a office 365 group using groups endpoint having on guest user from different domain. It is getting added successfully and I verified  on azure portal groups as well that guest user is a member of the group.

Post group creation, I have created a MS Teams team using beta version endopint createTeam for above group, team is getting created  successfully but in members guest users are missing. only domain user are getting shown.

Please let me know if any specific setting is required for guest user to get added in the MS Teams team.

Thanks,
Shubham

**Comment by MIchaelMainer** [comment]
Can you show us what you have tried? Please include links to the documentation that you are using. You should cross post this to StackOverflow as you'll get more views for your question. Post the link here once you post there. Please reopen when you have more information for us.
