### ISSUE TITLE
GraphClient.customRequest returns a BufferedInputStream instead of JsonObject when calling Beta endpoint

### ISSUE THREAD

**Issue by malvikam** [microsoftgraph/msgraph-sdk-java#456]
### Expected behavior
According to the [documentation](https://github.com/microsoftgraph/msgraph-sdk-java/wiki/Custom-Requests#deserializing-new-objects), calling GraphClient.customRequest without providing an existing model, the results are deserialized into JsonObject.

### Actual behavior
GraphClient.customRequest returns a java.io.BufferedInputStream that causes a ClassCastException
java.lang.ClassCastException: java.io.BufferedInputStream cannot be cast to com.google.gson.JsonObject

### Steps to reproduce the behavior
Issue occuring in version 1.7.1
We are using this code to query the https://graph.microsoft.com/beta/policies/identitySecurityDefaultsEnforcementPolicy endpoint. 

`````Java
suspend fun getSecurityDefaultTenantPolicy(accessToken: String): Boolean = suspendCoroutine { continuation ->
    val graphCallback = object : ICallback<JsonObject> {
            override fun success(result: JsonObject) {
                val isEnabled = result.get(isEnabledKey)
                continuation.resume(isEnabled?.asBoolean == true)
            }
            override fun failure(ex: ClientException?) {
                ex?.let {
                    continuation.resumeWithException(ex)
                }
                    ?: continuation.resumeWithException(Exception("Microsoft graph getSecurityDefaultTenantPolicy() failed with unknown exception."))
            }
        }
        this.accessToken = accessToken
        graphClient.serviceRoot = "https://graph.microsoft.com/beta/";
        graphClient.customRequest("/policies/identitySecurityDefaultsEnforcementPolicy").buildRequest()?.get(graphCallback)
    }
`````

This is resulting in 

`java.lang.ClassCastException: java.io.BufferedInputStream cannot be cast to com.google.gson.JsonObject
com.microsoft.authenticator.graphclient.GraphHelper$getSecurityDefaultTenantPolicy$2$graphCallback$1.success GraphHelper.kt:60
com.microsoft.graph.concurrency.DefaultExecutors$1.run DefaultExecutors.java:92
com.microsoft.graph.concurrency.SynchronousExecutor.execute SynchronousExecutor.java:45
com.microsoft.graph.concurrency.DefaultExecutors.performOnForeground DefaultExecutors.java:89
com.microsoft.graph.http.CoreHttpProvider$1.run CoreHttpProvider.java:155
java.util.concurrent.ThreadPoolExecutor.runWorker ThreadPoolExecutor.java:1167
java.util.concurrent.ThreadPoolExecutor$Worker.run ThreadPoolExecutor.java:641
java.lang.Thread.run Thread.java:764`

The exception occurs when the success callback is being called from DefaultExecutors.java line 92.

**Comment by baywet** [comment]
Hi @malvikam 
Thanks for reaching out.
Quick question: is there any reason you are not using the [beta SDK](https://github.com/microsoftgraph/msgraph-beta-sdk-java) to access beta APIs? You'll get the types you need as well as automatic serialization/deserlization for those.
Can you also provide the SDK version you are using please?
Can you format your code sample for readability please?
(use ```Java and ```` around the code)

**Comment by baywet** [comment]
also related #331

**Comment by malvikam** [comment]
@baywet thanks for quick response. We are using version 1.7.1. I was unaware of the beta SDK. We plan to query both v1 and beta endpoints and this msgraph-sdk-java provides a way to query both endpoints easily.

**Comment by baywet** [comment]
No worries. Beta SDK was released a couple of weeks ago (but it uses the same generation process as the v1 one, so besides the fact that it targets beta endpoints by default, it is as reliable).
I'm going to close the issue, let me know if we need to reopen.
