### ISSUE TITLE
Duplicate errors when upgrading from version 2.0.0 to 2.1.0

### ISSUE THREAD

**Issue by RegisStGelais** [microsoftgraph/msgraph-sdk-java#457]
My code compile with version 2.0.0 but with version 2.1.0 I get the following duplicate class errors.

Duplicate class org.hamcrest.BaseDescription found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.BaseMatcher found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.CoreMatchers found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.Description found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.Factory found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.Matcher found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.SelfDescribing found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.StringDescription found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.core.AllOf found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.core.AnyOf found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.core.DescribedAs found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.core.Is found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.core.IsAnything found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.core.IsEqual found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.core.IsInstanceOf found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.core.IsNot found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.core.IsNull found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.core.IsSame found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.internal.ArrayIterator found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.internal.SelfDescribingValue found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)
Duplicate class org.hamcrest.internal.SelfDescribingValueIterator found in modules jetified-hamcrest-core-1.1.jar (org.hamcrest:hamcrest-core:1.1) and jetified-junit-4.10.jar (junit:junit:4.10)

**Comment by baywet** [comment]
Salut Régis,
Which version of core are you using?

**Comment by RegisStGelais** [comment]
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'com.dropbox.core:dropbox-core-sdk:3.1.5'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.code.gson:gson:2.8.6'

    implementation 'com.dropbox.core:dropbox-core-sdk:3.1.5'
    api 'com.squareup.okhttp3:okhttp:4.4.0'

    implementation 'com.microsoft.identity.client:msal:1.6.0'
    implementation 'com.android.volley:volley:1.1.1'
    implementation 'com.microsoft.graph:microsoft-graph:2.1.0'

    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

}

```
I get no errors if I implement com.microsoft.graph:microsoft-graph:2.0.0

**Comment by baywet** [comment]
thanks!
Can you run `./gradlew dependencies` and copy the result here please?

**Comment by RegisStGelais** [comment]
Salut Vincent !

I used gradlew dependencies  (had to remove the ./) in the Android Studio terminal view and got this:

Welcome to Gradle 6.1.1!

Here are the highlights of this release:
 - Reusable dependency cache
 - Configurable compilation order between Groovy/Kotlin/Java/Scala
 - New sample projects in Gradle's documentation

For more details see https://docs.gradle.org/6.1.1/release-notes.html

Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

No configurations

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 24s
1 actionable task: 1 executed

Welcome to Gradle 6.1.1!

Here are the highlights of this release:
 - Reusable dependency cache
 - Configurable compilation order between Groovy/Kotlin/Java/Scala
 - New sample projects in Gradle's documentation

For more details see https://docs.gradle.org/6.1.1/release-notes.html

Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

No configurations

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 24s
1 actionable task: 1 executed

**Comment by baywet** [comment]
it looks that you are either not using gradle to build your project or that you were not in the right folder (where build.gradle is located) when you ran the command. I'm not super familiar with Android studio. Can you check whether you have a build.gradle in your repo please?

**Comment by RegisStGelais** [comment]
I have this build.graddle in the root of my project:

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}


And that one in the app sub-folder:

apply plugin: 'com.android.application'

android {
    signingConfigs {
        release {
            storeFile file('C:\\_Laubrass\\Android_Releases\\_laubrass.keystore.jks')
            storePassword 'laub7256'
            keyAlias = 'umtplus'
            keyPassword 'umtplus7256'
        }
    }
    compileSdkVersion 29
    buildToolsVersion '30.0.0 rc1'
    compileOptions.encoding = 'windows-1252'

    defaultConfig {
        applicationId "com.laubrass.android.umtplus"
        minSdkVersion 19
        //noinspection ExpiredTargetSdkVersion
        targetSdkVersion 22
        //noinspection HighAppVersionCode
        versionCode 2020061701
        // Note: Max value for versionCode in google play is 210000000
        versionName "20.0.0 (M33)"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release

            // Enables code shrinking, obfuscation, and optimization
            minifyEnabled true

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources true

            // Includes the default ProGuard rules files that are packaged with
            // the Android Gradle plugin. To learn more, go to the section about
            // R8 configuration files.
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'

        }

        debug {
            debuggable true
        }

    }
    flavorDimensions "version"
    productFlavors {
        MAX {
            dimension "version"
        }
        TIM {
            dimension "version"
        }
        SAM {
            dimension "version"
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "UmtPlus_${variant.name}_${variant.versionName}.apk"
                    .replace("Release_", "_V")
                    .replace("Debug_", "_Debug_V")
                    .replace(" ", "_")
                    .replace("(", "")
                    .replace(")", "")
                    .replace(".", "_")
                    .replace("_apk", ".apk")
        }
    }

    packagingOptions {
        pickFirst 'META-INF/jersey-module-version'
    }

}

repositories {
    maven { url 'https://pkgs.dev.azure.com/MicrosoftDeviceSDK/DuoSDK-Public/_packaging/Duo-SDK-Feed%40Local/maven/v1' }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'com.dropbox.core:dropbox-core-sdk:3.1.5'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.code.gson:gson:2.8.6'

    api 'com.squareup.okhttp3:okhttp:4.4.0'

    implementation 'com.microsoft.identity.client:msal:1.6.0'
    implementation 'com.android.volley:volley:1.1.1'
    implementation 'com.microsoft.graph:microsoft-graph:2.1.0'

    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}

**Comment by RegisStGelais** [comment]
it compile fine if I use implementation 'com.microsoft.graph:microsoft-graph:2.0.0'

**Comment by Miha22** [comment]
If you exclude junit, you wont be able to perform unit tests and will get error like 'Cannot resolve @org.junit.Test or @Before'
