### ISSUE TITLE
proguard rules

### ISSUE THREAD

**Issue by RegisStGelais** [microsoftgraph/msgraph-sdk-java#462]
Note: This is not an Issue but rather a question.

What are the proguard rules I need to add for the sdk to work in release build ?
Also note that until 2.1.1 is released, I use 2.0.0

**Comment by RegisStGelais** [comment]
I tryed these but my app does not work in release.

```
##---------------Begin: proguard configuration for MsGraph  ----------
-keep class com.microsoft.** { *; }
-keep class com.microsoft.**
-keep interface com.microsoft.** { *; }
-keepclasseswithmembernames class com.microsoft.** { *; }

-keep class com.sun.** { *; }
-keep class com.sun.**
-keep interface com.sun.** { *; }
##---------------END: proguard configuration for MsGraph  ----------

```

**Comment by RegisStGelais** [comment]
4 days, still in triage :(

**Comment by baywet** [comment]
> 4 days, still in triage :(

Our triage is weekly late on Thursdays.

**Comment by baywet** [comment]
I've been reaching out to a team at Microsoft building an Android app that has been downloaded millions of times using our Java SDK to get their proguard-rules.txt. Here is an abbreviated version of it.
```
-keep class com.microsoft.** { *; }

## GSON 2.2.4 specific rules ##
# Source: https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature
# For using GSON @Expose annotation
-keepattributes *Annotation*
-keepattributes EnclosingMethod
# Gson specific classes
-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.stream.** { *; }
# Gson specific classes used by Broker.
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

-dontnote sun.misc.Unsafe # see line 119
-dontnote com.google.gson.** # see line 119

# JUnit
-dontwarn org.junit.**
-dontwarn junit.**

# okhttp

-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**

# okio

-keep class sun.misc.Unsafe { *; }
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-dontwarn okio.**
``

**Comment by RegisStGelais** [comment]
I added these rules but it still does not work in release.
MSAL connects but I get no response when I try get the file list.
I will need to add some traces in a log file to figure out where it is not working.

**Comment by RegisStGelais** [comment]
.me()
                .drive()
                .root()
                .itemWithPath(AppPrefs.getInstance().getOneDriveFolder())
                .children()
                .buildRequest()
                .get(new ICallback<IDriveItemCollectionPage>()

returns with a failure:
 ex.toString() : com.microsoft.graph.core.ClientException: Error during http request
ex.getCause(): java.lang.RuntimeException: java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl

**Comment by baywet** [comment]
Please try it with 2.1.0

**Comment by RegisStGelais** [comment]
ok, I was able to upgrade to 2.1 using the trick in issue #450 
implementation('com.microsoft.graph:microsoft-graph:2.1.0'){
exclude group: 'org.hamcrest'
}

I can now, in release, get a file list and download a file but my uploadsession now crashs both in release and in debug.

You can close this issue. 

I will continu to investigate the uploadsession and comment on my issue #472 

( Merci Vincent ! )

**Comment by baywet** [comment]
glad I could help! I've added PR #476 so the required proguard rules are documented and we can improve them over time.
The PR will close this issue once it gets merged.

Bienvenu!

**Comment by atulgpt** [comment]
Hi @baywet since we are in process of integration we should also be needing the pro-guard rules. But the current one needs to include everything in the keep rule. As we are not using all of the lib features, keeping all the file will unnecessarily increase it's size and better pro-guard rules should be recommended. Should we reopen this issue or create a new one to track these concerns?

**Comment by baywet** [comment]
the rules will depend on a project base but I think our sample could be more specific by default. I.e. we should replace
```
-keep class com.microsoft.** { *; }
```

by 
```
#msgraph-java-core
-keep class com.microsoft.graph.content.** { *; }
-keep class com.microsoft.graph.httpcore.** { *; }

#msgraph-java-auth
-keep class com.microsoft.graph.auth.** { *; }

#MSAL
-keep class com.microsoft.aad.msal4j.** { *; }

#msgraph-java
-keep class com.microsoft.graph.authentication.** { *; }
-keep class com.microsoft.graph.concurrency.** { *; }
-keep class com.microsoft.graph.core.** { *; }
-keep class com.microsoft.graph.http.** { *; }
-keep class com.microsoft.graph.logger.** { *; }
-keep class com.microsoft.graph.options.** { *; }
-keep class com.microsoft.graph.serializer.** { *; }
# + any class you use from com.microsoft.graph.models or com.microsoft.graph.requests
```

This should drop the size by approx 10 000 classes and be much better for android development. What do you think? Can you give it a try?

**Comment by RegisStGelais** [comment]
I will give it a try and get back to you.

(Note: Did you see the sample code I sent you for my upload file issue? )

**Comment by baywet** [comment]
proguard is supposed to be able to keep any class/interface/... that's not loaded using reflection (direct reference in the tree) by default. The idea of those rules is to help it keep things it didn't discover by itself. As this is a template you can always tweak it to your project.

**Comment by baywet** [comment]
@atulgpt what results do you get with these rules instead of the global one https://github.com/microsoftgraph/msgraph-sdk-java/issues/462#issuecomment-694397258?

**Comment by atulgpt** [comment]
@baywet Let me check and then I will revert back with my findings. In the case of @RegisStGelais he might be using a lot of this library so that's why the result is the same with both the ProGuard rules.

**Comment by RegisStGelais** [comment]
In my case, both apks have the exact same size.

**Comment by atulgpt** [comment]
Hi @baywet sorry for late reponse...So I have checked the with both of the proguard configuration and apk seems to be around 3.3 MB in both the cases(I am talking about my sample project). But I found that even wothout any proguard rules apk is still coming out be 3.3 MB. So I printed the configuration of proguard and it seems that [MSAL library](https://github.com/AzureAD/microsoft-authentication-library-for-android) that I have added is adding these **proguard** rules
# The proguard configuration file for the following section is /Users/atulgup/.gradle/caches/transforms-2/files-2.1/8fef34674c6eecc4ce617b22a4c67aa0/jetified-msal-1.6.0/proguard.txt
# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in C:\Program Files\Android\android-sdk/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

##---------------Begin: proguard configuration for MSAL  --------
**-keep class com.microsoft.** { *; }**

##---------------Begin: proguard configuration for Nimbus  ----------
-keep class com.nimbusds.** { *; }

... some more rules..

# End of content from /Users/atulgup/.gradle/caches/transforms-2/files-2.1/8fef34674c6eecc4ce617b22a4c67aa0/jetified-msal-1.6.0/proguard.txt

**Comment by baywet** [comment]
No worries, thanks for coming back on this one. Very good catch! And thanks for opening the issue over msal. It's most likely because of this line https://www.github.com/AzureAD/microsoft-authentication-library-for-android/tree/dev/msal%2Fconsumer-rules.pro#L27

Which is probably impacting a lot of downstream library and consumers.

I'll try to open a pr over their repo tomorrow.

**Comment by atulgpt** [comment]
Hi, @baywet I think the line you mentioned is a very common rule in Proguard. Instead, the main culprit is this line: https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/29ce96c448dfa7ffca3baf1a38f3d5029ae8a483/msal/consumer-rules.pro#L20

**Comment by atulgpt** [comment]
One more rule that seems to be problematic is at this line: https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/29ce96c448dfa7ffca3baf1a38f3d5029ae8a483/msal/consumer-rules.pro#L23 As I have not used the library so not sure whether the used rule is correct or not

**Comment by RegisStGelais** [comment]
The only Proguard rule I use with MSAL 1.6.0 is:
##---------------Begin: proguard configuration for MSAL  ----------
#noinspection ShrinkerUnresolvedReference
-keep class com.microsoft.device.display.**
##---------------END: proguard configuration for MSAL  ----------

**Comment by baywet** [comment]
@atulgpt yep, I meant 20 but I was on my phone... sorry about that.

**Comment by baywet** [comment]
I've just authored https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1161
And https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/1047
I suspect the reason why they had such a large rule was because of the device display package @RegisStGelais was sharing in his last comment.
Hopefully they'll be able to merge and publish soon, then we'll bump and publish in our auth library and the end to end issue should be solved.

**Comment by atulgpt** [comment]
Hi @baywet thanks for the prompt response and current changes seems to be more correct. And for now should work. 
But do you have an idea why in MSAL library we want to keep all the files(using keep class com.microsoft.identity.client.\*\* \{ \*\; \})? Are in those libraries all those files are being used from reflection?

**Comment by baywet** [comment]
I have no idea. But I wanted to make the change that had the least chances of breaking something. With that change (and the other PR) they should still get to keep everything they need without impacting other libraries like ours. Ideally they'd come up with more specific rules and do extensive validation.

**Comment by atulgpt** [comment]
@baywet Yes that makes sense. Thanks for the quick support

**Comment by baywet** [comment]
Hi everyone,
Good news, the MSAL PR has been merged https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1203
I'm going to close this issue since there's no further action required here. Don't hesitate to publish feedback and app size reduction once MSAL releases a new version and you have added it to your application!
