### ISSUE TITLE
Conflict behavior parameter set via AdditionalDataManager on DriveItemUploadableProperties is not serialized correctly in the request body

### ISSUE THREAD

**Issue by niczon** [microsoftgraph/msgraph-sdk-java#468]
Unfortunately the fix for #393 in 2.1.0 is not okay.
Expected behavior
{
  "item": {
    "@microsoft.graph.conflictBehavior": "rename",
    "name": "vacation.gif"
  }
}

See API reference.
Actual behavior
{
  "item": {
    "name": "vacation.gif"
  }
  "@microsoft.graph.conflictBehavior": "rename"
}

The @microsoft.graph.conflictBehavior property is ignored by the service.
Steps to reproduce the behavior
DriveItemUploadableProperties upProps = new DriveItemUploadableProperties();
upProps.name = "vacation.gif";
upProps.additionalDataManager().put("@microsoft.graph.conflictBehavior", new JsonPrimitive("rename"));

// Create an upload session
UploadSession uploadSession = graphClient
    .me()
    .drive()
    .root()
    // itemPath like "/Folder/file.txt"
    // does not need to be a path to an existing item
    .itemWithPath(itemPath)
    .createUploadSession(upProps)
    .buildRequest()
    .post();

Proposed fix
Add @microsoft.graph.conflictBehavior to the DriveItemUploadableProperties class just like @odata.type:
    @SerializedName("@microsoft.graph.conflictBehavior")
    @Expose
    public String conflictBehavior;

Then we can set the conflict behavior by upProps.conflictBehavior = "rename"; and the parameter gets added to the item property correctly.
[AB#6034](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6034)

**Comment by baywet** [comment]
Thanks for the feedback! And sorry about that, it's a miss from my side.
I just authored #471 which should fix the issue for good. The PR will close this issue once it gets merged.
