### ISSUE TITLE
msgraph-sdk-java vs msgraph-sdk-android

### ISSUE THREAD

**Issue by RegisStGelais** [microsoftgraph/msgraph-sdk-java#474]
I'm integrating OneDrive in my Android app using msgraph-sdk-java and just realized that there is another library called  msgraph-sdk-android. (archived)

The android version seams dead or at least not very active.

Is it ok to use the msgraph-sdk-java library for my Android app ?

**Comment by baywet** [comment]
yes, this library is the official library for java and android based applications.
