### ISSUE TITLE
ChunkedUploadProvider: no success callback with DriveItem anymore in 2.2.0

### ISSUE THREAD

**Issue by niczon** [microsoftgraph/msgraph-sdk-java#491]
### Expected behavior

When uploading a DriveItem with ChunkedUploadProvider has completed (HTTP response 201 Created), we would get a success callback containing the DriveItem that has been uploaded.

### Actual behavior

We get another progress callback. The issue is in ChunkedUploadResponseHandler where session != null.

<img width="765" alt="ChunkedUploadResponseHandler" src="https://user-images.githubusercontent.com/71315274/93909653-418fec80-fd00-11ea-9abe-152389962cd2.PNG">

Also, the progress callbacks that we get are incorrect. In the next example it should return 5242880 (as the first chunk of 5 MB has just been uploaded), while we get 0.

<img width="699" alt="ReadSoFar" src="https://user-images.githubusercontent.com/71315274/93909964-b4996300-fd00-11ea-8cf8-76f1d9fa4fd8.PNG">

### Steps to reproduce the behavior

```
// Get an input stream for the file
File file = new File(localFilePath);
InputStream fileStream = new FileInputStream(file);
long streamSize = file.length();

// Create a callback used by the upload provider
IProgressCallback<DriveItem> callback = new IProgressCallback<DriveItem>() {
    @Override
    // Called after each slice of the file is uploaded
    public void progress(final long current, final long max) {
        System.out.println(
            String.format("Uploaded %d bytes of %d total bytes", current, max)
        );
    }

    @Override
    public void success(final DriveItem result) {
        System.out.println(
            String.format("Uploaded file with ID: %s", result.id)
        );
    }

    public void failure(final ClientException ex) {
        System.out.println(
            String.format("Error uploading file: %s", ex.getMessage())
        );
    }
};

// Create an upload session
UploadSession uploadSession = graphClient
    .me()
    .drive()
    .root()
    // itemPath like "/Folder/file.txt"
    // does not need to be a path to an existing item
    .itemWithPath(itemPath)
    .createUploadSession(new DriveItemUploadableProperties())
    .buildRequest()
    .post();

ChunkedUploadProvider<DriveItem> chunkedUploadProvider =
    new ChunkedUploadProvider<DriveItem>
        (uploadSession, graphClient, fileStream, streamSize, DriveItem.class);

// Do the upload
chunkedUploadProvider.upload(callback, customConfig);
```

**Comment by baywet** [comment]
Hey @niczon 
Thanks for the feedback. I was working on that as you were posting the issue and had already created #489
I'm going to close this one as duplicate.
