### ISSUE TITLE
Using skipToken in calendarView delta return empty list data

### ISSUE THREAD

**Issue by Vinctor** [microsoftgraph/msgraph-sdk-java#493]
In our application , i want to get the calendarView delta data from server,

```
IEventDeltaCollectionPage eventsPage = EventApi.getEventsDeltaInCalendar(identifier, serverCalendarId, options);
IEventDeltaCollectionRequestBuilder nextPage = eventsPage.getNextPage();
..../handler data
while (nextPage != null) {
    eventsPage = EventApi.getEventsDeltaInCalendar(nextPage,headerOption);
    nextPage = eventsPage.getNextPage();
}
String deltaLink = eventsPage.deltaLink();
```

In the first few cycles, the server returns the correct data
but later in the cycles ,the server returns the empty list, but not has the delta link

```
{
	"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(event)",
	"@odata.nextLink": "https://graph.microsoft.com/v1.0/me/calendars/{id}/calendarView/microsoft.graph.delta?$skiptoken=-e6j9ta3.......................",
	"value": []
}
```
This situation will be repeated many times until the correct result with deltaLink is returned.

I think it is unnecessary for the server to return empty data

**Comment by baywet** [comment]
Hi @Vinctor,
Thanks for reaching out. This is [a normal behavior expected by the service](https://stackoverflow.com/questions/55519289/microsoft-graph-api-calendarview-delta-query-sometimes-returns-nextlink-even-tho)
There's not much we can do in the SDK itself to mitigate that behavior.
As this repo is about the SDK, and not the service itself, I'm going to go ahead and close this issue.
You can either request that the service changes it's behavior on [uservoice](https://microsoftgraph.uservoice.com) or [contact support](https://developer.microsoft.com/en-us/graph/support) if you feel that this behavior is going on for too long.
