### ISSUE TITLE
The provided item ID is not valid for the requested drive

### ISSUE THREAD

**Issue by juanmarques** [microsoftgraph/msgraph-sdk-java#504]
Hello I'm trying use the graph to download from sharepoint , it works fine when I'm download from the "root" but it doesn't when comes to a specific site as following.

This my method call:

```
	public InputStream getFileByDriveId(String itemDriveId, String siteId) {
		return this.graphClient.sites(siteId).drive().items(itemDriveId).content().buildRequest().get();
	}
```

Error message in debug mode.
```
SEVERE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: invalidRequest
Error message: The provided item ID is not valid for the requested drive

GET https://graph.microsoft.com/v1.0/sites/8eb0793b-bd2c-4c55-9f89-c50344d812a6/drive/items/01T7RBXWROWXQHH3ZQYBC2LEHD66NW2NYM/content
SdkVersion : graph-java/v2.2.0
Authorization : [PII_REDACTED]


400 : Bad Request
Cache-Control : private
client-request-id : 9a7aa480-c144-4a8e-96d4-0a5ebba560e5
Content-Length : 325
Content-Type : application/json
Date : Sat, 26 Sep 2020 15:40:00 GMT
request-id : e653ab89-b3e1-448c-ae38-79394231a7f7
Strict-Transport-Security : max-age=31536000
x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"North Europe","Slice":"SliceC","Ring":"4","ScaleUnit":"004","RoleInstance":"AGSFE_IN_14"}}
{
  "error": {
    "code": "invalidRequest",
    "message": "The provided item ID is not valid for the requested drive",
    "innerError": {
      "date": "2020-09-26T15:40:01",
      "request-id": "e653ab89-b3e1-448c-ae38-79394231a7f7",
      "client-request-id": "9a7aa480-c144-4a8e-96d4-0a5ebba560e5"
    }
  }
}
```

**Comment by juanmarques** [comment]
Hello I have it working now..
By using the following request:

		List<Drive> driveCollection = this.graphClient.sites(siteId).drives().buildRequest().get().getCurrentPage();
		
		return this.graphClient.drives(driveCollection.stream().findFirst().get().id).items(itemDriveId).content().buildRequest().get()`

Is that the right way or I should use the request that I sent before?

**Comment by baywet** [comment]
Hey @juanmarques 
Thanks for reaching out and for your patience.
You should be able to write this if you have the drive id. Or maybe you want to get the information from the default drive without the id?
```Java
	return this.graphClient.sites(siteId).drives(driveId).items(itemDriveId).content().buildRequest().get();
```

**Comment by juanmarques** [comment]
I would like to get the information from the default drive without the id.

Thank you @baywet for the attention.

**Comment by baywet** [comment]
Are you sure the item id you have belongs to the "documents" document library? For SharePoint sites the default drive it the Documents library.
Also I noticed your site ID was a bit peculiar. It should look like this `yourtenant.sharepoint.com,sitecollectionguid,webguid`

**Comment by baywet** [comment]
I've just ran a unit test locally and I can confirm that the following works

```Java
final InputStream content = graphClient.sites("baywet.sharepoint.com,feb5ca4c-5076-4547-b7a6-ba449bb5b732,e7e9fdf9-21e0-4d0c-9680-d4ec71dac07c")
							.drive()
							.items("01Q6JGVZSYKU7B5FDTPBHIEKGVNYY6ISLF")
							.content()
							.buildRequest()
							.get();
```

**Comment by juanmarques** [comment]
aah ok..I have been using the site ID without the yourtenant.sharepoint.com and webguid...
Thanks a lot for your help!

**Comment by baywet** [comment]
no worries, happy coding. Closing.
