### ISSUE TITLE
Error "Access to OData is disabled" while creating calendar subscription for Amex

### ISSUE THREAD

**Issue by mjiniaslack** [microsoftgraph/msgraph-sdk-java#510]
Hey there,
I'm one of the developers of Slack's Outlook calendar integration built with the Graph API. Amex is running into the following error when we try to register a webhook for their calendars. All other calendar operations such as delta queries, listing calendars, creating events, etc work fine. We do have the necessary oauth scopes that include "Calendars.Read", "Calendars.Read.Shared", "Calendars.ReadWrite", "Calendars.ReadWrite.Shared", "User.Read", "offline_access".

The clientId of Slack's app is "74c10fbb-017f-4f00-ba68-9d3804d8ad09" registered under the account "platform-integrations@slack.com" in Azure portal.

Please help resolve this issue.

Here is a sample error message -
```
Error code: ExtensionError
Error message: Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]

POST https://graph.microsoft.com/v1.0/subscriptions
Accept: */*
Prefer: IdType=ImmutableId
SdkVersion: graph-java/v1.6.0
SdkVersion: graph-java/v1.6.0
Authorization: [REDACTED]


403 : Forbidden
Cache-Control: private
Content-Type: application/json
request-id: 25f33f36-cd6f-41bc-af91-87fe9fdadead
client-request-id: 25f33f36-cd6f-41bc-af91-87fe9fdadead
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"SliceC","Ring":"5","ScaleUnit":"000","RoleInstance":"AGSFE_IN_73"}}
Strict-Transport-Security: max-age=31536000
Date: Mon, 21 Sep 2020 16:30:10 GMT
Content-Length: 360
{
  "error": {
    "code": "ExtensionError",
    "message": "Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]",
    "innerError": {
      "date": "2020-09-21T16:30:11",
      "request-id": "25f33f36-cd6f-41bc-af91-87fe9fdadead",
      "client-request-id": "25f33f36-cd6f-41bc-af91-87fe9fdadead"
    }
  }
}
```

**Comment by baywet** [comment]
That's most likely caused by the fact you're missing an application policy to allow the Microsoft Graph Java SDK.
https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access
You are going to need to:
1. implement an interceptor in order to set a user-agent request header.
2. provide this user agent string so the admin can allow list it.
3. inject that interceptor in the ok http client. (this is something we're still fixing, see #501)

https://stackoverflow.com/questions/26509107/how-to-specify-a-default-user-agent-for-okhttp-2-x-requests

**Comment by mjiniaslack** [comment]
We are not using application permissions rather using delegated permissions.

**Comment by baywet** [comment]
This apply to applications accessing as app only and as user-delegated. The link I meant to share to configure Exchange is the following one.
https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-control-access-to-ews-in-exchange

**Comment by mjiniaslack** [comment]
So you are saying that in the current state (where we do not have a user agent) the error is because Amex has likely setup the `EwsApplicationAccessPolicy`policy to either block everything or allow a specific list of apps?

**Comment by baywet** [comment]
exactly.

**Comment by rduffysl** [comment]
Hi there,

We received the following from Amex, that their Access Policy setup seems to be correct:

> We are not using Application Access Policy in Exchange for the Slack OCal app. So Microsoft's first comment is not valid. Plus those policies only scope Application Permissions, not Delegated Permissions, which is what OCal uses.

>We are not using EWSAllowLists. Here's our current org level settings. The only configuration is to block older versions of Microsoft Communicator via EWSBlockList. All other applications are permitted. This is a default config from Microsoft (we didn't set it):

`Get-OrganizationConfig` | FL *ews*

EwsAllowEntourage :
EwsAllowList :
EwsAllowMacOutlook :
EwsAllowOutlook :
EwsApplicationAccessPolicy : EnforceBlockList
EwsBlockList : {*OC/4.0.7577.314*, *OC/4.0.7577.2*, *OC/4.0.7577.1*, *OC/4.0.7577.0*}
EwsEnabled : True`

> We don't apply or set any individual CAS mailbox level EWS Allow List restrictions either. Only the org-level settings are configured as per above.

**Comment by baywet** [comment]
@rduffysl @mjiniaslack thanks for the additional information.
Out of curiosity, have you tried with version 2.3.1 of the SDK?
If changing the version of the SDK doesn't improve the situation, please have the customer open a [support ticket](https://developer.microsoft.com/en-us/graph/support), as a SDK developer, I don't have access to service information for customers.

**Comment by mjiniaslack** [comment]
We are currently on version 1.6.0. Does this make a difference for the error in question?

**Comment by baywet** [comment]
I can't tell for sure as I only started working on the SDK 2 months ago (since version 2.0.0). But versions 2.0.0 to 2.3.0 fix 90+ bugs, so it'd be beneficial regardless.
