### ISSUE TITLE
Can't send email with attachment, java, graph, outlook api

### ISSUE THREAD

**Issue by Przemek-12** [microsoftgraph/msgraph-sdk-java#515]
Hi, I can't send mail message with attachment. I use exact same code as in unit tests: https://github.com/microsoftgraph/msgraph-sdk-java/pull/202/files#diff-ca39247b233dfb60518f697e16243541R124.
I get NoSuchMethodException at CollectionPageSerializer class, line 84.
java.lang.NoSuchMethodError: 'com.google.gson.JsonElement com.google.gson.JsonParser.parseString(java.lang.String)'.
In JsonParser class, there's no parseString method. There's only parse(String json).

**Comment by baywet** [comment]
Hi @Przemek-12 
Thanks for reaching out.
What version of Gson do you have in your project? (you can find out this information by typing `gradlew dependencies` at the root of your project)

**Comment by Przemek-12** [comment]
Thanks!
I'm using spring boot with maven nad my default version of gson was 2.8.5. I updated it to 2.8.6 and it works now.
Thank you for help.

**Comment by baywet** [comment]
no worries, happy coding. Closing.
