### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by RegisStGelais** [microsoftgraph/msgraph-sdk-java#525]
My question is MSGraph related but not about msgraph-sdk-java itself.

I am able to upload files (with an upload session) using msgraph-sdk-java to both personal and business OneDrive accounts.

But with my iOS app it works on a personal account but not on a business account.

I don't use a library on iOS.
My createUploadSession request returns with an "invalid request" error.

My request looks like this:
`https://graph.microsoft.com/v1.0/me/drive/root:/myfolder/myfilename:/createUploadSession`
with this header:
` headers["Content-Type"] = "application/json"`
and this json body:
`{\"item\":{\"@odata.type\":\"microsoft.graph.driveItemUploadableProperties\",\"@microsoft.graph.conflictBehavior\":\"replace\",\"fileSize\":\(fileSize!)},\"deferCommit\":false}"`

Any pointers would be greatly appreciated.

**Comment by baywet** [comment]
Hey @RegisStGelais 
Thanks for reaching out. I'm going to close this issue as we want to keep the focus of on java sdk specific conversations/issues.

Can I suggest you checkout the objective-c sdk for Microsoft Graph and see if you can start using it in your app?
https://github.com/microsoftgraph/msgraph-sdk-objc

Otherwise you can always ask questions like there on https://stackoverflow.com with the microsoft-graph tag (and ios in that case).
Closing

**Comment by RegisStGelais** [comment]
Tks @baywet.

I looked at that lib when I started my iOS project but it is not actively maintained (almost 2 years) and if I recall correctly, it is not compatible with the MSAL library.
I asked about the activity of the development and got that answer:
[https://github.com/microsoftgraph/msgraph-sdk-objc/issues/44]

I was just wondering if you could point me to where in your library the createuploadsession request is builded so I could have a look at the code and see if you do anything special in the case of a business account.
 
Regards,

**Comment by baywet** [comment]
Here is a sample on how you can use it in the java sdk. https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/test/java/com/microsoft/graph/functional/OneDriveTests.java#L92
Navigating the code you should be able to understand how it works.

**Comment by RegisStGelais** [comment]
this test unit is for downloads.
do you have one for upload sessions ?

**Comment by RegisStGelais** [comment]
Never mind, I found the upload test unit

**Comment by RegisStGelais** [comment]
@baywet,
I traced the execution of of the library up to the point where it posts createUploadSession and found out that the library uses this request url:
`https://graph.microsoft.com/v1.0/me/drive/root:/UmtPlus%2FChange%20Flat%20Tire.sco:/microsoft.graph.createUploadSession`
with that json body:
`{"item":{}}`

I modified my swift code to build the request the same way and it works.

Looks like when connected to a business account, the API does not like it when we add items in the json body. Or at least one of the items I was adding.

The funny thing is that the default value for @microsoft.graph.conflictBehavior is "fail". and I am able to overwrite a file even if I don't add the @microsoft.graph.conflictBehavior: replace item.

**Comment by RegisStGelais** [comment]
I tried all the items one by one and figured out that the business account does not like the filesize item nor the defetCommit.
I'm able to add the conflictBehaviour and it pass.

**Comment by baywet** [comment]
If there's anything that needs fixing in the objective c SDK and if you don't mind, can you open an issue over there please and even a pull request?

**Comment by RegisStGelais** [comment]
as I said. I don't use the objc lib. It may not have the issue. I don't know.
I directly build and call the rest APIs in Swift.
Thanks for taking the time to help me.
It is much appreciated.
