### ISSUE TITLE
Error `UnknownError` while fetching calendar events for several users

### ISSUE THREAD

**Issue by pbafna-slack** [microsoftgraph/msgraph-sdk-java#540]
Hey there,
I'm one of the developers of Slack's Outlook calendar integration built with the Graph API. Several users of this integration are running into the following error when we try to sync calendar events for user and also while deleting webhook for their calendars. 
We do have the necessary oauth scopes that include "Calendars.Read", "Calendars.Read.Shared", "Calendars.ReadWrite", "Calendars.ReadWrite.Shared", "User.Read", "offline_access".

The clientId of Slack's app is "74c10fbb-017f-4f00-ba68-9d3804d8ad09" registered under the account "platform-integrations@slack.com" in Azure portal.

Please help resolve this issue.

Here is a sample error message -
```slack.microsoft.OkHttpProvider$GraphFatalServiceException: Unexpected exception returned from the service.Error code: UnknownError
Error message: 

GET https://graph.microsoft.com/v1.0/users/<email>/calendars/<calendar-id>/calendarView/microsoft.graph.delta?$deltatoken=R0u...Vh4
Accept: */*
Prefer: IdType=ImmutableId
Prefer: odata.maxpagesize=250
SdkVersion: graph-java/v1.6.0
Authorization: [REDACTED]


503 : Service Unavailable
Cache-Control: private
Content-Type: application/json
request-id: bd2e6f90-1677-4dd8-a705-a4eb14fb1102
client-request-id: bd2e6f90-1677-4dd8-a705-a4eb14fb1102
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"SliceC","Ring":"5","ScaleUnit":"000","RoleInstance":"AGSFE_IN_38"}}
Preference-Applied: odata.track-changes
Strict-Transport-Security: max-age=31536000
Date: Wed, 14 Oct 2020 06:43:52 GMT
Content-Length: 266
{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "date": "2020-10-14T06:43:53",
      "request-id": "bd2e6f90-1677-4dd8-a705-a4eb14fb1102",
      "client-request-id": "bd2e6f90-1677-4dd8-a705-a4eb14fb1102"
    }
  }
}

**Comment by baywet** [comment]
Hi @pbafna-slack 
Thanks for reaching out. This repository is dedicated to issues with the SDK itself, not the service.
For the customers experiencing the issue, please open a [support ticket](https://developer.microsoft.com/en-us/graph/support) under their tenant to get this investigated and resolved.
Closing.
