### ISSUE TITLE
Make the JAR an OSGI Bundle

### ISSUE THREAD

**Issue by paul-mcculloch** [microsoftgraph/msgraph-sdk-java#544]
To use the SDK in an OSGi environment the JAR's MANIFEST.MF should include appropriate information about its dependencies etc.

https://github.com/AzureAD/microsoft-authentication-library-for-java, for example, is packaged as an OSGi bundle, via the maven bnd-maven-plugin & the associated bnd.bnd file. 
[AB#7124](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7124)

**Comment by baywet** [comment]
@paul-mcculloch thanks for the suggestion.
@darrelmiller can you review this one and let us know whether we should support yet another packaging?
FYI we already support JIGSAW see #297
I'm not sure what the impact of this format would be for android devs.
[Some reading](https://www.infoworld.com/article/3543072/what-is-osgi-java-modularity-with-the-open-service-gateway-initiative.html)

**Comment by maisarissi** [comment]
Hi @paul-mcculloch, thanks for your feedback, we truly appreciate that.
As we haven't received demand for adding this packaging and have had no interactions from other community members since you open this issue, we won't be adding another packaging for now.
