### ISSUE TITLE
Clearly define and document minimum support API level

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-java#546]
related #542
related #286 
related #530

There's a number of instances where we are using runtime APIs that are not available in Android, or only available for specific API levels and up. Saying "this library requires java X" is not enough as not all java 8 APIs are available on android to this day and desugaring won't bring those APIs to a specific API level.
During this evaluation we should consider downstream libraries, market shares of different android versions, and code of "writing legacy code/workarounds".
Once an API level is selected, we need to hunt for any transgression and set tooling to check for use of APIs unavailable for a specific API level. (static analysis)
This should be possible via the android configuration in build.gradle which should warn about any [transgression once configured](https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd).
 
[AB#6385](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6385)

**Comment by atulgpt** [comment]
Hi @baywet thanks for considering documenting api requirement for android clients. Also what will be the minimum Api level supported here? Will the library support api version 21 as making anything above 21 will break a lot of already clients using this lib including us.

**Comment by baywet** [comment]
@atulgpt do you have metrics in terms of downloads of your apps per Android version you could share with us? (privately, not here) That'd give us a good idea of actual market distribution.

**Comment by atulgpt** [comment]
Hi @baywet can you share your email id so to contact you and this info can be provided?

**Comment by baywet** [comment]
vibiret@microsoft.com

**Comment by atulgpt** [comment]
Hi, @baywet sorry for the delay...I am still in process of finding out how to share that info with you and awaiting a response from our internal team. Once I get the info I will update you regarding the same

**Comment by baywet** [comment]
no worries, thanks for the follow up. We'd only need the aggregated data of course and if possible some breakdown per metric (like per countries for instance).

**Comment by atulgpt** [comment]
Hi @baywet I have send the mail regarding the info. I have shared the last month MAU percentage on the these OSs(Android 0S 5,6 and 7). I know it took a while for the approval but I am hoping that it is still not too late.

**Comment by baywet** [comment]
while we're still working to get other numbers from internal applications. I started looking into it to see what API do we actually depend on at this time.
Here is some early information from my research. To get the validation of the API level working, we need to use the android-library instead of the java-library plugin.
We could do this either of two ways:
- setup a more complex project structure with multiple build.gradle files, one for android and one for java lib. Although it complexifies the project structure, this is probably the safest and it'll keep current publishing configurations in place without risking to lose JIGSAW or other configurations
- revamp the current build.gradle and move the configurations in the android node, like [msal](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/build.gradle). See [msal content](https://repo1.maven.org/maven2/com/microsoft/identity/client/msal/2.0.3/) vs [ours](https://repo1.maven.org/maven2/com/microsoft/graph/microsoft-graph/2.3.2/). This might require rework as some of the options might be different. Also the android library plugin publishes aar instead of jar, which all IDEs/platforms might not be compatible with. We might have to add configuration to enable [both jar and aar](https://stackoverflow.com/questions/26874498/publish-an-android-library-to-maven-with-aar-and-source-jar). Although this is a riskier approach, it also has the benefit of enabling us to publish a [proguard rule file](https://developer.android.com/studio/projects/android-library).

Another interesting note is that azure-identity has two libraries https://github.com/Azure/azure-sdk-for-android and https://github.com/Azure/azure-sdk-for-java. (API level 21). For consistency we might have to either use [variants](https://docs.gradle.org/current/userguide/variant_model.html) or split into two build.gradle and run two publishing sequences to get two libraries under different names, or fork the library (would require a lot of additional maintenance)

**Comment by baywet** [comment]
update: I've had success with the "setup an additional build.gradle for android" approach so far. We don't have a lot of API level infringements (see the attached report) over API level 21. (the definitive level is still TBD)
I've started #558 for people to follow the progress along.

[reports.zip](https://github.com/microsoftgraph/msgraph-sdk-java/files/5533243/reports.zip)

**Comment by baywet** [comment]
update: the work is pretty much complete at this point. There are still discussions that need to happen regarding the definitive API level.

**Comment by baywet** [comment]
update: the lowest level we'll be able to support is API level 21/android 5 because we have dependencies that require API level 21 as well. As the work is mostly implemented at this point I'm going to go ahead and close this issue. This work will be released with version 3 of the library.
