### ISSUE TITLE
Cloud Communications - Calling a Teams User from Android

### ISSUE THREAD

**Issue by sjdean** [microsoftgraph/msgraph-sdk-java#550]
As per title, Im trying to use the Graph API to establish an Audio call to a Teams user.

The documentation seems a little lacklustre, but I've pieced everything together as well as I can.

Using ClientCredentialProvider with a registered Azure AD App, appropriate permissions applied. I'm able to collect a list of users (though the recommended way to get a specific user seems to return no matches - requestOptions.add(new QueryOption("$filter", "identities/any(c:c/issuerAssignedId eq 'j.smith@yahoo.com' and c/issuer eq 'contoso.onmicrosoft.com')"));

I don't know what the callbackUri should be in all honesty, whether this needs to be an actual call back url or myapp://something.something as suggested elsewhere.

But we're able to create all the appropriate required variables, define our call, but when we post a call, we get back error code 9999 Unkown internal Server error.

If we dig deeper into where the post is made, we just get back error 500, Internal Server Error, with very little indication of what the error actually is.

Documentation elsewhere, such as the GroupCallBot https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/StatelessSamples/GroupCallBot suggests we need to setup a Bot? Done this, and still no joy.,

So we may well say first there's an issue with the documentation - Do we need to setup a bot or not? Can we make this a little clearer?
The $filter does not seem to work as above.
The misspelling on "Unkown"
Is calling Teams user through the Graph API actually supported?

And of course finally, how can I tell what we're doing wrong????

**Comment by baywet** [comment]
Hi @sjdean 
Thanks for reaching out.
The focus of issues in this repository is to discuss and address any potential issue/enhancement with the Microsoft Graph Java SDK itself.
The best way for you to get answers to questions like "how do I do X?" is to ask such questions on https://stackoverflow.com with the relevant tags (you should probably break this post down into more specific questions) or on the Microsoft Q&A Microsoft Graph forum (with the microsoft-graph-cloud-communications tag in your case) https://docs.microsoft.com/en-us/answers/questions/topics/single/128334.html

Closing.
