### ISSUE TITLE
delta does't work in AzureChina

### ISSUE THREAD

**Issue by Vinctor** [microsoftgraph/msgraph-sdk-java#552]
in my application, i try to login account with Azure China 21Vianet.
First, i login success with MSAL,
then i try to load data from server with
```
https://microsoftgraph.chinacloudapi.cn/v1.0/me/mailFolders/microsoft.graph.delta
```
later,i get  `400:Bad Request`  error, and the message
```
{
      "error": {
        "code": "ErrorInvalidIdMalformed",
        "message": "Id is malformed.",
        "innerError": {
          "date": "2020-10-28T11:18:25",
          "request-id": "9a6b40af-c64d-4409-b680-6beb6a85d41d",
          "client-request-id": "a9e73033-5341-46f0-a9ce-4fbdc1a8fd3e"
        }
      }
    }
```
Doesn't the AzureChina server support the `mailFolders Delta`?
Or has another  way to make it work?

**Comment by baywet** [comment]
Hi @Vinctor 
Thanks for reaching out. It is possible that this specific delta capability is not available yet in China 21Vianet.
This repository focuses on issues and improvement with the Microsoft Graph Java SDK, as there's nothing we can do in the SDK itself I'm going to go ahead and close this issue.
You could instead either open an issue on the documentation for [national clouds](https://docs.microsoft.com/en-us/graph/deployments) or for [mailfolders delta v1](https://docs.microsoft.com/en-us/graph/api/mailfolder-delta?view=graph-rest-1.0&tabs=http) stating that the fact this capability is not available in this national cloud is not documented. (to do so, scrool all the way at the bottom and click on "this page" under "feedback")
Alternatively you could ask the question in the [Microsoft-graph-mail](https://docs.microsoft.com/en-us/answers/questions/topics/single/128342.html) sub-forum on Microsoft Q&A
