### ISSUE TITLE
Persistent GraphFatalServiceException when trying to sync calendar

### ISSUE THREAD

**Issue by mjiniaslack** [microsoftgraph/msgraph-sdk-java#555]
Hey there,
I'm one of the developers of Slack's Outlook calendar integration built with the Graph API. A user is running into the following error when we try to sync their calendars. We do have the necessary oauth scopes that include "Calendars.Read", "Calendars.Read.Shared", "Calendars.ReadWrite", "Calendars.ReadWrite.Shared", "User.Read", "offline_access". And retries dont help. This seems to be a persistent error with just this account.

The clientId of Slack's app is "74c10fbb-017f-4f00-ba68-9d3804d8ad09" registered under the account "platform-integrations@slack.com" in Azure portal.

Please help resolve this issue.

Here is a sample error message -
```
com.microsoft.graph.http.GraphFatalServiceException: Unexpected exception returned from the service.Error code: UnknownError
Error message: 
GET https://graph.microsoft.com/v1.0/users/rodin.vongeorgi@bonial.com/calendars/AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0A7rMw7fyb7UKMpLoVKa598gAAABfdFwAA/calendarView/microsoft.graph.delta?$skiptoken=R0usmcdvmMuZCBYV0hguCCrW5LnNbubVpKEEE_287BGRvgO7W_ZKxHlBoxU4HC_rsE3uZfZ9Vc5Ytyu5xISIfnXTNf1MeBGmtJidsqGzZ0FITTqV47-kVuVDKtYw5_dgU9VbYEmL8fq1H9Z7pHQT1SVLpfTnUsDqz7Yz3fjg8RlCIMBqsa54ooyVIwYpIsKZKiNIxZg9XMYXDaMlk_gE0w.RsC4j2ScANboI5zHFj0aNVEB4KqpaNUgwlKypf0rbw0
Prefer : IdType=ImmutableId
Prefer : odata.maxpagesize=250
SdkVersion : graph-java/v2.3.2
Authorization : [PII_REDACTED]
503 : Service Unavailable

**Comment by baywet** [comment]
Hi @mjiniaslack 
This repository is dedicated to addressing issues with the SDK itself.
As you rightfully identified that the call is working for most users and as you're getting a 503 and not a 4XX error code, this is most likely an issue with the service itself.
Please reach out to our [support](https://developer.microsoft.com/en-us/graph/support) to get this sorted out (see the report issues with the service section).
Closing.
