### ISSUE TITLE
NoSuchElementException when there is no content in the response in case of an error

### ISSUE THREAD

**Issue by ashwanikumar04** [microsoftgraph/msgraph-sdk-java#565]
### Expected behavior
The library should not throw an exception even in the case when there is no body in case of an error.

### Actual behavior
The library is throwing an exception when there is no content in the response in case of error. 
```
Caused by: java.util.NoSuchElementException
ERROR|1119-172601634|pool-6-thread-5286	at java.base/java.util.Scanner.throwFor(Scanner.java:937)
ERROR|1119-172601634|pool-6-thread-5286	at java.base/java.util.Scanner.next(Scanner.java:1478)
ERROR|1119-172601634|pool-6-thread-5286	at com.microsoft.graph.http.DefaultHttpProvider.streamToString(DefaultHttpProvider.java:473)
ERROR|1119-172601634|pool-6-thread-5286	at com.microsoft.graph.http.GraphServiceException.createFromConnection(GraphServiceException.java:424)
ERROR|1119-172601634|pool-6-thread-5286	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:487)
ERROR|1119-172601634|pool-6-thread-5286	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:376)
```

### Steps to reproduce the behavior

Steps wise not sure how to reproduce it as we are seeing this error when calling a graph endpoint.

Looks like we are not checking the [iterator](https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/http/DefaultHttpProvider.java#L470)  before accessing `next`.

```
 public static String streamToString(final InputStream input) {
        final String httpStreamEncoding = "UTF-8";
        final String endOfFile = "\\A";
        final Scanner scanner = new Scanner(input, httpStreamEncoding);
        String scannerString = "";
        try {
        	scanner.useDelimiter(endOfFile);
            scannerString = scanner.next();
        } finally {
        	scanner.close();
        }
        return scannerString;
    }
```
I think we should have 
```
if(scanner.hasNext()){
 scannerString = scanner.next();
}
```

If it is ok, I can raise the MR with the fix.

Thanks

**Comment by baywet** [comment]
Hey @ashwanikumar04 ,
Thanks for reporting the issue!
You're right, this is probably a lack of defensive programming in this method.
Adding the suggestion you made will help of course.
The stacktrace points at [this line](https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/http/DefaultHttpProvider.java#L473), so on top of your suggested fix, I think we should add a check for InputStream being null.
If you think you can make the change, we'd be honoured to review your pull request.

**Comment by ashwanikumar04** [comment]
@baywet `Scanner` has requireNull for the stream. My stack trace  is for an older release
<img width="597" alt="Screenshot 2020-11-20 at 14 07 00" src="https://user-images.githubusercontent.com/3656437/99809080-b4b7b280-2b39-11eb-8dcc-daa70facde0c.png">

Thanks will try to raise the MR.

**Comment by ashwanikumar04** [comment]
Hello, @baywet I have the change ready in my local branch. However, I am not sure how to raise the PR for this as I am not in the contributors. What is the process to raise the PR in this case?

**Comment by baywet** [comment]
1. fork the repository under your username (little button top right corner)
1. add the fork as a remote to your local repo (`git remote add https://github.com/ashwanikumar04/msgraph-sdk-java downstream`)
1. push the branch (git push downstream)
1. open the pull request from [here](https://github.com/microsoftgraph/msgraph-sdk-java/pulls) (you should have a yellow message saying branch X was committed not long ago, create a pull request)

**Comment by ashwanikumar04** [comment]
@baywet Thanks a lot for the steps.
I have raised the PR/MR https://github.com/microsoftgraph/msgraph-sdk-java/pull/566.

Thanks

**Comment by KostasThan** [comment]
Hello, i was just reading throught, and i think that it might look a little cleaner if you used the[ try with resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) syntax.

**Comment by baywet** [comment]
Hi @KostasThan
Thanks for the suggestion.
If I'm not mistaking, PR #566 submitted by @ashwanikumar04 already contains that change.
Did I miss anything?

**Comment by KostasThan** [comment]
Hi again @baywet , 
I do not know how to check this
> If I'm not mistaking, PR #566 submitted by @ashwanikumar04 already contains that change.
 
and if you say so then it must be the case. I was just browsing  the comments, and based my comment on the photo above. It is actually my third day using github. 
I am sorry you had to read this. :sweat_smile:

**Comment by baywet** [comment]
welcome on github!
click on the pull request id and then on the "changed files" tab on top.

**Comment by KostasThan** [comment]
I see. Thank you!
As for:
>i think that it might look a little cleaner if you used the try with resources syntax

It is already there.
