### ISSUE TITLE
Getting NULL on deserializing the metrics in Call Record of type "Duration" 

### ISSUE THREAD

**Issue by ponrajit** [microsoftgraph/msgraph-sdk-java#568]
### Expected behavior
Should get the values for the metrics like AverageRoundTripDelay, AverageJitter, and Max Jitter which are of type "Duration".

### Actual behavior
Metrics like AverageRoundTripDelay, AverageJitter, MaxJitter which are of type "Duration" are always deserialized as NULL instead of the value reported in the call record. In GsonFactory.java at line:208, it should be "getAsString()" and not "toString()". 
This is preventing from getting the values.

**Comment by baywet** [comment]
Hey @ponrajit ,
Thanks for reaching out, do you mind sharing a code sample to reproduce the issue as well as a JSON payload you are getting please?
Thanks

**Comment by ponrajit** [comment]
Hi @baywet 

The "streams" JSON data received
"streams": [                             
                                {
                                    "streamId": "2101",
                                    "startDateTime": null,
                                    "endDateTime": null,
                                    "streamDirection": "calleeToCaller",
                                    "averageAudioDegradation": null,
                                    **"averageJitter": "PT0.004S",
                                    "maxJitter": "PT0.007S",**
                                    "averagePacketLossRate": 0,
                                    "maxPacketLossRate": 0,
                                    "averageRatioOfConcealedSamples": 0,
                                    "maxRatioOfConcealedSamples": null,
                                    **"averageRoundTripTime": "PT0.024S",**
                                    "maxRoundTripTime": "PT0.05S",
                                    "packetUtilization": 471,
                                    "averageBandwidthEstimate": 1174971,
                                    "wasMediaBypassed": null,
                                    "postForwardErrorCorrectionPacketLossRate": null,
                                    "averageVideoFrameLossPercentage": null,
                                    "averageReceivedFrameRate": null,
                                    "lowFrameRateRatio": null,
                                    "averageVideoPacketLossRate": null,
                                    "averageVideoFrameRate": null,
                                    "lowVideoProcessingCapabilityRatio": null,
                                    "averageAudioNetworkJitter": "PT0.014S",
                                    "maxAudioNetworkJitter": "PT0.022S"
                                }
                            ]

Code to get the metrics that are type 'Duration'
`// average jitter	
	        Long avgJitter = null;
		if (mediaStream.averageJitter != null) {
			avgJitter = mediaStream.averageJitter.getTimeInMillis(new Date());
		}`
It doesn't go inside the if block because it is always null.

Thanks

**Comment by baywet** [comment]
thanks for the additional information. I was able to reproduce and fix the issue.
I authored PR #569 which will close this issue when merged.
