### ISSUE TITLE
Create chatMessage in channel Application permission

### ISSUE THREAD

**Issue by jotbhags** [microsoftgraph/msgraph-sdk-java#579]
I see that in beta version of docs , the create message in channel "can" work using Application Teamwork.Migrate.All permission . Is this correct documentation to post a message in "Any" channel or is it supported only for "Migration" channels.

https://docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&tabs=http

We tried using this API using default scope and got 401 response code. Our application is setup in azure and has the admin consent for Teamwork.Migrate.All permission. FYI - We are able to create channels using graph API with the same app. We are using java SDK with client credential auth flow.

**Comment by baywet** [comment]
Hi @jotbhags 
This sounds like a service issue more than an issue with the SDK itself.
This repository is dedicated to tracking issues about the SDK.
I'm going to go ahead and close the issue.
Can you open an new one from the section "feedback", and then the button "this page" at the bottom of the page you linked? This will create the issue at the right place and route it to the product team.
Thanks!
