### ISSUE TITLE
ClientCredentialsProvider class usage issue

### ISSUE THREAD

**Issue by jeevanbalanmanoj** [microsoftgraph/msgraph-sdk-java#582]
Hi, I am an FTE at MS and I am trying to connect to ms graph with msal4j in a daemon app. The [samples](https://github.com/Azure-Samples/ms-identity-java-daemon) for client credential flow works with the HTTP client. However, when I try to use [ms graph SDK](https://github.com/Azure-Samples/ms-identity-java-daemon) I am running into a confusing situation about the ClientCredentialsProvider API. Here is the doc https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Java#ClientCredentialsProvider what is the expected value endpoint? In which package is this ClientCredentialsProvider class supposed to be in? ( Which imports are needed ) I am getting ClientCredentialProvider cannot be resolved to a type error.  What am I missing? Is it supposed to be a part of the sdk or msal4j itself?

**Comment by baywet** [comment]
Hey @jeevanbalanmanoj 
The class you are looking for is in [this package](https://github.com/microsoftgraph/msgraph-sdk-java-auth), [here](https://github.com/microsoftgraph/msgraph-sdk-java-auth/blob/dev/src/main/java/com/microsoft/graph/auth/confidentialClient/ClientCredentialProvider.java)

Let us know if you need anything else.

**Comment by baywet** [comment]
rest of the questions answered on teams, got to a working application and submitted the following PR to improve the getting started experience https://github.com/microsoftgraph/microsoft-graph-docs/pull/10909

**Comment by jeevanbalanmanoj** [comment]
Thanks for the super prompt resolution
