### ISSUE TITLE
HttpResponseCode.HTTP_NOBODY may cause NullPointerException when EventCollectionRequest.get()

### ISSUE THREAD

**Issue by ling595659851** [microsoftgraph/msgraph-sdk-java#595]
### Expected behavior
No Exception even though the Http response code is HttpResponseCode.HTTP_NOBODY(204)

### Actual behavior
java.lang.NullPointerException
	at java.util.Collections$UnmodifiableCollection.<init>(Collections.java:1028)
	at java.util.Collections$UnmodifiableList.<init>(Collections.java:1304)
	at java.util.Collections.unmodifiableList(Collections.java:1289)
	at com.microsoft.graph.http.BaseCollectionPage.<init>(BaseCollectionPage.java:71)
	at com.microsoft.graph.http.BaseCollectionPage.<init>(BaseCollectionPage.java:83)
	at com.microsoft.graph.requests.extensions.EventCollectionPage.<init>(EventCollectionPage.java:26)
	at com.microsoft.graph.requests.extensions.EventCollectionRequest.buildFromResponse(EventCollectionRequest.java:161)

### Steps to reproduce the behavior
I am adding an inteceptor to prevent too big reponse data, after I changed the response code to 204 in the http client inteceptor and use the EventCollectionRequest.get() method to get empty body, the SDK throws NPE.

![image](https://user-images.githubusercontent.com/11716573/101735779-5a3cc100-3afd-11eb-858e-7169cb201b60.png)
![image](https://user-images.githubusercontent.com/11716573/101735820-69237380-3afd-11eb-891b-ccf3a66e790e.png)
![image](https://user-images.githubusercontent.com/11716573/101736168-f070e700-3afd-11eb-8771-10e9cb90ceef.png)

**Comment by baywet** [comment]
Hi @ling595659851 
Thanks for reaching out.
Can you tell us which version of the SDK and core you are using ? If not on 2.5.0 and 1.0.5 can you try with those versions and see if you still have the issue please?
Can you also share the code you wrote to execute the request please? As well as the response payload if possible.
Thanks!

**Comment by ling595659851** [comment]
Hi @baywet 
I am using Graph Java SDK 2.3.2. after I changed to 2.5.0, still have the issue.
Inteceptor example is:
`.addInterceptor(chain -> {
                Response response = chain.proceed(chain.request());
                try {
                    if (response.isSuccessful() && response.networkResponse() != null) {
                        String bodyLengthStr = response.networkResponse().header("Content-Length");
                        if (StringUtils.isEmpty(bodyLengthStr) ) {
                            return response;
                        }
                        // convert byte to MB
                        int responseDataSize = Integer.parseInt(bodyLengthStr) / (1 << 20);
                        if (responseDataSize >= 1 && responseDataSize < 10) {
                            log.warn("too big for the request url [{}] with bodySize [{}] MB", chain.request().url(), responseDataSize);
                        } else if (responseDataSize >= 10) {
                            log.error("too big for the request url [{}] with bodySize [{}] MB", chain.request().url(), responseDataSize);
                            response = response.newBuilder()
                                    .code(HttpResponseCode.HTTP_NOBODY)
                                    .body(ResponseBody.create(MediaType.parse("text/plain; charset=utf-8"), "")).build();
                        }
                    }
                } catch (Exception e) {
                    log.error("unexpected error when do the content size analyse", e);
                }
                return response;
            })`

**Comment by baywet** [comment]
thanks for trying with the new version. What's the code for the request? i.e. : graphClient.Something().Something()...

**Comment by ling595659851** [comment]
`LinkedList<Option> requestOptions = new LinkedList<>();
requestOptions.add(new QueryOption("startDateTime", LocalDateTime.now().toString()));
requestOptions.add(new QueryOption("endDateTime", LocalDateTime.now().plusDays(7).toString()));
requestOptions.add(new QueryOption("$top", 300));
`
I used this method: graphClinet.me().calendar().calendarView().buildRequest(requestOptions).get();

**Comment by baywet** [comment]
Thanks for the additional information. I was able to identify and fix the issue. I authored PR #599 which will close this issue once merged.
