### ISSUE TITLE
Fetching email with large attachments caused OutOfMemoryError

### ISSUE THREAD

**Issue by thomas-gh** [microsoftgraph/msgraph-sdk-java#606]
When fetching an email with large attachments expanded, MessageRequest threw OutOfMemoryError.

The stack trace below indicated the root of the issue is 

>   final JsonObject[] sourceArray = serializer.deserializeObject(**json.get("attachments").toString()**, JsonObject[].class);

Converting a huge GSON object into a string can cause OutOfMemoryError.

Tested on version 1.9.0. The latest version 2.5.0 has the same code in this line.

<code>
 java.lang.OutOfMemoryError: Java heap space	at java.util.Arrays.copyOf(Arrays.java:3332)	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)	at java.lang.StringBuffer.append(StringBuffer.java:270)	at java.io.StringWriter.write(StringWriter.java:101)	at com.google.gson.stream.JsonWriter.string(JsonWriter.java:593)	at com.google.gson.stream.JsonWriter.value(JsonWriter.java:419)	at com.google.gson.internal.bind.TypeAdapters$29.write(TypeAdapters.java:746)	at com.google.gson.internal.bind.TypeAdapters$29.write(TypeAdapters.java:760)	at com.google.gson.internal.bind.TypeAdapters$29.write(TypeAdapters.java:698)	at com.google.gson.internal.Streams.write(Streams.java:72)	at com.google.gson.JsonElement.toString(JsonElement.java:325)	at com.microsoft.graph.models.extensions.Message.setRawObject(Message.java:361)	at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:95)	at com.microsoft.graph.http.CoreHttpProvider.handleJsonResponse(CoreHttpProvider.java:514)	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:396)	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:204)	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:184)	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:306)	at com.microsoft.graph.requests.extensions.MessageRequest.get(MessageRequest.java:67)	at 
</code> 
[AB#7128](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7128)

**Comment by baywet** [comment]
Hi @thomas-gh 
Thanks for reaching out.

Potentially related https://github.com/microsoftgraph/msgraph-sdk-serviceissues/issues/42

Out of curiosity, why are you deserializing to JsonObject[] and not Attachment[] ?
Thanks!

**Comment by thomas-gh** [comment]
> Hi @thomas-gh
> Thanks for reaching out.
> 
> Potentially related [microsoftgraph/msgraph-sdk-serviceissues#42](https://github.com/microsoftgraph/msgraph-sdk-serviceissues/issues/42)
> 
> Out of curiosity, why are you deserializing to JsonObject[] and not Attachment[] ?
> Thanks!

That line of code that deserializes to JsonObject[] is in `setRawObject` method of Message class in SDK.

`com.microsoft.graph.models.extensions.Message.setRawObject(Message.java:361)`

**Comment by thomas-gh** [comment]
Ideally, the attachments can deserialized directly from the <code>json</code> object. Currently, the memory footprint for a 50MB file attachment is 

1. json parameter - 50MB
2. `sourceArray = deserialize(json.get("attachments").toString())` - a 50MB string is returned from `toString` method, then the result `sourceArray` uses 50MB
3. `array = deserialize (sourceArray.toString())` - a 50MB string is returned from `toString` method, then the `result` array uses 50MB

**Comment by baywet** [comment]
Thanks for looking into this further. I haven't had time to look into this in details yet but it's on my todo.
From looking at the screenshot you provided, there are a number of odd things here.

1. Why does the SDK do serializer.deserializeObject(json.get("attachments").toString(), JsonObject[].class)` when it could do `json.get("attachments").getAsJsonArray()` ? That'd probably save 50MB to maybe 100MB right away.
2. Why does the SDK pass in a string parameter to the deserializeObject method when it already has a JsonElement? The underlying method is probably parsing it as a first thing. Another 50MB.

**Comment by baywet** [comment]
Update: I haven't forgotten this issue but my plate has been busy on other matters other the last few weeks.
I just submitted a PR to improve an issue related to this one which could positively improve the current issue, see https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/122

I still have to investigate the things I mentioned above, thanks a lot for the patience!

**Comment by baywet** [comment]
Also related https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/123

**Comment by baywet** [comment]
update, a number of improvements in the upcoming v3 should drastically improve the situation.
Once #625, https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/123 and https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/122 get merged, I'd love for you to try the preview of v3 (see #628 ) and compare memory usage.
