### ISSUE TITLE
"Graph service exception: ErrorAccessDenied" when trying to access events/calendar

### ISSUE THREAD

**Issue by MaksimR-AVISPL** [microsoftgraph/msgraph-sdk-java#616]
Greetings, 

Using CCProvider to authenticate as an application. All the features are working just fine for now, except for one thing: 
I'm getting the "Graph service exception: ErrorAccessDenied" every time I try to access calendar or events. 

Here's the code snippet that I use (pretty much the example from the documentation):

`        IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( ccProvider ).buildClient();

        LinkedList<Option> requestOptions = new LinkedList<Option>();
        requestOptions.add(new HeaderOption("Prefer", "outlook.timezone=\"Pacific Standard Time\""));

        IEventCollectionPage events = graphClient.me().events()
                .buildRequest( requestOptions )
                .select("subject,body,bodyPreview,organizer,attendees,start,end,location")
                .get();`
  
According to the documentation: 
https://docs.microsoft.com/en-us/graph/api/user-list-events?view=graph-rest-1.0&tabs=http
Seems like I only need _Calendars.Read_ and _Calendars.ReadWrite_ permissions, I've added them, admin consent is granted, but that didn't help to resolve the issue. 

Token contains these permissions: 
  "roles": [
    "Calls.JoinGroupCall.All",
    "OnlineMeetings.ReadWrite.All",
    "Calendars.Read",
    "Mail.ReadBasic.All",
    "Calls.InitiateGroupCall.All",
    "Calls.JoinGroupCallAsGuest.All",
    "Group.ReadWrite.All",
    "Directory.Read.All",
    "User.Read.All",
    "Calendars.ReadWrite",
    "Calls.AccessMedia.All",
    "Calls.Initiate.All"
  ],

Is there anything else I might need in order to make calendar/events resources work, or does it sound like an issue with the java-sdk? 

Thank you

 
[AB#7640](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7640)

**Comment by baywet** [comment]
Hi @MaksimR-AVISPL 
Thanks for reaching out.
The fact that permissions are listed as roles and not scopes leads me to think your application is authenticating using an app-only context. (this means only the application is represented in the token, no user)

/me (and everything under it) relies on finding a user identity in the token (delegated auth context) to understand who's the current user and find their data.

Depending on your scenario you can:
- Switch to a delegated context
- Change the code for graphClient.users("userEmailOrId").events()...

I hope this helps resolve your problem.
Let me know if you have further questions

**Comment by MaksimR-AVISPL** [comment]
Thank you, this works if I provide a specific user id/email. But this won't work for an application identity, right? 
I have tried providing app object/client id as an identifier and it didn't work, so I assume, if I want to stick to the app-only context - I need to have a specific user that the application will use to request specific resources for? 

Thanks!

**Comment by MaksimR-AVISPL** [comment]
Also just wanted to clarify if there's a way to extend the application permissions, so there's a specific user attached to the application, is it something that can be done? Looking at the token it seems like "idtyp" is a context, wonder if it's possible to extend it to "app,user", or is it single context only?

**Comment by baywet** [comment]
The application itself doesn't have a license/account for outlook, this is why it doesn't have a mailbox/calendar and using it's id in the "users" parameter won't work. But depending on permissions you give it, it will be able to access users' calendars/mailboxes as well as shared calendar/mailboxes.
So for a "service account" scenario, the app could either have it's own user provisioned or use a shared mailbox.

For delegated context you'll need to change your app registration to select the delegated type permissions and change the way the application authenticates so it uses a delegated context. [More reading on the auth scenarios](https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-flows-app-scenarios)

**Comment by MaksimR-AVISPL** [comment]
Ok so in order to access shared calendars/mailboxes - I still need to use delegated context, right? In the Azure app permissions there are .Shared permissions only available in a Delegated context. 

Would it matter if I use application and use a specific user id to access mailbox/calendar (with app-only context) vs. using delegated context, so an application would act on behalf of the same user in order to retrieve the same information? 
I believe these would be similar functionally, correct? 

Also - (I guess Im not getting something right) - In [this article](https://docs.microsoft.com/en-us/graph/api/user-list-calendars?view=graph-rest-1.0&tabs=java) it is shown that Application context is available for the operation, which made me think that calling 
`graphClient.me().calendars()` with an application context would retrieve all the calendars that are "visible" within the set of permissions, however, .Shared permissions are not available in an application context and are not required by this resource. But, as you have mentioned, application itself doesn't have a mailbox/calendar so I'm not sure which calendars are available within an application context in this case.

**Comment by baywet** [comment]
Sorry, I thought that group calendars were available with app only but [it doesn't seem to be the case](https://docs.microsoft.com/en-us/graph/api/calendar-get?view=graph-rest-1.0&tabs=http)

Again, I'm not sure what your scenario is, but unless you're building some kind of background agent to scan the data/automatically send invites (as an app, not as a user) or something that wouldn't "require a human", you should probably go with delegated permissions.

Functionality can vary when you are accessing the same endpoint with delegated or app-only context. This a very endpoint specific question.

To re-iterate: anything under `/me` (or `.me()` in java) is not going to work with application permissions, even though the documentation could lead you to think it might. You have to replace the `/me` part by `/users/userId` (`/users("userId")`) for the call to succeed with app-only context.

As the question is about authentication scenarios and permissions. I'm going to close this issue.
I suggest you either:
- Post using "this page" in the feedback section of [this page](https://docs.microsoft.com/en-us/graph/api/user-list-calendars?view=graph-rest-1.0&tabs=java) if your question is about "which scope/permission should I use for my scenario?"
- Post using "this page" in the feedback section of [this page](https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-flows-app-scenarios) if your question is about "which context should I use"
- Post on stackoverflow or Microsoft Q&A with the microsoft graph tag for any of the questions above.

You question will get triaged and assigned to specialists on the matter (auth or outlook) who can better answer the question.
