### ISSUE TITLE
Message size

### ISSUE THREAD

**Issue by ProRoman** [microsoftgraph/msgraph-sdk-java#619]
Could you add message size support to Message class.

Or using $expand=singleValueExtendedProperties($filter=Id eq 'LONG 0x0E08') is appropriate way to get message size?

Thanks! 
[AB#7712](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7712)

**Comment by baywet** [comment]
Hi @ProRoman 
Thanks for reaching out.
I don't think the API provides that information today.
This repository and the issues are strictly related to the SDK itself. For a property to show up in the SDK, it needs to be added in the API. You can request such improvement in the API by [creating an idea on uservoice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests)
Closing for now. Let me know if I misunderstood your request.

**Comment by ProRoman** [comment]
Thanks @baywet 

But problem now if I request extended properties I can not update read state later. I get

```
Caused by: com.microsoft.graph.http.GraphFatalServiceException: Unexpected exception returned from the service.Error code: ErrorItemSavePropertyError
Error message: Item save operation did not succeed.
```

**Comment by baywet** [comment]
Was it your application that created the extended property to begin with?

**Comment by ProRoman** [comment]
no, it is message size LONG 0x0E08

**Comment by baywet** [comment]
what happens if you assign null the the singleValueExtendedProperties before executing the update?
