### ISSUE TITLE
releases and tags

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#62]
I see release 0.1.0 went to [bintray](https://bintray.com/microsoftgraph/Maven/microsoft-graph/0.1.0#files/com%2Fmicrosoft%2Fgraph%2Fmicrosoft-graph%2F0.1.0). Catch is the codebase has not been tagged so we don't know what code to associate with that release.

Common pattern is to tag as `0.1.0` or `v0.1.0`. I prefer the first but don't care.

Can we ensure the git repo gets tagged with each release please? We should also update the [releases](https://github.com/microsoftgraph/msgraph-sdk-java/releases) info on the github site.

**Comment by cbales** [comment]
Yes, it is on the to-do list. We will follow [this format](https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases)
