### ISSUE TITLE
Getting GraphFatalServiceException while doing CopyItem for few oneDrive files with 504 Gateway timeout message

### ISSUE THREAD

**Issue by ssapa** [microsoftgraph/msgraph-sdk-java#627]
Expected behavior
On using IGraphServiceClient.drives("driveID").root().itemWithPath("Item_PATH").copy(targetItem, ParentReference).buildRequest().post(), we should get the DriveItem object in the result with the resposeCode 202.

Actual behavior : 
Few times, while doing multiple and many concurrent calls to copy different files, I got a streak of GraphFatalServiceException type exceptions intermittently. So when we get this, I am doing retry attempt. But the second request is giving Name already exists error message.

Exception Details -->
Throwable detail: com.microsoft.graph.http.GraphFatalServiceException: Unexpected exception returned from the service.Error code: UnknownError\nError message: \n\nPOST https://graph.microsoft.com/v1.0/drives/b!A5GL7aV13EOiocvwYtGLxMooxz3vr0JPqZA9_DpzUKTJ9HQROSuuRrmVDBpuHNw6/root:/performancetestFolder/NewCopyPerformance/NSPerformanceFolderCreateNS11:/microsoft.graph.copy\nSdkVersion : graph-java/v2.3.0\nAuthorization : [PII_REDACTED]\n{\"parentReference\":{\"path\":\"/drives/b!A5GL7aV13EOi[...]\n\n504 : Gateway Timeout\n[...]\n\n[Some information was truncated for brevity, enable debug logging for more details]\n\tat com.microsoft.graph.http.GraphServiceException.createFromConnection(GraphServiceException.java:490)\n\tat com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:503)\n\tat com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:423)\n\tat com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:220)\n\tat com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:200)\n\tat com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:345)\n\tat com.microsoft.graph.requests.extensions.DriveItemCopyRequest.post(DriveItemCopyRequest.java:45)\n\tat

Steps to reproduce the behavior
The issue seems to be random for me. Try to copy about 500 files one after the other and I am observing this issue randomly for 5-8 files.

Why or when do we see such errors. What is the appropriate way to handle these ? 
[AB#7816](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7816)

**Comment by ssapa** [comment]
@darrelmiller This is similar to https://github.com/microsoftgraph/msgraph-sdk-java/issues/207. Can you please check once.

**Comment by baywet** [comment]
Hi @ssapa 
Thanks for reaching out.
It sounds like the service is "getting hot" and not replying in time to your request while still performing the action in the background.
Do you have a few timestamps and request ids to share with us please? So we can check the logs we have access to.
Thanks!

**Comment by ssapa** [comment]
@baywet Here is the timestamp of above request : 2021-01-27T12:16:46.323Z. Not sure how to get the request ID.

**Comment by baywet** [comment]
it should be in the response headers as "request-id"

**Comment by ssapa** [comment]
Today I again faced this GraphFatalServiceException with UNKNOWNERROR. But this time it is for Delete Item. Here is the stack trace and request-ID details.

**Request-ID** : 876ae4c2-6828-44d0-96e5-fc675e755c2e

**Stacktrace with all responseheaders :** 

responseHeaders : [Cache-Control : no-cache, client-request-id : 51ad42d7-d8a7-476c-acbb-567486bd2311, Content-Type : application/json, Date : Wed, 03 Feb 2021 13:58:43 GMT, request-id : 876ae4c2-6828-44d0-96e5-fc675e755c2e, Strict-Transport-Security : max-age=31536000, Transfer-Encoding : chunked, Vary : Accept-Encoding, x-ms-ags-diagnostic : {\"ServerInfo\":{\"DataCenter\":\"South India\",\"Slice\":\"E\",\"Ring\":\"3\",\"ScaleUnit\":\"000\",\"RoleInstance\":\"MA1PEPF00001303\"}}]","exc":"com.microsoft.graph.http.GraphFatalServiceException: Unexpected exception returned from the service.Error code: UnknownError\nError message: \n\nDELETE https://graph.microsoft.com/v1.0/drives/b!A5GL7aV13EOiocvwYtGLxMooxz3vr0JPqZA9_DpzUKTJ9HQROSuuRrmVDBpuHNw6/root:/TargetPerformanceCopyFolder/NewPerformanceTarget/SushmaPerformanceFolderCreateNS942:\nSdkVersion : graph-java/v2.3.0\nAuthorization : [PII_REDACTED]\n\n\n500 : Internal Server Error\n[...]\n\n[Some information was truncated for brevity, enable debug logging for more details]\n\tat com.microsoft.graph.http.GraphServiceException.createFromConnection(GraphServiceException.java:490)\n\tat com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:503)\n\tat com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:423)\n\tat com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:220)\n\tat com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:200)\n\tat com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:345)\n\tat com.microsoft.graph.requests.extensions.DriveItemRequest.delete(DriveItemRequest.java:102)\n\tat

**Comment by baywet** [comment]
Thanks for providing the additional information. I was able to see your request in the logs of Microsoft Graph. The logs indicate that the backend SharePoint services ran into an error. Unfortunately, for privacy reasons I don't have access to the SharePoint logs, only the support teams do.
Please [open a support ticket](https://developer.microsoft.com/en-us/graph/support) mentioning your MS Graph correlation id 51ad42d7-d8a7-476c-acbb-567486bd2311 and the timestamp Wed, 03 Feb 2021 13:58:43 GMT.
Closing as this is not related to the SDK itself.
