### ISSUE TITLE
Trust anchor for certification path not found in Microsoft Graph API

### ISSUE THREAD

**Issue by arunsankar8** [microsoftgraph/msgraph-sdk-java#642]
I have been using the Microsoft Graph API in my android application to get the calendar events etc... for the past 6, 7 months. The Authentication and events data retrieval were all working fine, but Microsoft Graph is not working properly on devices under 4.4 lately, when I try to get user data or calendar events, an exception occurs. I run the same codes on 2 android SDK versions, on 6.0, I can get all the data I want but on 4.4, it fails with the exception :

`Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
`
(The Microsoft Graph were working fine on devices under 4.4 till last December but it stopped giving the following exception)

These are the libraries that are used on the project now

```
implementation 'com.microsoft.identity.client:msal:2.0.5'
implementation 'com.microsoft.graph:microsoft-graph:2.5.0'

implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
implementation("com.squareup.retrofit2:retrofit:2.9.0")

implementation("com.squareup.okhttp3:okhttp:3.12.8") {
force = true
}

implementation "com.squareup.okhttp3:logging-interceptor:3.12.8"
``` 
[AB#7995](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7995)

**Comment by baywet** [comment]
Hi @arunsankar8 
Thanks for reaching out.
Is it possible those devices do not have their root certificates up to date? Or TLS is disabled for some reason? Or is the application/device using a proxy that could be wrongly configured?

For the certificates, please [check that](https://www.digicert.com/dc/blog/official-list-trusted-root-certificates-android/) DigiCert Global Root G2 is installed and enabled on the device with the following fingerprint "cb3ccbb76031e5e0138f8dd39a23f9de47ffc35e43c1144cea27d46a5ab1cb5f"

**Comment by arunsankar8** [comment]
Hi @baywet  

I checked the installed certificates in my device as you said and there is no certificate named **DigiCert Global Root G2** installed, only **DigiCert Global Root CA**, **DigiCert Assured ID Root CA**, **DigiCert High Assurance EV Root CA** is there. 

Could you please guide me to install the certificate and resolve the issue.

**Comment by baywet** [comment]
In the same menu you found the "trusted credentials" option you'll find a "install a certificate" option. Then select "CA certificate" and follow the assistant.
Before doing so, you'll need to download the certificate on the device, you can get it from [this page](https://www.digicert.com/kb/digicert-root-certificates.htm) (make sure you select the Root G2 and not ID Root G2 certificate.

**Comment by arunsankar8** [comment]
Hi @baywet 

Thanks for your kind help, I tried to install the certificate but the device keeps asking for the password for credential storage. Unfortunately, none of the solutions from other online forums are working for me to reset the password. I will look for more solutions for installing the certificate. 

Just for my curiosity can you please tell me why it now requires this certificate for Microsoft Graph API to continue working on devices under 4.4. Because the Microsoft Graph has been working fine on this same android device with version 4.4.2 till last year.

**Comment by baywet** [comment]
Hi @arunsankar8 
That's too bad to read.
I believe one of the certificates in the chain might have been renewed and depends on this new authority when it used to depend on an authority that was already part of the root certificates in the past on older android versions. I don't have any hard evidence yet to confirm that though.
Let us know if you find the solution.
Closing
