### ISSUE TITLE
NPE when trying to get user schedule (v 3.0.0-SNAPSHOT)

### ISSUE THREAD

**Issue by qavid** [microsoftgraph/msgraph-sdk-java#643]
Hi, I'm trying to get schedule for user by using v3 of Graph Java SDK, but getting NPE.
Swallowed exception is:
```
java.lang.NoSuchMethodException: com.microsoft.graph.requests.CalendarGetScheduleCollectionRequest.<init>(java.lang.String,com.microsoft.graph.core.IBaseClient,java.util.List)
...
com.microsoft.graph.http.BaseCollectionRequestBuilder.buildRequest(BaseCollectionRequestBuilder.java:61)
```

I'm not sure if this is a problem of BaseActionCollectionRequestBuilder (buildRequest method should be overridden and take parameters/body argument into account) or all implementations of BaseActionCollectionRequest (except GroupCheckGrantedPermissionsForAppCollectionRequest) are missing constructor without parameters/body argument.

### Expected behavior
Building getScheduleRequest should succeed and create CalendarGetScheduleCollectionRequest instance.
https://docs.microsoft.com/en-us/graph/api/calendar-getschedule?view=graph-rest-1.0&tabs=java

### Actual behavior
NPE is thrown when trying to build CalendarGetSchedule request.

```
Exception in thread "main" java.lang.NullPointerException: Cannot assign field "body" because "request" is null
	at com.microsoft.graph.requests.CalendarGetScheduleCollectionRequestBuilder.buildRequest(CalendarGetScheduleCollectionRequestBuilder.java:55)
	at com.microsoft.graph.requests.CalendarGetScheduleCollectionRequestBuilder.buildRequest(CalendarGetScheduleCollectionRequestBuilder.java:30)
	at com.microsoft.graph.http.BaseCollectionRequestBuilder.buildRequest(BaseCollectionRequestBuilder.java:49)
```

### Steps to reproduce the behavior

dependency: com.microsoft.graph:microsoft-graph:3.0.0-SNAPSHOT

Kotlin sample:
```
val schedulesList = listOf("adelev@contoso.onmicrosoft.com", "meganb@contoso.onmicrosoft.com")

val startTime = DateTimeTimeZone()
startTime.dateTime = "2019-03-15T09:00:00"
startTime.timeZone = "Pacific Standard Time"

val endTime = DateTimeTimeZone()
endTime.dateTime = "2019-03-15T18:00:00"
endTime.timeZone = "Pacific Standard Time"

graphClient.me().calendar()
	.getSchedule(CalendarGetScheduleParameterSet()
		.apply {
			this.schedules = schedulesList
			this.endTime = endTime
			this.startTime = startTime
			this.availabilityViewInterval = 60
		})
	.buildRequest()
``` 
[AB#8000](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8000)

**Comment by baywet** [comment]
Hi @qavid 
Thank you for trying our preview version and providing feedback.
I was able to investigate, reproduce and fix the bug. I authored a PR #649 which will close this issue and update the snapshot version once it gets merged.
