### ISSUE TITLE
JFrog is sunsetting Bintray/Jcenter

### ISSUE THREAD

**Issue by CesarValiente** [microsoftgraph/msgraph-sdk-java#644]
FJYI Jcenter was shutting down on May 1st so your artifacts will not be available from there anymore. Please move your artifacts to a different feed as ADO, Github packages, MavenCentral, etc.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Thanks,
Cesar
 
[AB#8001](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8001)

**Comment by baywet** [comment]
Hi @CesarValiente 
Thanks for letting us know. We received an email from brintray and we already created an issue to track the work here. https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/131

Closing

**Comment by CesarValiente** [comment]
oh! my bad! didn't see the previous issue. Thanks!
