### ISSUE TITLE
GraphError#isError(GraphErrorCodes .ITEM_NOT_FOUND)

### ISSUE THREAD

**Issue by J-Bastian** [microsoftgraph/msgraph-sdk-java#652]
### Expected behavior
GraphError#isError should return true when the exception has the code "itemNotFound" and the provided GraphErrorCodes is ITEM_NOT_FOUND

### Actual behavior
It returns false since the strings "ITEM_NOT_FOUND" and "itemNotFound" don't match

### Steps to reproduce the behavior

Make a Microsoft Graph call returning a "itemNotFound" error:

For example, in Graph Explorer (https://developer.microsoft.com/en-us/graph/graph-explorer)
GET https://graph.microsoft.com/v1.0/me/drive/items/NOT_A_REAL_VALUE

Sample exception:
{
    "error": {
        "code": "itemNotFound",
        "message": "The resource could not be found.",
        "innerError": {
            "date": "2021-02-08T09:56:08",
            "request-id": "31395976-ea18-42ee-8f9a-c19d9bbb9987",
            "client-request-id": "420329db-d36f-d313-4191-01b4124b8aa7"
        }
    }
}

SDK Version: 2.6.0

Sample code:
```
 IGraphServiceClient graphClient = <init graph client> ;

try {
     graphClient.me().drive().items("NOT_A_REAL_VALUE").buildRequest().get();
     Assert.fail();
}
catch (GraphServiceException e) {
boolean isItemNotFound = e.getError().error.isError(GraphErrorCodes.ITEM_NOT_FOUND);
        Assert.assertTrue(isItemNotFound);
}
``` 
[AB#8036](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8036)

**Comment by baywet** [comment]
Hi @J-Bastian 
Thanks for reaching out and for the detailed repro information which made this issue easy to identify and fix.
I just authored PR #654 which fixes this bug and which will close this issue when it gets merged.

**Comment by J-Bastian** [comment]
Hi @baywet,

Thanks for the quick fix !
