### ISSUE TITLE
Calling setMaxRetries on BaseCollectionRequest sets maxRedirects on baseRequest

### ISSUE THREAD

**Issue by mtgerb** [microsoftgraph/msgraph-sdk-java#659]
### Expected behavior

maxRetries is set correctly

### Actual behavior

maxRedirects is set when calling setMaxRetries on BaseCollectionRequest

There seems to be a typo at https://github.com/microsoftgraph/msgraph-sdk-java/blob/ee1678b0dd2a96ade4844833626f51edaa8af992/src/main/java/com/microsoft/graph/http/BaseCollectionRequest.java#L274

 
[AB#8085](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8085)

**Comment by baywet** [comment]
Hi @mtgerb 
Thanks for reporting this issue.
Would you mind submitting a pull request to fix it?
If you can't, or don't want to, just let me know, I'll go ahead and fix it myself.

**Comment by mtgerb** [comment]
Hi @baywet
I just submitted the pull request

**Comment by baywet** [comment]
thanks a lot, I'll review it ASAP!

**Comment by baywet** [comment]
reviewed. This should go out with the next generation next week. Thanks again!
