### ISSUE TITLE
Errors once type hiding removed

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#66]
This method in `BaseCollectionRequest<T1, T2`> is hiding types:

```java
@SuppressWarnings("unchecked")
protected <T1, T2> T1 post(final T2 serializedObject) throws ClientException {
        baseRequest.setHttpMethod(HttpMethod.POST);
    return (T1) baseRequest.getClient().getHttpProvider().send(this, responseClass, serializedObject);
}
```
When the `<T1, T2>` is removed from the `post` method a number of collection related compile errors turn up. This may indicate bugs (`ClassCastException`s) waiting for a user to hit those methods.

**Comment by deepak2016** [comment]
Hi David, what do you mean by removing template <T1, T2> parameters from post method signature. Are you indicating to use specific class names instead of generic T1 & T2? @davidmoten

**Comment by davidmoten** [comment]
>Hi David, what do you mean by removing template <T1, T2> parameters from post method signature. Are you indicating to use specific class names instead of generic T1 & T2?

The parameters `<T1, T2>` on that method signature should not be there because the class itself has those declared generic types. When you redeclare them in the method signature the class level types T1, T2 are ignored and the types for the method are *inferred*.  We thus lose the benefits of type safety and there was no real point in adding those generic types to the class!

The action I propose is to make the signature:

```java
@SuppressWarnings("unchecked")
protected T1 post(final T2 serializedObject) throws ClientException {
        baseRequest.setHttpMethod(HttpMethod.POST);
    return (T1) baseRequest.getClient().getHttpProvider().send(this, responseClass, serializedObject);
}
```
Once that is done that provokes some compile errors which should be studied and addressed (over to you on that but we can discuss more here if you like).

**Comment by deepak2016** [comment]
I have following proposal to fix the issue. 
Introduce new BaseMethodBody.java in core package.
```
public class BaseMethodBody {
    /**
     * The raw representation of this class
     */
    private JsonObject rawObject;

    /**
     * The serializer
     */
    private ISerializer serializer;

    /**
     * Gets the raw representation of this class
     *
     * @return the raw representation of this class
     */
    public JsonObject getRawObject() {
        return rawObject;
    }

    /**
     * Gets serializer
     *
     * @return the serializer
     */
    protected ISerializer getSerializer() {
        return serializer;
    }

    /**
     * Sets the raw JSON object
     *
     * @param serializer the serializer
     * @param json the JSON object to set this object to
     */
    public void setRawObject(final ISerializer serializer, final JsonObject json) {
        this.serializer = serializer;
        rawObject = json;

    }
}
```

BaseDriveItemInviteCollectionRequest has instance of DriveItemInviteBody, which it passes to post method of BaseCollectionRequest. Similarly other Base*CollectionRequest classes have instance of some body class and that gets passed to post method of base class. Now, we will make all these body classes a derived class of BaseMethodBody. This will be generator change.
`public class DriveItemInviteBody extends BaseDriveItemInviteBody {`
`public class BaseDriveItemInviteBody extends BaseMethodBody {`


Changes in BaseCollectionRequest class: 
```
protected T1 post(final BaseMethodBody serializedObject) throws ClientException {
        baseRequest.setHttpMethod(HttpMethod.POST);
        return (T1) baseRequest.getClient().getHttpProvider().send(this, responseClass, serializedObject);
    }
```
This change will be in http package. 

These changes solves the type safety issue. Now that all the objects being passed to post method will be derived class of newly introduced base class.

**Comment by davidmoten** [comment]
@deepak2016 Yeah I think that something like BaseMethodBody is part of the solution. However, what you are suggesting just weakens typing because any subclass of BaseMethodBody can be passed to the `post` method. I've outlined a type-safe solution in #116 and #119. Have you tried following that pattern?

**Comment by darrelmiller** [comment]
@deepak2016 The approach that @davidmoten is suggesting in #116 is where we need to go.  This is a design flaw that I think has leaked over from C#.  We need to fix it there too.  When I'm in your offices next week, I'll show you the proposal I have for fixing the issue in C# and we can see if we can apply the same approach in Java.

**Comment by deepak2016** [comment]
We have removed type hiding in the method and fix takes care of corresponding warning and error. We will be undertaking redesign task for the SDK to address deeper issues with SDK design, but this particular issue is resolved with the fix.
