### ISSUE TITLE
getSchedule returns null (v 3.0.0-SNAPSHOT)

### ISSUE THREAD

**Issue by qavid** [microsoftgraph/msgraph-sdk-java#660]
Hi, 
similar problem to #643 is with CalendarGetScheduleCollectionRequestBuilder

### Expected behavior
Calling post method on CalendarGetScheduleCollectionRequest should return not null instance of CalendarGetScheduleCollectionPage.

### Actual behavior
Calling post method on CalendarGetScheduleCollectionRequest returns null due to swallowed exception:
```
java.lang.NoSuchMethodException: com.microsoft.graph.requests.CalendarGetScheduleCollectionRequestBuilder.<init>(java.lang.String,com.microsoft.graph.core.IBaseClient,java.util.List)
...
com.microsoft.graph.http.BaseCollectionRequest.buildFromResponse(BaseCollectionRequest.java:126)
com.microsoft.graph.http.BaseActionCollectionRequest.post(BaseActionCollectionRequest.java:103)
```

### Steps to reproduce the behavior
dependency: com.microsoft.graph:microsoft-graph:3.0.0-SNAPSHOT

Kotlin sample:
```
val schedulesList = listOf("adelev@contoso.onmicrosoft.com", "meganb@contoso.onmicrosoft.com")

val startTime = DateTimeTimeZone()
startTime.dateTime = "2019-03-15T09:00:00"
startTime.timeZone = "Pacific Standard Time"

val endTime = DateTimeTimeZone()
endTime.dateTime = "2019-03-15T18:00:00"
endTime.timeZone = "Pacific Standard Time"

val result = graphClient.me().calendar()
	.getSchedule(CalendarGetScheduleParameterSet()
		.apply {
			this.schedules = schedulesList
			this.endTime = endTime
			this.startTime = startTime
			this.availabilityViewInterval = 60
		})
	.buildRequest()
	.post()
checkNotNull(result) //
```

 
[AB#8086](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8086)

**Comment by baywet** [comment]
hi @qavid
Thanks again for trying the v3 and letting us know about quirks.
I'm sorry I didn't catch that when fixing the previous bug. Some request builders were missing a default constructor.
I have authored multiple PRs to fix it, including #661 which will close this issue when merged.
There might be a bit of lead time (few days) before this is available in the snapshots as we have a bit of a backlog of pull requests to review across the SDKs repositories at the moment.
Thank you for your patience.
