### ISSUE TITLE
IRequestBuilder add buildRequest()  

### ISSUE THREAD

**Issue by valenpo** [microsoftgraph/msgraph-sdk-java#667]
Is it possible to add method IRequestBuilder.buildRequest() that will return ICollectionRequest. This simplify page iteration. 
```java
class IBaseCollectionPageIterator<T1, T2 extends IRequestBuilder> implements Iterator {

    private final Stack<T1> currentPage = new Stack<>();
    private IBaseCollectionPage<T1, T2> collectionPage;

    public IBaseCollectionPageIterator(IBaseCollectionPage<T1, T2>  collectionPage) {
        this.collectionPage = collectionPage;
        currentPage.addAll(collectionPage.getCurrentPage());
    }

    @Override
    public boolean hasNext() {
        if (!currentPage.isEmpty() && Objects.nonNull(currentPage.peek()))
            return true;
        else {
            final T2 nextPage = collectionPage.getNextPage();
            if (isNull(nextPage))
                return false;
            else {
                this.collectionPage = nextPage.buildRequest().get;
                currentPage.addAll(this.collectionPage.getCurrentPage());
                return false;
            }
        }
    }

    @Override
    public T1 next() {
        return currentPage.pop();
    }
}
```

 
[AB#8153](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8153)

**Comment by baywet** [comment]
Hi @valenpo 
Thanks for reaching out.
We already have a [specification for page iterators across SDKs](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/sdks/paging.md) and I have opened [an issue](https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/111) to add this in the [upcoming v3](https://github.com/microsoftgraph/msgraph-sdk-java/issues/628) of the SDK.

I'm going to go ahead and close this issue you just created as we already have an item tracking that work.
Please go ahead and provide additional feedback on the issue I linked.

If you feel like contributing, we'll be more than happy to support you in the process. Submit a pull request on the core repository with the feature/v2 as a base branch.

**Comment by valenpo** [comment]
Hi @baywet, 

Thanks for response, I look specification and it is plenty of repeated boilerplate for page iteration. I look V3, and try do a pool request. 

Thanks.
