### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by brunoborges** [microsoftgraph/msgraph-sdk-java#67]
Please also publish this library to Maven Central.

**Comment by brunoborges** [comment]
Hi @cbales, has this project been released to Maven Central already?

**Comment by brunoborges** [comment]
Good stuff @deepak2016 , thanks!

Keep in mind though that once GA is released, it must not contain `-SNAPSHOT`and it must be available on `Maven Central`, meaning that developers shouldn't be required to configure the `<profile>`.

**Comment by deepak2016** [comment]
Sure @brunoborges 
I am marking this issue closed.

**Comment by davidmoten** [comment]
@deepak2016 if I remember correctly 0.3 is already released so you should
be publishing 0.4-SNAPSHOT not 0.3-SNAPSHOT. gradle.properties was already
set at 0.4-SNAPSHOT in developing branch and did not need to be overridden.

**Comment by deepak2016** [comment]
@davidmoten Have noted your point. Will take care of it in our future releases. I'm working to merge generated code into java sdk and then will do 0.4 release for gradle as well as maven.
