### ISSUE TITLE
Improve Changelog / Release Notes

### ISSUE THREAD

**Issue by black-snow** [microsoftgraph/msgraph-sdk-java#673]
*IMHO* the [changelog](https://github.com/microsoftgraph/msgraph-sdk-java/releases) needs some improvements. Most lines read like

```
Merge pull request #655 from microsoftgraph/v1.0/pipelinebuild/50
```

and if you didn't open that PR yourself you have no idea what's actually changed. When I see that a new version is out I take a look at the changelog / the release notes to see:

- if there are breaking changes (and if yes, what's the upgrade path)
- are there important bug fixes?
- any new features that I'm really longing for?

Anything else is, to me as a consumer, bogus.

If there's a changelog in addition to the release notes it may have as much internal details as there is.

Cheers! 

P.S.: Or is there another changelog somewhere else?

[AB#8241](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8241)

**Comment by baywet** [comment]
Hi @black-snow ,
Thanks for reaching out and thanks for the feedback.
Right now the release notes for all the Microsoft Graph SDKs are built using [this Azure DevOps task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops) which by default takes the changelog and adds it as release notes.
If we can't commit to manually writing those release notes (across so many languages with weekly generations, it'd be too much manual work), maybe we can improve the automated process that creates those notes.
As a note, bugfixes are listed, see [this release as an example](https://github.com/microsoftgraph/msgraph-sdk-java/releases/tag/2.8.0), as long as the information is clearly indicated in the commit message.

Besides bugfixes and feature additions, what are your expectations regarding the release notes? are you expecting to see new types/properties there? Are you aware of [the API changelog](https://developer.microsoft.com/en-us/graph/changelog) ?

**Comment by baywet** [comment]
As of the breaking changes, we follow semver for our SDKs, so any breaking change will translate in a major version bump. If we plan multiple breaking changes, we'll document an upgrade guide like we have for the upcoming v3 (see #628 ).

**Comment by black-snow** [comment]
Thanks for the quick response!

I already figured it's a list of commit messages. I wasn't aware of the API changelog, thanks!
For the SDK, I'd expect useful information for SDK consumers, i. e. user-facing bugfixes, additions, deprecations etc. - I'd like not to know about all the internals (as a consumer).

Maybe the task could be adjusted to look for some keywords like bugfix, addition, breaking, documentation, internal etc.? And then the messages could be sorted into some subsections like [here](https://github.com/dropwizard/dropwizard/releases) or [here](https://github.com/spring-projects/spring-boot/releases)?

**Comment by baywet** [comment]
Thanks for the additional information.
Those release notes sure look nicer. This is something we'd have to do across the different languages for consistency.
I'm going to let @mairissi and @roinochieng (our program managers) look at that discussion, come up with an expected format for the release notes and comment here.
@ddyett I think this issue should live in a different repo but I'm not sure which one. Sdk design maybe?

**Comment by darrelmiller** [comment]
@black-snow  The API Changelog is the central place to see additions and deprecations to the API.  This repo is home to the generated service library that should track the API updates automatically.  There should be almost no additional information in these release notes.  The core library https://github.com/microsoftgraph/msgraph-sdk-java-core is where you should expect to find release notes with the details of bugfixes and enhancements to the SDK.

**Comment by baywet** [comment]
To recap some of the things that were said on the meeting today:

## service libs
For the service libraries there's no point generating a more explicit changelog as it's mostly going to be dependabot PRs (already explicit enough) or service metadata generation updates. In the case of the service metadata updates, we could add a link in the release description to the changelog like this https://developer.microsoft.com/en-us/graph/changelog/?filterBy=v1.0&from=2021-08-17&to=2021-08-24 where: filterBy is a constant determined by the current repo, from is the date of the last release, to is the date of the generation PR/today.

## core lib
For the core libs, it'd be good to standardize on [keep a changelog](https://keepachangelog.com/en/1.0.0/) as there's ton of tooling to write the release notes automatically from it, and it keeps a linear changelog anyone can refer to. See the examples on [kiota releases](https://github.com/microsoft/kiota/releases/tag/v0.0.7) that gets its information from [kiota changelog](https://github.com/microsoft/kiota/blob/main/CHANGELOG.md#007---2021-08-04)
The benefit of doing that (beside a standard open source approach that's familiar to a lot of people out there) is that the dependabot PRs (or other dependency management tooling) could extract the release notes when updating things. See the difference between [a PR that provides a standard changelog](https://github.com/microsoft/kiota/pull/515) and [one that doesn't](https://github.com/microsoftgraph/java-spring-webhooks-sample/pull/172). Until the changelog generation was fixed on core, I was [doing something similar](https://github.com/microsoftgraph/msgraph-sdk-java-core/releases/tag/2.0.7)

**Comment by maisarissi** [comment]
Hey @black-snow.
We changed the Release Notes shape for both, service and core libraries.
Specifically talking about the service library, which was the reason you have opened this issue, you can see [v5.5.0](https://github.com/microsoftgraph/msgraph-sdk-java/releases/tag/v5.5.0) for better context, we made it cleaner. And of course, the same applies on the core library -- [v2.0.9](https://github.com/microsoftgraph/msgraph-sdk-java-core/releases/tag/v2.0.9).
Please, feel free to reopen if you believe we still need to discuss further improvements.

**Comment by black-snow** [comment]
That's awesome, thanks y'all ;)
