### ISSUE TITLE
SDK not sending latest/ refreshed auth token to graph service

### ISSUE THREAD

**Issue by tapanp** [microsoftgraph/msgraph-sdk-java#677]
### Expected behavior
Graph api should use latest auth token to query graph service

### Actual behavior
SDK is sending old token to graph service that results in following error:

`com.microsoft.graph.http.GraphServiceException: Error code: InvalidAuthenticationToken Error message: Access token has expired or is not yet valid. GET https://graph.microsoft.com/v1.0/users/{user_name}/memberOf SdkVersion : graph-java/v2.8.1 Authorization : [PII_REDACTED] 401 : Unauthorized [...] [Some information was truncated for brevity, enable debug logging for more details]
`

### Steps to reproduce the behavior

1. Create a web app that uses Azure AD authentication and deploy it to Azure app service. I have taken sample app service (https://github.com/Azure-Samples/ms-identity-java-webapp/tree/master/msal-java-webapp-sample) and added following code to access groups. 

> `''
>    
>     IAccount account = SessionManagementHelper.getAuthSessionObject(httpRequest).account();
>     IDirectoryObjectCollectionWithReferencesPage memberOf = graphClient.users(account.username()).memberOf()
>                 .buildRequest()
>                 .get();
> 
>     JsonObject responseObject = memberOf.getRawObject();
> 
> `''

This call will work as expected right after deployment.

2.  Now test again after long interval (next day).
3. We will get below error now.

> `com.microsoft.graph.http.GraphServiceException: Error code: InvalidAuthenticationToken Error message: Access token has expired or is not yet valid. GET https://graph.microsoft.com/v1.0/users/{user_name}/memberOf SdkVersion : graph-java/v2.8.1 Authorization : [PII_REDACTED] 401 : Unauthorized [...] [Some information was truncated for brevity, enable debug logging for more details]`

4. However, same will work fine if you call graph service directly using HttpURLConnection as shown below:

> ```
> 
> IAccount account = SessionManagementHelper.getAuthSessionObject(httpRequest).account();
> 
> //        IDirectoryObjectCollectionWithReferencesPage memberOf = graphClient.users(account.username()).memberOf()
> //                .buildRequest()
> //                .get();
> //
> //        JsonObject responseObject = memberOf.getRawObject();
> 
>         // Microsoft Graph user endpoint
> //        URL url = new URL(authHelper.getMsGraphEndpointHost() + String.format("v1.0/me/transitiveMemberOf/microsoft.graph.group?$count=true"));
>         URL url = new URL(authHelper.getMsGraphEndpointHost() + String.format("v1.0/users/%s/memberOf", account.username()));
>         HttpURLConnection conn = (HttpURLConnection) url.openConnection();
> 
>         // Set the appropriate header fields in the request header.
>         conn.setRequestProperty("Authorization", "Bearer " + accessToken);
>         conn.setRequestProperty("Accept", "application/json");
> 
>         String response = HttpClientHelper.getResponseStringFromConn(conn);
> 
>         int responseCode = conn.getResponseCode();
>         if(responseCode != HttpURLConnection.HTTP_OK) {
>             throw new IOException(response);
>         }
> 
>         JSONObject responseObject = HttpClientHelper.processResponse(responseCode, response);
> 
> ```

 
[AB#8277](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8277)

**Comment by baywet** [comment]
Hi @tapanp 
Thanks for reaching out.
Can you let us know what version of the SDK you are using as well as the core library? If your application is not using 2.8.1 for the library and 1.0.8 for core, can you make sure you update those and try again please?

Also, can you share the code of your AuthenticationProvider implementation?
How is your graph client instantiated, are you relying on a static instance?

**Comment by tapanp** [comment]
@baywet Yes, it's because my graph client instance is static instance. change it to following and its working fine.

```
IGraphServiceClient graphClient = GraphServiceClient.builder()
                .authenticationProvider( request -> request.addHeader("Authorization", "Bearer " + accessToken) )
                .buildClient(); 
```

closing the issue.
