### ISSUE TITLE
Changing password request is logging out sensitive information

### ISSUE THREAD

**Issue by AshTappin** [microsoftgraph/msgraph-sdk-java#685]
I am currently using the Microsoft Graph Java SDK to change a user's password like so:

```
graphServiceClient
  .me()
  .changePassword(currentPassword, newPassword)
  .buildRequest()
  .post();

```
However, when the Graph API throws an exception, the change password request is written to the log with the passwords displaying in plain text! Is there a way of hiding this sensitive information? For now, I have added a custom logger the Graph Server Client which in effect suppresses logging but I was wondering if there was something more fine grained in the SDK?

**Comment by baywet** [comment]
Hi @AshTappin 
Thanks for reaching out.
What verbosity do you have set on the logger? The logger will log the payload only if the level is set to debug.
To set the log level you can do `graphServiceClient.getLogger().setLoggingLevel(LoggerLevel.ERROR);`

**Comment by AshTappin** [comment]
Hi @baywet 
Yes I am setting the logging level to ERROR and the payload is still logged. This is what I see 

`[com.microsoft.graph.http.GraphServiceException: Error code: Request_BadRequest
Error message: The specified password does not comply with password complexity requirements. Please provide a different password.

POST https://graph.microsoft.com/v1.0/me/microsoft.graph.changePassword
SdkVersion : graph-java/v2.3.1
Authorization : [PII_REDACTED]
{"currentPassword":"<password>","newPassword":"pass[...]

400 : Bad Request
[...]

`

**Comment by AshTappin** [comment]
Looking into it a bit further, if I supplied a logger that doesn't do anything, then some logs do not appear but some Spring magic in my server logs out the Graph Service exception thrown with the payload in the message. I can change my server to not log this exception at all, but wondering if the GraphServiceException could still be constructed with bits of the payload hidden?

**Comment by baywet** [comment]
Hi @AshTappin 
Thanks for the additional information.
I believe you are still seeing the payload in the spring logs because those are calling getMessage on the error, which provides a truncated version of the request payload by default.
I've just authored #689 to fix that behavior, which will close this issue when merged.
If you can, I'd appreciate if you could test this version before we merge the pull request and confirm that it fixes the issue.
Thanks!

**Comment by AshTappin** [comment]
Hi @baywet , thank you ! I will test and let you know

**Comment by baywet** [comment]
Yes but this version is not out yet. You can test the snapshot for 2.9.0 or clone and make a local reference in the meantime.

**Comment by AshTappin** [comment]
Hi @baywet, I have cloned, built a local jar, referenced it in my project and I can confirm that this fixes the issue. The following is logged 
```
Resolved [com.microsoft.graph.http.GraphServiceException: Error code: Request_BadRequest
Error message: The specified password does not comply with password complexity requirements. Please provide a different password.

POST https://graph.microsoft.com/v1.0/me/microsoft.graph.changePassword
SdkVersion : graph-java/v2.9.0
Authorization : [PII_REDACTED]
[...]

400 : Bad Request
[...]
```
Thank you so much for resolving this quickly!

**Comment by baywet** [comment]
@AshTappin thanks for confirming!
The update should go out with the next service metadata generation next week. (2.10.0)
