### ISSUE TITLE
Gson/Jdk 9 serialization warnings

### ISSUE THREAD

**Issue by JohnAustin-MSFT** [microsoftgraph/msgraph-sdk-java#69]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [X ] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [ X] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [ X] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
No serialization warnings on POST 

### Actual behavior
[POSTDraftMessageWarning.zip](https://github.com/microsoftgraph/msgraph-sdk-java/files/1772322/POSTDraftMessageWarning.zip)
NFO: Starting to send request, URL https://graph.microsoft.com/v1.0/me/mailFolders/Drafts/messages/AQMkAGFiMmViMzU2LWExOGEtNGY2YS04MzkzLTE4YTlmNTNkYWEAMWEARgAAA6Rab21vU6xDt5I_G5um6EYHABUsriz4zOpLoeCGQBXajO4AAAMRAAAAFSyuLPjM6kuh4IZAFdqM7gAEd_oxLAAAAA==/microsoft.graph.send
Feb 28, 2018 4:17:25 PM com.microsoft.graph.logger.DefaultLogger logDebug
INFO: Request Method POST
Feb 28, 2018 4:17:25 PM com.microsoft.graph.logger.DefaultLogger logDebug
INFO: Response code 202, Accepted
Feb 28, 2018 4:17:25 PM com.microsoft.graph.logger.DefaultLogger logDebug
INFO: Handling accepted response
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.ConstructorConstructor (file:/C:/Users/johnau/.m2/repository/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar) to constructor java.lang.Void()
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.ConstructorConstructor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Feb 28, 2018 4:17:25 PM com.microsoft.graph.logger.DefaultLogger logDebug
INFO: Deserializing a non-IJsonBackedObject type Void
Feb 28, 2018 4:17:25 PM com.microsoft.graph.logger.DefaultLogger logDebug

### Steps to reproduce the behavior

mGraphServiceClient
                    .me()
                    .mailFolders("Drafts")
                    .messages(messageId)
                    .send()
                    .buildRequest()
                    .post(callback);

**Comment by davidmoten** [comment]
See https://github.com/google/gson/issues/1190. I'll ask there about progress.

**Comment by davidmoten** [comment]
I've done a bit of reading and this may be just because we are using gson to serialize a Void return type. The Void constructor is private so gson forces access (to a platform type) hence the warning. I can look at this a bit later but some special treatment for Void in the `DefaultHttpProvider` may sidestep this issue. 

@JohnAustin-MSFT Let us know if you bump into this with types other than java.lang.Void.
