### ISSUE TITLE
Getting MIME content is not working in Graph API ( 3.1.0) for Java SDK

### ISSUE THREAD

**Issue by sunil-marudappa** [microsoftgraph/msgraph-sdk-java#722]
Hi Support team,
I am trying to get the mime-content of the message with attachment,
I am using 3.1.0, which has content method, I am using this method to get the mime-content(uses /$value), below is my request. Below is the reference docuementation we are using.

https://docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&tabs=http#example-3-expand-and-get-the-properties-of-the-item-attached-to-a-message

I am getting the response with code 200 and header as Content-Type: text/plain, body has nothing and body.contentLength() is coming as -1,

Kindly help me if I am missing anything in the request/headers

Code for mime content for message:
Request: https://graph.microsoft.com/v1.0/users/{Email Id}/messages/{message id}/$value
graphClient.users({emailId}).messages(message.id).content()
.buildRequest()
.get();
I tried to fetch the same mime-content for attachment as well, below is the code
final String baseUrl = graphClient.users(userProfile).messages(message.id).attachments(attchId).buildRequest().getRequestUrl().toString();
final CustomRequestBuilder downloadRequestBuilder = new CustomRequestBuilder<>(baseUrl + "/$value", graphClient, new ArrayList(), InputStream.class);
final InputStream stream = downloadRequestBuilder.buildRequest().get();

In either case, I am getting the body as empty and body.contentLenght() is -1.
Kindly help me on this. 
[AB#8944](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8944)

**Comment by baywet** [comment]
Hi @sunil-marudappa 
Thanks for reaching out.
Just the following should allow you to get the mime content of the message.
```Java
final InputStream result = graphClient.me().messages("id").content().buildRequest().get()
```

Then the following should allow you to represent the mime content at text
```Java
final BufferedReader r = new BufferedReader(new InputStreamReader(result));
final StringBuilder content = new StringBuilder();
String line;
while ((line = r.readLine()) != null) {
     content.append(line).append('\n');
}
```

**Comment by sunil-marudappa** [comment]
Thank you for the code, since we get the string as mime content, how can we save this text as .msg file ?
Is .eml is better way or .msg is better way ?
I am able to save it as .eml file, would like to know, how we can save this as .msg file, coz, .msg is outlook format file.
Kindly let me know, on this issue.

**Comment by baywet** [comment]
This follow up question is outside the scope of this repository. The goal of the issues on this repository is to discuss issues related to the Java SDK for Microsoft Graph. You're able to get the MIME content from Microsoft Graph using the SDK and save it as eml file now. I suggest you ask how to convert a MIME/eml message to msg using Java on another forum like [stackoverflow](https://stackoverflow.com.)
Closing for now.

**Comment by sunil-marudappa** [comment]
Thanks a ton, it worked, please close the ticket
