### ISSUE TITLE
Search for sites returns a 403 (v3.2.0), but not in the .NET SDK

### ISSUE THREAD

**Issue by devManderson** [microsoftgraph/msgraph-sdk-java#724]
### Expected behavior
Search for sharepoint sites via the java graph sdk returns a "SiteCollectionPage" object
https://docs.microsoft.com/en-us/graph/api/site-search?view=graph-rest-1.0&tabs=java

### Actual behavior
The search for sharepoint sites with the java sdk returns a 403 message, with the .net sdk I get the expected result. I use the same clientId & user for the login. Getting the sharepoint site I search for (called it "graphtest") via the siteId works fine, also I get the user, lists and items in both (java & .net) sdks. Only the search won't work for me  

### Steps to reproduce the behavior

JAVA SDK: openjdk-15.0.2
Graph SDK Version via maven: com.microsoft.graph:microsoft-graph:3.2.0

Java IDE:
IntelliJ IDEA 2020.3.3 (Ultimate Edition)
Build #IU-203.7717.56, built on March 15, 2021
Runtime version: 11.0.10+8-b1145.96 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1014M
Cores: 4

My java code:

        final InteractiveBrowserCredential interactiveBrowserCredential = new InteractiveBrowserCredentialBuilder()
                .clientId(CLIENT_ID)
                .redirectUrl("http://localhost:8765")
                .build();

        List<String> scopes = new ArrayList<>();
        scopes.add("https://graph.microsoft.com/.default");

        final TokenCredentialAuthProvider tokenCredentialAuthProvider = new TokenCredentialAuthProvider(scopes, interactiveBrowserCredential);

        final GraphServiceClient graphClient =
                GraphServiceClient
                        .builder()
                        .authenticationProvider(tokenCredentialAuthProvider)
                        .buildClient();

        LinkedList<Option> requestOptions = new LinkedList<Option>();
        requestOptions.add(new QueryOption("search", "graphtest"));
        
        // Here I get a 403: forbidden
        SiteCollectionPage sites = graphClient.sites()
                .buildRequest(requestOptions)
                .get();

        System.out.println("sites = " + sites);

And my c# code:

            IPublicClientApplication publicClientApplication = PublicClientApplicationBuilder
           .Create(CLIENT_ID)
           .WithDefaultRedirectUri()
           .Build();

            List<string> scopes = new List<string>();
            scopes.Add("https://graph.microsoft.com/.default");

            InteractiveAuthenticationProvider authProvider = new InteractiveAuthenticationProvider(publicClientApplication, scopes);

            GraphServiceClient graphClient = new GraphServiceClient(authProvider);

            var queryOptions = new List<QueryOption>();
            queryOptions.Add(new QueryOption("search", "graphtest"));

            var sites = await graphClient.Sites
                .Request(queryOptions)
                .GetAsync();

            Console.WriteLine("sites = " + sites);

My API permissions in azure:
![image](https://user-images.githubusercontent.com/21075250/114513804-e17c7b80-9c3a-11eb-9874-77b209114133.png)

The errors I get in the console from the java code:
```
  OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
  SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
  SLF4J: Defaulting to no-operation (NOP) logger implementation
  SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
  ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
  Apr 13, 2021 8:46:17 AM com.microsoft.graph.logger.DefaultLogger logError
  SEVERE: CoreHttpProvider[sendRequestInternal] - 386Graph service exception Error code: accessDenied
  Apr 13, 2021 8:46:17 AM com.microsoft.graph.logger.DefaultLogger logError
  SEVERE: CoreHttpProvider[sendRequestInternal] - 386Error message: Access denied
  Apr 13, 2021 8:46:17 AM com.microsoft.graph.logger.DefaultLogger logError
  SEVERE: CoreHttpProvider[sendRequestInternal] - 386
  Apr 13, 2021 8:46:17 AM com.microsoft.graph.logger.DefaultLogger logError
  SEVERE: CoreHttpProvider[sendRequestInternal] - 386GET https://graph.microsoft.com/v1.0/sites?search=graphtest
  Apr 13, 2021 8:46:17 AM com.microsoft.graph.logger.DefaultLogger logError
  SEVERE: CoreHttpProvider[sendRequestInternal] - 386SdkVersion : graph-java/v3.2.0
  Apr 13, 2021 8:46:17 AM com.microsoft.graph.logger.DefaultLogger logError
  SEVERE: CoreHttpProvider[sendRequestInternal] - 386
  Apr 13, 2021 8:46:17 AM com.microsoft.graph.logger.DefaultLogger logError
  SEVERE: CoreHttpProvider[sendRequestInternal] - 386
  Apr 13, 2021 8:46:17 AM com.microsoft.graph.logger.DefaultLogger logError
  SEVERE: CoreHttpProvider[sendRequestInternal] - 386403 : Forbidden
  Apr 13, 2021 8:46:17 AM com.microsoft.graph.logger.DefaultLogger logError
  SEVERE: CoreHttpProvider[sendRequestInternal] - 386[...]
  Apr 13, 2021 8:46:17 AM com.microsoft.graph.logger.DefaultLogger logError
  SEVERE: CoreHttpProvider[sendRequestInternal] - 386
  Apr 13, 2021 8:46:17 AM com.microsoft.graph.logger.DefaultLogger logError
  SEVERE: CoreHttpProvider[sendRequestInternal] - 386[Some information was truncated for brevity, enable debug logging for more details]
  Apr 13, 2021 8:46:17 AM com.microsoft.graph.logger.DefaultLogger logError
  SEVERE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: accessDenied
  Error message: Access denied
  
  GET https://graph.microsoft.com/v1.0/sites?search=graphtest
  SdkVersion : graph-java/v3.2.0
  
  
  403 : Forbidden
  [...]
  
  [Some information was truncated for brevity, enable debug logging for more details]
  Exception in thread "main" com.microsoft.graph.http.GraphServiceException: Error code: accessDenied
  Error message: Access denied
  
  GET https://graph.microsoft.com/v1.0/sites?search=graphtest
  SdkVersion : graph-java/v3.2.0


403 : Forbidden
[...]

[Some information was truncated for brevity, enable debug logging for more details]
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:419)
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:378)
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:491)
	at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:420)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:386)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:214)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:191)
	at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:102)
	at com.microsoft.graph.http.BaseEntityCollectionRequest.get(BaseEntityCollectionRequest.java:78)
	at sample.JExample.main(JExample.java:42)
``` 
[AB#8951](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8951)

**Comment by baywet** [comment]
Hi @devManderson 
Thanks for reaching out.
If you run the following code and you crack open the JWT you get in https://jwt.ms, what scopes do you have listed?

```Java
final String token = tokenCredentialAuthProvider.getAuthorizationTokenAsync(new URL("https://graph.microsoft.com/v1.0/")).get();
//log the token, or attach and debug
```

**Comment by devManderson** [comment]
Hej @baywet,

I hope you mean this part:

> "scp": "AuditLog.Read.All Directory.AccessAsUser.All email Group.ReadWrite.All openid profile User.ReadWrite.All",

So, should I set this as permissions in azure? Or are these the permissions I have?

**Comment by baywet** [comment]
thanks for the additional details, these do not match at all the screenshot you provided earlier. Can you double check you are using the same app id between the two apps please? Otherwise yes, you'll need to add either Sites.Read.All or Sites.ReadWrite.All to the corresponding app registration in the azure portal. An alternative would be to pass the scopes to the provider instead of `https://graph.microsoft.com/.default`.

**Comment by devManderson** [comment]
Double & tripple check

![image](https://user-images.githubusercontent.com/21075250/114732421-c85ef200-9d42-11eb-8bb3-4f71d204d284.png)

I'm using the application ID, in my java an c# code I called the variable CLIENT_ID (see in my code), could this be wrong?

Passing the scopes directly did give me other errors, so I did stick to https://graph.microsoft.com/.default

**Comment by baywet** [comment]
The client id and the application id are the same id.
The Java SDK doesn't do anything with the token other than requesting it from the authentication library and passing it when executing requests. I'd suggest doing the same exercise of getting the token with your dotnet application and comparing the scopes. You probably have a difference of scopes between the two apps.

What error are you getting when you pass scopes to the java application? (instead of using .default)

**Comment by devManderson** [comment]
So I used this c# code to grab the token:

`var token = publicClientApplication.AcquireTokenInteractive(scopes).ExecuteAsync().Result.AccessToken;`

and I get from jwt.ms:

> "scp": "ExternalItem.Read.All Files.Read.All openid profile Sites.Read.All Sites.ReadWrite.All User.Read email"

Looks like the permission I have set in azure. 

I didn't notice before but, I get for c# from jwt:

> "app_displayname": "MSGraphTest",
> "appid": "fa6adbf7-XXXX-XXXX-XXXX-XXXXXXXXXX",

The app name and appId is correct, but for java:

 > "app_displayname": "Microsoft Azure CLI",
 > "appid": "04b07795-XXXX-XXXX-XXXX-XXXXXXXXXX",

This app name & the appId are not mine and I don't use them anywhere...

![image](https://user-images.githubusercontent.com/21075250/114828666-79f53600-9dca-11eb-85ec-9d51c9b2d743.png)

If I pass the scope to java application I get:

>java.util.concurrent.ExecutionException: com.azure.core.exception.ClientAuthenticationException: Failed to acquire token with Interactive Browser Authentication.

Don't know if I do something completely wrong at all :(

**Comment by baywet** [comment]
Thanks for the additional details, it looks like you're impacted by [this bug](https://github.com/Azure/azure-sdk-for-java/issues/19796) I logged a few weeks ago. Upgrade to azure identity 1.2.5 and things should work properly.

**Comment by devManderson** [comment]
Yeah! I updated to azure identity 1.2.5 from 1.2.3 and now it works for me, thanks a lot.
