### ISSUE TITLE
GetMessage for messageid throws exception with ItemNotFound

### ISSUE THREAD

**Issue by sunil-marudappa** [microsoftgraph/msgraph-sdk-java#731]
Dear Team,

I am using graph sdk version 3.1.0, I have a scenario where I need to fetch the message for given messageId, but its throwing ItemNotFound exception. Below is the steps, I followed.

1) Created the draft, which returned the messageid eg: "abcd123A==".
2) using same messageId, I am uploading large attachment using session.
3) Called the send email (returns void) to send the email, now email is sent and residing sentItem folder.
4) Using the same messageId of "abcd123A==", I wanted to get the mimeContent of the message, where its throwing exception with message ItemNotFound in store.

Below is the GET call made to fetch the mimeContent of the message.
GET https://graph.microsoft.com/v1.0/users/{userEmail}/messages/abcd123A==/$value
SdkVersion : graph-java/v3.1.0.

I am observing that, once the mail is been sent, if we try to fetch the collection of message from sentItem folder, the messageid is looks different than what ever messageid received on creating draft.

Kindly help me with the above given scenario, where I need to fetch the message based on the messageId (created during draft).
I feel, its a bad idea to list all the messages and compare with subject/body/attachment and fetch the id.
Kindly suggest me on this.

Thanks & Regards
Sunil Marudappa.
 
[AB#9084](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9084)

**Comment by baywet** [comment]
Hi @sunil-marudappa 
Thanks for reaching out.
Can you provide a reproduction code please?

**Comment by sunil-marudappa** [comment]
Thank you for the response.

After quite research, I have used the SingleValueLegacyExtendedPropertyCollectionPage to set the property id and value and filtering (used the  messages().filter) it out based on the property id and value. I am able to get the message sent using singleValueExtendedProperty id and value. I am using the below code to set the SinglevalueLegacyExtendedProeprty.


SingleValueLegacyExtendedPropertyCollectionResponse response = new SingleValueLegacyExtendedPropertyCollectionResponse();
		SingleValueLegacyExtendedProperty property = new SingleValueLegacyExtendedProperty();
		property.id = "String " + UUID.randomUUID().toString() + " Name " + "UpdateEmailUUID";
		property.value = SINGLE_EXTENDED_PROPERTY_VALUE;
		
		response.value = Arrays.asList(property); 
		SingleValueLegacyExtendedPropertyCollectionPage collectionPage = new SingleValueLegacyExtendedPropertyCollectionPage(response, null);
		message.singleValueExtendedProperties = collectionPage;

I am facing a sonar issue here, that I am setting SingleValueLegacyExtendedPropertyCollectionRequestBuilder as null as shown below, which is a nonNullable object.
SingleValueLegacyExtendedPropertyCollectionPage collectionPage = new SingleValueLegacyExtendedPropertyCollectionPage(response, null);

can you please suggest me, is there any other way to set the singleValueExtendedProperty to my message ? I wanted to get rid of sonar issue.

**Comment by baywet** [comment]
either use `@SuppressWarning("rule")`with the name of the rule right above the line you new up the collectionPage or pass in this as a second parameter `new SingleValueLegacyExtendedPropertyCollectionRequestBuilder("", graphClient, null)`
