### ISSUE TITLE
/users/{id | userPrincipalName}/contactFolders returns no contactfolders

### ISSUE THREAD

**Issue by Fabian95qw** [microsoftgraph/msgraph-sdk-java#732]
Hello i'm currently upgrading my module from using ews for accessing user contacts to microsoft graph.
I'm using the latest version via maven. (3.3.0)

I'm using the ClientSecretCredentials for the Authentication.

The permissions i set are: 
Contacts.Read (https://graph.microsoft.com/Contacts.Read)
Users.Read.All (https://graph.microsoft.com/User.Read.All)

### Expected behavior
https://docs.microsoft.com/en-us/graph/api/user-list-contactfolders?view=graph-rest-1.0&tabs=java

Returns a ContactFolderCollectionPage Containing a List of ContactFolders.

### Actual behavior

When using the GraphServiceClient to access the Contactfolders, it doesn not return an error, but also does not return any contactfolders.

```
ContactFolderCollectionPage CurrentFolderPage = GC.users(TargetUser.id).contactFolders().buildRequest().get();	
log.debug("Count:" + CurrentFolderPage.getCurrentPage().size());
```
The Count of ContactFolders is 0 despite the testuser having 2 ContactFolders.
Using the UPN instead of the id does not make a difference.

So i wanted to check, if i can get the Contacts by directly looking for them.
```
ContactCollectionPage ContactPage = GC.users(TargetUser.id).contacts().buildRequest().get();
log.debug("Count:" + ContactPage.getCurrentPage().size());
```
It returns a count of 10 which isn't really correct, but i might have to get multiple pages to get them all. 

### Steps to reproduce the behavior

This is the Code i'm testing it with:

```
List<String> Scopes = new ArrayList<String>();
Scopes.add(".default");
		
ClientSecretCredential CSC =new ClientSecretCredentialBuilder()
		.clientId(ClientID)
		.clientSecret(ClientSecret)
		.tenantId(TenantID)
		.build();

TokenCredentialAuthProvider TCAP = new TokenCredentialAuthProvider(Scopes, CSC);		
GraphServiceClient<Request> GC = GraphServiceClient.builder().authenticationProvider(TCAP).buildClient();
ContactFolderCollectionPage CurrentFolderPage = GC.users("example@example.com").contactFolders().buildRequest().get();	
log.debug("Count:" + CurrentFolderPage.getCurrentPage().size());
```
 
[AB#9097](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9097)

**Comment by baywet** [comment]
Hi @Fabian95qw 
Thanks for reaching out.
Out of curiosity, do you get different result when [you try on graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=me%2FcontactFolders&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com) (don't forget to login first)

**Comment by Fabian95qw** [comment]
Hello baywet

Using: https://graph.microsoft.com/v1.0/me/contactFolders returns nothing as well.
But i also understood why that is now!
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('[ID]')/contactFolders",
    "value": []
}

/me/contactFolders returns all Subfolders of the default Contact Folder,  But the ContactFolders in my case are on the same level as the Contactsfolder.

So it's like this:

Contacts
TestContacts
Private Contacts

Instead of
Contacts |
              |-> TestContacts
              |-> Private Contacts

So i just misunderstood this Point.
Well now the issue is, how do i list those other Folders.
Because of course List MailboxFolders (https://docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&tabs=java) doesn't return the contactsfolders.

So i either need a way of accessing/filtering trough all folders from the Exchange Root folder, or all customers need to make sure, their contactfolders are defined as subfolders of the default "Contacts" folder.

**Comment by baywet** [comment]
Thanks for sharing this additional information. This repository is dedicated to discussions about the Java SDK itself. This became a question about service capabilities (i.e. what call can I make to get X). Please ask your new question [on the dedicated Microsoft Graph Contacts Microsoft Q&A topic](https://docs.microsoft.com/en-us/answers/questions/topics/single/297616.html) this way your question will get routed to the service team behind the contacts APIs and you'll get a better answer.
