### ISSUE TITLE
Include appRole `value` property in AppRoleAssignment object

### ISSUE THREAD

**Issue by MayurDhande-GSLab** [microsoftgraph/msgraph-sdk-java#743]
Hello
I am trying to get `AppRoleAssignment` for a user present in Azure AD.
I observed that `com.microsoft.graph.models.extension.AppRoleAssignment` does not have role `value` property (which is returned in token claims). There is `appRoleId` property.
To get the `value` I need to make an additional API call to the servicePrincipal where this role resides.

It would be helpful if there is an additional `value` property in `AppRoleAssignment`.

Library and version used:
artifcat-id: microsoft-graph
version: 2.3.2

 
[AB#9319](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9319)

**Comment by baywet** [comment]
Hi @MayurDhande-GSLab ,
Thanks for reaching out.
[The metadata](https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/clean_v10_metadata/cleanMetadataWithDescriptionsv1.0.xml) doesn't indicate the presence of a value field on the approleassignment entity type. What leads you to think there should be a value field?
Also, you should upgrade the SDK to version 3.4.0, version 2.X is not kept up to date anymore with service changes.

**Comment by MayurDhande-GSLab** [comment]
Hi @baywet 

After authentication, our user is authorized based on the role `value` which is returned in JWT token claim. That's why I believe role `value` attribute is one of the most significant property.

Consider a case a where I want to validate if a user has `manager` role assigned in Azure AD, and if I list `AppRoleAssignment` for that user, I get `appRoleId` and `resourceId` (and some other attributes). 

Now, just to know what is the role `value` of this `appRoleId`, I have to make another API call to the servicePrincipal with previously retrieved `resourceId` and filter the `AppRole` object that matches `appRoleId` and retrieve it's `value`. Then system identifies if `manager` role is missing or not. Had the `appRoleValue` be part of `AppRoleAssignment` I can validate there itself and don't have to make additional API call just to see role value for the roleId.

That's why I believe it should be included in `AppRoleAssignment`.

**Comment by baywet** [comment]
@MayurDhande-GSLab thanks for the additional details.
I believe that once you have the app role id as well as the service principal id from the app role assignment, you need to query the [service principal](https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0) to get the app roles collection and iterate over those until you find the matching app role id.
Something like

```Java
graphClient.servicePrincipals("id").appRoles().buildRequest().get();
// find the matching app role in the collection via the app role id provided by the app role assignment
````

**Comment by MayurDhande-GSLab** [comment]
@baywet  Hi Vincent, that is exactly what we are doing. But this is an additional API call.
My point is if we list `AppRoleAssignment` for a user, it would be beneficial to get appRole `value` in the same response, instead of having to make additional API call to service principal just to get the role value.

**Comment by baywet** [comment]
@MayurDhande-GSLab 
Thanks for the additional context. This repository is specifically about issues/questions with the Java SDK. If I understand the value of the request, there's not much I can do about it myself.
You should [request this feature](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph) (or upvote it if it already exists) so the product team considers adding it to this specific API.
Closing.
