### ISSUE TITLE
Problem with Updating a range format in Excel with Microsoft Graph

### ISSUE THREAD

**Issue by samba914** [microsoftgraph/msgraph-sdk-java#744]
Using v3.3.0

Hello, I'm trying to update a range format in Excel-Sheet with Microsoft Graph SDK like the example found on https://docs.microsoft.com/fr-fr/graph/api/rangeformat-update?view=graph-rest-1.0&tabs=java

With the exemple given on the Microsoft documentation, when i run the code below,

```java
IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

WorkbookRangeFill workbookRangeFill = new WorkbookRangeFill();
workbookRangeFill.color = "#00FF00";

graphClient.me().drive().items("{id}").workbook().worksheets("sheet1")
    .range(WorkbookWorksheetRangeParameterSet
        .newBuilder()
        .withAddress("$B$1")
        .build()).format().fill()
    .buildRequest()
    .patch(workbookRangeFill);

```

We should have this result on the cell "B1" (The color green is applied to the cell B1)

![image](https://user-images.githubusercontent.com/45944998/117557754-9d806900-b076-11eb-875a-bb92680626e6.png)

But when i run exactly the same code in my application, the color is applied on the whole worksheet (as the picture below) and i don't know why.

![image](https://user-images.githubusercontent.com/45944998/117557867-f13f8200-b077-11eb-9238-276a8aafdf11.png)

I think this is a bug, but maybe I'm doing something wrong or there's a workaround.

I appreciate any feedback

**Comment by samba914** [comment]
Sorry the problem was with this code
```java
graphClient.me().drive().items("{id}").workbook().worksheets("sheet1")
    .range(WorkbookWorksheetRangeParameterSet
        .newBuilder()
        .withAddress("$B$1")
        .build()).format().fill()
    .buildRequest()
    .patch(workbookRangeFill);
```

So when i run 
```java
graphClient.me().drive().items(fileId).workbook().worksheets("sheet1")
				.range(WorkbookWorksheetRangeParameterSet.newBuilder().withAddress("$B$1").build()).format().fill()
				.buildRequest().getRequestUrl().toString();
```

I get this following url request : 
*https://graph.microsoft.com/v1.0/me/drive/items/F9984BEA49A514E3!106/workbook/worksheets/sheet1/microsoft.graph.range/format/fill*

**Comment by baywet** [comment]
Hi @samba914,
Thanks for the additional details.
This problem is because of the [lack of composable functions support](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/315).
You might want to [try a solution similar to thisvworkaround](https://github.com/microsoftgraph/msgraph-sdk-java/issues/737#issuecomment-829441710)
Closing this issue as we already have multiple issues logged for the same defect.
