### ISSUE TITLE
Non-compatible changes in sharepoint upload API

### ISSUE THREAD

**Issue by JV-TMCZ** [microsoftgraph/msgraph-sdk-java#754]
Hello,
I would like to upload small file to sharepoint folder. I fould sample in [docs](https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=java#example-updating-an-existing-file) 
Unfortunatelly, **provided sample is not syntactically correct - could not be compiled!**
```
GraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

byte[] stream = Base64.getDecoder().decode("The contents of the file goes here.");
	graphClient.me().drive().items("{item-id}")
	.buildRequest()
	.put(_stream_);
```
method `put()` does not accept stream any more.
```
    @Nullable
    public DriveItem put(@Nonnull final DriveItem newDriveItem) throws ClientException {
        return (DriveItem)this.send(HttpMethod.PUT, newDriveItem);
    }
```

Probably, documentation was not updated to reflect latest (v3) changes. This obsolete sample for java sdk is in several different places. 

Please update documentation, add functional sample. Thank you.  
[AB#9414](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9414)

**Comment by baywet** [comment]
Hi @JV-TMCZ ,
Thanks for letting us know!
FYI this sample generation bug is already logged here https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/371

The correct usage is

```Java
GraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

byte[] stream = Base64.getDecoder().decode("The contents of the file goes here.");
	graphClient.me().drive().items("{item-id}")
        .content()
	.buildRequest()
	.put(_stream_);
```

Notice the addition of `.content()`.

Closing.
