### ISSUE TITLE
Save Microsoft GraphAPI OutlookItem response as eml

### ISSUE THREAD

**Issue by abhi-moo** [microsoftgraph/msgraph-sdk-java#758]
### Expected behavior
ItemAttachment does not return contentBytes byte[] data for .msg and .eml file types in the following version.
 ```
   //Microsoft graph API dependencies
compile group: 'com.microsoft.graph', name: 'microsoft-graph', version: '3.0.0'

```
### Actual behavior. 
Data contentBytes byte[] is empty.

### Steps to reproduce the behavior
Attach a .msg to email. Then try to get the byte[] data.

Our scenario: We need to save the .msg attachment into a local drive. 
Unfortunately content bytes is not available for this ItemAttachment response for .msg/.eml file types.

I was able to use the following call and get Mime response.

`https://graph.microsoft.com/v1.0/me/messages/<MessageID>/attachments/<AttachmentId>/$value
`
![image](https://user-images.githubusercontent.com/81188855/118177521-6a343600-b3f8-11eb-8104-976d744d1406.png)

**Question:** How do I save this response to an eml outlook file? I tried renaming the result to .eml/.msg but nothing worked. Any third party libraries are there?

Note I was able to save attachment present inside by converting to bytes.
`byte [] result = Base64.getMimeDecoder().decode(bytes);
`

 
[AB#9469](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9469)

**Comment by baywet** [comment]
Hi @abhi-moo,
Thanks for reaching out. Once you have the raw value, you should be able to parse is to a MimeMessage (using an input stream to feed it to [the constructor](https://docs.oracle.com/javaee/7/api/javax/mail/internet/MimeMessage.html#MimeMessage-javax.mail.Folder-java.io.InputStream-int-))
After that, using the [writeTo](https://docs.oracle.com/javaee/7/api/javax/mail/internet/MimeMessage.html#writeTo-java.io.OutputStream-) method you should be able to save it to an eml file (open standard, msg is outlook specific)

**Comment by abhi-moo** [comment]
Hi @baywet 

Thanks for responding. I 

![image](https://user-images.githubusercontent.com/81188855/118511583-aa94fc00-b6f7-11eb-8542-095eb35863d0.png)

**Comment by abhi-moo** [comment]
@baywet  
Thanks for responding, this is really valuable. I will give this a try with the reponse from GraphAPI. FYI, I'd stored the response in a txt file and tried to parse (Note that my Ultraedit was asking for ASCII format and I choose default)

Looks like content was not decoded and it was unable to open.

![image](https://user-images.githubusercontent.com/81188855/118512502-7968fb80-b6f8-11eb-8721-74c541468b75.png)

**Question:** The following code reads from a text file instead of response now. Do we need to set actual Mailbox properties properties in order to decode?

`        File file = new File("src/main/resources/eml-5-12.txt");
        Path path =  file.toPath();
        byte[] bytes = Files.readAllBytes(path);

        //byte [] result = Base64.getMimeDecoder().decode(bytes);

        Properties properties = System.getProperties();
        Session session = Session.getInstance(properties);

        //Use MimeMessage
        MimeMessage mimeMessage = new MimeMessage(session, new ByteArrayInputStream(bytes));

        //Create a Outputstream
        try (OutputStream outputStream = new FileOutputStream("src/main/resources/result-5-17.eml")) {
            mimeMessage.writeTo(outputStream);
        }`

I will try directly reading the response from GraphAPI and retry and get back to you.

**Comment by baywet** [comment]
I thought this was a single thread but we had a very similar question on #722

**Comment by abhi-moo** [comment]
@baywet 
Yes its very similar but instead of the whole email I'm trying to get .msg attachment contents. (Note: A .msg attached to an email)

Any idea why content() is not applicable to attachments? I tried the following but did not work:
`final InputStream result = graphServiceClient.users(email).messages(mailId).content().attachments(attachment.id).buildRequest().get()
`
Error message: The request URI is not valid. The segment '$value' must be the last segment in the URI because it is one of the following: $ref, $batch, $count, $value, $metadata, a named media resource, an action, a noncomposable function, an action import, a noncomposable function import, an operation with void return type, or an operation import with void return type.


Please let me know if there is another way to call content() on attachment.

Thank you.

**Comment by baywet** [comment]
That's a specific behavior from the API itself, contact, event (ics), and email (msg) attachment are treated as regular Microsoft Graph  contact, event and messages (the API object, not the binary object) allowing you to query them directly using the API and "saving" you from having to download the binary and use some other library.

Unfortunately the attachments collection doesn't support OData Cast last time I checked.

But maybe something like that will work
`GET https://graph.microsoft.com/v1.0/users/id/messages/id/attachments/id/item/$value`

But I can't guarantee it.

**Comment by abhi-moo** [comment]
@baywet 
The following code did not work. 
`GET https://graph.microsoft.com/v1.0/users/id/messages/id/attachments/id/item/$value`

Last couple of questions to you before wrapping up and appreciate your patience in answering :) 

**Question:** 

- How can we save the email (msg) attachment response to eml? The query works fine and returns an OutlookItem type.

- If you or anyone in your team has enough time bandwidth, can you folks please reproduce this issue and save the response to .eml file?

Code used to get OutlookItem .msg data:
`graphServiceClient.users(email).messages(mailId).attachments(attachment.id).buildRequest().expand("microsoft.graph.itemattachment/item").get()`

**Response of OutlookItem:** 
![Uploading image.png…]()

Thank you.

**Comment by baywet** [comment]
Hi @abhi-moo ,
Thanks for the additional information.
This scenario is outside of the scope of the SDK itself and we won't be spending time investigating it on our side.
I believe the only way to save the message as an eml file would be to use the [MimeMessage class](https://docs.oracle.com/javaee/7/api/javax/mail/internet/MimeMessage.html) and map/set each field from the Microsoft Graph Message object.

**Comment by abhi-moo** [comment]
@baywet 
I've discussed this issue at our team and we need this functionality from SDK in the long term. Last question before you can close this - How do I create enhancement request for GraphAPI SDK to provide raw content bytes data for .msg/eml in future releases?

I request you also bring this up at your engineering team and discuss about opening the data for .msg/eml attachments. I see lot of teams using GraphAPI will need this functionality in the long term.

Thank you.

**Comment by baywet** [comment]
For API features requests (like this one as the SDK cannot provide something the API it depends on doesn't provide), you can create  or upvote existing requests [here](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph)

For SDK features request (that are specific to what the SDK does without a dependency on the service), creating issues here is the best thing to do.
Closing.
