### ISSUE TITLE
Upgrade to 3.5.0

### ISSUE THREAD

**Issue by AllenConquest** [microsoftgraph/msgraph-sdk-java#759]
I just bumped my version to 3.5.0 from 3.4.0. I am now getting this compile issue:

### Expected behavior

I would expect a clean compile

### Actual behavior

`error: package com.azure.identity does not exist import com.azure.identity.ClientSecretCredential;
`

I am using this code:

```
      final ClientSecretCredential myClientSecretCredential = new ClientSecretCredentialBuilder()
          .clientId(anApplicationId)
          .clientSecret(aSecret)
          .authorityHost(anAuthority)
          .tenantId(aTenent)
          .build();
```
In fact I am now getting this error:

```
[ERROR] /Users/allenconquest/Developer/pdf-converter/PDFConverter/src/main/java/com/energysys/pdfconverter/GraphServices.java:[19,25] error: package com.azure.identity does not exist
[ERROR] /Users/allenconquest/Developer/pdf-converter/PDFConverter/src/main/java/com/energysys/pdfconverter/GraphServices.java:[20,25] error: package com.azure.identity does not exist
[ERROR] /Users/allenconquest/Developer/pdf-converter/PDFConverter/src/main/java/com/energysys/pdfconverter/GraphServices.java:[225,12] error: cannot find symbol
  symbol:   class ClientSecretCredential
  location: class GraphServices
```
after doing `mvn -U clean install`

 
[AB#9475](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9475)

**Comment by baywet** [comment]
@AllenConquest thanks for reaching out.
Yes we replaced azure identity by azure core in our core library. Thaking a dependency on azure identity to begin with was a mistake as the SDK itself only needs things from azure core.
The only thing you need to do is add azure identity back in your project.
See [this](https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/README.md#12-install-via-maven)

**Comment by AllenConquest** [comment]
Thank you. That solved my problem.
