### ISSUE TITLE
Action parameters are treated as required

### ISSUE THREAD

**Issue by caitlinrussell** [microsoftgraph/msgraph-sdk-java#76]
Currently all action parameters are treated as required. If new parameters are added after the introduction of an action, this would be a breaking change to the SDK. We need to set a default value of null for these parameters and remove the final keyword.
I don't believe we have hit any instances of this yet. We will hit this in the next generation with:

copyNotebook
copyToNotebook
copyToSectionGroup
[AB#6046](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6046)

**Comment by deepak2016** [comment]
Wanted to understand more on this issue. @darrelmiller can you provide more insight into this issue?

**Comment by darrelmiller** [comment]
Due to limitations of OData not supporting Action overloading and Java not supporting Optional parameters we will likely need to change the signature of Actions to accept an argument instead of parameters.  This may be made tolerable in Java using a builder.  e.g. something like

```java
User[sdsd].SendMail(SendMailArgumentBuilder
                       .WithRecipient(...)
                       .WithSubject(...)
                       .Build())
```

**Comment by baywet** [comment]
related https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/261
