### ISSUE TITLE
Graph service exception Error code: ErrorQuotaExceeded with message "Error message: Cannot get ID from name."

### ISSUE THREAD

**Issue by sunil-marudappa** [microsoftgraph/msgraph-sdk-java#764]
Dear Team,

I am creating the draft message using graph-sdk 3.1,0. I am able to get the draftedMessageId.
Using this id, I am trying to update the draft with to, cc, bcc, body, I am trying to call patch request with updated values, I am getting below error which says "Error message: Cannot get ID from name.". I am trying to understand this issue here, kindly help me what is issue here, same error is coming while sending the email after draft creation(with to, cc).

2021-05-17 12:45:23.460 ERROR 43840 --- [ctor-http-nio-3] global                                   : Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: ErrorQuotaExceeded
Error message: Cannot get ID from name.

PATCH https://graph.microsoft.com/v1.0/users/XXXXXXX/messages/AAMkADIzOTk0ZGE0LTM3NDMtNDVmNC1hMDI1LWNhZjhlYTY4NzYyZABGAAAAAADNi3vV7r2rQZhnzEtDpBVbBwBuk9kw84y_Q5iZ3kzrhAWXAAAAAAEPAABuk9kw84y_Q5iZ3kzrhAWXAAAmMbyVAAA=
SdkVersion : graph-java/v3.1.0
[...]

403 : Forbidden
[...] 
[AB#9494](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9494)

**Comment by sunil-marudappa** [comment]
After quite research, i got to know source of issue, I am adding the SingleValueLegacyExtendedProperty to message.
Below is the code, I need to set this property, because using this property id, I am fetching the email after send.
Kindly help me with this issue.

SingleValueLegacyExtendedPropertyCollectionResponse response = new SingleValueLegacyExtendedPropertyCollectionResponse();
		SingleValueLegacyExtendedProperty property = new SingleValueLegacyExtendedProperty();
		property.id = "String " + UUID.randomUUID().toString() + " Name " + "UpdateEmailUUID";
		property.value = SINGLE_EXTENDED_PROPERTY_VALUE;
		
		response.value = Arrays.asList(property); 
		SingleValueLegacyExtendedPropertyCollectionRequestBuilder builder 
				= new SingleValueLegacyExtendedPropertyCollectionRequestBuilder("", graphClient, null);
		SingleValueLegacyExtendedPropertyCollectionPage collectionPage = new SingleValueLegacyExtendedPropertyCollectionPage(response, builder);
		message.singleValueExtendedProperties = collectionPage;

**Comment by baywet** [comment]
Hi @sunil-marudappa 
As your code is working fine with one user and not the other, this seems to be related to the service behavior/user configuration.
Issues here are reserved to discussions about the SDK itself, not the service.
You should probably post [on the dedicated Microsoft Q&A Microsoft Graph Mail topic](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-mail.html) to get eyes of the product team on that issue.
Closing.
