### ISSUE TITLE
The property 'attendees' does not exist on type 'Microsoft.OutlookServices.Event' while create event in hybrid deployment

### ISSUE THREAD

**Issue by genroelgvozo** [microsoftgraph/msgraph-sdk-java#766]
### Expected behavior

Create event
https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=http

### Actual behavior

Give 400 error for post event `graphServiceClient.me().events().buildRequest().post(event)`
```
Error message: The property 'attendees' does not exist on type 'Microsoft.OutlookServices.Event'. Make sure to only use property names that are defined by the type or mark the type as open type. REST APIs for this mailbox are currently in preview. You can find more information about the preview REST APIs at https://dev.outlook.com/.
POST https://graph.microsoft.com/v1.0/me/events
SdkVersion : graph-java/v3.2.0
SdkVersion : graph-java/v3.2.0
[...]
400 : Bad Request
```

I have hybrid deployment of exchange, and give error for local mailboxes. Use microsoft-graph 3.4.0
For online mailboxes api works correct. 

All of requirements in https://docs.microsoft.com/en-us/graph/hybrid-rest-support#requirements-for-the-rest-api-to-work-in-hybrid-deployments are met

get calendar `graphServiceClient.me().calendarView().buildRequest(options).get()` works correct to for all types of mailboxes

Authorization Code Flow is used if it is importannt

 
[AB#9499](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9499)

**Comment by baywet** [comment]
Hi @genroelgvozo ,
Thanks for reaching out.
As your code is working fine with one user and not the other, this seems to be related to the service behavior/user configuration.
Issues here are reserved to discussions about the SDK itself, not the service.
You should probably post [on the dedicated Microsoft Q&A Microsoft Graph Calendar topic](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-calendar.html) to get eyes of the product team on that issue.
Closing.
