### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#77]
The addition of InTune classes has pushed the memory requirement to compile the project with gradle to 10GB (on linux). I'm fortunate to have plenty of RAM on my work desktop but this high requirement will preclude me from using gradle on this project on my laptop for instance (which has 8GB).

These high memory requirements will make contributions from the community more difficult.

Might be time to split the project into multiple projects (in this repo)?

**Comment by cbales** [comment]
Somewhat related to [https://github.com/microsoftgraph/msgraph-sdk-android/issues/71](https://github.com/microsoftgraph/msgraph-sdk-android/issues/71)

**Comment by willalewis** [comment]
I have this issue on OS X also. I had to increase the jvm max memory to 12g in order to build.

**Comment by deepak2016** [comment]
Hi David, we have completed fixing java templates for vipr to automatically generate java files with organised import statements. We would soon refresh SDK and that would eliminate the need to manually perform organise imports.
Eliminating this manual step to organise import would help us later to automate sdk refresh process as well.

**Comment by davidmoten** [comment]
I ask again, what argument is there for holding off on a *one time* use of organize imports in the IDE? It's an incredibly easy thing to do. Delighted for you to work on the generation side of things but it should not prevent this happening now.

**Comment by davidmoten** [comment]
@deepak2016 response please?

**Comment by deepak2016** [comment]
@davidmoten we are planning to refresh SDK as part of current sprint.

**Comment by davidmoten** [comment]
@deepak2016 that sounds ok but this could have been resolved a long time ago. I never got an answer to my direct question of 6 weeks ago (and 2 weeks ago and 5 days ago)! Got one yet?

**Comment by davidmoten** [comment]
@deepak2016 @darrelmiller I'm at a bit of a loss why no answer on my questions on a one-time organize imports. No travis CI build, no-one can build the project with less than 11GB. For me that means I can't build an artifact on my laptop. The worse case is that when your newly generated classes are ready and are merged in to the codebase we get a diff that shows import statements with different orderings. Who cares?
