### ISSUE TITLE
Log requests and responses

### ISSUE THREAD

**Issue by slowcar** [microsoftgraph/msgraph-sdk-java#772]
I would like to log requests and responses to the endpoint (the json sent/received).
I did not find an option to do this, and would like to propose this as a feature request.

 
[AB#9538](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9538)

**Comment by slowcar** [comment]
Found the answer myself.
Using HttpClients.custom() i can call addInterceptor to add a HttpLoggingInterceptor

it's a bit tricky as it requires logging-interceptor as a dependency, which should have the same version as the okhttp3 client used in the graph SDK.
I would prefer if the graph SDK could offer an option for this, and encapsulate the functionality.

**Comment by baywet** [comment]
Hi @slowcar ,
Thanks for reaching out and for the feedback.
This is something we're not making easy by intention: if it were easy, it'd be easier for consumers to roll out that change to production by mistake and start logging information that should not be in the logs.
Closing for now as you seem to have found the solution, but don't hesitate to comment if you have additional comments/questions.
