### ISSUE TITLE
InteractiveBrowserCredentialBuilder using enablePersistentCache

### ISSUE THREAD

**Issue by devManderson** [microsoftgraph/msgraph-sdk-java#773]
### Expected behavior
The InteractiveBrowserCredentialBuilder.java class im SDK v3.2.0 contains the method enablePersistentCache(), the comment above the method says the following:

> Enables the shared token cache which is disabled by default. If enabled, the credential will store tokens in a cache persisted to the machine, protected to the current user, which can be shared by other credentials and processes.
> Returns: An updated instance of this builder with if the shared token cache enabled specified.

This is exactly what I want to do. Storing the token from the login, so the user don't need to login each time the (desktop)  application is startet.

So I would love to use the function from the builder like:

```
        final InteractiveBrowserCredential interactiveBrowserCredential = new InteractiveBrowserCredentialBuilder()
                .clientId(SPValues.CLIENT_ID)
                .redirectUrl("http://localhost")
                .enablePersistentCache()
                .build();
```

### Actual behavior
Can't use the enablePersistentCache() in the builder and I don't find any way around to enable it

### Steps to reproduce the behavior
See code example from "Expected behavior"

 
[AB#9559](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9559)

**Comment by baywet** [comment]
Hi @devManderson 
Thanks for reaching out. The code snippet you shared only contains code from Azure Identity, can you open a new issue [on this repo instead](https://github.com/Azure/azure-sdk-for-java). This way you'll get attention from the developers behind this code.
Thanks! Closing.
