### ISSUE TITLE
Upgrading to 3.6.0 results in an authentication error

### ISSUE THREAD

**Issue by dai-00** [microsoftgraph/msgraph-sdk-java#774]
Upgrading the SDK from `2.10.0` to `3.6.0` by following [this upgrade guide](https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/docs/upgrade-to-v3-auth.md#client-credential-flow) results in an error.

`ERROR ClientSecretCredential: Azure Identity => ERROR in getToken() call for scopes [https://graph.microsoft.com/.default]: Could not initialize class reactor.netty.http.client.HttpClientSecure`

Libraries used
- Microsoft Graph SDK: 3.6.0
- Azure Identity: 1.2.5

### Expected behavior

Successful authentication 

### Actual behavior

Failed authentication

### Steps to reproduce the behavior

[Original version using `2.10.0`]
```
    val provider = new ClientCredentialProvider(
      ClientId,
      Scopes,
      ClientSecret,
      TenantId,
      NationalCloud.Global
    )
    GraphServiceClient.builder().authenticationProvider(provider).buildClient()
```

[New version using `3.6.0`]
```
    val clientSecretCredential = new ClientSecretCredentialBuilder()
      .clientId(ClientId)
      .clientSecret(ClientSecret)
      .tenantId(TenantId)
      .build();
    val authProvider = new TokenCredentialAuthProvider(clientSecretCredential)
    GraphServiceClient.builder().authenticationProvider(authProvider).buildClient()
```

Authentication succeeds with the original version, but not with the new version.

 
[AB#9569](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9569)

**Comment by baywet** [comment]
Hi @dai-00 ,
Thanks for reaching out.
DO you get the same error if you call `authProvider.getAuthorizationTokenAsync(new URI("https://graph.microsoft.com/")).get()` before you build the client?

**Comment by dai-00** [comment]
Yes, I got the same error.

` java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class reactor.netty.http.client.HttpClientSecure`

It looks like some dependency issue that does not occur in the previous version(`2.10.0`)

Probably related to [this](https://github.com/Azure/azure-sdk-for-java/issues/19041)?

**Comment by dai-00** [comment]
Adding an explicit dependency on [Netty](https://mvnrepository.com/artifact/io.netty/netty-all) did solve the issue, though this causes JVM(openjdk8) to crash(SIGSEGV) for some reason.
(workaround was to replace it with oraclejdk8)

The crash should have nothing to do with this library, so I close this issue.

**Comment by baywet** [comment]
thanks for confirming and providing a solution for others!
