### ISSUE TITLE
Authentication Provider creation

### ISSUE THREAD

**Issue by gaut7** [microsoftgraph/msgraph-sdk-java#791]
### Expected behavior
I want to create GraphServiceClient object using Authprovider. As per my flow i have access token and refresh token persist in my local database and i want to use that for creating Authprovider object.  

### Actual behavior
Right now i can see few option to create Authprovider object like by passing "username and password" or  authenticate user through UI and that will give us Authprovider object but in my case i can't ask user always to authenticate him/her self through UI. Basically i want some work around using access token and refresh token which we have in our system against that user.

### Steps to reproduce the behavior

 
[AB#9771](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9771)

**Comment by baywet** [comment]
Hi @gaut7 
Thanks for reaching out.
Azure identity leverages MSAL for Java under the covers which [allows you to persist the token cache](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-java-token-cache-serialization).
(by default it's in memory)

Using the token cache, MSAL automatically renews access tokens using refresh tokens when necessary avoiding to prompt the user for authentication. The behavior will also depend on policies that the domain administrator set.

This behavior should work with any of the token credential (any of the authentication scenario).

If you have further questions on how to set the token cache for the token credential object, I suggest you reach out to the [azure java sdk repo](https://github.com/Azure/azure-sdk-for-java/) which contains the code for azure identity. You'll get more specific answers there.

Closing for now.
