### ISSUE TITLE
How to get authenticationProvider with new azure-sdk-for-java OAuth2AuthorizedClient

### ISSUE THREAD

**Issue by mattstrain** [microsoftgraph/msgraph-sdk-java#793]
With the azure-sdk-for-java you can now obtain authorisation tokens for clients and on behalf of users as part of the API like this.

```
public String callGraph(@RegisteredOAuth2AuthorizedClient("graph") OAuth2AuthorizedClient graph) {
  
if (null != graph) {
            String body = webClient
                .get()
                .uri(GRAPH_ME_ENDPOINT)
                .attributes(oauth2AuthorizedClient(graph))
                .retrieve()
                .bodyToMono(String.class)
                .block();
            LOGGER.info("Response from Graph: {}", body);
            return "Graph response " + (null != body ? "success." : "failed.");
        } else {
            return "Graph response failed.";
        }
}
```
However all the samples there don't use this API and just call the api directly using a webclient. See [azure-spring-boot-sample-active-directory-resource-server-obo](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-resource-server-obo/src/main/java/com/azure/spring/sample/aad/controller/SampleController.java)

How do we build a GraphService client using this API from a OAuth2AuthorizedClient object? 
[AB#9805](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9805)

**Comment by baywet** [comment]
Hey @mattstrain ,
Thanks for reaching out. Right now OBO is not supported by azure identity java and we have an issue tracking this [here](https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/132).

The workarounds include using MSAL or relying on frameworks/libraries (like spring) to "trade" the token for your application. Once this is done, you can derive from [BaseAuthenticationProvider](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/dev/src/main/java/com/microsoft/graph/authentication/BaseAuthenticationProvider.java) to pass the new token to the graph client.
Let me know if you have further questions.

**Comment by mattstrain** [comment]
Great thanks for the update. I'll keep an eye on that issue for updates.
