### ISSUE TITLE
Customize GraphServiceClient builder is not setting AUTHORIZATION properly

### ISSUE THREAD

**Issue by liwangatli** [microsoftgraph/msgraph-sdk-java#794]
### Sample code

**Create a customized OkHttpClient instance**

    OkHttpClient httpClient = new OkHttpClient.custom()
        .sslSocketFactory(...) // we need set sslSocket, you can ignore this
        .proxy(...) // we need set proxy, you can ignore this
        .build();

**My auth provider**

    public class GraphServiceAuthenticator extends BaseAuthenticationProvider {

      private final String _oauthToken; // graph api oauth token

      public GraphServiceAuthenticator(String oauthToken) {
        _oauthToken = oauthToken;
      }

      @Nonnull
      @Override
      public CompletableFuture<String> getAuthorizationTokenAsync(@Nonnull URL requestUrl) {
        return CompletableFuture.completedFuture(_oauthToken);
      }
    }

**create a GraphServiceClient instance**

    IAuthenticationProvider authProvider = new GraphServiceAuthenticator("OAUTH_TOKEN_STRING");
    GraphServiceClient<Request> graphServiceClient =
        GraphServiceClient.builder()
            .httpClient(_httpClient) //customized OkHttpClient
            .authenticationProvider(authProvider)
            .buildClient();

### Expected behavior
_graphServiceClient_ should have "Authorization" in the request headers

### Actual behavior
_graphServiceClient_ does not have "Authorization" in the request headers

### Steps to reproduce the behavior
create _BaseAuthenticationProvider_ and  _GraphServiceClient_ instances as I mentioned above. Request will fail with error  “Access token is empty.”

 
[AB#9820](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9820)

**Comment by baywet** [comment]
Hi @liwangatli,
Thanks for reaching out.
Can you also share how you get the `_httpClient` please?
Thanks!

**Comment by liwangatli** [comment]
> Hi @liwangatli,
> Thanks for reaching out.
> Can you also share how you get the `_httpClient` please?
> Thanks!

**Comment by liwangatli** [comment]
> > Hi @liwangatli,
> > Thanks for reaching out.
> > Can you also share how you get the `_httpClient` please?
> > Thanks!

I updated the description

**Comment by baywet** [comment]
Closing as the author is a Microsoft employee and confirmed internally this part is now working.
