### ISSUE TITLE
buildRequest varargs overload

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#8]
This is a very common pattern in the generated code:
public interface IBaseMessageCollectionRequestBuilder extends IRequestBuilder {

    IMessageCollectionRequest buildRequest();

    IMessageCollectionRequest buildRequest(final java.util.List<Option> requestOptions);

   ...
Firstly the final keyword doesn't do anything and can be chucked.
Secondly, a varargs overload would make life easier for the client:
  IMessageCollectionRequest buildRequest(Option... requestOptions);
Without the varargs overload I have to do this (using guava dependency as well):
.buildRequest(Lists.newArrayList(new QueryOption("filter", "isRead eq false")));
I would like to do:
.buildRequest(new QueryOption("filter", "isRead eq false"));
[AB#6039](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6039)

**Comment by baywet** [comment]
Hi @davidmoten 
Thanks for your feedback and for your patience on the matter.
I've just authored #477 which adds that feature.
The PR will close this issue once it gets merged.

**Comment by baywet** [comment]
BTW in the same version (2.2.0) we're also adding a fluent method for filter. This way you will be able to add the filter query without having to create all these objects manually.
