### ISSUE TITLE
CheckMemberObject is retuning empty values

### ISSUE THREAD

**Issue by ivanmaria** [microsoftgraph/msgraph-sdk-java#806]
I am trying to use checkMemberObject endpoint via msgraph-sdk-java v3.9.0. However, it is returning empty values instead of returning the list of ids. It works well via Postman.

I tried debugging and found that the response of checkMemberObject indeed contains list of ids but it is not being deserialized correctly.

### Expected behavior
checkMemberObject output should produce list of ids.

### Actual behavior
checkMemberObject output returns empty list.

### Steps to reproduce the behavior

Refer the following snippet to reproduce the issue

```
graphServiceClient
.users("<id>")
.checkMemberObjects(DirectoryObjectCheckMemberObjectsParameterSet
    .newBuilder()
    .withIds(<list_of_ids>)
    .build())
.buildRequest()
.post();
.
.
.
// Verify the DirectoryObjectCheckMemberObjectsCollectionPage output
```

 
[AB#9932](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9932)

**Comment by baywet** [comment]
Hey @ivanmaria 
Thanks for reaching out.
If you run the following code, what result do you get?
```Java
final String result = new DefaultSerializer(new DefaultLogger()).serializeObject(DirectoryObjectCheckMemberObjectsParameterSet
    .newBuilder()
    .withIds(<list_of_ids>)
    .build())
```

Also what version of the core library do you have?

**Comment by ivanmaria** [comment]
Hi @baywet 

I am currently AFK so I wont be able to provide you the output immediately. However, this time the issue is while deserializing the response.

**Comment by baywet** [comment]
Thanks for the additional details. Core should be either 2.0.4 [as required by the package](https://mvnrepository.com/artifact/com.microsoft.graph/microsoft-graph/3.9.0) or 2.0.6 as latest. Please update core as it [contains a bug fixed with 2.0.6](https://github.com/microsoftgraph/msgraph-sdk-java-core/releases/tag/2.0.6).

**Comment by ivanmaria** [comment]
Hi @baywet,

```
final String result = new DefaultSerializer(new DefaultLogger()).serializeObject(DirectoryObjectCheckMemberObjectsParameterSet
    .newBuilder()
    .withIds(<list_of_ids>)
    .build())
```
On running the above code, I get the following response:
`{"ids":["2b530f8a-8520-48a1-a5ed-20eba6baabe8"]}`

As I said earlier the issue is not with the Request but it is due to the deserialization of Response. 

---

I checked the core library version and it was 2.0.4. However, according to these [release notes](https://github.com/microsoftgraph/msgraph-sdk-java/releases/tag/3.9.0) the version should have been 2.0.5. Am I missing something here?

Anyway, I tried with the 2.0.6 version as well and the issue still persists. Could you look into it?

Thanks

**Comment by baywet** [comment]
Hey @ivanmaria,
Thanks for the additional details.
We had to revert that change to avoid a spillover of the bug I was mentioning, but apparently the release notes didn't follow. Just edited the notes. Thanks.

After investigating this issue, I discovered an unhandled case in the deserializer and a defect in the code generator.
I've authored 4 PRs to fix this issue overall.

**Comment by ivanmaria** [comment]
Hi @baywet,
Thanks for fixing it. By when can we expect the release? As I see the [3.10.0 milestone](https://github.com/microsoftgraph/msgraph-sdk-java/milestone/26) is past due by 4 days.

**Comment by baywet** [comment]
We hit a roadblock because of some metadata changes as you can see in #814.
However just upgrading the core library to 2.0.8 should address your issue.
