### ISSUE TITLE
toRecipients list is wrong for Non Delivery Reports

### ISSUE THREAD

**Issue by NataliaDobryaeva** [microsoftgraph/msgraph-sdk-java#807]
### Expected behavior

toRecipients list of NDR message contains the email address of the recipient

### Actual behavior

toRecipients list of the NDR message contains email addresses of the recipients that failed. 

### Steps to reproduce the behavior

User with email address "user@test.com" sends email to an invalid (non-existing) email address "aaa@test.com". Then user recieves a Non Delivery Notification. Outlook 365 web client displays NDN correctly and "TO" field contains email "user@test.com". But MS Graph SDK Message object contains toRecipients list with "aaa@test.com" inside instead of the real recipient of this NDN message - "user@test.com". 

 
[AB#9940](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9940)

**Comment by baywet** [comment]
Hi @NataliaDobryaeva,
This seems like a service issue. This repository is dedicated to issues about the java SDK itself.
I suggest you either [contact support](https://developer.microsoft.com/en-us/graph/support), or post on Microsoft Q&A (see the previous link), or create an issue by [using the feedback section from the documentation page](https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-1.0&tabs=http#feedback).
Closing.
