### ISSUE TITLE
Function option 'token' being appended to Drive Delta next link

### ISSUE THREAD

**Issue by willalewis** [microsoftgraph/msgraph-sdk-java#81]
### Expected behavior

The following code should return the next drive delta page:
`
IDriveItemDeltaCollectionPage currentPage = graphClient.drives(driveId).root().delta(deltaLink).buildRequest().get();
currentPage.getNextPage().buildRequest().get();
`

### Actual behavior

Request sent looks like:
`
GET https://graph.microsoft.com/beta/drives('{drive-id}')/root/microsoft.graph.delta(token='MzslMjMzOyUyMzE7MzszZjdjNWVhOC0zMmI1LTQ0OGUtOWI0MC1iN2RjMzVjMGQyYjM7NjM2NTgwMzA0MTI5MjMwMDAwOzkxMzA2MDI2OyUyM1BhZ2VkPVRSVUUlMjZwX0lEPTI0MTk7JTIzOyUyMzQ')(token=null)
`
Which results in this response:
`
400 : Bad Request
HTTP/1.1 400 Bad Request
Transfer-Encoding : chunked
Strict-Transport-Security : max-age=31536000
Cache-Control : private
x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"West US","Slice":"SliceA","Ring":"5","ScaleUnit":"002","Host":"AGSFE_IN_29","ADSiteName":"WST"}}
client-request-id : 9c1d8be2-1c3d-4b3d-9d53-8c26afca7686
Duration : 2.3244
request-id : 9c1d8be2-1c3d-4b3d-9d53-8c26afca7686
Date : Thu, 29 Mar 2018 22:25:40 GMT
Content-Type : application/json
{
  "error": {
    "code": "BadRequest",
    "message": "Syntax error at position 160 in \u0027token\u003d\u0027MzslMjMzOyUyMzE7Mzs5ZmY3MzExYy0yYzRmLTQwZGMtYmVjNS0zMWI3NDJlNTI5YTE7NjM2NTc5NTg5ODA4ODAwMDAwOzkxMjY5NjYzOyUyM1BhZ2VkPVRSVUUlMjZwX0lEPTI1NTg7JTIzOyUyMzQ\u0027)(token\u003dnull\u0027.",
    "innerError": {
      "request-id": "9c1d8be2-1c3d-4b3d-9d53-8c26afca7686",
      "date": "2018-03-29T22:25:40"
    }
  }
}
`

### Cause

BaseDriveItemDeltaCollectionRequestBuilder is always applying the "token" function option, even when the request URL already contains one.

**Comment by dadheech115** [comment]
@willalewis , Thanks for reporting this issue.
This issue is now fixed in the [Code Generator](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator). You will be able to get the fix once we release the new version of the Java SDK
