### ISSUE TITLE
Unknown internal server error while trying to remove a participant from the Call

### ISSUE THREAD

**Issue by MaksimR-AVISPL** [microsoftgraph/msgraph-sdk-java#816]
Trying to remove call participant using method described here https://docs.microsoft.com/en-us/graph/api/participant-delete?view=graph-rest-1.0&tabs=java 

It's been working fine for CVI licensed accounts, but produces the following error for a Development account 

error -> {JsonObject@7934} "{"code":"9999","message":"Unknown internal server error.","innerError":{"date":"2021-07-01T14:26:18","request-id":"de149e4c-e316-4682-a539-0ccdac07c86f","client-request-id":"a15f1853-9973-420b-9c5c-1c6cc1080451"}}"

Wonder if Im doing anything wrong here. "AllowRemoveParticipantAppIds" permission is granted.

Thanks!  
[AB#10105](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10105)

**Comment by baywet** [comment]
Hey @MaksimR-AVISPL ,
Thanks for reaching out.
This sounds like a service side issue. Are you getting the same error using the Microsoft Graph explorer?

**Comment by MaksimR-AVISPL** [comment]
Hi @baywet 
Thanks for your response! 
Well, I haven't managed to run it with graph explorer, but running with postman results with the very same error. 
Just wonder if there's any way to know the reason for it and if it's possible to make it work (developer account is used for the failing scenarios, but everything else there works just fine. Also it works fine for a CVI licensed corporate account, along with the participants removal)

**Comment by baywet** [comment]
@MaksimR-AVISPL 
Thanks for the additional information. As you're running into the same issue with postman, this confirms this looks like a service issue.
This repo is dedicated to issues about the SDK itself, and I'm going to go ahead and close the issue.
You can either:
- use the "feedback" section in the documentation page of the API call that's failing for you, and use this to create an issue in the docs repo which will get routed to the right service team.
- contact the [support](https://developer.microsoft.com/en-us/graph/support)
- ask your question [on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/topics/single/128334.html)
