### ISSUE TITLE
Patching ranges not available

### ISSUE THREAD

**Issue by cghislai** [microsoftgraph/msgraph-sdk-java#824]
Patching a range is not available using the request builder api.

According to the documentation, i should be able to

1) update a range data (https://docs.microsoft.com/en-us/graph/api/range-update?view=graph-rest-1.0&tabs=http)
2) create a table over that range (https://docs.microsoft.com/en-us/graph/api/tablecollection-add?view=graph-rest-1.0&tabs=http)

However, I don't see how to perform step 1 with this sdk. Adding rows to a new table prevents me to pass the header row.

I managed to work around by using the http provider directly, but this seems like a workaround.

```
        WorkbookWorksheetRangeRequest rangeRequest = getDriveRequestBuilder()
                .items(indexedWorkbookIdValue)
                .workbook()
                .worksheets(workbookWorksheet.id)
                .range(worksheetRangeParameterSet)
                .buildRequest(worksheetRangeParameterSet.getFunctionOptions());
        rangeRequest.addHeader(OfficeConstants.HEADER_WORKBOOK_SESSION_ID, sessionInfo.id);

        JsonArray rowsArray = parseJsonDoubleArray(tableData);
        JsonObject jsonObject = new JsonObject();
        jsonObject.add("values", rowsArray);
        IHttpRequest nativeRequest = rangeRequest.withHttpMethod(HttpMethod.PATCH);
        rangeRequest.getClient().getHttpProvider()
                .send(nativeRequest, Void.class, jsonObject);
```

Also note that passing the parameters to the `.range()` method does not seem to work, while passing the function options in the `buildRequest()` method seems to work. I noticed that for other requests as well.

 
[AB#10262](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10262)

**Comment by baywet** [comment]
Hey @cghislai 
Thanks for reaching out.
This is due to issues on the service and with the metadata.
We've already captured two issues for it (links below), you might want to check in the first issue for workaround.
https://github.com/microsoftgraph/msgraph-sdk-serviceissues/issues/108
https://github.com/microsoftgraph/msgraph-sdk-serviceissues/issues/72

Closing as there's not much we can do in the SDK at this point.

**Comment by cghislai** [comment]
Thanks for your feedback. Glad to know the service metadata issue is already tracked.

Im not sure I understand the workaround you suggest though. The issue you linked appears to be about path names / graph function names, which are not always accepted when fully namespeced.
This issue is just about the PATCH method not available for that endpoint. Documentation and graph explorer contains snippets for javascript, but not for other languages.

Regards,

**Comment by baywet** [comment]
yes, sorry. What I meant to express was that:
- Your workaround seems correct for the time being.
- Should you use an OData method (function/action) after the range, like chart for instance, the SDK calls them using the full name (prefixed with Microsoft.Graph), which is valid from an OData conventions perspective. But the service doesn't understand it, you'll need to use the method short name (hence the workaround in the first issue I pointed at).

**Comment by cghislai** [comment]
ok, thanks for the clarification :)
