### ISSUE TITLE
add a worfklow for pkgdiff generation

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-java#828]
related #827 

Each week this SDK is generated from the latest metadata changes.
We've previously on a custom diff generation relying on a text file to tell us what were the differences (less text to parse than the source code), but the SDK has outgrown this approach and this generates a lot of noise in the CI.

Using GitHub actions we want a new workflow that:
- [ ] builds the SDK on the current branch
- [ ] copies the jar somewhere for later use
- [ ] switches to the dev branch
- [ ] builds the SDK
- [ ] compares the JAR using pkgdiff (`pkgdiff -hide-unchanged old.jar new.jar`)
- [ ] attaches the resulting output folder as an artifact of the workflow run

> Note: this workflow should probably reuse the existing trigger conditions from the type summary workflow (see linked PR)

> Note: excluding gradle tasks (-x javadoc) in the gradle build commands will save significant time. The unit tests and javadoc tasks are good candidates.

> Note: once the workflow is finalized, duplicate it on the beta repo 
[AB#10296](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10296)

**Comment by ramsessanchez** [comment]
To avoid building twice, since we've recently added the build workflows here on GH, would it be simpler to compare the jar of the CI build task with that of the last previous successful deployment?
