### ISSUE TITLE
Microsoft Graph: Team owner not found for group

### ISSUE THREAD

**Issue by nhicolas7** [microsoftgraph/msgraph-sdk-java#835]
I have a project in Java. When I run the project I got a error:
Error message: Team owner not found for group

```Java
		final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
				.clientId("1111")
				.clientSecret("222")
				.tenantId("333")
				.build();
		List<String> scope = new ArrayList<>();
		scope.add("https://graph.microsoft.com/.default");
		final TokenCredentialAuthProvider tokenCredentialAuthProvider = new TokenCredentialAuthProvider( scope, clientSecretCredential);
		final GraphServiceClient graphClient =
				GraphServiceClient
						.builder()
						.authenticationProvider(tokenCredentialAuthProvider)
						.buildClient();
		GroupCollectionPage groupCollectionPage = graphClient.groups()
				.buildRequest()
				.get();

		//Primera parte creacion del grupo
		Group group = new Group();
		group.description = "Group with designated owner and members207";
		group.displayName = "Operations group207";
		LinkedList<String> groupTypesList = new LinkedList<String>();
		groupTypesList.add("Unified");
		group.groupTypes = groupTypesList;
		group.mailEnabled = false;
		group.mailNickname = "operations207";
		group.securityEnabled = true;
		
		group.additionalDataManager().put("\"owners@odata.bind\"", new JsonPrimitive("[  \"https://graph.microsoft.com/v1.0/directoryObjects/77777\"]"));
		
		String sIdGrupo = graphClient.groups()
				.buildRequest()
				.post(group).id;
		try {
			sleep(30000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		Team team = new Team();
      TeamMemberSettings memberSettings = new TeamMemberSettings();
      memberSettings.allowCreateUpdateChannels = true;
      team.memberSettings = memberSettings;
      TeamMessagingSettings messagingSettings = new TeamMessagingSettings();
      messagingSettings.allowUserEditMessages = true;
      messagingSettings.allowUserDeleteMessages = true;
      team.messagingSettings = messagingSettings;
      TeamFunSettings funSettings = new TeamFunSettings();
      funSettings.allowGiphy = true;
      funSettings.giphyContentRating = GiphyRatingType.STRICT;
      team.funSettings = funSettings;
      graphClient.groups(sIdGrupo).team()
            .buildRequest()
            .put(team);)
```

**Comment by baywet** [comment]
Hi @nhicolas7 
Thanks for reaching out.
The group needs to have owners setup before it can be promoted at a team.
Please have a look at [add group owners](https://docs.microsoft.com/en-us/graph/api/group-post-owners?view=graph-rest-1.0&tabs=http), update your code snippet and let us know whether you're still experiencing issues.

**Comment by nhicolas7** [comment]
Good morning, thanks for the answer, but I add a owner in the code (down lines), but it doesn´t work, too I have read the documentacion for create a owner for a team but It doesn't work.

group.additionalDataManager().put("\"owners@odata.bind\"", new JsonPrimitive("[  \"https://graph.microsoft.com/v1.0/directoryObjects/77777\"]"));
but the

**Comment by baywet** [comment]
Hey @nhicolas7 
Thanks for the additional information.
Would you mind trying this instead?

```Java
final JsonArray array = new JsonArray();
array.add("https://graph.microsoft.com/v1.0/directoryObjects/77777");
group.additionalDataManager().put("owners@odata.bind", array);
```

**Comment by nhicolas7** [comment]
Thanks  @baywet , for the answer, but I get this error: 

`Error message: Resource '77777' does not exist or one of its queried reference-property objects are not present.

POST https://graph.microsoft.com/v1.0/groups
SdkVersion : graph-java/v4.1.0
SdkVersion : graph-java/v4.1.0
[...]

404 : Not Found
[...]`

**Comment by baywet** [comment]
you are replacing ' 7777'  by the group id (guid) when testing right?

**Comment by nhicolas7** [comment]
Hi @baywet , about your question: Yes  I am using the guid .
1) I login in with my user and password, in this page https://developer.microsoft.com/en-us/graph/graph-explorer.
2) I run the end point of "GET my profile"
3) After that, I get the id in the response and use it.

**Comment by baywet** [comment]
Hi @nhicolas7 
Can you try with ` users` instead of `directoryObjects` in the URL please?

**Comment by nhicolas7** [comment]
I have made two test :

a) First test with your code, changing the url:

    final JsonArray array = new JsonArray();
    array.add("https://graph.microsoft.com/v1.0/users/7777777");
    group.additionalDataManager().put("owners@odata.bind", array);
    
    Response: 
    Error message: Resource '7777777' does not exist or one of its queried reference-property objects are not present.
    
    POST https://graph.microsoft.com/v1.0/groups
    SdkVersion : graph-java/v4.1.0
    SdkVersion : graph-java/v4.1.0
    [...]
    
    404 : Not Found
    [...]

b) Second, with mi code , changing the url:	

    group.additionalDataManager().put("\"owners@odata.bind\"", new JsonPrimitive("[ \"https://graph.microsoft.com/v1.0/users/7777777\"]"));
    String idGroup = graphClient.groups().buildRequest().post(group).id;
    
    Response:
    Error message: Team owner not found for group 7777777
    
    PUT https://graph.microsoft.com/v1.0/groups/7777777/team
    SdkVersion : graph-java/v4.1.0
    [...]
    
    400 : Bad Request
    [...]

**Comment by baywet** [comment]
Hi @nhicolas7 
I've just ran the following unit test which successfully created a group with the rightful owner.

```Java
public void createGroupWithOwner() {
        Group group = new Group();
        group.displayName = "Group Test 2";
        group.mailEnabled = false;
        group.mailNickname = "grouptest2";
        group.securityEnabled = true;
        final User owner = graphServiceClient.me().buildRequest().get();
        final JsonArray array = new JsonArray();
        array.add("https://graph.microsoft.com/v1.0/users/" + owner.id); // or any user id
        group.additionalDataManager().put("owners@odata.bind", array);
        final Group created = graphServiceClient.groups()
                                        .buildRequest()
                                        .post(group);
        assertNotNull(created);
        assertNotNull(created.id);
    }
```

Please update your code to reflect this. After that, if you're still experiencing issues, it might be because of something on the service side as I've demonstrated the SDK works properly for this use.

**Comment by nicolass7** [comment]
ThanKs @baywet , for the reply, I update my code, but  I get this error, when i  use my GUI:
Error message: Resource 'XXXXXXXX-XXXX-XXXX-XXX-XXXXXXXXXXXX' does not exist or one of its queried reference-property objects are not present.

POST https://graph.microsoft.com/v1.0/groups
SdkVersion : graph-java/v4.1.0
SdkVersion : graph-java/v4.1.0
[...]

404 : Not Found
[...]

**Comment by baywet** [comment]
are you able to query the user itself? `client.users('id').buildRequest().get()` ?

**Comment by nicolass7** [comment]
About your question, I don´t able to get an answer right.

    final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
		    .clientId("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
		    .clientSecret("yyyy")
		    .tenantId("zzzzz")
		    .build();
    List scope = new ArrayList<>();
    scope.add("https://graph.microsoft.com/.default");
    final TokenCredentialAuthProvider tokenCredentialAuthProvider = new TokenCredentialAuthProvider( scope, clientSecretCredential);
    
    final GraphServiceClient graphClient =
		    GraphServiceClient
				    .builder()
				    .authenticationProvider(tokenCredentialAuthProvider)
				    .buildClient();    
    User user  = graphClient.users("XXXXXXXX-XXXX-XXXX-XXX-XXXXXXXXXXXX").buildRequest().get();
    log.info(">>idUser"+user.id);
	
I got this error:	
		
    Error message: Resource 'XXXXXXXX-XXXX-XXXX-XXX-XXXXXXXXXXXX' does not exist or one of its queried reference-property objects are not present.
    
    GET https://graph.microsoft.com/v1.0/users/XXXXXXXX-XXXX-XXXX-XXX-XXXXXXXXXXXX
    SdkVersion : graph-java/v4.1.0
    
    
    404 : Not Found
    [...]

**Comment by baywet** [comment]
It looks like you're trying to query a user who's outside of the tenant your application is authenticated for.
This repository is dedicated to the java SDK itself, not to questions/issues encountered on the service side.
I'm going to go ahead and close this issue and suggest you [post on the Microsoft Graph Identity Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-identity.html) instead so you get help from the service team.
Also, before you post there, you should make sure the app the tenant id your app uses matches the tenant Id of the user you are trying to target.

**Comment by nicolass7** [comment]
Ok, Thanks @baywet.
