### ISSUE TITLE
Allow to shutdown the default backgroundExecutor

### ISSUE THREAD

**Issue by J0s3f** [microsoftgraph/msgraph-sdk-java#84]
The default backgroundExecutor keeps running for about a minute after the last task until it is shut down by the JVM.

It would be good to have the option to shut it down programatically.

### Expected behavior

After all requests are handled the program quits if the main thread has ended.

### Actual behavior

Program keeps running for about a minute.

### Steps to reproduce the behavior

Just run the basic example given in the readme in a single main method.

### Possilble solution
Add a option to call shutdown() of the thread pool. The following works with reflection and gives the expected result. Obviously, a solution without reflection is needed.
```java
        //get background executor and shutdown:
        DefaultExecutors ex = (DefaultExecutors)graphClient.getExecutors();
        Field pool = ex.getClass().getDeclaredField("backgroundExecutor");
        pool.setAccessible(true);
        ThreadPoolExecutor executor = (ThreadPoolExecutor)pool.get(ex);
        System.out.println("Shutting down");
        executor.shutdown();
```
The most important part is to decide how the API/Interface should look. Implementing it should be trivial-

**Comment by MIchaelMainer** [comment]
Thank you for reporting this.
753763

**Comment by deepak2016** [comment]
This issue got fixed with PR# https://github.com/microsoftgraph/msgraph-sdk-java/pull/102
