### ISSUE TITLE
[Feature] Role Inheritance and permission management

### ISSUE THREAD

**Issue by Jatish-Khanna** [microsoftgraph/msgraph-sdk-java#861]
A new feature in the Graph SDK that supports (BreakRoleInheritance)[https://collab365.com/sharepoint-item-permissions-using-flow-part-1/]

### Steps to reproduce the behavior

 
[AB#10811](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10811)

**Comment by baywet** [comment]
Hi @Jatish-Khanna 
Thanks for reaching out.
This repo is dedicated to the SDK itself, which is generated from service metadata.
You are requesting a feature that needs to be made available in the service first before it can show up in the SDK.
I'm going to go ahead and close this issue, as well as suggest [you create a feature request on the dedicated platform](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph).
