### ISSUE TITLE
SDK lower than 26 support

### ISSUE THREAD

**Issue by ed-mauro** [microsoftgraph/msgraph-sdk-java#866]
### Expected behavior

Readme says that Desugar may be used to enabled the usage of the package with SDK lower than 26 (item 7).

### Actual behavior

Does not work since Google documentation states that: Desugar currently doesn't support MethodHandle.invoke or MethodHandle.invokeExact

### Steps to reproduce the behavior

Compile a test app for SDK 24. It won't compile, even with Desugar enabled.

 
[AB#10841](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10841)

**Comment by baywet** [comment]
Hi @ed-mauro 
Thanks for reaching out.
We're aware some limitations currently exist for API level < 26.
There's a [ongoing thread on the core library](https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/252) which I invite you to leave your feedback on. We're evaluating what to do for the Android development story.
Closing.
