### ISSUE TITLE
Group member and User memberOf fields are always null

### ISSUE THREAD

**Issue by hadarcarmely** [microsoftgraph/msgraph-sdk-java#87]
When getting a user using the sdk, the memberOf field is always null even though the user is a member of multiple groups:
**Steps to reproduce the behavior** (replace the "USER_NAME"):

    IUserRequest requestContacts = graphClient
                .users("USER_NAME")
                .buildRequest();
    requestContacts.get(new ICallback<User>() {
            public void success(final User result) {
                System.out.println("Found " + result.memberOf);
            }
            public void failure(final ClientException ex) {
                System.out.println("Failure function exception: " + ex);
            }

The "result" object contains a "memberOf" field that is always null.

The same problem occurs when getting a group using the sdk, the members field is always null even though the group has multiple users.
**Steps to reproduce the behavior** (replace the "GROUP_ID"):

    IGroupRequest requestContacts = graphClient
                .groups("GROUP_ID")
                .buildRequest();
    requestContacts.get(new ICallback<Group>() {
            public void success(final Group result) {
                System.out.println("Found " + result.members);
            }
            public void failure(final ClientException ex) {
                System.out.println("Failure function exception: " + ex);
            }

The "result" object contains a "members" field that is always null.

**Expected behavior.**
I tried getting the user memberOf field and the group members field using a custom request and the data was correct.
Example (replace "USER_NAME"):

    JsonObject response = graphClient
                .customRequest("/"USER_NAME"/memberOf")
                .buildRequest()
                .get();

memberOf documentation: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_list_memberof
If a user is part of a office 365 mailing group, I expect to get the list of mailing groups.

Groups documentation: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/group_list_members
If a group contains users, I expect to get the list of user emails.

**Actual behavior** 
Both fields are always null.

**Comment by hadarcarmely** [comment]
Thank you for the fast replay!

**Comment by hadarcarmely** [comment]
Hi,
Thank you for the fast replay.
I have another question. I would like to extract the following fields as
well:
accountEnabled
onPremisesImmutableId
onPremisesSyncEnabled

Is there a way to get them without using the custom option?

Thank you,
Hadar.

**Comment by cbales** [comment]
All three of these properties must be fetched with an $expand query option, I believe.
