### ISSUE TITLE
"createLink" for a drive item is not working and instead shows "itemNotFound"

### ISSUE THREAD

**Issue by pjsaran** [microsoftgraph/msgraph-sdk-java#876]
Hi,

"createLink" for a drive item is not working and instead shows "itemNotFound".

### Expected behavior

Here is the documentation -> https://docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-1.0&tabs=http

When use the API "https://graph.microsoft.com/v1.0/sites/siteid/drive/items/itemid/createLink " the result should be JSON response like below.

```
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#permission",
  "@odata.type": "#microsoft.graph.permission",
  "id": "d7ece8e0-5280-43ee-bde2-33470b431066",
  "roles": [
    "read"
  ],
  "hasPassword": false,
  "link": {
    "scope": "organization",
    "type": "view",
    "webUrl": "https://xxx.sharepoint.com/:f:/s/yyy/EhLiExJxPKBCocyeZT5cyJMBjR25DsKhknSn5-8eBXe_aw",
    "preventsDownload": false
  }
}
```

### Actual behavior

This was working fine earlier. But getting below response since yesterday.

```
{
  "error": {
    "code": "itemNotFound",
    "message": "Item not found",
    "innerError": {
      "date": "2021-09-03T08:10:04",
      "request-id": "45aa31bb-7868-4ca3-85e0-04df2dd5ffc3",
      "client-request-id": "45aa31bb-7868-4ca3-85e0-04df2dd5ffc3"
    }
  }
}
```

### Steps to reproduce the behavior

- Use this endpoint to ensure the item is available.

  GET  -> https://graph.microsoft.com/v1.0/sites/<siteid>/drive/items/itemid

- Use below endpoint to create a shared link for the item. This is when we see the error. This was working 2 days back.

  POST -> https://graph.microsoft.com/v1.0/sites/siteid/drive/items/itemid/createLink 
  BODY -> 
  
```
  {
    "type": "view",
    "scope": "organization"
  }
```

- However , the below endpoint works (workaround)

  POST -> https://graph.microsoft.com/v1.0/drives/driveid/items/itemid/createLink
  BODY -> 
```
  {
    "type": "view",
    "scope": "organization"
  }
```

**Comment by baywet** [comment]
Hi @pjsaran 
This sounds like a service issue. This repository is dedicated to the Java SDK and issues/features/questions relative to the SDK specifically.
At the bottom of the documentation page, you'll be able to find a feedback section, using the "this page" option will create an issue which will get routed to the service team directly.
Alternatively you can [contact the support](https://developer.microsoft.com/en-us/graph/support) or post on the dedicated [Microsoft Q&A forum](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-files.html).
Closing.

**Comment by pjsaran** [comment]
thank you @baywet
