### ISSUE TITLE
Getting MIME content for Message Collections

### ISSUE THREAD

**Issue by msolinas-ion** [microsoftgraph/msgraph-sdk-java#881]
Hello all!

According to what reported for [this issue](https://github.com/microsoftgraph/msgraph-sdk-java/issues/323), the support for extracting the MIME content has been added to the java SDK in the [MessageRequestBuilder](https://github.com/microsoftgraph/msgraph-sdk-java/pull/520/files). What I need is the possibility to do the same in the MessageCollectionRequestBuilder and/or in the MessageDeltaCollectionRequestBuilder, e.g. something like:

_MessageDeltaCollectionPage deltaMessagePage = graphClient.me().mailFolders("Inbox").messages().delta().content().buildRequest(reqOpts(deltaToken)).get();_

Given I found nothing for this, my original idea was to iterate over the returned MessageDeltaCollectionPage to get the Ids and issue N requests to query for each single MIME message. If possible, I would like to avoid this N+1 queries, and issue only a single query.

Thanks in advance,
Marco

**Comment by baywet** [comment]
Hey @msolinas-ion 
Thanks for reaching out.
For the SDK to support this, the service would have to support two things first:

- Indexing on individual items in a delta request
- Having $value support on delta endpoints

Today, none of these things are supported in the service, hence why we can't offer that feature in the SDK itself.
If you'd like to see this supported by the service, please [create and idea on the feature request forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph)
Closing.
