### ISSUE TITLE
Facing issues with Timezone

### ISSUE THREAD

**Issue by josephswaroopa** [microsoftgraph/msgraph-sdk-java#887]
Hi Team,

Actually iam trying to add/remove events with different timezones,but iam getting below error and given code also for addEvent,
The code is working only for two timezones are "pacific Standard Time" & "Eastern Standard Time".If iam trying for other timezones getting below Error.Please help me in this.

Can i what are the possible timezones i can pass to create event?

Code : 

String CLIENT_ID = "*****************";
			final List<String> SCOPES = Arrays.asList(new String[]{"https://graph.microsoft.com/.default"});
			
			String CLIENT_SECRET = "*************";
			String TENANT_GUID = "*****************";
			String proxyHost = "****************";
			
			int proxyPort = 8080;
			ProxyOptions proxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP,
					new InetSocketAddress(proxyHost, proxyPort));
			final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
					.clientId(CLIENT_ID).clientSecret(CLIENT_SECRET).tenantId(TENANT_GUID).proxyOptions(proxyOptions)
					.build();
			
			
					
			final TokenCredentialAuthProvider tokenCredAuthProvider = new TokenCredentialAuthProvider(SCOPES,
					clientSecretCredential);
			
			
			userMail="**************";
			
			String graphUrl="https://graph.microsoft.com/v1.0/users/"+userMail+"/calendar/events";
			String token = tokenCredAuthProvider.getAuthorizationTokenAsync(new URL(graphUrl)).get();
			logger.info("Token : "+token);
			final OkHttpClient httpClient = com.microsoft.graph.httpcore.HttpClients
					.createDefault(tokenCredAuthProvider).newBuilder()
					.proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort))).build();
			final GraphServiceClient graphClient = GraphServiceClient.builder().httpClient(httpClient).buildClient();
			
			Event newEvent = new Event();

			newEvent.subject = subject;
			ItemBody itemBody = new ItemBody();
			itemBody.contentType=BodyType.HTML;
			itemBody.content=body;
			newEvent.body=itemBody;
			DateTimeTimeZone startTime = new DateTimeTimeZone();
			startTime.dateTime=startDate.toString();
			//startTime.timeZone=sessionInfoBean.getDescription();
			startTime.timeZone="Bolivia Standard Time";
			newEvent.start=startTime;
			DateTimeTimeZone endTime = new DateTimeTimeZone();
			endTime.dateTime=endDate.toString();
					endTime.timeZone="Bolivia Standard Time";
			newEvent.end=endTime;
			Location location = new Location();
			location.displayName = sessionInfoBean.getLocation();
		newEvent.location=location;
			LinkedList<Attendee> attendeesList = new LinkedList<Attendee>();
			Attendee attendee = new Attendee();
				EmailAddress emailAddress = new EmailAddress();
				emailAddress.address = userMail;
				emailAddress.name = userName;
				attendee.emailAddress = emailAddress;
				attendee.type = AttendeeType.REQUIRED;
			attendeesList.add(attendee);
			newEvent.attendees=attendeesList;
			newEvent.isOnlineMeeting=true;
			newEvent.onlineMeetingProvider=OnlineMeetingProviderType.TEAMS_FOR_BUSINESS;
			logger.info("Event>>"+newEvent.toString());
			
			
			// POST /me/events
			 eventIdResponse=graphClient.users(userMail).events().buildRequest().post(newEvent).id;
			logger.info("response create status>>>"+eventIdResponse);
			
Error:

400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]
com.microsoft.graph.http.GraphServiceException: Error code: TimeZoneNotSupportedException
Error message: A valid TimeZone value must be specified. The following TimeZone value is not supported: 'Bolivia Standard Time'.

POST https://graph.microsoft.com/v1.0/users/parvinder.rehal@alpha.morganstanley.com/events
SdkVersion : graph-java/v3.2.0
SdkVersion : graph-java/v3.2.0
[...]

400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:419)
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:378)
	at com.micro

**Comment by baywet** [comment]
Hi @josephswaroopa 
Thanks for reaching out.
Have you seen [this documentation page](https://docs.microsoft.com/en-us/graph/api/resources/datetimetimezone?view=graph-rest-1.0) I believe is should answer your question.

**Comment by baywet** [comment]
What time zones are available is driven by the service. This repository is focused on the Java SDK specifically.
I suggest that you post this follow up question [on the dedicated Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/128331/microsoft-graph-calendar.html) forums. It will get attention from the service team this way.
Closing.
