### ISSUE TITLE
send email with attachments

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#90]
I'd like to send an email with an attachment but it is unclear how to do so.

Here's a fragment from [OutlookTests](https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/test/java/com/microsoft/graph/functional/OutlookTests.java):

```java
Message message = new Message();
message.subject = "Test E-Mail";
...
// how do i set attachments?
message.attachments = new AttachmentCollectionPage(response??, builder??);
// now add the attachments to the page
...
testBase.graphClient.me().sendMail(message, true).buildRequest().post();
```

In its current state the `AttachmentCollectionPage` object seems read-focused. How do I use it for write (or is this the wrong approach)?

**Comment by davidmoten** [comment]
Any ideas on this one?

**Comment by davidmoten** [comment]
I see the last commit is 22 days ago. You still around @cbales?

**Comment by davidmoten** [comment]
Ah, a little dig and I see @cbales has left Microsoft (thanks for your efforts, fare thee well!). @MIchaelMainer got a new lead on this one?

**Comment by deepak2016** [comment]
Hello David, I am Deepak Agrawal and have joined SDK team. I am looking into sending email with attachment scenario and will let you know my findings.

**Comment by davidmoten** [comment]
This may help @deepak2016.

I spent a bit of time with the debugger and figured out how to send attachments with an email:

```java
EmailAddress address = new EmailAddress();
address.address = "blah@gmail.com";
Recipient recipient = new Recipient();
recipient.emailAddress = address;

// need to use a MyMessage to serialize attachments
MyMessage message = new MyMessage();
message.subject = "Test E-Mail";
message.toRecipients = Collections.singletonList(recipient);
        
FileAttachment att = new FileAttachment();
att.contentBytes = "hello there!".getBytes(StandardCharsets.UTF_8);
att.contentType = "text/plain";
att.name = "hi.txt";
att.oDataType = "#microsoft.graph.fileAttachment";
message.addAttachment(att);

client.users(mailbox) //
    .sendMail(message, true) //
    .buildRequest() //
    .post();

private static final class MyMessage extends Message {
        @SerializedName("attachments")
        @Expose
        private List<Attachment> attachmentsToSend = new ArrayList<>();

        public void addAttachment(FileAttachment att) {
            attachmentsToSend.add(att);
        }
    }
```

I definitely class this as a workaround. It certainly does not use the API in any sort of discoverable way so this issue should stay open as a marker for the problem generally. I could not solve this problem without intimate knowledge of the internals and that's a bad thing.

Another red flag is that I had to set the `oDataType` of the `FileAttachment`. I suggest that the `oDataType` should be part of the metadata used by the generator (and generated classes should set the type). Do you agree @MIchaelMainer? I had a look at the metadata and there are no mentions of `oDataType`s there.

**Comment by MIchaelMainer** [comment]
By the nature of these being generated from the metadata, these client libraries require that a user is familiar with the protocol to use them.  With that said, adding a file attachment and sending the email in a single call is not discoverable (I didn't find in in the docs). We should consider a helper to make this much more straightforward to do. Perhaps a sendMailWithAttachments(message, List<Attachment> attachments, true) where the helper applies the odataType and **attachments** on a message .

IIRC, we considered adding the odataType on generation. We decided against it since we weren't guaranteed that all services would handle it the same way. For the most part, the service APIs infers the type from the payload.

**Comment by davidmoten** [comment]
>Perhaps a sendMailWithAttachments(message, List attachments, true) where the helper applies the odataType and attachments on a message .

I guess that would work but don't we have a problem generally where the API doesn't support modification of collections?

**Comment by MIchaelMainer** [comment]
I'm not sure if I follow. The API does allow the modification of collections, depending on the collection. In this case, according to the workaround that you figured out, *attachments* collection is updated. [Here's the spec](docs.oasis-open.org/odata/odata/v4.01/cs01/part1-protocol/odata-v4.01-cs01-part1-protocol.html#sec_CreateRelatedEntitiesWhenCreatinganE).

**Comment by davidmoten** [comment]
Ah oops, confusing terminology from me. I meant the SDK API (should just have said SDK).

**Comment by davidmoten** [comment]
As a side comment, sending emails with large attachments (>3MB) is a **disaster** with the Graph API. See https://stackoverflow.com/questions/50692280/send-reference-attachment-to-email-via-graph-api. In combination with the lack of support for nested `eml` attachments (read use-case, see #21) Graph support for email is very limited. This puts me in a difficult position where my only real option is to return to the [ews-java-api](https://github.com/OfficeDev/ews-java-api) which is a dead project. I will be forced to fork it and support it myself (or use it as is which might be possible for my limited use cases). Yuk.

BTW, this is not criticism of the work on *msgraph-sdk-java*. I have appreciated greatly the efforts of all concerned!

@MIchaelMainer who manages the *ews-java-api* api? It appears to be a dead project (last PR merged late 2016).  If it's officially dead then so be it but the project README.md should reflect this. If it's not officially dead  I would love to see it get some resources (after all the API it is used to talk to is not dead and Graph is not ready to replace it).

**Comment by MIchaelMainer** [comment]
@davidmoten your critical and constructive feedback is welcomed here. Please don't pull the punches. 

No one at Microsoft is maintaining the *ews-java-api*.  There appears to be a couple of active forks by @OS-JaR and @eveoh. I'd rather point people to the most active and mature fork than letting folks be disappointed by this repo.

**Comment by OS-JaR** [comment]
@MIchaelMainer So there is no chance for MS support of _ews-java-api_ ? I already suspected it, so I suggest an unofficial cummunity here:
https://github.com/OfficeDev/ews-java-api/issues/661

**Comment by MIchaelMainer** [comment]
@OS-JaR I don't see a chance that we will pick back up *ews-java-api* development. If there is a maintained fork, I'll ask that we update the *officedev/ews-java-api* repo readme to point at that fork.

**Comment by davidmoten** [comment]
@MIchaelMainer thanks for checking up

**Comment by MIchaelMainer** [comment]
On the deep nested attachment expansion, I just checked on this issue - no word yet.

**Comment by davidmoten** [comment]
@MIchaelMainer much obliged!

**Comment by OS-JaR** [comment]
Hi @MIchaelMainer,
what would you recommend? Fork the '_ews-java-api_'-repo or create a new repo and copy the code?
Any restrictions from Microsoft? I would love if '_ews-java-api_' can be maintained by a community, because we really need this, espacially for server-side mail handling (read jounal mailboxes, read envelopes ...). As commented [HERE](https://github.com/OfficeDev/ews-java-api/issues/661), we should create a community repo/fork. Can you help me/us?

Thanks,
Jan

FYI: @davidmoten

**Comment by davidmoten** [comment]
@OS-JaR happy to chip in on a fork but my contributions will likely be limited to supporting the email space for the moment (and the project may work as is for that, I'll see).

My 50c is yes just fork to a new organisation account on github, add keen experienced people as committers (Microsoft people as well if they want) so we have coverage when key people are busy with other things. Change the maven `groupId`, sort out deployment to Maven Central so it's super easy (I can help with that if required). The product is big so we might be pushing for the community to be solving their own problems and submitting PRs for review (after discussion preferrably). I guess it depends on how much time reviewers and committers have to contribute but my guess is not a lot. The licence is the MIT licence which is pretty permissive so I don't think that will get in the way.

Once we are established ask @MIchaelMainer to mention the fork on the README and we see how it goes.

Now this approach may not be in agreement with @MIchaelMainer and I would defer to the wishes of the project owners on this stuff.

**Comment by poonamsehjwani** [comment]
Not able to send mail with attachment using AttachmentCollectionPage.. Can you please provide a way to send the attachment?

**Comment by davidmoten** [comment]
@poonamsehjwani example is further up in the thread. I have it working (but is limited to small attachments).

**Comment by poonamsehjwani** [comment]
Thanks @davidmoten !!!.. But with the above workaround still mail is sent without attachment..
Moreover I tried with
 message.attachments = new AttachmentCollectionPage(response, null);

I have opened a new issue for that  : https://github.com/microsoftgraph/msgraph-sdk-java/issues/192
Could you please help me on this..

**Comment by AvinashKharche** [comment]
Hello,
I am trying to send email using sendEmail API but unable to send using Java SDK. 
Can someone please help.

`   AttachmentCollectionResponse attachmentCollectionResponse = new AttachmentCollectionResponse();
        attachmentCollectionResponse.value = emailAttachments;
        AttachmentCollectionPage attachmentCollectionPage = new AttachmentCollectionPage(attachmentCollectionResponse, null);
        message.attachments = attachmentCollectionPage;`

**Comment by davidmoten** [comment]
I can't give you up to date advice about sending mail with msgraph-sdk-java. I now use [odata-client-msgraph](https://github.com/davidmoten/odata-client) for this. Sending email example is [here](https://github.com/davidmoten/odata-client#sending-an-email-with-an-attachment). The principles will be similar though with msgraph-sdk-java so that might help a bit.

**Comment by baywet** [comment]
Hi everyone,
Thanks for the feedback and the patience on the matter.
I was able to update and review, test and fix PR #202 which never had been merged for some reason and which addresses this issue. It should go out with version 2.1.0, either this week or the following.
Once the PR gets merged, it'll close this issue.

**Comment by davidmoten** [comment]
Thanks @baywet, to close it off please put example code here or a link.

**Comment by baywet** [comment]
Hey David,
You can find a sample on how to attach files with emails (<4MB) in our unit tests.
https://github.com/microsoftgraph/msgraph-sdk-java/pull/202/files#diff-ca39247b233dfb60518f697e16243541R124
