### ISSUE TITLE
Handle HTTP/1.1 504 Gateway Timeout

### ISSUE THREAD

**Issue by J0s3f** [microsoftgraph/msgraph-sdk-java#91]
I get the response "HTTP/1.1 504 Gateway Timeout" quite often recently.
There should be a option to automatically retry requests on temporary errors.
Something similar to the [BackOff](https://developers.google.com/api-client-library/java/google-http-java-client/reference/1.20.0/com/google/api/client/util/BackOff) settings in [Google HTTP Client](https://github.com/google/google-http-java-client) seems reasonable.

There should probably also be support for [throttling](https://developer.microsoft.com/en-us/graph/docs/concepts/throttling) where the time to wait is known.

Of course such a wait time should work for multiple threads.

**Comment by deepak2016** [comment]
Thanks @J0s3f for reporting the issue. We are looking into the issue and will get back to you with our findings.

**Comment by baywet** [comment]
Hi @J0s3f 
Thanks for the feedback and the patience on the matter.
This was added in the core library about a year after your original comment. I'm not sure why your comment wasn't updated back then.
https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/master/src/main/java/com/microsoft/graph/httpcore/RetryHandler.java#L32.
Closing.
