### ISSUE TITLE
Manage Authentication on httpProvider instead of httpClient

### ISSUE THREAD

**Issue by mxmmarmol** [microsoftgraph/msgraph-sdk-java#923]
Design problem.

Issue with GraphServiceClient is that authentication is managed by an interceptor inside OkHttpClient based on the IAuthenticationProvider that only takes in account the url to understand if authentacion is needed and retrieve the access token.
This make almost impossible to re-share an OKHttpClient inside a server with multiple threads.
https://stackoverflow.com/questions/66820194/microsoft-graph-3-0-java-net-sockettimeoutexception-while-retrieving-group-membe

### Expected behavior

Be able to re-use OkHttpClient on multiple threads inside a server/node/pod for multiple Graph users.

### Actual behavior

Authentication is depends on an Interceptor loaded using IAuthenticationProvider which only takes in account URL. When having to access many users graph api a new client is needed because of the dependency on IAuthenticationProvider been based per url and not understanding the user context. This on the ends consumes sockets and ends up causing timeouts.
https://stackoverflow.com/questions/66820194/microsoft-graph-3-0-java-net-sockettimeoutexception-while-retrieving-group-membe

### Steps to reproduce the behavior
Production environment, hundred of users access on same server/node/pod.

### Proposed change
Make the authentication dependent on HttpProvider and add the logic to decide if adding the header on getHttpRequest method inside it. This is better because the authorization header is added based on the GraphServiceClient call, and the OkHttpClient is left alone so it can be shared between multiple GraphServiceClients.

**Comment by henry-filosa** [comment]
@baywet Hello, we're having the same issue. Is there a tracker for when Kiota will be integrated into the graph SDK?

**Comment by baywet** [comment]
Hey @henry-filosa 
Our Program Managers @maisarissi (Java) @RabebOthmani (Kiota) are in the process of organizing the different milestones/projects so we can better communicate progress on that effort.
Right now the main issue tracking this work for Java is here https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/323

You can also look at [the Java project](https://github.com/microsoft/kiota/projects/7) under kiota to get a better sense of where we're at. I hope this helps.
