### ISSUE TITLE
Application API throwing Graph Service Exception - Object ID not found

### ISSUE THREAD

**Issue by SabbitRex** [microsoftgraph/msgraph-sdk-java#934]
Hi Team, sorry to bother, really hard with documentation...

I am trying to setup client secret using for an application that I created but I am getting below error...

```
Error message: Resource '0c26b421-895d-4bd9-88ac-f6a300e269d9' does not exist or one of its queried reference-property objects are not present.

GET https://graph.microsoft.com/v1.0/applications/0c26b421-895d-4bd9-88ac-f6a300e269d9
SdkVersion : graph-java/v5.6.0
```

The code that I was using to set secret is...

```
                PasswordCredential passwordCredential = new PasswordCredential();
		passwordCredential.displayName = "Password friendly name";
                
                graphClient.applications(appId)
				.addPassword(ApplicationAddPasswordParameterSet
					.newBuilder()
					.withPasswordCredential(passwordCredential)
					.build())
				.buildRequest()
				.post();
```

Here appId is "0c26b421-895d-4bd9-88ac-f6a300e269d9" which I got when I created the application...

                ```
                Application application = new Application();
		application.displayName = "Test App";
		
		String appId = graphClient.applications()
				.buildRequest()
				.post(application)
				.appId;
               ```

When I check in the UI, I found the appId was present present and Application was created. 
Then I tried to get the application to see if it existed...but it again gave same error object no found.

```
Application application = graphClient.applications(appId)
				.buildRequest()
				.get();
```

I am trying to setup the secret (add secret and then save the secret string) but it does not seem to work. Any idea on what I am missing?

**Comment by baywet** [comment]
Hi @SabbitRex 
Thanks for reaching out.
Please create issues related to the models/fluent API here, and issues related to the core layer in the core repository for sanity (I've transferred your issue).
You're running into the same distribution issue you ran into with https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/353.
And the solution is the same: exponential back-off when you query back on an object you just created.
In a general sense, this is something you will experience on identity objects (users, groups, applications...)

**Comment by SabbitRex** [comment]
Okay but this time I am just sending a just single request to create the application and then a single request to add secret, just one time. I even tried with retry logic, it api call fails retry with a wait of 500 ms.

Should not a wait 500 ms and retry logic (recall API to get that application based on app-id) work? I had a max retry count of 20 with 500 ms wait each time it fails before retrying?

**Comment by SabbitRex** [comment]
besides I am not doing any operation which will lead to API throttling such that I get a 429 error code (too many request to handle) - I am just getting 404.

**Comment by SabbitRex** [comment]
I found this thread - seems like other folks had same problem, but could not find a resolution I guess...

https://github.com/microsoftgraph/microsoft-graph-docs/issues/3539

**Comment by SabbitRex** [comment]
So I did a little change in my code 

```
                LinkedList<Option> requestOptions = new LinkedList<>();
		requestOptions.add(new QueryOption("$filter", "appId eq '" + appId + "'")); 
		 
		ApplicationCollectionPage application = graphClient.applications()
				.buildRequest(requestOptions)
				.get();
```

So I changed Application to ApplicationCollectionPage and added a query options and this seems to be working...

However when I am doing this...

```
                 LinkedList<Option> requestOptions = new LinkedList<>();
		requestOptions.add(new QueryOption("$filter", "appId eq '" + appId + "'")); 
		 
		Application application = graphClient.applications(appId)
				.buildRequest(requestOptions)
				.get();
```

This wont work.

**Comment by baywet** [comment]
Right, I missed that part in your original snippet.

This should work instead (+ the replication delay back-off when you get a 404)
```Java
Application application = new Application();
	application.displayName = "Test App";
	
	String objId = graphClient.applications()
			.buildRequest()
			.post(application)
			.Id;

Application application = graphClient.applications(objId)
				.buildRequest()
				.get();

```
(see how I changed the app id by id)

Besides that, the filtering won't solve for the replication issue.

Again, the service relies on multiple replicas for identity objects.
Two subsequent requests will most likely fall on two different replicas. (sometimes you can get lucky and fall on the same one, but this is not a guarantee).
Replication takes time between replicas, from a few 100's of milliseconds all the way to 15 minutes (can happen when the service is unhealthy).
Your code needs to be built to account for that, whether you're making 2 calls, or hundreds (like your other issue).
The SDK already handles transient errors (throttling etc...) for you.

**Comment by SabbitRex** [comment]
Oh god, that was such a small change and made everything working. 

After the change I noticed the "appId" is the one visible in portal essentially the application client id and "id" is thr object Id which was actually needed. 


Closing of the question. Thank you again, you're a savior and I love what you do with the sdk. ❤️
