### ISSUE TITLE
Unable to move "Other permissions" to "Configured permissions" using Graph API - Java

### ISSUE THREAD

**Issue by SabbitRex** [microsoftgraph/msgraph-sdk-java#937]
Hi Graph Team,

I am trying to add permissions programmatically but in doing so all the permissions are coming to "Other Permissions" instead of "Configured Permission"

Here is my code :

```
                AppRoleAssignment appRoleAssignment = new AppRoleAssignment();
		appRoleAssignment.principalId = UUID.fromString(clientSerPrinObjId);
		appRoleAssignment.resourceId = UUID.fromString(resSerPrinObjId);
		
		for (AppRole appRole : roles) {
			System.out.println("Adding app role : " + appRole.value);
			appRoleAssignment.appRoleId = appRole.id;
			
			graphClient.servicePrincipals(resSerPrinObjId).appRoleAssignedTo()
			.buildRequest()
			.post(appRoleAssignment);
		}
```
Here in the "roles" I have a List which has two application permission - Test.Role and Demo.Role and once I call the post - These permissions are going to "Other Permissions" instead of "Configured Permission"

Here is a screen shot...

![image](https://user-images.githubusercontent.com/29224909/141974944-3596bd3f-d0ae-4bc5-b0c0-7cdfcb749966.png)

How can I move these permission to "Configured Permissions"?

**Comment by baywet** [comment]
Hi @SabbitRex 
Thanks for reaching out.
The SDK seems to be behaving like expected, and it seems the issue/question you have is more about the behavior of the service itself.
This repository is dedicated to the SDK itself, for service questions [please use the dedicated identity Q&A forum](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-identity.html) where members from the service team with better knowledge of it will be able to answer you.
Closing.
