### ISSUE TITLE
How to fetch exapnd with selected fields(Java Graph SDK)

### ISSUE THREAD

**Issue by jsandeepm** [microsoftgraph/msgraph-sdk-java#940]
I am trying fetching the users details. I want to fetch users with manager details(only manager id, givenname, mail, userPrincipalName).

Below is my code. I am not able to fetch the manager with required fields

> private static final String COLUMN_NAMES =
            "accountEnabled," +
            "businessPhones," +
            "companyName," +
            "country," +
            "createdDateTime," +
            "department," +
            "displayName," +
            "givenName," +
            "jobTitle," +
            "mail," +
            "mailNickname," +
            "mobilePhone," +
            "surname," +
            "usageLocation," +
            "userPrincipalName," +
            "id";

`
UserCollectionPage usersPage = graphServiceClient.users().buildRequest().select(COLUMN_NAMES).expand("manager").get();
 List<User> users = usersPage.getCurrentPage();
`

what is right way to fetch managers required fields with user details?

Thank you,
Sandeep M

**Comment by baywet** [comment]
Hi @jsandeepm 
Thanks for reaching out.
You need to expand select, that is replacing "manager" by "manager($select=id,givenName,mail,userPrincipalName)".

**Comment by jsandeepm** [comment]
> Hi @jsandeepm Thanks for reaching out. You need to expand select, that is replacing "manager" by "manager($select=id,givenName,mail,userPrincipalName)".

That resolved my requirements. Thank you very much for quick reply.
