### ISSUE TITLE
About using Microsoft graph to build Android apps, the class in the example was not found

### ISSUE THREAD

**Issue by saosirse** [microsoftgraph/msgraph-sdk-java#959]
According to official documents（ https://docs.microsoft.com/zh-cn/graph/tutorials/android?context=outlook%2Fcontext ）Use Microsoft graph to build Android applications.

However, when I write code according to the examples in the document, I find that some classes cannot be found in the corresponding packages, such as com.microsoft.graph.authentication.baseauthenticationprovider, which cannot be found in packages that depend on Microsoft graph: 3.1.0, and com.microsoft.graph.options cannot be found.

Is there a problem with the document sample code? Or do I rely on the wrong package? (I checked other versions of packages on GitHub and found no relevant classes)

**Comment by ramsessanchez** [comment]
@saosirse This tutorial seems to be a bit outdated, apologies for that. The Java SDK no longer relies on the msal identity dependency for authentication. Instead, I would recommend using the installation guide we have for the java SDK here: https://github.com/microsoftgraph/msgraph-sdk-java#1-installation. 
The dependencies here should contain the libraries you need to make calls against the MsGraph service and should facilitate your process going forward. Please feel free to reach back on this repository if you run into further issues.

**Comment by saosirse** [comment]
@ramsessanchez 
Now I want to integrate the relevant functions of outlook on the Android client.
If I use the SDK(msgraph-sdk-java) you provide，Are there any documents or samples for using this SDK on Android clients?

**Comment by ramsessanchez** [comment]
@saosirse Unfortunately I do think the android tutorial is a bit outdated as far as authentication goes, however the sdk itself has remained quite the same. 
https://github.com/microsoftgraph/msgraph-sdk-java#13-enable-proguard-android
https://docs.microsoft.com/en-us/graph/sdks/create-client?tabs=Android
https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Android#interactive-provider
https://docs.microsoft.com/en-us/graph/sdks/create-requests?tabs=CS
Here are a few links to hopefully get you started.

**Comment by saosirse** [comment]
@ramsessanchez 
Thank you for your information. I'll review them and rebuild the project
