### ISSUE TITLE
Error message: Invalid filter clause

### ISSUE THREAD

**Issue by huangdezhou008** [microsoftgraph/msgraph-sdk-java#967]
GET https://graph.microsoft.com/v1.0/me/mailFolders/AAMkAGI1ZTcyZDUyLTUwYjAtNDQ3Zi04MmJiLTk0NDYyMjRjZDg5YwAuAAAAAAAt9u-CPVJiQr1bW65ncf0rAQALZx8mRleUSpRunE2oMh9mAAAAAAEJAAA=/messages?%24select=id%2CtoRecipients%2Csubject%2Cfrom%2CisRead%2CisReadReceiptRequested%2CisDeliveryReceiptRequested%2CparentFolderId%2CsentDateTime%2CreceivedDateTime%2Cbody%2Cimportance%2CcreatedDateTime&%24filter=receivedDateTime%20ge%202021-12-15%20and%20receivedDateTime%20lt%202021-12-18%20and%20startswith%28importance%2C%27NO%27%29&%24orderby=receivedDateTime%20desc%2Cimportance%2Csubject%20asc
Prefer : outlook.body-content-type="text"
SdkVersion : graph-java/v2.2.0
Authorization : [PII_REDACTED]

**Comment by huangdezhou008** [comment]
![image](https://user-images.githubusercontent.com/16448968/146393968-87fd0b46-4153-42ba-8a4c-240fa9b0a274.png)
![image](https://user-images.githubusercontent.com/16448968/146394014-e50e1acf-298b-4269-b6ed-2afdadb5ce3c.png)

**Comment by ramsessanchez** [comment]
Hello @huangdezhou008, I don't believe Office365MailDTO is a supported class. Please upgrade the SDK and attempt a build using the newest classes. Also, ensure you are using the latest azure identity, 1.4.0<, this will ensure that your graph client service is working in sync with the latest graph-core library, which the newest graph-sdk heavily relies on.

**Comment by huangdezhou008** [comment]
@ramsessanchez  ,i want to query data ,but it throw 400 error ,https://docs.microsoft.com/zh-cn/graph/query-parameters?view=graph-rest-1.0
