### ISSUE TITLE
how can i query email by receivedDateTime, 

### ISSUE THREAD

**Issue by huangdezhou008** [microsoftgraph/msgraph-sdk-java#972]
IMessageCollectionPage page = this.getGraphClient(messageExtendParam).me().mailFolders(inbox).messages()
                    .buildRequest(options)
                    .get();

想根据receivedDateTime 的时分秒去搜索数据，怎么实现

**Comment by huangdezhou008** [comment]
@SerializedName("receivedDateTime")
    @Expose
    public java.util.Calendar receivedDateTime;

**Comment by huangdezhou008** [comment]
this.filter.add(String.format("receivedDateTime ge 2021-12-20T04:11:34Z"
            ));
            this.filterNames.add("receivedDateTime");

**Comment by ramsessanchez** [comment]
Hi @huangdezhou008, apologies for the long delay. Have been out on holiday, however, I hope it's not too late and hope that this code snippet can  help solve your problem. 

`GraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

LinkedList<Option> requestOptions = new LinkedList<Option>();
requestOptions.add(new QueryOption("receivedDateTime", "2022-01-06T15:28:29Z"));

MessageCollectionPage messages = graphClient.me().messages()
	.buildRequest( requestOptions )
	.get();`
