### ISSUE TITLE
OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token

### ISSUE THREAD

**Issue by hg3317593-1** [microsoftgraph/msgraph-sdk-java#977]
### Expected behavior
Get Users information and page through a collection using Microsoft Graph java sdk. Can get the next page of users.

### Actual behavior
Get error "AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token" while executing the second call to get next page of users.

### Steps to reproduce the behavior

Page reference: https://docs.microsoft.com/en-us/graph/sdks/paging?tabs=java.
Auth code provider reference: https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Java#authorization-code-provider.

Using the following code:

```Java
public static void main(String [] rags){
        String clientId = "a76c273#$%^&*...........02c34b85a65";
        String clientSecret = "m0V7Q~1u#$%^&*(....-o~_uixVnufNLS";
        String redirectUri = "https://localhost/";
        List scopes = new ArrayList();
        scopes.add("User.Read.All");
//        scopes.add("People.Read.All");
        String code = "0.ATcATqvJ5Ce91UCEWSMLo@#$%^&*.......................DdSvESAA";
        final AuthorizationCodeCredential authCodeCredential = new AuthorizationCodeCredentialBuilder()
                .clientId(clientId)
                .clientSecret(clientSecret) //required for web apps, do not set for native apps
                .authorizationCode(code)
                .redirectUrl(redirectUri)
                .build();
        final TokenCredentialAuthProvider tokenCredAuthProvider = new TokenCredentialAuthProvider(scopes, authCodeCredential);
        GraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider(tokenCredAuthProvider).buildClient();
        LinkedList<HeaderOption> requestOptions = new LinkedList<>();
        requestOptions.add(new HeaderOption("ConsistencyLevel", "eventual"));

        //String accessToken = getUserAccessToken(tokenCredAuthProvider);
        
        UserCollectionPage users = graphClient.users()
                .buildRequest(requestOptions)
                .count()
                .top(5)
                .get();
        System.out.println("------------------------11111-------------------------");

        UserCollectionRequestBuilder nextPage = users.getNextPage();
        UserCollectionPage userCollectionPage = nextPage.buildRequest(requestOptions).get();

        System.out.println("end");
    }
```

The first call "UserCollectionPage users = graphClient.users().buildRequest(requestOptions).count().top(5).get();" works fine. I can get the first 5 users. But when it runs to "UserCollectionPage userCollectionPage = nextPage.buildRequest(requestOptions).get();" to get the next 5 users , it throws "OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token".

I searched for this issue on StackOverFlow and found 3 similar issues:
https://stackoverflow.com/questions/69806282/oauth2-authorization-code-was-already-redeemed-please-retry-with-a-new-valid-co.
https://stackoverflow.com/questions/66846020/microsoft-graph-api-for-java-authentication-code-provider-works-only-on-first-re.
https://stackoverflow.com/questions/69815549/microsoft-graph-and-java-multiple-calls-against-authorization-code-flow.

The answers are not helpful.

**Comment by baywet** [comment]
Hi @hg3317593-1 
Thanks for reaching out. Can you provide the versions of the Graph SDK, Graph Core and Azure Identity your application is using please?
If your application is not on 5.9.0, 2.0.10 and 1.4.2, can you upgrade the dependencies and try again please?

**Comment by hg3317593-1** [comment]
@baywet Thank you for the reply.

Here are the versions I used before:
 
![image](https://user-images.githubusercontent.com/77661261/148142023-5b725445-096a-41b3-b47b-ff2103e3359e.png)

After I updated the versions to  5.9.0, 2.0.10 and 1.4.2, I still got the same issue.

**Comment by baywet** [comment]
Graph auth is deprecated, can you remove it and try again please? I just want to make sure we're not impacted by extrenal factors here.

**Comment by hg3317593-1** [comment]
> Graph auth is deprecated, can you remove it and try again please? I just want to make sure we're not impacted by extrenal factors here.

Removed Graph auth and the issue still exists.

**Comment by baywet** [comment]
Thanks for helping eliminating those external factors.
It seems the access token is not being cached, so when the second request executes, it tries to get another token from the same authorization code, leading to the error.

If you have a look at [the documentation for the authentication library](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/identity/azure-identity#authenticating-users) you'll see this mention for this credential.
> authenticate a user with a previously obtained authorization code as part of an Oauth 2 flow

My question to you is: how are you obtaining the auth code? And why are you not using a `InteractiveBrowserCredential` or a `DeviceCodeCredential` instead? 
(your repro sample is a console application, but what's going to be the real use here?)

**Comment by hg3317593-1** [comment]
> Thanks for helping eliminating those external factors. It seems the access token is not being cached, so when the second request executes, it tries to get another token from the same authorization code, leading to the error.
> 
> If you have a look at [the documentation for the authentication library](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/identity/azure-identity#authenticating-users) you'll see this mention for this credential.
> 
> > authenticate a user with a previously obtained authorization code as part of an Oauth 2 flow
> 
> My question to you is: how are you obtaining the auth code? And why are you not using a `InteractiveBrowserCredential` or a `DeviceCodeCredential` instead? (your repro sample is a console application, but what's going to be the real use here?)

@baywet  Thanks for the information. I sign in with a URL like this: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code and get the code in the address bar of the browser. And then copy it into my code "String code = "#$%^&";"

The reason why I use authorization code flow is that our customer is referring to the code sample here: https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Java#authorization-code-provider.

I think they are using auth code flow in the application based on the design. In the read use scene from my customer, they write a method like "String code = getCode();". And they sign in interactively to get the code and then list the users.

So, if auth code flow is not used like this, how it should be? Is there any sample code for our reference?

**Comment by baywet** [comment]
Thanks for sharing this additional information. I do think there's a bit of confusion here on how the authentication is supposed to work.
The authorization code is not meant to be used manually/copy pasted by the user. It's meant to be used in integration with other application components like the browser, or another device (device code in case of limited input capabilities).
I do think you should strongly suggest your customer to use the [interactive browser credendials](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Java#interactive-provider) or the [device code credentials](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Java#device-code-provider).
There are some edge cases where to integrate with some platform layers, the auth code is obtained by a third party layer the application developer does not have control over, in which case they can use the lower level auth code flow, but this is more work for the app developer that can be handled automatically by the other credentials for them.

**Comment by hg3317593-1** [comment]
> Thanks for sharing this additional information. I do think there's a bit of confusion here on how the authentication is supposed to work. The authorization code is not meant to be used manually/copy pasted by the user. It's meant to be used in integration with other application components like the browser, or another device (device code in case of limited input capabilities). I do think you should strongly suggest your customer to use the [interactive browser credendials](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Java#interactive-provider) or the [device code credentials](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Java#device-code-provider). There are some edge cases where to integrate with some platform layers, the auth code is obtained by a third party layer the application developer does not have control over, in which case they can use the lower level auth code flow, but this is more work for the app developer that can be handled automatically by the other credentials for them.

@baywet  I don't think customer wants to use interactive browser credendials or device code credentials. Interactive browser credendials is for mobile or desktop application. Device code credentials uses device code but customer's application is a web application which requires users to sign in.

> The authorization code is not meant to be used manually/copy pasted by the user. 
Customer also doesn't simply manually copy pasted the code. Let me give you a scene, if we have an application which has front end and backend. In front end, we implement interactively sign in to get the code and pass the code to backend, then we use "AuthorizationCodeCredential authCodeCredential = new AuthorizationCodeCredentialBuilder().clientId(clientId).clientSecret(clientSecret).authorizationCode(code).redirectUrl(redirectUri).build();" to get the authCodeCredential. I think the scene is reasonable right?

Can you provide a Github sample which uses Microsoft Graph java sdk and [Authorization code provider](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Java#authorization-code-provider)?

**Comment by baywet** [comment]
What you are describing is the on-behalf flow, where the web app call Microsoft Graph representing not only itself but also the user using the web app.
Is this app an application that returns HTML or an API? In both cases accessing this app/api should be secured via AAD/MIP.
Have a look at [this sample](https://github.com/Azure-Samples/ms-identity-java-spring-tutorial/) and let me know whether it answers your questions (ignore all the b2c stuff).

**Comment by hg3317593-1** [comment]
> What you are describing is the on-behalf flow, where the web app call Microsoft Graph representing not only itself but also the user using the web app. Is this app an application that returns HTML or an API? In both cases accessing this app/api should be secured via AAD/MIP. Have a look at [this sample](https://github.com/Azure-Samples/ms-identity-java-spring-tutorial/) and let me know whether it answers your questions (ignore all the b2c stuff).

Maybe the scene I described is indeed like on-behalf-of flow. It's a bad scene. Let's assume that we only have a web application, we sign in and get the code, and put the code into 

```
final AuthorizationCodeCredential authCodeCredential = new AuthorizationCodeCredentialBuilder()
                .clientId(clientId)
                .clientSecret(clientSecret) //required for web apps, do not set for native apps
                .authorizationCode(code)
                .redirectUrl(redirectUri)
                .build();
```

I think this scene is clear right?

Thank you, I have checked the sample you shared and it uses a different code to get the graphServiceClient. Anyway, will look into deeper to see if we have a workaround.

**Comment by baywet** [comment]
Alright, at this point we've clearly established this is an authentication issue. Not an  SDK issue.
Although I still think you should be using a different flow in your case, I might be wrong, I will encourage you to reach out to the maintainers of [the azure identity library](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/identity/azure-identity) to get better support.

I also encourage you to update your reproduction code to the following to outline the fact the issue comes from the authentication part and not the graph SDK.

```Java
public static void main(String [] rags){
        String clientId = "a76c273#$%^&*...........02c34b85a65";
        String clientSecret = "m0V7Q~1u#$%^&*(....-o~_uixVnufNLS";
        String redirectUri = "https://localhost/";
        List scopes = new ArrayList();
        scopes.add("User.Read.All");
//        scopes.add("People.Read.All");
        String code = "0.ATcATqvJ5Ce91UCEWSMLo@#$%^&*.......................DdSvESAA";
        final AuthorizationCodeCredential authCodeCredential = new AuthorizationCodeCredentialBuilder()
                .clientId(clientId)
                .clientSecret(clientSecret) //required for web apps, do not set for native apps
                .authorizationCode(code)
                .redirectUrl(redirectUri)
                .build();
        final TokenCredentialAuthProvider tokenCredAuthProvider = new TokenCredentialAuthProvider(scopes, authCodeCredential);
        GraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider(tokenCredAuthProvider).buildClient();
        LinkedList<HeaderOption> requestOptions = new LinkedList<>();
        requestOptions.add(new HeaderOption("ConsistencyLevel", "eventual"));

        URL url = new URL("https://graph.microsoft.com/v1.0/me");
        String accessToken = tokenCredAuthProvider.getAuthorizationTokenAsync(url); // should return something
        String accessToken2 = tokenCredAuthProvider.getAuthorizationTokenAsync(url); // should return something if it worked properly but will be empty with the current issue
        
```

Closing.
