### ISSUE TITLE
upgrade-to-v3 documentation - example code for batch wrong

### ISSUE THREAD

**Issue by marmor7** [microsoftgraph/msgraph-sdk-java#995]
### Expected behavior
The documentation code for doing batches is:

```
final BatchRequestContent batchRequestContent = new BatchRequestContent();
final String meGetId = batchRequestContent.addbatchRequestStep(graphClient.me().buildRequest().getHttpRequest());
final BatchResponseContent batchResponseContent = graphClient.batch().buildRequest().post(batchRequestContent);
final User me = batchResponseContent.getResponseById(meGetId).getDeserializedBody(User.class);
```
(also note the lower case 'b' in `addbatchRequestStep` which is a typo, should be 'B')

However that failed in runtime as `getHttpRequest` will return the `nativeRequestType` which is actually `okhttp3.Request`
while addBatchRequestStep expects `IHttpRequest`.

It took me a while to figure out the correct code, which is like this:

```
final BatchRequestContent batchRequestContent = new BatchRequestContent();
final String meGetId = batchRequestContent.addBatchRequestStep(graphClient.me().buildRequest(), HttpMethod.GET);
final BatchResponseContent batchResponseContent = graphClient.batch().buildRequest().post(batchRequestContent);
final User me = batchResponseContent.getResponseById(meGetId).getDeserializedBody(User.class);
```

Also, the docs could use examples of non-GET methods with or without body, there are no examples of that online that I could find.

```
// POST with body
IHttpRequest request = client.me().contacts().buildRequest().withHttpMethod(POST).getHttpRequest();
batchRequestContent.addBatchRequestStep(request, POST, body);
```

```
// DELETE with resource id, without body
final BatchRequestContent batchContent = new BatchRequestContent();
batchContent.addBatchRequestStep(client.me().contacts(id).buildRequest(), DELETE);
```

### Actual behavior
Documentation's code doesn't compile (typo) and when typo is fixed throws in runtime:
`okhttp3.Request cannot be cast to com.microsoft.graph.http.IHttpRequest`

### Steps to reproduce the behavior
Run the code from the migration docs

**Comment by baywet** [comment]
Hi @marmor7 
Thanks for reporting this!
Would you be willing to submit a pull request to address this? FYI the source for the page is [located here](https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/docs/upgrade-to-v3.md)

**Comment by baywet** [comment]
thanks a lot! when this pull request gets merged, it'll close this issue.
